/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Agda.Syntax

/-!
# `DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact`, transliterated

Generated by `tools/agda2lean.py` from the ingested upstream source
`upstream/dashi_agda/agent/itir-producer-complete-token-heads/DASHI/Cognition/PNF/ProducerCertifiedTokenReferenceFibreExact.agda`.
Do not edit by hand: re-run the translator instead.
-/

open Agda

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where

  open import Agda.Builtin.Equality

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  ------------------------------------------------------------------------
  -- Exact specialization for SensibLaw migration 176.
  --
  -- One strict-v2 parser token carries five live numeric semantic-symbol
  -- references and four live annotation-origin references.  The bounded producer
  -- already owns all nine coordinates before authority insertion.  Migration 176
  -- replaces their nine per-row FK lookups with one producer certificate over the
  -- complete bounded reference fibre, while generic writers retain set-wise
  -- authority validation and authority-side reverse-restrict guards.
  --
  -- This theorem is intentionally narrower than arbitrary FK elimination: it says
  -- only that, when the producer carries authority witnesses for these exact nine
  -- coordinates, the semantic final row is unchanged by omitting nine redundant
  -- per-row membership lookups.
  ------------------------------------------------------------------------

  record TokenReferenceFibre
    (Symbol Origin : Set)
    : Set where
    constructor tokenReferenceFibre
    field
      orthSymbol : Symbol
      lemmaSymbol : Symbol
      posSymbol : Symbol
      tagSymbol : Symbol
      dependencySymbol : Symbol
      lemmaOrigin : Origin
      posOrigin : Origin
      tagOrigin : Origin
      dependencyOrigin : Origin

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  open TokenReferenceFibre public

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  record TokenReferenceAuthority
    (Symbol Origin : Set)
    : Set₁ where
    field
      SymbolAuthoritative : Symbol → Set
      OriginAuthoritative : Origin → Set

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  open TokenReferenceAuthority public

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  record ProducerCertifiedTokenReferences
    (Symbol Origin : Set)
    (authority : TokenReferenceAuthority Symbol Origin)
    : Set₁ where
    field
      references : TokenReferenceFibre Symbol Origin
      orthSymbolWitness : SymbolAuthoritative authority (orthSymbol references)
      lemmaSymbolWitness : SymbolAuthoritative authority (lemmaSymbol references)
      posSymbolWitness : SymbolAuthoritative authority (posSymbol references)
      tagSymbolWitness : SymbolAuthoritative authority (tagSymbol references)
      dependencySymbolWitness :
        SymbolAuthoritative authority (dependencySymbol references)
      lemmaOriginWitness : OriginAuthoritative authority (lemmaOrigin references)
      posOriginWitness : OriginAuthoritative authority (posOrigin references)
      tagOriginWitness : OriginAuthoritative authority (tagOrigin references)
      dependencyOriginWitness :
        OriginAuthoritative authority (dependencyOrigin references)

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  open ProducerCertifiedTokenReferences public

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  -- Successful per-row RI checks cannot alter any of the nine references; they
  -- only re-establish authority membership already supplied by the producer.
  producerCertifiedTokenRow :
    ∀ {Symbol Origin : Set}
      {authority : TokenReferenceAuthority Symbol Origin} ,
    ProducerCertifiedTokenReferences Symbol Origin authority →
    TokenReferenceFibre Symbol Origin
  producerCertifiedTokenRow = references

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  lookupCheckedTokenRow :
    ∀ {Symbol Origin : Set}
      {authority : TokenReferenceAuthority Symbol Origin} ,
    ProducerCertifiedTokenReferences Symbol Origin authority →
    TokenReferenceFibre Symbol Origin
  lookupCheckedTokenRow = references

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  producerCertifiedTokenReferenceExact :
    ∀ {Symbol Origin : Set}
      {authority : TokenReferenceAuthority Symbol Origin}
      (certificate : ProducerCertifiedTokenReferences Symbol Origin authority) ,
    producerCertifiedTokenRow certificate ≡ lookupCheckedTokenRow certificate
  producerCertifiedTokenReferenceExact certificate = refl

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  consumerObservationExact :
    ∀ {Symbol Origin Observation : Set}
      {authority : TokenReferenceAuthority Symbol Origin}
      (certificate : ProducerCertifiedTokenReferences Symbol Origin authority)
      (observe : TokenReferenceFibre Symbol Origin → Observation) ,
    observe (producerCertifiedTokenRow certificate)
      ≡ observe (lookupCheckedTokenRow certificate)
  consumerObservationExact certificate observe = refl

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  ------------------------------------------------------------------------
  -- Physical realization receipt.
  --
  -- Keep each coordinate explicit instead of collapsing the measured nine-FK
  -- surface into an opaque scalar.  In the legacy row-FK realization every field
  -- costs one persistent membership check per admitted row.  Under the exact
  -- producer certificate, none of those nine semantic obligations requires a
  -- per-row persistent lookup.
  ------------------------------------------------------------------------

  record TokenReferenceLookupReceipt : Set where
    constructor tokenReferenceLookupReceipt
    field
      admittedRows : Nat
      orthSymbolLookups : Nat
      lemmaSymbolLookups : Nat
      posSymbolLookups : Nat
      tagSymbolLookups : Nat
      dependencySymbolLookups : Nat
      lemmaOriginLookups : Nat
      posOriginLookups : Nat
      tagOriginLookups : Nat
      dependencyOriginLookups : Nat

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  open TokenReferenceLookupReceipt public

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  producerCertifiedLookupReceipt : Nat → TokenReferenceLookupReceipt
  producerCertifiedLookupReceipt count =
    tokenReferenceLookupReceipt
      count zero zero zero zero zero zero zero zero zero

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  perRowForeignKeyLookupReceipt : Nat → TokenReferenceLookupReceipt
  perRowForeignKeyLookupReceipt count =
    tokenReferenceLookupReceipt
      count count count count count count count count count count

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  producerCertifiedHasNoPerRowSymbolLookups :
    ∀ count ,
    orthSymbolLookups (producerCertifiedLookupReceipt count) ≡ zero
  producerCertifiedHasNoPerRowSymbolLookups count = refl

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  producerCertifiedHasNoPerRowOriginLookups :
    ∀ count ,
    dependencyOriginLookups (producerCertifiedLookupReceipt count) ≡ zero
  producerCertifiedHasNoPerRowOriginLookups count = refl

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  perRowOrthLookupScalesWithRows :
    ∀ count ,
    orthSymbolLookups (perRowForeignKeyLookupReceipt count) ≡ count
  perRowOrthLookupScalesWithRows count = refl

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  perRowDependencyOriginLookupScalesWithRows :
    ∀ count ,
    dependencyOriginLookups (perRowForeignKeyLookupReceipt count) ≡ count
  perRowDependencyOriginLookupScalesWithRows count = refl

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  record ProducerCertifiedTokenReferenceAdmission
    (Symbol Origin : Set)
    (authority : TokenReferenceAuthority Symbol Origin)
    : Set₁ where
    field
      certificate : ProducerCertifiedTokenReferences Symbol Origin authority
      finalReferenceFibreExact :
        producerCertifiedTokenRow certificate ≡ lookupCheckedTokenRow certificate
      noPerRowOrthLookup :
        ∀ count ,
        orthSymbolLookups (producerCertifiedLookupReceipt count) ≡ zero
      noPerRowOriginLookup :
        ∀ count ,
        dependencyOriginLookups (producerCertifiedLookupReceipt count) ≡ zero

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  open ProducerCertifiedTokenReferenceAdmission public

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

  compileProducerCertifiedTokenReferenceAdmission :
    ∀ {Symbol Origin : Set}
      {authority : TokenReferenceAuthority Symbol Origin}
      (certificate : ProducerCertifiedTokenReferences Symbol Origin authority) ,
    ProducerCertifiedTokenReferenceAdmission Symbol Origin authority
  compileProducerCertifiedTokenReferenceAdmission certificate = record
    { certificate = certificate
    ; finalReferenceFibreExact = producerCertifiedTokenReferenceExact certificate
    ; noPerRowOrthLookup = producerCertifiedHasNoPerRowSymbolLookups
    ; noPerRowOriginLookup = producerCertifiedHasNoPerRowOriginLookups
    }

