/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Agda.Syntax
import AgdaVendor.DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact

/-!
# `DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreRegression`, transliterated

Generated by `tools/agda2lean.py` from the ingested upstream source
`upstream/dashi_agda/agent/itir-producer-complete-token-heads/DASHI/Cognition/PNF/ProducerCertifiedTokenReferenceFibreRegression.agda`.
Do not edit by hand: re-run the translator instead.
-/

open Agda

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreRegression where

  open import Agda.Builtin.Equality

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreRegression where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreRegression where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.Unit

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreRegression where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.Unit
  open import DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreRegression where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.Unit
  open import DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact

  natAuthority : TokenReferenceAuthority Nat Nat
  natAuthority = record
    { SymbolAuthoritative = λ _ => ⊤
    ; OriginAuthoritative = λ _ => ⊤
    }

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreRegression where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.Unit
  open import DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact

  sampleReferences : TokenReferenceFibre Nat Nat
  sampleReferences =
    tokenReferenceFibre
      11 12 13 14 15
      1 1 3 1

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreRegression where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.Unit
  open import DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact

  sampleCertificate : ProducerCertifiedTokenReferences Nat Nat natAuthority
  sampleCertificate = record
    { references = sampleReferences
    ; orthSymbolWitness = tt
    ; lemmaSymbolWitness = tt
    ; posSymbolWitness = tt
    ; tagSymbolWitness = tt
    ; dependencySymbolWitness = tt
    ; lemmaOriginWitness = tt
    ; posOriginWitness = tt
    ; tagOriginWitness = tt
    ; dependencyOriginWitness = tt
    }

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreRegression where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.Unit
  open import DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact

  sampleFinalReferenceFibreExact :
    producerCertifiedTokenRow sampleCertificate
      ≡ lookupCheckedTokenRow sampleCertificate
  sampleFinalReferenceFibreExact =
    producerCertifiedTokenReferenceExact sampleCertificate

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreRegression where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.Unit
  open import DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact

  sampleConsumerExact :
    orthSymbol (producerCertifiedTokenRow sampleCertificate)
      ≡ orthSymbol (lookupCheckedTokenRow sampleCertificate)
  sampleConsumerExact =
    consumerObservationExact sampleCertificate orthSymbol

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreRegression where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.Unit
  open import DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact

  sampleProducerOrthChecksZero :
    orthSymbolLookups (producerCertifiedLookupReceipt 7) ≡ zero
  sampleProducerOrthChecksZero =
    producerCertifiedHasNoPerRowSymbolLookups 7

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreRegression where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.Unit
  open import DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact

  sampleProducerOriginChecksZero :
    dependencyOriginLookups (producerCertifiedLookupReceipt 7) ≡ zero
  sampleProducerOriginChecksZero =
    producerCertifiedHasNoPerRowOriginLookups 7

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreRegression where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.Unit
  open import DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact

  sampleLegacyOrthChecksSeven :
    orthSymbolLookups (perRowForeignKeyLookupReceipt 7) ≡ 7
  sampleLegacyOrthChecksSeven = refl

agda_module DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreRegression where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.Unit
  open import DASHI.Cognition.PNF.ProducerCertifiedTokenReferenceFibreExact

  sampleLegacyOriginChecksSeven :
    dependencyOriginLookups (perRowForeignKeyLookupReceipt 7) ≡ 7
  sampleLegacyOriginChecksSeven = refl

