module DASHI.Physics.Foundations.BidirectionallyAdmissibleHistoryFibreExact where

open import DASHI.Core.Prelude
open import Agda.Builtin.String using (String)

------------------------------------------------------------------------
-- TSFV-native history surface.
--
-- Histories are constrained by both boundary sides before any source
-- weighting, stationary-phase classification, projection, or observation.
-- This owner is deliberately weaker than a dynamical law: it records the
-- globally admissible fibre over a boundary pair and does not assume that the
-- fibre is generated by one forward update map.
------------------------------------------------------------------------

record BidirectionallyAdmissibleHistoryFibre : Set₁ where
  field
    InitialBoundary : Set
    FinalBoundary : Set
    History : Set

    admissibleFromBoth :
      InitialBoundary → FinalBoundary → History → Set

    fibreReading : String

open BidirectionallyAdmissibleHistoryFibre public

record BoundaryPairHistoryWitness
    (surface : BidirectionallyAdmissibleHistoryFibre) : Set where
  field
    initialBoundary : InitialBoundary surface
    finalBoundary : FinalBoundary surface
    history : History surface

    admissibilityWitness :
      admissibleFromBoth surface initialBoundary finalBoundary history

open BoundaryPairHistoryWitness public

------------------------------------------------------------------------
-- Finite specimen: the same initial boundary supports different histories
-- under different final-boundary compatibility conditions.
------------------------------------------------------------------------

data ToyInitialBoundary : Set where
  initialSource : ToyInitialBoundary

data ToyFinalBoundary : Set where
  detectorLeft : ToyFinalBoundary
  detectorRight : ToyFinalBoundary

data ToyHistory : Set where
  leftCompatibleHistory : ToyHistory
  rightCompatibleHistory : ToyHistory
  incompatibleHistory : ToyHistory

data ToyBidiAdmissible :
  ToyInitialBoundary → ToyFinalBoundary → ToyHistory → Set where
  leftHistoryAdmissible :
    ToyBidiAdmissible initialSource detectorLeft leftCompatibleHistory
  rightHistoryAdmissible :
    ToyBidiAdmissible initialSource detectorRight rightCompatibleHistory

canonicalBidirectionallyAdmissibleHistoryFibre :
  BidirectionallyAdmissibleHistoryFibre
canonicalBidirectionallyAdmissibleHistoryFibre =
  record
    { InitialBoundary = ToyInitialBoundary
    ; FinalBoundary = ToyFinalBoundary
    ; History = ToyHistory
    ; admissibleFromBoth = ToyBidiAdmissible
    ; fibreReading =
        "A history belongs to a boundary-pair fibre only after compatibility with both boundary sides; no forward-only generator is assumed."
    }

canonicalLeftBoundaryPairHistoryWitness :
  BoundaryPairHistoryWitness canonicalBidirectionallyAdmissibleHistoryFibre
canonicalLeftBoundaryPairHistoryWitness =
  record
    { initialBoundary = initialSource
    ; finalBoundary = detectorLeft
    ; history = leftCompatibleHistory
    ; admissibilityWitness = leftHistoryAdmissible
    }

canonicalRightBoundaryPairHistoryWitness :
  BoundaryPairHistoryWitness canonicalBidirectionallyAdmissibleHistoryFibre
canonicalRightBoundaryPairHistoryWitness =
  record
    { initialBoundary = initialSource
    ; finalBoundary = detectorRight
    ; history = rightCompatibleHistory
    ; admissibilityWitness = rightHistoryAdmissible
    }

leftAndRightCompatibleHistoriesAreDistinct :
  leftCompatibleHistory ≡ rightCompatibleHistory → ⊥
leftAndRightCompatibleHistoriesAreDistinct ()

record BidirectionalAdmissibilityBoundary : Set where
  constructor bidirectionalAdmissibilityBoundary
  field
    admissibleMeansForwardGenerated : Bool
    admissibleMeansForwardGeneratedIsFalse :
      admissibleMeansForwardGenerated ≡ false

    finalBoundaryCompatibilityIsBackwardSignalling : Bool
    finalBoundaryCompatibilityIsBackwardSignallingIsFalse :
      finalBoundaryCompatibilityIsBackwardSignalling ≡ false

    admissibleMeansStronglyWeighted : Bool
    admissibleMeansStronglyWeightedIsFalse :
      admissibleMeansStronglyWeighted ≡ false

    admissibleMeansObserved : Bool
    admissibleMeansObservedIsFalse :
      admissibleMeansObserved ≡ false

canonicalBidirectionalAdmissibilityBoundary :
  BidirectionalAdmissibilityBoundary
canonicalBidirectionalAdmissibilityBoundary =
  bidirectionalAdmissibilityBoundary
    false refl
    false refl
    false refl
    false refl
