import Welds.YMBidiLatticeShell

#check Welds.YMBidiLatticeShell.cmp116VolumeMarkedTotalEnergyLe
#check Welds.YMBidiLatticeShell.cmp116VolumeMarkedFarShellEnergyTsumLe
#check Welds.YMBidiLatticeShell.cmp116VolumeCauchyShellEstimate
