module DASHI.ItalPersistenceIndigenousIntersectionalValidation where

import DASHI.Culture.RastafariItalReturnPersistenceExact
import DASHI.Culture.RastafariItalIndigenousIntersectionalBoundaryExact
import DASHI.Culture.RastafariItalIndigenousKnowledgeDirectReuseExact
import DASHI.Culture.RastafariItalGovernedLineageCrossPollinationExact
import DASHI.Culture.RastafariItalBenefitReturnGovernanceExact
import DASHI.Culture.RastafariItalLoopControlGovernanceExact
import DASHI.Culture.RastafariItalSocioTechnicalPowerDirectReuseExact
import DASHI.Culture.MarxLabourUnionSourceBoundaryExact
import DASHI.Culture.RastafariItalExitRefusalMarxUnionCrossPollinationExact
import DASHI.Culture.RastafariItalCollectiveOptionConeEfficacyExact
