module DASHI.Cognition.LanguagePhaseEverything where

import DASHI.Cognition.AnesthesiaLanguagePhaseControl
import DASHI.Cognition.KepplerGlutamateZPFMDLTest
import DASHI.Cognition.ResidualPhaseEmpiricalContact
import DASHI.Cognition.ResidualPhaseGeometry
import DASHI.Cognition.VisualCompressionAttractors
