{-# OPTIONS --safe #-}
module DASHI.Physics.YangMills.BalabanCMP98Equation120SelectedSemanticsRound217Exact where

------------------------------------------------------------------------
-- ROUND217 BIDI: STRUCTURE THE LAST R216 SOURCE-SEMANTICS PAYMENT.
--
-- R215/R216 now own qSource construction.  The remaining question is not
-- another q theorem; it is whether the objects feeding that construction are
-- the already-selected physical CMP98 objects.
--
-- The repository has already separated those authorities:
--   * R170: literal Eq.(119) background bonds are the selected variational
--           background bonds;
--   * R175: the selected background already owns the principal-log cut/chart;
--   * R177/R178: the Eq.(119) Lie carrier is literal SU2LieAlgebra and its
--                g/g^-1/Ad operators are generated by the existing Federbush
--                convention family.
--
-- This owner packages those existing receipts without allowing them to replace
-- R215's qSource.  In particular, the historical selected-cut derivative
-- producer may be used as evidence for source semantics, but its inherited
-- qSource field has no authority here.
------------------------------------------------------------------------

open import Agda.Builtin.Nat using (Nat)

open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.YangMills.BalabanSU2LieAlgebraCarrier as Lie
import DASHI.Physics.YangMills.BalabanCMP98MultiscaleAveragingDerivativeRound126Exact as R126
import DASHI.Physics.YangMills.BalabanCMP98Equation119OneStepDerivativeRound146Exact as R146
import DASHI.Physics.YangMills.BalabanCMP98Equation119CanonicalCoarseSegmentRound158Exact as R158
import DASHI.Physics.YangMills.BalabanCMP98Equation119DifferentialDexpRound159Exact as R159
import DASHI.Physics.YangMills.BalabanCMP98Equation119SelectedBackgroundBondWeldRound170Exact as R170
import DASHI.Physics.YangMills.BalabanCMP98Equation119SelectedExistingCutRound175Exact as R175
import DASHI.Physics.YangMills.BalabanCMP98Equation119FederbushCalculusReuseRound177Exact as R177
import DASHI.Physics.YangMills.BalabanCMP98Equation119FederbushSelectedCutProducerRound178Exact as R178

record Equation120SelectedSourceSemantics
    {C n Value group CoarseField FineField LieCarrier}
    (source : R158.CanonicalL13Equation119Source C n Value group) : Set₁ where
  field
    selectedBackgroundWeld :
      R170.SelectedBackgroundBondWeld
        {CoarseField = CoarseField}
        {FineField = FineField}
        {Lie = LieCarrier}
        source

    selectedCut :
      R175.SelectedExistingCutInputs source selectedBackgroundWeld

open Equation120SelectedSourceSemantics public

-- Specialize the Lie-calculus side to the literal SU(2) carrier already used by
-- R178. This record intentionally carries no qSource equality.
record Equation120SelectedSU2Semantics
    {n Value group CoarseField FineField}
    (source : R158.CanonicalL13Equation119Source
      R178.su2SignedCarrier n Value group) : Set₁ where
  field
    selectedSource :
      Equation120SelectedSourceSemantics
        {CoarseField = CoarseField}
        {FineField = FineField}
        {LieCarrier = Lie.SU2LieAlgebra}
        source

    federbushConvention : R177.ExistingFederbushConventionFamily

open Equation120SelectedSU2Semantics public

selectedBackgroundReceipt :
  ∀ {n Value group CoarseField FineField}
    {source : R158.CanonicalL13Equation119Source
      R178.su2SignedCarrier n Value group} →
  Equation120SelectedSU2Semantics
    {CoarseField = CoarseField} {FineField = FineField} source →
  R170.SelectedBackgroundBondWeld
    {CoarseField = CoarseField}
    {FineField = FineField}
    {Lie = Lie.SU2LieAlgebra}
    source
selectedBackgroundReceipt semantics =
  selectedBackgroundWeld (selectedSource semantics)

selectedCutReceipt :
  ∀ {n Value group CoarseField FineField}
    {source : R158.CanonicalL13Equation119Source
      R178.su2SignedCarrier n Value group}
    (semantics : Equation120SelectedSU2Semantics
      {CoarseField = CoarseField} {FineField = FineField} source) →
  R175.SelectedExistingCutInputs source
    (selectedBackgroundReceipt semantics)
selectedCutReceipt semantics = selectedCut (selectedSource semantics)

selectedFederbushCalculus :
  ∀ {n Value group CoarseField FineField}
    {source : R158.CanonicalL13Equation119Source
      R178.su2SignedCarrier n Value group} →
  Equation120SelectedSU2Semantics
    {CoarseField = CoarseField} {FineField = FineField} source →
  R159.UniformAdjointDifferentialCalculus
    (R126.Vector (R146.additive R178.su2SignedCarrier))
selectedFederbushCalculus semantics =
  R177.asUniformAdjointDifferentialCalculus (federbushConvention semantics)

cmp98Equation120SelectedSemanticsRound217Level : ProofLevel
cmp98Equation120SelectedSemanticsRound217Level = machineChecked

cmp98Equation120SelectedBackgroundReuseRound217Level : ProofLevel
cmp98Equation120SelectedBackgroundReuseRound217Level = machineChecked

cmp98Equation120SelectedFederbushReuseRound217Level : ProofLevel
cmp98Equation120SelectedFederbushReuseRound217Level = machineChecked

-- These are now the literal remaining source receipts rather than one opaque
-- `selected semantics` flag. Under the selected-background architecture they
-- are recovery/adaptation targets, not new qSource mathematics.
literalCMP98SelectedBackgroundWeldRound217Level : ProofLevel
literalCMP98SelectedBackgroundWeldRound217Level = conditional

literalCMP98SelectedCutRadiusRound217Level : ProofLevel
literalCMP98SelectedCutRadiusRound217Level = conditional

literalCMP98PrincipalYFederbushIdentificationRound217Level : ProofLevel
literalCMP98PrincipalYFederbushIdentificationRound217Level = conditional

-- The perturbation projection / scalar-action fields entering R216 must still
-- be the literal physical A-coordinate maps. This is deliberately kept
-- separate from background-link and principal-chart authority.
literalCMP98PerturbationCoordinateSemanticsRound217Level : ProofLevel
literalCMP98PerturbationCoordinateSemanticsRound217Level = conditional
