module DASHI.Physics.YangMills.BalabanKKTConstraintImageEnergyContractionExact where

------------------------------------------------------------------------
-- PRIMARY SOURCES
--
-- Roger Penrose,
-- "A Generalized Inverse for Matrices", Proceedings of the Cambridge
-- Philosophical Society 51 (1955), 406--413.
-- DOI: 10.1017/S0305004100030401.
--
-- Franco Brezzi,
-- "On the Existence, Uniqueness and Approximation of Saddle-Point Problems
-- Arising from Lagrangian Multipliers", RAIRO Analyse Numerique 8 (1974),
-- 129--151. No DOI assigned to the cited article.
--
-- Roger A. Horn and Charles R. Johnson,
-- "Matrix Analysis", second edition, Cambridge University Press, 2012.
-- DOI: 10.1017/CBO9781139020411.
--
-- DASHI CONTRIBUTION
--
-- The G2 Green vectors are generated by the KKT constraint map L.  On such a
-- vector v=Lx the Moore--Penrose quadratic form needs no global K+ norm bound:
--
--   <Lx,K+Lx>
--     = ||L* K+ Lx||^2
--     = ||repair(x)||^2
--     <= ||x||^2.
--
-- This is sharper than the Schur fallback and removes K+ entirely from any
-- G2 energy estimate once an explicit state-space preimage is known.
------------------------------------------------------------------------

open import Agda.Builtin.Equality using (_≡_; refl)
open import Data.Rational.Base as ℚ using (0ℚ; _+_; _≤_)
import Data.Rational.Properties as ℚP
import Data.Rational.Tactic.RingSolver as ℚRing
open import Relation.Binary.PropositionalEquality using (subst; sym; trans)

open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.YangMills.BalabanFiniteRectangularRationalExact as Rect
import DASHI.Physics.YangMills.BalabanP33FiniteKKTAdmissibleProjectorExact as KKT
import DASHI.Physics.YangMills.BalabanP33FiniteKKTPseudoinverseProjectorExact as Pseudo
import DASHI.Physics.YangMills.BalabanKKTGramPseudoinversePositiveExact as Positive
import DASHI.Physics.YangMills.BalabanSelectedConstraintAtomGreenExpansionExact as Green

projectRepairOrthogonal :
  ∀ {Multiplier}
    (pseudoData : Pseudo.FiniteKKTPseudoinverseData Multiplier)
    vector →
  KKT.stateDot
    (Pseudo.admissibleProject pseudoData vector)
    (Pseudo.constraintRepair pseudoData vector)
  ≡ 0ℚ
projectRepairOrthogonal pseudoData vector =
  let
    project = Pseudo.admissibleProject pseudoData vector
    repairMultiplier =
      Pseudo.pseudoApply pseudoData (Pseudo.constraintApply pseudoData vector)

    repairToAdjoint :
      KKT.stateDot project (Pseudo.constraintRepair pseudoData vector)
      ≡ KKT.stateDot project
          (Pseudo.constraintAdjointApply pseudoData repairMultiplier)
    repairToAdjoint = refl

    moveToConstraint :
      KKT.stateDot project
        (Pseudo.constraintAdjointApply pseudoData repairMultiplier)
      ≡ Rect.finiteDot
          (Pseudo.multiplierCarrier pseudoData)
          (Pseudo.constraintApply pseudoData project)
          repairMultiplier
    moveToConstraint = sym
      (Rect.rectangularAdjointExact
        (Pseudo.multiplierCarrier pseudoData)
        KKT.physicalStateCarrier
        (Pseudo.constraintMatrix pseudoData)
        project repairMultiplier)
  in
  trans repairToAdjoint
    (trans moveToConstraint
      (trans
        (Green.finiteDotLeftPointwiseCong
          (Pseudo.multiplierCarrier pseudoData)
          (Pseudo.constraintZero
            (Pseudo.projectConstraintZero pseudoData vector)))
        (Rect.finiteDotZeroLeft
          (Pseudo.multiplierCarrier pseudoData) repairMultiplier)))

repairProjectOrthogonal :
  ∀ {Multiplier}
    (pseudoData : Pseudo.FiniteKKTPseudoinverseData Multiplier)
    vector →
  KKT.stateDot
    (Pseudo.constraintRepair pseudoData vector)
    (Pseudo.admissibleProject pseudoData vector)
  ≡ 0ℚ
repairProjectOrthogonal pseudoData vector =
  trans
    (Rect.finiteDotSymmetric KKT.physicalStateCarrier
      (Pseudo.constraintRepair pseudoData vector)
      (Pseudo.admissibleProject pseudoData vector))
    (projectRepairOrthogonal pseudoData vector)

stateDecompositionPointwise :
  ∀ {Multiplier}
    (pseudoData : Pseudo.FiniteKKTPseudoinverseData Multiplier)
    vector coordinate →
  vector coordinate
  ≡ Rect.vectorAdd
      (Pseudo.admissibleProject pseudoData vector)
      (Pseudo.constraintRepair pseudoData vector)
      coordinate
stateDecompositionPointwise pseudoData vector coordinate =
  ℚRing.solve-∀
    (vector coordinate)
    (Pseudo.constraintRepair pseudoData vector coordinate)

pseudoStatePythagorean :
  ∀ {Multiplier}
    (pseudoData : Pseudo.FiniteKKTPseudoinverseData Multiplier)
    vector →
  KKT.stateNormSq vector
  ≡ KKT.stateNormSq (Pseudo.admissibleProject pseudoData vector)
    + KKT.stateNormSq (Pseudo.constraintRepair pseudoData vector)
pseudoStatePythagorean pseudoData vector =
  trans
    (KKT.stateNormPointwiseCong
      (stateDecompositionPointwise pseudoData vector))
    (Rect.normSqAddOrthogonal
      KKT.physicalStateCarrier
      (Pseudo.admissibleProject pseudoData vector)
      (Pseudo.constraintRepair pseudoData vector)
      (projectRepairOrthogonal pseudoData vector)
      (repairProjectOrthogonal pseudoData vector))

repairNormContraction :
  ∀ {Multiplier}
    (pseudoData : Pseudo.FiniteKKTPseudoinverseData Multiplier)
    vector →
  KKT.stateNormSq (Pseudo.constraintRepair pseudoData vector)
  ≤ KKT.stateNormSq vector
repairNormContraction pseudoData vector =
  let
    projectNormNonnegative =
      KKT.stateNormSqNonnegative (Pseudo.admissibleProject pseudoData vector)
    repairNorm = KKT.stateNormSq (Pseudo.constraintRepair pseudoData vector)
    belowSum :
      repairNorm
      ≤ KKT.stateNormSq (Pseudo.admissibleProject pseudoData vector) + repairNorm
    belowSum =
      subst
        (λ lower → lower ≤
          KKT.stateNormSq (Pseudo.admissibleProject pseudoData vector) + repairNorm)
        (sym (ℚP.+-identityˡ repairNorm))
        (ℚP.+-mono-≤ projectNormNonnegative ℚP.≤-refl)
  in
  subst
    (λ upper → repairNorm ≤ upper)
    (sym (pseudoStatePythagorean pseudoData vector))
    belowSum

constraintImagePseudoEnergyExact :
  ∀ {Multiplier}
    (pseudoData : Pseudo.FiniteKKTPseudoinverseData Multiplier)
    vector →
  Positive.pseudoQuadratic pseudoData
    (Pseudo.constraintApply pseudoData vector)
  ≡ KKT.stateNormSq (Pseudo.constraintRepair pseudoData vector)
constraintImagePseudoEnergyExact pseudoData vector =
  Positive.pseudoQuadraticAsAdjointNormSq
    pseudoData (Pseudo.constraintApply pseudoData vector)

constraintImagePseudoEnergyContraction :
  ∀ {Multiplier}
    (pseudoData : Pseudo.FiniteKKTPseudoinverseData Multiplier)
    vector →
  Positive.pseudoQuadratic pseudoData
    (Pseudo.constraintApply pseudoData vector)
  ≤ KKT.stateNormSq vector
constraintImagePseudoEnergyContraction pseudoData vector =
  subst
    (λ lower → lower ≤ KKT.stateNormSq vector)
    (constraintImagePseudoEnergyExact pseudoData vector)
    (repairNormContraction pseudoData vector)

kktConstraintImageEnergyContractionLevel : ProofLevel
kktConstraintImageEnergyContractionLevel = machineChecked
