module DASHI.Physics.YangMills.BalabanClayGate4Attachment254IntegratedLedger where

open import DASHI.Physics.YangMills.CompactLieProofLevel

import DASHI.Physics.YangMills.BalabanClayGate4Attachment254CompletionLedger as Completion
import DASHI.Physics.YangMills.BalabanClayGate4PhysicalAveragingConventionSelectionExact as Convention
import DASHI.Physics.YangMills.BalabanClayGate4PhysicalWeightedL2NormalizationExact as WeightedL2
import DASHI.Physics.YangMills.BalabanClayGate4WeightedSchurSummableSlackReuseExact as WeightedSlack
import DASHI.Physics.YangMills.BalabanClayGate4T3SelfAdjointFormNormReuseExact as T3FormNorm
import DASHI.Physics.YangMills.BalabanClayGate4FiveChannelSelfAdjointOperatorBoundExact as FiveChannel
import DASHI.Physics.YangMills.BalabanClayGate4T3FiveChannelSelfAdjointReuseExact as T3FiveChannel
import DASHI.Physics.YangMills.BalabanClayGate4FiniteTangentMatrixRepresentationExact as Matrix
import DASHI.Physics.YangMills.BalabanClayGate4FiniteMatrixSpectrumDeterminantAssemblyExact as MatrixDeterminant

completionLedgerLevel = Completion.attachment254CompletionLedgerLevel

gate4CMP109ConventionSelectionLevel =
  Convention.gate4CMP109ConventionSelectionLevel
gate4CMP109PhysicalMeaningAssemblyLevel =
  Convention.gate4CMP109PhysicalMeaningAssemblyLevel

literalFiniteWeightedL2NormLevel =
  WeightedL2.literalFiniteWeightedL2NormLevel
physicalWeightedL2MeaningAssemblyLevel =
  WeightedL2.physicalWeightedL2MeaningAssemblyLevel
formalTransposePhysicalAdjointUniquenessLevel =
  WeightedL2.formalTransposePhysicalAdjointUniquenessLevel

weightedSchurNearContractionAdapterLevel =
  WeightedSlack.weightedSchurNearContractionAdapterLevel
weightedSchurSummableSlackEnvelopeLevel =
  WeightedSlack.weightedSchurSummableSlackEnvelopeLevel

t3SelfAdjointFormNormAttachmentLevel =
  T3FormNorm.t3SelfAdjointFormNormAttachmentLevel
t3RestrictedFormToOperatorNormLevel =
  T3FormNorm.t3RestrictedFormToOperatorNormLevel

fiveChannelAbsoluteFormAggregationLevel =
  FiveChannel.fiveChannelAbsoluteFormAggregationLevel
fiveChannelSelfAdjointOperatorNormLevel =
  FiveChannel.fiveChannelSelfAdjointOperatorNormLevel
t3FiveChannelLiteralInstantiationLevel =
  T3FiveChannel.t3FiveChannelLiteralInstantiationLevel
t3FiveChannelOperatorNormAssemblyLevel =
  T3FiveChannel.t3FiveChannelOperatorNormAssemblyLevel

finiteTangentBasisCarrierLevel = Matrix.finiteTangentBasisCarrierLevel
restrictedHessianMatrixSplitLevel = Matrix.restrictedHessianMatrixSplitLevel
matrixOperatorNormTransportLevel = Matrix.matrixOperatorNormTransportLevel
selfAdjointMatrixHermitianTransportLevel =
  Matrix.selfAdjointMatrixHermitianTransportLevel

finiteMatrixSpectrumDeterminantAssemblyLevel =
  MatrixDeterminant.finiteMatrixSpectrumDeterminantAssemblyLevel
assembledPhysicalMatrixSplitLevel =
  MatrixDeterminant.assembledPhysicalMatrixSplitLevel
assembledInverseNormBoundLevel =
  MatrixDeterminant.assembledInverseNormBoundLevel
assembledPrimaryDeterminantMultiplierLevel =
  MatrixDeterminant.assembledPrimaryDeterminantMultiplierLevel

physicalCMP109LiteralMapInputsLevel =
  Convention.physicalCMP109LiteralMapInputsLevel
physicalCMP109DerivativeInputsLevel =
  Convention.physicalCMP109DerivativeInputsLevel
physicalCMP109SupportInputsLevel =
  Convention.physicalCMP109SupportInputsLevel
physicalCMP109NormalizationInputsLevel =
  Convention.physicalCMP109NormalizationInputsLevel
cmp98KernelEstimateTransferToCMP109InputsLevel =
  Convention.cmp98KernelEstimateTransferToCMP109InputsLevel

physicalCMP109FineCoarseWeightInputsLevel =
  WeightedL2.physicalCMP109FineCoarseWeightInputsLevel
physicalInnerProductScalingInputsLevel =
  WeightedL2.physicalInnerProductScalingInputsLevel
physicalFormalTransposeCharacterizationInputsLevel =
  WeightedL2.physicalFormalTransposeCharacterizationInputsLevel

physicalWeightedSchurStateMeaningInputsLevel =
  WeightedSlack.physicalWeightedSchurStateMeaningInputsLevel
physicalWeightedSchurNearFactorBudgetInputsLevel =
  WeightedSlack.physicalWeightedSchurNearFactorBudgetInputsLevel
physicalWeightedSchurSlackSummabilityInputsLevel =
  WeightedSlack.physicalWeightedSchurSlackSummabilityInputsLevel

physicalT3HessianSelfAdjointnessInputsLevel =
  T3FormNorm.physicalT3HessianSelfAdjointnessInputsLevel
physicalT3RestrictedFormAbsoluteBoundInputsLevel =
  T3FormNorm.physicalT3RestrictedFormAbsoluteBoundInputsLevel
physicalT3InnerProductNormIdentificationInputsLevel =
  T3FormNorm.physicalT3InnerProductNormIdentificationInputsLevel

physicalFiveChannelRemainderSplitInputsLevel =
  FiveChannel.physicalFiveChannelRemainderSplitInputsLevel
physicalFiveChannelAbsoluteFormBoundsInputsLevel =
  FiveChannel.physicalFiveChannelAbsoluteFormBoundsInputsLevel
physicalT3FiveChannelFormBoundsInputsLevel =
  T3FiveChannel.physicalT3FiveChannelFormBoundsInputsLevel
physicalT3RemainderSelfAdjointnessInputsLevel =
  T3FiveChannel.physicalT3RemainderSelfAdjointnessInputsLevel
physicalT3FiveChannelNormMeaningInputsLevel =
  T3FiveChannel.physicalT3FiveChannelNormMeaningInputsLevel

physicalGaugeFixedTangentBasisInputsLevel =
  Matrix.physicalGaugeFixedTangentBasisInputsLevel
physicalRestrictedMatrixRepresentationInputsLevel =
  Matrix.physicalRestrictedMatrixRepresentationInputsLevel
physicalMatrixActionInjectivityInputsLevel =
  Matrix.physicalMatrixActionInjectivityInputsLevel
physicalMatrixOperatorNormIdentificationInputsLevel =
  Matrix.physicalMatrixOperatorNormIdentificationInputsLevel

physicalTangentMatrixAssemblyInputsLevel =
  MatrixDeterminant.physicalTangentMatrixAssemblyInputsLevel
physicalCoercivitySpectrumIdentificationInputsLevel =
  MatrixDeterminant.physicalCoercivitySpectrumIdentificationInputsLevel
physicalDeterminantMatrixIdentificationInputsLevel =
  MatrixDeterminant.physicalDeterminantMatrixIdentificationInputsLevel
physicalInverseNormIdentificationInputsLevel =
  MatrixDeterminant.physicalInverseNormIdentificationInputsLevel

attachment254IntegratedLedgerLevel : ProofLevel
attachment254IntegratedLedgerLevel = machineChecked
