module DASHI.Physics.YangMills.BalabanUnifiedFeshbachLossTailExact where

------------------------------------------------------------------------
-- ROUND69: ONE LOCAL GEOMETRIC FESHBACH LOSS -> UNIFORM TOTAL LOSS CEILING
--
-- PRIMARY SOURCES / CALIBRATION
--
-- Volker Bach, Thomas Chen, Juerg Froehlich and Israel Michael Sigal,
-- "Smooth Feshbach Map and Operator-Theoretic Renormalization Group Methods",
-- Journal of Functional Analysis 203 (2003), 44--92.
-- DOI: 10.1016/S0022-1236(03)00057-0.
--
-- David C. Brydges, John Dimock and Thomas R. Hurd,
-- "Estimates on Renormalization Group Transformations",
-- Canadian Journal of Mathematics 50 (1998), 756--793.
-- DOI: 10.4153/CJM-1998-041-5.
--
-- DASHI CONTRIBUTION
--
-- L6 should not ask for an opaque total spectral-loss number.  If the actual
-- same-object Schur/Feshbach loss at RG depth n obeys
--
--   loss_n <= L (17/32)^n,
--
-- then the Round69 geometric-tail theorem gives every finite accumulated loss
-- the common ceiling
--
--   ell = (32/15) L.
--
-- Hence the physical mass-gap budget reduces to one local loss amplitude L and
-- the strict comparison (32/15)L < m0.
------------------------------------------------------------------------

open import Agda.Builtin.Nat using (Nat; zero)
open import Data.Rational.Base as ℚ using (ℚ; 0ℚ; _*_; _≤_; _<_)
import Data.Rational.Tactic.RingSolver as ℚRing
open import Relation.Binary.PropositionalEquality using (subst)

open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.YangMills.BalabanUnifiedSeventeenThirtySecondTailModulusExact as Tail
import DASHI.Physics.YangMills.BalabanUnifiedSeventeenThirtySecondIterationExact as Iter

record GeometricFeshbachLoss : Set₁ where
  field
    lossAtScale : Nat → ℚ
    amplitude : ℚ
    amplitudeNonnegative : 0ℚ ≤ amplitude
    lossBound : ∀ n → lossAtScale n ≤ amplitude * Iter.thetaPower n
open GeometricFeshbachLoss public

asIncrementMajorant : GeometricFeshbachLoss → Tail.GeometricUnifiedIncrementMajorant
asIncrementMajorant dataSet = record
  { Tail.GeometricUnifiedIncrementMajorant.increment = lossAtScale dataSet
  ; Tail.GeometricUnifiedIncrementMajorant.amplitude = amplitude dataSet
  ; Tail.GeometricUnifiedIncrementMajorant.amplitudeNonnegative =
      amplitudeNonnegative dataSet
  ; Tail.GeometricUnifiedIncrementMajorant.incrementBound = lossBound dataSet
  }

accumulatedLoss : GeometricFeshbachLoss → Nat → ℚ
accumulatedLoss dataSet count =
  Tail.finiteIncrementTail (asIncrementMajorant dataSet) zero count

totalLossCeiling : GeometricFeshbachLoss → ℚ
totalLossCeiling dataSet = Tail.tailFactor * amplitude dataSet

accumulatedLossBelowUniformCeiling :
  (dataSet : GeometricFeshbachLoss) → ∀ count →
  accumulatedLoss dataSet count ≤ totalLossCeiling dataSet
accumulatedLossBelowUniformCeiling dataSet count =
  let
    base = Tail.finiteIncrementTailModulus
      (asIncrementMajorant dataSet) zero count
  in
  subst
    (λ right → accumulatedLoss dataSet count ≤ right)
    (ℚRing.solve-∀ Tail.tailFactor (amplitude dataSet))
    base

record TerminalFloorWithGeometricLoss : Set₁ where
  field
    terminalFloor : ℚ
    geometricLoss : GeometricFeshbachLoss
    geometricLossFitsTerminalFloor :
      totalLossCeiling geometricLoss < terminalFloor
open TerminalFloorWithGeometricLoss public

geometricFeshbachLossTailLevel : ProofLevel
geometricFeshbachLossTailLevel = machineChecked

-- Remaining physical L6 estimate: show the SAME scale-to-scale Feshbach loss
-- generated by the literal transfer/RG map is bounded by one amplitude times
-- (17/32)^n.  The all-depth total loss then costs no new analysis.
physicalGeometricFeshbachLossLevel : ProofLevel
physicalGeometricFeshbachLossLevel = conditional
