{-# OPTIONS --safe #-}
module DASHI.Physics.YangMills.BalabanCMP116CanonicalSelectedT5ApplicationRound339Exact where

------------------------------------------------------------------------
-- ROUND339 / TWO-COORDINATE SELECTED-T5 CMP116 APPLICATION
--
-- R338 removes two representational residuals from the generic R334/R1130
-- application ABI:
--
-- * pair admissibility is the canonical common-domain membership generated by
--   R114;
-- * source order is the ordinary rational order used by the selected T5
--   consumer.
--
-- Therefore, after one canonical source theorem payment, the selected-T5 H1
-- application needs only:
--
--   A. same-object magnitude identification;
--   B. source-envelope -> selected rooted-shell quantitative calibration.
--
-- This owner proves that those two coordinates compile directly into the
-- existing proof-bearing source application and hence R320.  Neither coordinate
-- is claimed inhabited here.
------------------------------------------------------------------------

open import Agda.Builtin.Bool using (Bool; true; false)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Data.Rational.Base as ℚ using (ℚ; _≤_)

open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.YangMills.BalabanCMP116CommonAnalyticRadiusRound103Exact as Common
import DASHI.Physics.YangMills.BalabanCMP116CanonicalCommonRadiusRound104Exact as R104
import DASHI.Physics.YangMills.BalabanCMP116CanonicalRadiusToCommonDomainRound114Exact as R114
import DASHI.Physics.YangMills.BalabanClayT5PhysicalMeasureGramContinuityExact as Gram
import DASHI.Physics.YangMills.BalabanConnectedCovarianceExpectationLimitRound278Exact as R278
import DASHI.Physics.YangMills.NormalizedTwoSourceConnectedCumulantExact as Cumulant
import DASHI.Physics.YangMills.BalabanClayT2TraversalRootedShellExact as Shell
import DASHI.Physics.YangMills.BalabanT5UnlocalizedJSourceLocalizationRound318Exact as R318
import DASHI.Physics.YangMills.BalabanT5DirectSelectedMarkedDecayRound320Exact as R320
import DASHI.Physics.YangMills.BalabanCMP116PublishedAuthoritySelectedT5ApplicationExact as Application
import DASHI.Physics.YangMills.BalabanCMP116CanonicalCommonDomainSourceRound338Exact as R338

record CanonicalSelectedT5CMP116Application
    {Measure TestObservable : Set}
    {dataSet : Gram.PhysicalMeasureConvergenceData Measure TestObservable ℚ}
    {extension : R278.ScalarCovarianceConvergenceExtension dataSet}
    (base : R318.UnlocalizedT5StateFamilyJPresentation dataSet extension)
    (demands : R104.CMP116FiniteNormalizedAnalyticDemands)
    (source : R338.CanonicalCommonDomainCMP116Source base demands)
    : Set₁ where
  field
    sourceMagnitudeIsSelectedMagnitude : ∀ cutoff left right →
      R338.differentiatedMagnitude source
        (R318.scaleOf base cutoff)
        (R318.volumeOf base cutoff)
        (Cumulant.sourceDirectionOf (R318.meaning base) left)
        (Cumulant.sourceDirectionOf (R318.meaning base) right)
      ≡
      R278.magnitude extension
        (Cumulant.literalMixedSecondLogDerivative
          (R318.meaning base)
          (Cumulant.sourceDirectionOf (R318.meaning base) left)
          (Cumulant.sourceDirectionOf (R318.meaning base) right)
          cutoff)

    sourceEnvelopeBelowSelectedRootedShell : ∀ cutoff left right →
      R338.sourceEnvelope source
        (R318.scaleOf base cutoff)
        (R318.volumeOf base cutoff)
        (R338.sourceRoot source
          (R318.scaleOf base cutoff)
          (R318.volumeOf base cutoff)
          (Cumulant.sourceDirectionOf (R318.meaning base) left)
          (Cumulant.sourceDirectionOf (R318.meaning base) right))
        (R338.sourceDistance source
          (Cumulant.sourceDirectionOf (R318.meaning base) left)
          (Cumulant.sourceDirectionOf (R318.meaning base) right))
      ≤
      Shell.rootedShell (R318.shellData base)
        (R318.scaleOf base cutoff)
        (R318.volumeOf base cutoff)
        (R318.connectingRoot base cutoff left right)
        (R318.physicalDistance base left right)

open CanonicalSelectedT5CMP116Application public

asHistoricalSelectedT5AuthorityApplication :
  ∀ {Measure TestObservable}
    {dataSet : Gram.PhysicalMeasureConvergenceData Measure TestObservable ℚ}
    {extension : R278.ScalarCovarianceConvergenceExtension dataSet}
    {base : R318.UnlocalizedT5StateFamilyJPresentation dataSet extension}
    {demands : R104.CMP116FiniteNormalizedAnalyticDemands}
    {source : R338.CanonicalCommonDomainCMP116Source base demands} →
  CanonicalSelectedT5CMP116Application base demands source →
  Application.SelectedT5CMP116AuthorityApplication
    base (R338.canonicalSourceBuildsGenericPublishedSource source)
asHistoricalSelectedT5AuthorityApplication
    {base = base} {demands = demands} {source = source} application = record
  { Application.SelectedT5CMP116AuthorityApplication.sourceOrderToRational =
      λ proof → proof
  ; Application.SelectedT5CMP116AuthorityApplication.selectedPairAdmissible =
      λ cutoff left right →
        Common.sourceCoordinateInside
          (R114.canonicalCMP116CommonDomain
            {R318.Scale base} {R318.Volume base} demands)
          (R318.scaleOf base cutoff)
          (R318.volumeOf base cutoff)
  ; Application.SelectedT5CMP116AuthorityApplication.sourceMagnitudeIsSelectedMagnitude =
      sourceMagnitudeIsSelectedMagnitude application
  ; Application.SelectedT5CMP116AuthorityApplication.sourceEnvelopeBelowSelectedRootedShell =
      sourceEnvelopeBelowSelectedRootedShell application
  }

canonicalApplicationBuildsR320Payment :
  ∀ {Measure TestObservable}
    {dataSet : Gram.PhysicalMeasureConvergenceData Measure TestObservable ℚ}
    {extension : R278.ScalarCovarianceConvergenceExtension dataSet}
    {base : R318.UnlocalizedT5StateFamilyJPresentation dataSet extension}
    {demands : R104.CMP116FiniteNormalizedAnalyticDemands}
    {source : R338.CanonicalCommonDomainCMP116Source base demands} →
  CanonicalSelectedT5CMP116Application base demands source →
  R320.DirectSelectedT5MarkedDecayPayment base
canonicalApplicationBuildsR320Payment application =
  Application.sourceAuthorityApplicationBuildsR320Payment
    (asHistoricalSelectedT5AuthorityApplication application)

record Round339Boundary : Set where
  constructor round339-boundary
  field
    pairDomainIndependentApplicationLeaf : Bool
    pairDomainIndependentApplicationLeafIsFalse :
      pairDomainIndependentApplicationLeaf ≡ false

    sourceOrderIndependentApplicationLeaf : Bool
    sourceOrderIndependentApplicationLeafIsFalse :
      sourceOrderIndependentApplicationLeaf ≡ false

    sourceMagnitudeSameObjectStillRequired : Bool
    sourceMagnitudeSameObjectStillRequiredIsTrue :
      sourceMagnitudeSameObjectStillRequired ≡ true

    sourceEnvelopeCalibrationStillRequired : Bool
    sourceEnvelopeCalibrationStillRequiredIsTrue :
      sourceEnvelopeCalibrationStillRequired ≡ true

    twoCoordinatesCompileDirectlyToR320 : Bool
    twoCoordinatesCompileDirectlyToR320IsTrue :
      twoCoordinatesCompileDirectlyToR320 ≡ true

    freshYMDecayEstimateIntroduced : Bool
    freshYMDecayEstimateIntroducedIsFalse :
      freshYMDecayEstimateIntroduced ≡ false

canonicalRound339Boundary : Round339Boundary
canonicalRound339Boundary =
  round339-boundary
    false refl
    false refl
    true refl
    true refl
    true refl
    false refl

round339SourceMagnitudeSameObjectLevel : ProofLevel
round339SourceMagnitudeSameObjectLevel = conditional

round339SourceEnvelopeCalibrationLevel : ProofLevel
round339SourceEnvelopeCalibrationLevel = conditional

round339CompilerLevel : ProofLevel
round339CompilerLevel = machineChecked

clayPromotion : Bool
clayPromotion = false

clayPromotionIsFalse : clayPromotion ≡ false
clayPromotionIsFalse = refl
