module DASHI.Physics.YangMills.Everything where

-- Authoritative Yang--Mills lane rollup.
-- Keep leaf modules out of DASHI.Everything; aggregate them here first.

import DASHI.Physics.YangMills.ClayPromotionAuthorityGate
import DASHI.Physics.YangMills.P01P33ProofSurfaces
import DASHI.Physics.YangMills.YMSupportGraphDistance
import DASHI.Physics.YangMills.MassGapSpectralStatement
import DASHI.Physics.YangMills.OSAxiomBundle

-- Step-V / RG surfaces that the closure audit found were previously unwired.
import DASHI.Physics.YangMills.PostulateInventory
import DASHI.Physics.YangMills.BalabanStepVSpatialKPCertificate
import DASHI.Physics.YangMills.BalabanRGStepVLane
import DASHI.Physics.YangMills.O4CovarianceRestorationGate
import DASHI.Physics.YangMills.YMMassGapRoute
import DASHI.Physics.YangMills.BalabanClayGate4LightweightValidation

-- Existing theorem-level high-alpha route consumed by the operator/domain weld.
import DASHI.Physics.YangMills.BalabanCMP98Equation119PositiveBondSelectedCutFederbushRound184Exact
import DASHI.Physics.YangMills.BalabanCMP98SelectedPhysicalUnitCarrierRound187Exact
import DASHI.Physics.YangMills.BalabanCMP98RawUnitPathHomomorphismRound189Exact
import DASHI.Physics.YangMills.BalabanCMP98Equation119CanonicalP4CutRadiusFirewallExact
import DASHI.Physics.YangMills.BalabanCMP98Equation119PointwiseSemanticSelectedCutExact
import DASHI.Physics.YangMills.BalabanCMP98Equation119DisjunctivePhysicalSourceCutExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PerturbationCarrierWeldExact
import DASHI.Physics.YangMills.BalabanCMP98Equation119TwoCarrierSelectedBondExact
import DASHI.Physics.YangMills.BalabanRationalUnitQuaternionRealLieAdjointExact
import DASHI.Physics.YangMills.BalabanCMP98Equation119GeometryRelativeContourExact
import DASHI.Physics.YangMills.BalabanCMP98Path13TwoCarrierSourceFamilyExact
import DASHI.Physics.YangMills.BalabanPath13CanonicalBondCenteredEmbeddingExact
import DASHI.Physics.YangMills.BalabanPath13RadiusSixWalkAgreementExact
import DASHI.Physics.YangMills.BalabanCMP98Path13ReducedFamilyGeometryExact
import DASHI.Physics.YangMills.BalabanCMP98Path13RelativeContourPrincipalImageExact
import DASHI.Physics.YangMills.BalabanPath13RadiusOperatorDefectRouteExact
import DASHI.Physics.YangMills.BalabanPath13RadiusPrincipalImageRouteExact
import DASHI.Physics.YangMills.BalabanPath13SelectedVariationalRadiusExact
import DASHI.Physics.YangMills.BalabanPath13SelectedBackgroundRadiusFibreExact
import DASHI.Physics.YangMills.BalabanPath13SelectedBackgroundOperatorChartExact
import DASHI.Physics.YangMills.BalabanCMP98Path13ReducedTwoCarrierSourceFamilyExact
import DASHI.Physics.YangMills.BalabanCMP98Path13VariationalRadiusSourceFamilyExact
import DASHI.Physics.YangMills.BalabanR208BishopLegacyRingEmbeddingExact
import DASHI.Physics.YangMills.BalabanCMP98Path13BishopBridgeSourceFamilyExact
import DASHI.Physics.YangMills.BalabanCMP98Path13DirectCalculusSourceFamilyExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PreferredDirectCalculusSourceFamilyExact
import DASHI.Physics.YangMills.BalabanCMP98Path13UniformCalculusDecompositionExact
import DASHI.Physics.YangMills.BalabanCMP98Path13SplitCalculusPreferredSourceFamilyExact
import DASHI.Physics.YangMills.BalabanCMP98Path13DexpInversePairExact
import DASHI.Physics.YangMills.BalabanCMP98Path13ReducedAdjointExpFamilyExact
import DASHI.Physics.YangMills.BalabanCMP98Path13MinimalSemanticCalculusExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PreferredMinimalSemanticSourceFamilyExact

-- Source-sign correction: the printed CMP98 Eq. (119) roles are
-- dexpPlus/Jplus/Ad(exp), despite historical compatibility field names.
import DASHI.Physics.YangMills.BalabanCMP98Path13PrintedSemanticOperatorsExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PrintedRoleSourceFamilyExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PrintedOperatorChartWeldExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PreferredPrintedRoleSourceFamilyExact
import DASHI.Physics.YangMills.BalabanPath13Eq119PrintedRoleCorrectionProvenanceExact

-- T3 right-Jacobian cross-pollination into the corrected printed-role path.
import DASHI.Physics.YangMills.BalabanCMP98Path13T3PrintedOperatorAdapterExact
import DASHI.Physics.YangMills.BalabanCMP98Path13T3SelectedPrintedSemanticsExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PreferredT3PrintedRoleSourceFamilyExact
import DASHI.Physics.YangMills.BalabanPath13Eq119T3PrintedRoleProvenanceExact

-- Preferred T3 scalar boundary: Eq. (119) consumes only the rational->legacy
-- ring embedding. Bishop completeness/convergence remains a compatibility
-- producer, not a primitive Path13 source payment.
import DASHI.Physics.YangMills.BalabanCMP98Path13PreferredT3MinimalScalarSourceFamilyExact
import DASHI.Physics.YangMills.BalabanPath13Eq119T3MinimalScalarProvenanceExact

-- Split Path13 physics from R171's source-independent standard representation.
import DASHI.Physics.YangMills.BalabanPath13SplitPhysicalStandardOperatorCutExact
import DASHI.Physics.YangMills.BalabanPath13SplitPhysicalPrincipalImageRouteExact
import DASHI.Physics.YangMills.BalabanCMP98Path13SplitT3SelectedSemanticsExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PreferredSplitPhysicalT3SourceFamilyExact
import DASHI.Physics.YangMills.BalabanPath13Eq119SplitPhysicalStandardProvenanceExact

-- Direct source-theorem specialization to the literal Path13 carrier.
import DASHI.Physics.YangMills.BalabanPath13VariationalSpecializationExact
import DASHI.Physics.YangMills.BalabanPath13VariationalRadiusFromSpecializationExact

-- Align the selected/cut defect algebra with the R171 operator kernel itself.
import DASHI.Physics.YangMills.BalabanR171OperatorKernelGroupDefectAdapterExact
import DASHI.Physics.YangMills.BalabanPath13R171AlignedVariationalRouteExact

-- Least-privilege current source: minimal printed semantics plus direct 74-link
-- cut budget (37/1024 <= selected radius). T3 and 1/24 are compatibility paths.
import DASHI.Physics.YangMills.BalabanPath13DirectRelative74CutExact
import DASHI.Physics.YangMills.BalabanCMP98Path13PreferredR171AlignedPrintedSourceExact

-- Newest canonical status surface for the source-correct preferred route.
import DASHI.Physics.YangMills.BalabanCMP98Path13CurrentPreferredSourceFrontierExact

-- Finite P33 M7 precursor.
import DASHI.Physics.YangMills.BalabanP33ProjectedHamiltonianDomainExact

-- Preferred M7 operator route.
import DASHI.Physics.YangMills.YMKatoClosedFormHamiltonianExact

-- T5 continuum routes.
import DASHI.Physics.YangMills.BalabanClayT5PreferredContinuumOSGapExact
import DASHI.Physics.YangMills.BalabanClayT5PreferredOSGramFromExpectationExact
import DASHI.Physics.YangMills.BalabanClayT5QuantitativeContinuumClosureCompilerExact
import DASHI.Physics.YangMills.BalabanClayT5CompactUniqueFullSequenceExact
import DASHI.Physics.YangMills.BalabanClayT5SubsequenceProkhorovExtractionExact
import DASHI.Physics.YangMills.BalabanClayT5UniformTightnessSubsequenceInheritanceExact
import DASHI.Physics.YangMills.BalabanClayT5MomentCompactContainmentExact
import DASHI.Physics.YangMills.BalabanClayT5WeakExpectationPropertyClosureExact
import DASHI.Physics.YangMills.BalabanClayT5WeakTopologyClusterCylinderAgreementExact
import DASHI.Physics.YangMills.BalabanClayT5WeakExpectationGramReflectionClosureExact
import DASHI.Physics.YangMills.BalabanClayT5SelectedSequentialConvergenceExact
import DASHI.Physics.YangMills.BalabanClayT5SelectedMomentCompactContainmentExact
import DASHI.Physics.YangMills.BalabanClayT5SelectedUniformTightnessBridgeExact
import DASHI.Physics.YangMills.BalabanClayT5SelectedProkhorovExtractionExact
import DASHI.Physics.YangMills.BalabanClayT5SelectedCompactUniqueFullSequenceExact
import DASHI.Physics.YangMills.BalabanClayT5SelectedWeakExpectationClosureExact
import DASHI.Physics.YangMills.BalabanClayT5SelectedWeakGramReflectionClosureExact
import DASHI.Physics.YangMills.BalabanClayT5SelectedContinuumOSExact
import DASHI.Physics.YangMills.BalabanClayT5SelectedContinuumOSGapBridgeExact
import DASHI.Physics.YangMills.BalabanClayT5DirectExpectationPropertyClosureExact
import DASHI.Physics.YangMills.BalabanClayT5ExpectationLinkedContinuumOSExact
import DASHI.Physics.YangMills.BalabanClayT5CoerciveMomentMarkovContainmentExact
import DASHI.Physics.YangMills.BalabanClayT5PreferredPhysicalCoerciveMomentBridgeExact
import DASHI.Physics.YangMills.BalabanClayT5Path4GaugeEnergyObservableRealizationExact
import DASHI.Physics.YangMills.BalabanClayT5FunctionalPath4GaugeEnergyObservableExact
import DASHI.Physics.YangMills.BalabanClayT5Path4GaugeEnergyMarkovBridgeExact
import DASHI.Physics.YangMills.BalabanPath4SU2ConfiguredGaugeFixedEnergyNonnegativeExact
import DASHI.Physics.YangMills.BalabanPath4SU2RealCoercivityExtensionExact
import DASHI.Physics.YangMills.BalabanClayT5CylinderDeterminingClusterUniquenessExact
import DASHI.Physics.YangMills.BalabanClayT5DiagonalFiniteVolumeSameObjectExact
import DASHI.Physics.YangMills.BalabanClayT5PreferredDiagonalExpectationProducerExact

-- Current terminal schedulers after Eq. (119), Kato-M7 and T5 minimization.
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound191Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound192Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound193Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound194Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound195Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound196Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound197Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound198Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound199Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound200Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound201Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound202Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound203Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound204Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound205Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound206Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound207Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound208Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound209Exact
import DASHI.Physics.YangMills.BalabanClayT1ResidualIntrospectionRound210Exact
import DASHI.Physics.YangMills.BalabanClayT1IntrospectiveBindingRound211Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound210Exact
import DASHI.Physics.YangMills.BalabanClayCurrentTerminalCutsetRound211Exact

-- Compatibility source-realization route retained after introspection.
import DASHI.Physics.YangMills.BalabanR108BackedPresentCutActionExact
import DASHI.Physics.YangMills.BalabanPreferredSourceRealizationFrontierRound212Exact

-- Preferred CMP119-native source route.
import DASHI.Physics.YangMills.BalabanCMP119SourceNativeRawStateActiveBoundsExact
import DASHI.Physics.YangMills.BalabanCMP122Theorem1ToRawCMP119ActiveExact
import DASHI.Physics.YangMills.BalabanCMP119RawStateFromFiniteBetaHistoryExact
import DASHI.Physics.YangMills.BalabanCMP119RegularSectorCMP109116Round215Exact
import DASHI.Physics.YangMills.BalabanCMP119RegularSectorBC1Round215Exact
import DASHI.Physics.YangMills.BalabanPreferredRawSourceFrontierRound216Exact
import DASHI.Physics.YangMills.BalabanCMP119RawSourceRealizationSplitRound217Exact
import DASHI.Physics.YangMills.BalabanPreferredRawSourceFrontierRound217Exact

-- Row-C continuation after same-density introspection.
import DASHI.Physics.YangMills.BalabanHeatDoobJointGradientCovarianceRound251Exact
import DASHI.Physics.YangMills.BalabanHeatDoobJointRowCCompilerRound252Exact
import DASHI.Physics.YangMills.BalabanHeatDoobRationalCurvatureMajorantRound253Exact
import DASHI.Physics.YangMills.BalabanHeatDoobExpectationContractionRound254Exact
import DASHI.Physics.YangMills.BalabanCMP116FirstGradientLocalizationRound255Exact
import DASHI.Physics.YangMills.BalabanCMP116SharedFirstVariationCoordinateRound256Exact
import DASHI.Physics.YangMills.BalabanHeatDoobMarkedTemporalMajorizationRound257Exact
import DASHI.Physics.YangMills.BalabanStochasticSpatialEnvelopeToConnectedClusteringRound258Exact
import DASHI.Physics.YangMills.BalabanPreferredRowCFrontierRound259Exact

-- R261-R269: typed same-carrier Langevin/Hessian recut.
import DASHI.Physics.YangMills.BalabanPreferredRowCSpatialFrontierRound261Exact
import DASHI.Physics.YangMills.CompactLieLangevinSkewConnectionCancellationExact
import DASHI.Physics.YangMills.BalabanLangevinHessianBidirectionalWeldRound262Exact
import DASHI.Physics.YangMills.BalabanLangevinPhysicalHessianSourceRecutRound263Exact
import DASHI.Physics.YangMills.BalabanCMP109LangevinTypedSecondVariationRound267Exact
import DASHI.Physics.YangMills.BalabanLangevinAnchoredInfluenceRound268Exact

import DASHI.Physics.YangMills.BalabanPath13Eq119SourceRouteProvenanceExact
import DASHI.Physics.YangMills.BalabanPath13Eq119BishopBridgeProvenanceExact
import DASHI.Physics.YangMills.BalabanPath13Eq119DirectCalculusProvenanceExact
import DASHI.Physics.YangMills.BalabanPath13Eq119SplitCalculusProvenanceExact
import DASHI.Physics.YangMills.BalabanPath13Eq119MinimalSemanticProvenanceExact
import DASHI.Physics.YangMills.BalabanCMP98Equation119RecoveredShortestSourceCutExact
import DASHI.Physics.Closure.YMStrictSelectedHodgeVariationPairing
import DASHI.Physics.YangMills.BalabanVacuumOrthogonalMoscoRecoveryExact
import DASHI.Physics.YangMills.BalabanClayDenseCoreSpectralGapExact
import DASHI.Physics.YangMills.BalabanOSExponentialClusteringImpliesHamiltonianGapExact
import DASHI.Physics.YangMills.BalabanClayHighestAlphaReuseExact
import DASHI.Physics.YangMills.BalabanClayMassGapGatePackageExact

-- Canonical B proof-search consumer after R270-R309 normalization.  This one
-- owner imports the direct finite-T5 source route, arbitrary-pair continuum
-- clustering, standard clustering->spectrum transfer, and the proof-bearing
-- selected-J applicability split; Row C remains an optional producer tactic.
import DASHI.Physics.YangMills.BalabanClayCanonicalBCurrentExact

-- Receipt-vs-theorem terminal audit.
import DASHI.Physics.YangMills.BalabanCMP98Equation119ClayTerminalBidiRound186Exact
import DASHI.Physics.YangMills.BalabanCMP98TerminalHamiltonianBidiRound188Exact
import DASHI.Physics.YangMills.BalabanCMP98ClayBoundarySupersessionRound190Exact

-- September 2026 bidirectional Lean/Agda operator-domain cross-pollination.
import DASHI.Physics.YangMills.YMOperatorDomainContinuumSources2026Exact
import DASHI.Physics.YangMills.YMAristotleOperatorReturn2026Exact
import DASHI.Physics.YangMills.YMOperatorDomainContinuumFrontier2026Exact
