/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Agda.Syntax

/-!
# `DASHI.Physics.Closure.BTCanonicalNeckAnalogue`, transliterated

Generated by `tools/agda2lean.py` from the ingested upstream source
`upstream/dashi_agda/master/DASHI/Physics/Closure/BTCanonicalNeckAnalogue.agda`.
Do not edit by hand: re-run the translator instead.
-/

open Agda

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where

  open import Agda.Builtin.Bool

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  ------------------------------------------------------------------------
  -- Concrete finite Bruhat-Tits neck analogues.
  --
  -- This module records only the discrete BT neck analogue at the canonical
  -- prime lanes p = 2, 3, 7.  For each lane the cross-section is the finite
  -- neighbor sphere of a (p + 1)-regular Bruhat-Tits tree, so its cardinality
  -- is definitionally p + 1.
  --
  -- It deliberately does not promote a smooth S2 cross-section, a smooth
  -- epsilon-neck theorem, Ricci-flow surgery, or any terminal geometry claim.

  data «⊥» : Set where

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  NotTrue : Bool → Set
  NotTrue b =
    b ≡ true → «⊥»

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  falseNotTrue : NotTrue false
  falseNotTrue ()

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  data BTPrimeLane : Set where
    p2Lane :
      BTPrimeLane
    p3Lane :
      BTPrimeLane
    p7Lane :
      BTPrimeLane

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  canonicalBTPrimeLanes : List BTPrimeLane
  canonicalBTPrimeLanes =
    p2Lane
    ∷ p3Lane
    ∷ p7Lane
    ∷ []

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  primeValue : BTPrimeLane → Nat
  primeValue p2Lane =
    2
  primeValue p3Lane =
    3
  primeValue p7Lane =
    7

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  crossSectionCardinalityForLane : BTPrimeLane → Nat
  crossSectionCardinalityForLane lane =
    suc (primeValue lane)

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  data BTDiscreteCenter : Set where
    canonicalRootCenter :
      BTPrimeLane →
      BTDiscreteCenter
    depthCenter :
      BTPrimeLane →
      Nat →
      BTDiscreteCenter

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  data DepthIndexedScaleToken : Set where
    depthScaleToken :
      BTPrimeLane →
      Nat →
      DepthIndexedScaleToken

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  data NeckRadiusToken : Set where
    radiusOneEdgeAtDepth :
      BTPrimeLane →
      Nat →
      NeckRadiusToken

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  data CrossSectionAnalogue : Set where
    finiteNeighborSphere :
      BTPrimeLane →
      CrossSectionAnalogue

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  data PathCylinderAnalogue : Set where
    btGeodesicPathTimesFiniteSphere :
      BTPrimeLane →
      Nat →
      CrossSectionAnalogue →
      PathCylinderAnalogue

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  data BTNeckAnalogueStatus : Set where
    concreteDiscreteBTNeckAnalogue :
      BTNeckAnalogueStatus
    smoothS2CrossSectionUnavailable :
      BTNeckAnalogueStatus
    epsilonNeckTheoremUnavailable :
      BTNeckAnalogueStatus

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  canonicalBTNeckAnalogueStatus : List BTNeckAnalogueStatus
  canonicalBTNeckAnalogueStatus =
    concreteDiscreteBTNeckAnalogue
    ∷ smoothS2CrossSectionUnavailable
    ∷ epsilonNeckTheoremUnavailable
    ∷ []

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  data SmoothS2CrossSection : Set where

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  smoothS2CrossSectionUnavailableHere :
    SmoothS2CrossSection →
    «⊥»
  smoothS2CrossSectionUnavailableHere ()

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  data SmoothEpsilonNeckTheorem : Set where

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  epsilonNeckTheoremUnavailableHere :
    SmoothEpsilonNeckTheorem →
    «⊥»
  epsilonNeckTheoremUnavailableHere ()

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  btDiscreteNeckStatement : String
  btDiscreteNeckStatement =
    "BT discrete neck analogue: center at depth d, scale token (p,d), cross-section finite neighbor sphere of cardinality p+1, and path-cylinder analogue geodesic path times finite sphere."

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  smoothBoundaryStatement : String
  smoothBoundaryStatement =
    "Smooth S2 cross-section and smooth epsilon-neck theorem are unavailable and not promoted in this finite BT analogue."

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  record BTCanonicalNeckAnalogue : Set where
    field
      status :
        List BTNeckAnalogueStatus

      statusIsCanonical :
        status ≡ canonicalBTNeckAnalogueStatus

      primeLane :
        BTPrimeLane

      pValue :
        Nat

      pValueIsPrimeLaneValue :
        pValue ≡ primeValue primeLane

      depth :
        Nat

      center :
        BTDiscreteCenter

      centerIsDepthCenter :
        center ≡ depthCenter primeLane depth

      scaleToken :
        DepthIndexedScaleToken

      scaleTokenIsDepthIndexed :
        scaleToken ≡ depthScaleToken primeLane depth

      neckRadius :
        NeckRadiusToken

      neckRadiusIsOneEdgeAtDepth :
        neckRadius ≡ radiusOneEdgeAtDepth primeLane depth

      crossSection :
        CrossSectionAnalogue

      crossSectionIsFiniteNeighborSphere :
        crossSection ≡ finiteNeighborSphere primeLane

      crossSectionCardinality :
        Nat

      crossSectionCardinalityIsPPlusOne :
        crossSectionCardinality ≡ crossSectionCardinalityForLane primeLane

      pathCylinder :
        PathCylinderAnalogue

      pathCylinderIsCanonical :
        pathCylinder
        ≡
        btGeodesicPathTimesFiniteSphere primeLane depth crossSection

      pathCylinderAnalogueConstructed :
        Bool

      pathCylinderAnalogueConstructedIsTrue :
        pathCylinderAnalogueConstructed ≡ true

      smoothS2CrossSectionPromoted :
        Bool

      smoothS2CrossSectionPromotedIsFalse :
        smoothS2CrossSectionPromoted ≡ false

      smoothS2CrossSectionBlocked :
        NotTrue smoothS2CrossSectionPromoted

      epsilonNeckTheoremPromoted :
        Bool

      epsilonNeckTheoremPromotedIsFalse :
        epsilonNeckTheoremPromoted ≡ false

      epsilonNeckTheoremBlocked :
        NotTrue epsilonNeckTheoremPromoted

      clayOrGeometrizationPromoted :
        Bool

      clayOrGeometrizationPromotedIsFalse :
        clayOrGeometrizationPromoted ≡ false

      statement :
        String

      statementIsCanonical :
        statement ≡ btDiscreteNeckStatement

      boundaryStatement :
        String

      boundaryStatementIsCanonical :
        boundaryStatement ≡ smoothBoundaryStatement

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  open BTCanonicalNeckAnalogue public

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  canonicalBTNeckAnalogueAt :
    BTPrimeLane →
    Nat →
    BTCanonicalNeckAnalogue
  canonicalBTNeckAnalogueAt lane d =
    record
      { status =
          canonicalBTNeckAnalogueStatus
      ; statusIsCanonical =
          refl
      ; primeLane =
          lane
      ; pValue =
          primeValue lane
      ; pValueIsPrimeLaneValue =
          refl
      ; center =
          depthCenter lane d
      ; centerIsDepthCenter =
          refl
      ; depth =
          d
      ; scaleToken =
          depthScaleToken lane d
      ; scaleTokenIsDepthIndexed =
          refl
      ; neckRadius =
          radiusOneEdgeAtDepth lane d
      ; neckRadiusIsOneEdgeAtDepth =
          refl
      ; crossSection =
          finiteNeighborSphere lane
      ; crossSectionIsFiniteNeighborSphere =
          refl
      ; crossSectionCardinality =
          crossSectionCardinalityForLane lane
      ; crossSectionCardinalityIsPPlusOne =
          refl
      ; pathCylinder =
          btGeodesicPathTimesFiniteSphere lane d (finiteNeighborSphere lane)
      ; pathCylinderIsCanonical =
          refl
      ; pathCylinderAnalogueConstructed =
          true
      ; pathCylinderAnalogueConstructedIsTrue =
          refl
      ; smoothS2CrossSectionPromoted =
          false
      ; smoothS2CrossSectionPromotedIsFalse =
          refl
      ; smoothS2CrossSectionBlocked =
          falseNotTrue
      ; epsilonNeckTheoremPromoted =
          false
      ; epsilonNeckTheoremPromotedIsFalse =
          refl
      ; epsilonNeckTheoremBlocked =
          falseNotTrue
      ; clayOrGeometrizationPromoted =
          false
      ; clayOrGeometrizationPromotedIsFalse =
          refl
      ; statement =
          btDiscreteNeckStatement
      ; statementIsCanonical =
          refl
      ; boundaryStatement =
          smoothBoundaryStatement
      ; boundaryStatementIsCanonical =
          refl
      }

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  canonicalP2BTNeckAnalogue :
    BTCanonicalNeckAnalogue
  canonicalP2BTNeckAnalogue =
    canonicalBTNeckAnalogueAt p2Lane 2

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  canonicalP3BTNeckAnalogue :
    BTCanonicalNeckAnalogue
  canonicalP3BTNeckAnalogue =
    canonicalBTNeckAnalogueAt p3Lane 3

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  canonicalP7BTNeckAnalogue :
    BTCanonicalNeckAnalogue
  canonicalP7BTNeckAnalogue =
    canonicalBTNeckAnalogueAt p7Lane 7

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  p2CrossSectionCardinalityIs3 :
    crossSectionCardinality canonicalP2BTNeckAnalogue ≡ 3
  p2CrossSectionCardinalityIs3 =
    refl

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  p3CrossSectionCardinalityIs4 :
    crossSectionCardinality canonicalP3BTNeckAnalogue ≡ 4
  p3CrossSectionCardinalityIs4 =
    refl

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  p7CrossSectionCardinalityIs8 :
    crossSectionCardinality canonicalP7BTNeckAnalogue ≡ 8
  p7CrossSectionCardinalityIs8 =
    refl

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  p2PathCylinderConstructed :
    pathCylinderAnalogueConstructed canonicalP2BTNeckAnalogue ≡ true
  p2PathCylinderConstructed =
    refl

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  p3PathCylinderConstructed :
    pathCylinderAnalogueConstructed canonicalP3BTNeckAnalogue ≡ true
  p3PathCylinderConstructed =
    refl

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  p7PathCylinderConstructed :
    pathCylinderAnalogueConstructed canonicalP7BTNeckAnalogue ≡ true
  p7PathCylinderConstructed =
    refl

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  p2SmoothS2CrossSectionNotPromoted :
    smoothS2CrossSectionPromoted canonicalP2BTNeckAnalogue ≡ false
  p2SmoothS2CrossSectionNotPromoted =
    refl

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  p3SmoothS2CrossSectionNotPromoted :
    smoothS2CrossSectionPromoted canonicalP3BTNeckAnalogue ≡ false
  p3SmoothS2CrossSectionNotPromoted =
    refl

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  p7SmoothS2CrossSectionNotPromoted :
    smoothS2CrossSectionPromoted canonicalP7BTNeckAnalogue ≡ false
  p7SmoothS2CrossSectionNotPromoted =
    refl

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  p2EpsilonNeckTheoremNotPromoted :
    epsilonNeckTheoremPromoted canonicalP2BTNeckAnalogue ≡ false
  p2EpsilonNeckTheoremNotPromoted =
    refl

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  p3EpsilonNeckTheoremNotPromoted :
    epsilonNeckTheoremPromoted canonicalP3BTNeckAnalogue ≡ false
  p3EpsilonNeckTheoremNotPromoted =
    refl

agda_module DASHI.Physics.Closure.BTCanonicalNeckAnalogue where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  p7EpsilonNeckTheoremNotPromoted :
    epsilonNeckTheoremPromoted canonicalP7BTNeckAnalogue ≡ false
  p7EpsilonNeckTheoremNotPromoted =
    refl

