/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Agda.Syntax
import AgdaVendor.DASHI.Physics.Closure.ReflectionPositivityForWilsonReceipt

/-!
# `DASHI.Physics.Closure.LatticeMassGapFromTransferMatrixReceipt`, transliterated

Generated by `tools/agda2lean.py` from the ingested upstream source
`upstream/dashi_agda/agent/evidence-polarity-cross-pollination/DASHI/Physics/Closure/LatticeMassGapFromTransferMatrixReceipt.agda`.
Do not edit by hand: re-run the translator instead.
-/

open Agda

agda_module DASHI.Physics.Closure.LatticeMassGapFromTransferMatrixReceipt where

  open import Agda.Primitive

agda_module DASHI.Physics.Closure.LatticeMassGapFromTransferMatrixReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool

agda_module DASHI.Physics.Closure.LatticeMassGapFromTransferMatrixReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

agda_module DASHI.Physics.Closure.LatticeMassGapFromTransferMatrixReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.String

agda_module DASHI.Physics.Closure.LatticeMassGapFromTransferMatrixReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.String
  open import Data.List.Base

agda_module DASHI.Physics.Closure.LatticeMassGapFromTransferMatrixReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.String
  open import Data.List.Base

  open import DASHI.Physics.Closure.ReflectionPositivityForWilsonReceipt

agda_module DASHI.Physics.Closure.LatticeMassGapFromTransferMatrixReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.String
  open import Data.List.Base
  open import DASHI.Physics.Closure.ReflectionPositivityForWilsonReceipt

  data LatticeGapReason : Set where
    compactGaugeGroupPeterWeyl :
      LatticeGapReason

    finiteSpatialLatticeDiscreteSpectrum :
      LatticeGapReason

    continuumLimitMayCloseGap :
      LatticeGapReason

agda_module DASHI.Physics.Closure.LatticeMassGapFromTransferMatrixReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.String
  open import Data.List.Base
  open import DASHI.Physics.Closure.ReflectionPositivityForWilsonReceipt

  canonicalLatticeGapReasons : List LatticeGapReason
  canonicalLatticeGapReasons =
    compactGaugeGroupPeterWeyl
    ∷ finiteSpatialLatticeDiscreteSpectrum
    ∷ continuumLimitMayCloseGap
    ∷ []

agda_module DASHI.Physics.Closure.LatticeMassGapFromTransferMatrixReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.String
  open import Data.List.Base
  open import DASHI.Physics.Closure.ReflectionPositivityForWilsonReceipt

  record LatticeMassGapFromTransferMatrixReceipt : Setω where
    field
      reflectionReceipt :
        DASHI.Physics.Closure.ReflectionPositivityForWilsonReceipt.ReflectionPositivityForWilsonReceipt

      finiteReflectionPositive :
        DASHI.Physics.Closure.ReflectionPositivityForWilsonReceipt.finiteLatticeReflectionPositivityInherited reflectionReceipt ≡ true

      transferMatrixDefined :
        Bool

      transferMatrixDefinedIsTrue :
        transferMatrixDefined ≡ true

      finiteLatticeSpectrumDiscrete :
        Bool

      finiteLatticeSpectrumDiscreteIsTrue :
        finiteLatticeSpectrumDiscrete ≡ true

      finiteLatticeGapPositive :
        Bool

      finiteLatticeGapPositiveIsTrue :
        finiteLatticeGapPositive ≡ true

      uniformContinuumGapProved :
        Bool

      uniformContinuumGapProvedIsFalse :
        uniformContinuumGapProved ≡ false

      clayYangMillsPromoted :
        Bool

      clayYangMillsPromotedIsFalse :
        clayYangMillsPromoted ≡ false

      terminalClayClaimPromoted :
        Bool

      terminalClayClaimPromotedIsFalse :
        terminalClayClaimPromoted ≡ false

      reasons :
        List LatticeGapReason

      reasonsAreCanonical :
        reasons ≡ canonicalLatticeGapReasons

agda_module DASHI.Physics.Closure.LatticeMassGapFromTransferMatrixReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.String
  open import Data.List.Base
  open import DASHI.Physics.Closure.ReflectionPositivityForWilsonReceipt

  open LatticeMassGapFromTransferMatrixReceipt public

agda_module DASHI.Physics.Closure.LatticeMassGapFromTransferMatrixReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.String
  open import Data.List.Base
  open import DASHI.Physics.Closure.ReflectionPositivityForWilsonReceipt

  canonicalLatticeMassGapFromTransferMatrixReceipt :
    LatticeMassGapFromTransferMatrixReceipt
  canonicalLatticeMassGapFromTransferMatrixReceipt =
    record
      { reflectionReceipt =
          DASHI.Physics.Closure.ReflectionPositivityForWilsonReceipt.canonicalReflectionPositivityForWilsonReceipt
      ; finiteReflectionPositive =
          refl
      ; transferMatrixDefined =
          true
      ; transferMatrixDefinedIsTrue =
          refl
      ; finiteLatticeSpectrumDiscrete =
          true
      ; finiteLatticeSpectrumDiscreteIsTrue =
          refl
      ; finiteLatticeGapPositive =
          true
      ; finiteLatticeGapPositiveIsTrue =
          refl
      ; uniformContinuumGapProved =
          false
      ; uniformContinuumGapProvedIsFalse =
          refl
      ; clayYangMillsPromoted =
          false
      ; clayYangMillsPromotedIsFalse =
          refl
      ; terminalClayClaimPromoted =
          false
      ; terminalClayClaimPromotedIsFalse =
          refl
      ; reasons =
          canonicalLatticeGapReasons
      ; reasonsAreCanonical =
          refl
      }

agda_module DASHI.Physics.Closure.LatticeMassGapFromTransferMatrixReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.String
  open import Data.List.Base
  open import DASHI.Physics.Closure.ReflectionPositivityForWilsonReceipt

  latticeMassGapFromTransferMatrixKeepsClayFalse :
    clayYangMillsPromoted canonicalLatticeMassGapFromTransferMatrixReceipt
    ≡
    false
  latticeMassGapFromTransferMatrixKeepsClayFalse =
    refl

agda_module DASHI.Physics.Closure.LatticeMassGapFromTransferMatrixReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.String
  open import Data.List.Base
  open import DASHI.Physics.Closure.ReflectionPositivityForWilsonReceipt

  latticeMassGapFromTransferMatrixKeepsTerminalFalse :
    terminalClayClaimPromoted canonicalLatticeMassGapFromTransferMatrixReceipt
    ≡
    false
  latticeMassGapFromTransferMatrixKeepsTerminalFalse =
    refl

