/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Agda.Syntax
import AgdaVendor.DASHI.Physics.YangMills.CompactLieProofLevel

/-!
# `DASHI.Physics.Closure.NSPeriodicNearShellOverlapCount`, transliterated

Generated by `tools/agda2lean.py` from the ingested upstream source
`upstream/dashi_agda/master/DASHI/Physics/Closure/NSPeriodicNearShellOverlapCount.agda`.
Do not edit by hand: re-run the translator instead.
-/

open Agda

agda_module DASHI.Physics.Closure.NSPeriodicNearShellOverlapCount where

  open import Agda.Builtin.Equality

agda_module DASHI.Physics.Closure.NSPeriodicNearShellOverlapCount where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List

agda_module DASHI.Physics.Closure.NSPeriodicNearShellOverlapCount where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat

agda_module DASHI.Physics.Closure.NSPeriodicNearShellOverlapCount where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat

  open import DASHI.Physics.YangMills.CompactLieProofLevel

agda_module DASHI.Physics.Closure.NSPeriodicNearShellOverlapCount where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel

  ------------------------------------------------------------------------
  -- Proof-oriented representation of the rational dyadic hat profile.
  ------------------------------------------------------------------------

  data DyadicHatSupport : Set where
    noActiveShell : DyadicHatSupport
    oneActiveShell : Nat → DyadicHatSupport
    twoAdjacentShells : Nat → DyadicHatSupport

agda_module DASHI.Physics.Closure.NSPeriodicNearShellOverlapCount where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel

  activeShells : DyadicHatSupport → List Nat
  activeShells noActiveShell = []
  activeShells (oneActiveShell j) = j ∷ []
  activeShells (twoAdjacentShells j) = j ∷ suc j ∷ []

agda_module DASHI.Physics.Closure.NSPeriodicNearShellOverlapCount where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel

  length : ∀ {A : Set} , List A → Nat
  length [] = zero
  length (_ ∷ xs) = suc (length xs)

agda_module DASHI.Physics.Closure.NSPeriodicNearShellOverlapCount where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel

  data AtMostTwo : Nat → Set where
    «zero-at-most-two» : AtMostTwo zero
    «one-at-most-two» : AtMostTwo (suc zero)
    «two-at-most-two» : AtMostTwo (suc (suc zero))

agda_module DASHI.Physics.Closure.NSPeriodicNearShellOverlapCount where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel

  activeShellCountAtMostTwo :
    ∀ support , AtMostTwo (length (activeShells support))
  activeShellCountAtMostTwo noActiveShell = «zero-at-most-two»
  activeShellCountAtMostTwo (oneActiveShell j) = «one-at-most-two»
  activeShellCountAtMostTwo (twoAdjacentShells j) = «two-at-most-two»

agda_module DASHI.Physics.Closure.NSPeriodicNearShellOverlapCount where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel

  oneShellLength : ∀ j , length (activeShells (oneActiveShell j)) ≡ suc zero
  oneShellLength j = refl

agda_module DASHI.Physics.Closure.NSPeriodicNearShellOverlapCount where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel

  twoShellLength : ∀ j ,
    length (activeShells (twoAdjacentShells j)) ≡ suc (suc zero)
  twoShellLength j = refl

agda_module DASHI.Physics.Closure.NSPeriodicNearShellOverlapCount where
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel

  nearShellOverlapCountLevel : ProofLevel
  nearShellOverlapCountLevel = machineChecked

