/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Agda.Syntax

/-!
# `DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact`, transliterated

Generated by `tools/agda2lean.py` from the ingested upstream source
`upstream/dashi_agda/master/DASHI/Physics/Closure/NSTriadKNLuoPhysicalBlockDecayReductionExact.agda`.
Do not edit by hand: re-run the translator instead.
-/

open Agda

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where

  ------------------------------------------------------------------------
  -- PROVENANCE
  --
  -- Author: Xiaoyutao Luo.
  -- Title: "A Beale--Kato--Majda Criterion with Optimal Frequency and
  -- Temporal Localization".
  -- Journal of Mathematical Fluid Mechanics 21 (2019), article 1.
  -- DOI: 10.1007/s00021-019-0411-z.
  -- arXiv DOI: 10.48550/arXiv.1803.05569.
  --
  -- PURPOSE
  -- Express the physical fixed-shift bootstrap as an implication chain from the
  -- integrated cutoff estimate and correction comparison to block decay, shell
  -- decay, Sobolev regularity and continuation regularity.  The algebraic block
  -- induction is not requested as a fresh physical theorem.
  ------------------------------------------------------------------------

  open import Agda.Builtin.Bool

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

  record PhysicalBlockDecayPrimitiveInputs : Set₁ where
    field
      IntegratedCutoffEnergyInequality : Set
      integratedCutoffEnergyInequality :
        IntegratedCutoffEnergyInequality

      FluxCorrectionBelowExplicitMajorant : Set
      fluxCorrectionBelowExplicitMajorant :
        FluxCorrectionBelowExplicitMajorant

      ExplicitMajorantBelowDyadicDecayTarget : Set
      explicitMajorantBelowDyadicDecayTarget :
        ExplicitMajorantBelowDyadicDecayTarget

      FixedShiftRecursion : Set
      fixedShiftRecursionFromPhysicalInequalities :
        IntegratedCutoffEnergyInequality →
        FluxCorrectionBelowExplicitMajorant →
        ExplicitMajorantBelowDyadicDecayTarget →
        FixedShiftRecursion

      BaseBlockFinite : Set
      baseBlockFinite : BaseBlockFinite

      BaseBlockUniformBound : Set
      baseBlockUniformBound : BaseBlockFinite → BaseBlockUniformBound

      RecursionCoefficientStrictlyBelowOne : Set
      recursionCoefficientStrictlyBelowOne :
        RecursionCoefficientStrictlyBelowOne

      CorrectionDecayCompatibleWithTarget : Set
      correctionDecayCompatibleWithTarget :
        CorrectionDecayCompatibleWithTarget

      PhysicalBlockDecayCertificate : Set
      blockInductionCloses :
        FixedShiftRecursion →
        BaseBlockUniformBound →
        RecursionCoefficientStrictlyBelowOne →
        CorrectionDecayCompatibleWithTarget →
        PhysicalBlockDecayCertificate

      ShellUniformDyadicDecay : Set
      blockDecayGivesShellUniformDyadicDecay :
        PhysicalBlockDecayCertificate → ShellUniformDyadicDecay

      ShellL2Decay : Set
      energyDecayImpliesShellL2Decay :
        ShellUniformDyadicDecay → ShellL2Decay

      GradientShellDecay : Set
      dissipationDecayImpliesGradientShellDecay :
        ShellUniformDyadicDecay → GradientShellDecay

      AlphaAboveOneSummability : Set
      alphaAboveOneSummability : AlphaAboveOneSummability

      RequiredContinuationRegularity : Set
      shellDecayAndSummabilityGiveRequiredRegularity :
        ShellL2Decay →
        GradientShellDecay →
        AlphaAboveOneSummability →
        RequiredContinuationRegularity

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

  open PhysicalBlockDecayPrimitiveInputs public

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

  derivedFixedShiftRecursion :
    (inputs : PhysicalBlockDecayPrimitiveInputs) →
    FixedShiftRecursion inputs
  derivedFixedShiftRecursion inputs =
    fixedShiftRecursionFromPhysicalInequalities inputs
      (integratedCutoffEnergyInequality inputs)
      (fluxCorrectionBelowExplicitMajorant inputs)
      (explicitMajorantBelowDyadicDecayTarget inputs)

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

  derivedBaseBlockUniformBound :
    (inputs : PhysicalBlockDecayPrimitiveInputs) →
    BaseBlockUniformBound inputs
  derivedBaseBlockUniformBound inputs =
    baseBlockUniformBound inputs (baseBlockFinite inputs)

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

  derivedPhysicalBlockDecayCertificate :
    (inputs : PhysicalBlockDecayPrimitiveInputs) →
    PhysicalBlockDecayCertificate inputs
  derivedPhysicalBlockDecayCertificate inputs =
    blockInductionCloses inputs
      (derivedFixedShiftRecursion inputs)
      (derivedBaseBlockUniformBound inputs)
      (recursionCoefficientStrictlyBelowOne inputs)
      (correctionDecayCompatibleWithTarget inputs)

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

  derivedShellUniformDyadicDecay :
    (inputs : PhysicalBlockDecayPrimitiveInputs) →
    ShellUniformDyadicDecay inputs
  derivedShellUniformDyadicDecay inputs =
    blockDecayGivesShellUniformDyadicDecay inputs
      (derivedPhysicalBlockDecayCertificate inputs)

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

  derivedRequiredContinuationRegularity :
    (inputs : PhysicalBlockDecayPrimitiveInputs) →
    RequiredContinuationRegularity inputs
  derivedRequiredContinuationRegularity inputs =
    shellDecayAndSummabilityGiveRequiredRegularity inputs
      (energyDecayImpliesShellL2Decay inputs
        (derivedShellUniformDyadicDecay inputs))
      (dissipationDecayImpliesGradientShellDecay inputs
        (derivedShellUniformDyadicDecay inputs))
      (alphaAboveOneSummability inputs)

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

  record PhysicalBlockDecayReceipt : Set₁ where
    field
      primitiveInputs : PhysicalBlockDecayPrimitiveInputs
      fixedShiftRecursion : FixedShiftRecursion primitiveInputs
      blockDecayCertificate :
        PhysicalBlockDecayCertificate primitiveInputs
      shellUniformDecay : ShellUniformDyadicDecay primitiveInputs
      continuationRegularity :
        RequiredContinuationRegularity primitiveInputs

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

  open PhysicalBlockDecayReceipt public

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

  physicalBlockDecayReceipt :
    PhysicalBlockDecayPrimitiveInputs → PhysicalBlockDecayReceipt
  physicalBlockDecayReceipt inputs = record
    { primitiveInputs = inputs
    ; fixedShiftRecursion = derivedFixedShiftRecursion inputs
    ; blockDecayCertificate =
        derivedPhysicalBlockDecayCertificate inputs
    ; shellUniformDecay = derivedShellUniformDyadicDecay inputs
    ; continuationRegularity =
        derivedRequiredContinuationRegularity inputs
    }

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

  physicalBlockDecayReductionConstructed : Bool
  physicalBlockDecayReductionConstructed = true

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

  continuationRegularityDerivedFromPhysicalDecay : Bool
  continuationRegularityDerivedFromPhysicalDecay = true

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

  physicalBlockDecayReductionConstructedIsTrue :
    physicalBlockDecayReductionConstructed ≡ true
  physicalBlockDecayReductionConstructedIsTrue = refl

agda_module DASHI.Physics.Closure.NSTriadKNLuoPhysicalBlockDecayReductionExact where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

  continuationRegularityDerivedFromPhysicalDecayIsTrue :
    continuationRegularityDerivedFromPhysicalDecay ≡ true
  continuationRegularityDerivedFromPhysicalDecayIsTrue = refl

