/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Agda.Syntax
import AgdaVendor.DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

/-!
# `DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt`, transliterated

Generated by `tools/agda2lean.py` from the ingested upstream source
`upstream/dashi_agda/master/DASHI/Physics/Closure/PrimeBandLPDefinitionReceipt.agda`.
Do not edit by hand: re-run the translator instead.
-/

open Agda

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where

  open import Agda.Primitive

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base

  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  ------------------------------------------------------------------------
  -- Prime-band Littlewood-Paley definition receipt.
  --
  -- This receipt records the formal prime-band DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt projector surface for
  -- p in {2,3,5}.  A low-frequency residual is included.  Completeness is
  -- recorded only because the dyadic p=2 bands cover the ordinary DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt frequency
  -- axis; triadic and pentadic bands are additional carrier diagnostics, not an
  -- independent proof of completeness.

  data PrimeBandLPDefinitionStatus : Set where
    primeBandLPProjectorsRecorded :
      PrimeBandLPDefinitionStatus

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  data PrimeBand : Set where
    p2Band :
      PrimeBand

    p3Band :
      PrimeBand

    p5Band :
      PrimeBand

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  canonicalPrimeBands :
    List PrimeBand
  canonicalPrimeBands =
    p2Band
    ∷ p3Band
    ∷ p5Band
    ∷ []

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  data PrimeBandLPComponent : Set where
    lowFrequencyResidual :
      PrimeBandLPComponent

    dyadicProjectors :
      PrimeBandLPComponent

    triadicProjectors :
      PrimeBandLPComponent

    pentadicProjectors :
      PrimeBandLPComponent

    dyadicCompletenessCover :
      PrimeBandLPComponent

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  canonicalPrimeBandLPComponents :
    List PrimeBandLPComponent
  canonicalPrimeBandLPComponents =
    lowFrequencyResidual
    ∷ dyadicProjectors
    ∷ triadicProjectors
    ∷ pentadicProjectors
    ∷ dyadicCompletenessCover
    ∷ []

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  data PrimeBandLPBlocker : Set where
    missingSmoothMultiplierConstruction :
      PrimeBandLPBlocker

    missingBesovNormEquivalenceProof :
      PrimeBandLPBlocker

    missingNonlinearNSPassage :
      PrimeBandLPBlocker

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  canonicalPrimeBandLPBlockers :
    List PrimeBandLPBlocker
  canonicalPrimeBandLPBlockers =
    missingSmoothMultiplierConstruction
    ∷ missingBesovNormEquivalenceProof
    ∷ missingNonlinearNSPassage
    ∷ []

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  data PrimeBandLPPromotion : Set where

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  primeBandLPPromotionImpossibleHere :
    PrimeBandLPPromotion →
    ⊥
  primeBandLPPromotionImpossibleHere ()

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  primeBandLPFormula : String
  primeBandLPFormula =
    "Delta_{p,j} is the DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt projector to prime band |xi| approximately p^j for p in {2,3,5}; S_0 is the low-frequency residual"

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  dyadicCompletenessStatement : String
  dyadicCompletenessStatement =
    "Completeness is true because the dyadic p=2 bands plus S_0 cover the standard DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt frequency axis"

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  record PrimeBandLPDefinitionReceipt : Setω where
    field
      lpCarrierReceipt :
        DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt.NSLittlewoodPaleyCarrierReceipt

      lpCarrierCandidateRecorded :
        DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt.carrierLPDecompositionDefined lpCarrierReceipt ≡ true

      status :
        PrimeBandLPDefinitionStatus

      primeBands :
        List PrimeBand

      primeBandsAreCanonical :
        primeBands ≡ canonicalPrimeBands

      components :
        List PrimeBandLPComponent

      componentsAreCanonical :
        components ≡ canonicalPrimeBandLPComponents

      bandCount :
        Nat

      bandCountIsThree :
        bandCount ≡ 3

      lowFrequencyResidualRecorded :
        Bool

      lowFrequencyResidualRecordedIsTrue :
        lowFrequencyResidualRecorded ≡ true

      projectorFormula :
        String

      projectorFormulaIsCanonical :
        projectorFormula ≡ primeBandLPFormula

      dyadicBandsCover :
        Bool

      dyadicBandsCoverIsTrue :
        dyadicBandsCover ≡ true

      completenessRecorded :
        Bool

      completenessRecordedIsTrue :
        completenessRecorded ≡ true

      completenessStatement :
        String

      completenessStatementIsCanonical :
        completenessStatement ≡ dyadicCompletenessStatement

      smoothMultiplierConstructionProved :
        Bool

      smoothMultiplierConstructionProvedIsFalse :
        smoothMultiplierConstructionProved ≡ false

      navierStokesRegularityPromoted :
        Bool

      navierStokesRegularityPromotedIsFalse :
        navierStokesRegularityPromoted ≡ false

      clayNavierStokesPromoted :
        Bool

      clayNavierStokesPromotedIsFalse :
        clayNavierStokesPromoted ≡ false

      blockers :
        List PrimeBandLPBlocker

      blockersAreCanonical :
        blockers ≡ canonicalPrimeBandLPBlockers

      promotionFlags :
        List PrimeBandLPPromotion

      promotionFlagsAreEmpty :
        promotionFlags ≡ []

      receiptBoundary :
        List String

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  open PrimeBandLPDefinitionReceipt public

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  canonicalPrimeBandLPDefinitionReceipt :
    PrimeBandLPDefinitionReceipt
  canonicalPrimeBandLPDefinitionReceipt =
    record
      { lpCarrierReceipt =
          DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt.canonicalNSLittlewoodPaleyCarrierReceipt
      ; lpCarrierCandidateRecorded =
          refl
      ; status =
          primeBandLPProjectorsRecorded
      ; primeBands =
          canonicalPrimeBands
      ; primeBandsAreCanonical =
          refl
      ; components =
          canonicalPrimeBandLPComponents
      ; componentsAreCanonical =
          refl
      ; bandCount =
          3
      ; bandCountIsThree =
          refl
      ; lowFrequencyResidualRecorded =
          true
      ; lowFrequencyResidualRecordedIsTrue =
          refl
      ; projectorFormula =
          primeBandLPFormula
      ; projectorFormulaIsCanonical =
          refl
      ; dyadicBandsCover =
          true
      ; dyadicBandsCoverIsTrue =
          refl
      ; completenessRecorded =
          true
      ; completenessRecordedIsTrue =
          refl
      ; completenessStatement =
          dyadicCompletenessStatement
      ; completenessStatementIsCanonical =
          refl
      ; smoothMultiplierConstructionProved =
          false
      ; smoothMultiplierConstructionProvedIsFalse =
          refl
      ; navierStokesRegularityPromoted =
          false
      ; navierStokesRegularityPromotedIsFalse =
          refl
      ; clayNavierStokesPromoted =
          false
      ; clayNavierStokesPromotedIsFalse =
          refl
      ; blockers =
          canonicalPrimeBandLPBlockers
      ; blockersAreCanonical =
          refl
      ; promotionFlags =
          []
      ; promotionFlagsAreEmpty =
          refl
      ; receiptBoundary =
          "B1 records prime-band DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt projectors for p in {2,3,5} and a low-frequency residual"
          ∷ "Completeness is recorded because dyadic bands cover the standard DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt decomposition"
          ∷ "No NS regularity or Clay promotion is asserted"
          ∷ []
      }

agda_module DASHI.Physics.Closure.PrimeBandLPDefinitionReceipt where
  open import Agda.Primitive
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import Data.Empty
  open import Data.List.Base
  open import DASHI.Physics.Closure.NSLittlewoodPaleyCarrierReceipt

  primeBandLPDefinitionDoesNotPromoteClay :
    clayNavierStokesPromoted canonicalPrimeBandLPDefinitionReceipt ≡ false
  primeBandLPDefinitionDoesNotPromoteClay =
    refl

