/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Agda.Syntax

/-!
# `DASHI.Physics.Closure.QuantumPathFibreObservationQuotient`, transliterated

Generated by `tools/agda2lean.py` from the ingested upstream source
`upstream/dashi_agda/master/DASHI/Physics/Closure/QuantumPathFibreObservationQuotient.agda`.
Do not edit by hand: re-run the translator instead.
-/

open Agda

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where

  open import Agda.Builtin.Bool

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  ------------------------------------------------------------------------
  -- Quantum optics as phase-sensitive transport over admissible path fibres.
  --
  -- This is a theorem-thin observation surface for the fetched thread tail.
  -- It records the shared carrier behind double-slit, Feynman/Fermat mirrors,
  -- gratings/masks, and quantum eraser experiments:
  --
  --   admissible path fibres
  --     → amplitude/action/phase contribution
  --     → quotient-dependent observable
  --
  -- The module deliberately does not promote a hidden classical path, a
  -- retrocausal update, a collapse theorem, global QED completeness, or an
  -- O(1) rendering theorem.

  data PathFibreLayer : Set where
    sourceBoundaryLayer : PathFibreLayer
    admissibleFibreLayer : PathFibreLayer
    amplitudeLayer : PathFibreLayer
    actionLayer : PathFibreLayer
    phaseContributionLayer : PathFibreLayer
    interferenceLayer : PathFibreLayer
    observationQuotientLayer : PathFibreLayer
    coincidenceSelectionLayer : PathFibreLayer

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalQuantumPathLayers : List PathFibreLayer
  canonicalQuantumPathLayers =
    sourceBoundaryLayer
    ∷ admissibleFibreLayer
    ∷ amplitudeLayer
    ∷ actionLayer
    ∷ phaseContributionLayer
    ∷ interferenceLayer
    ∷ observationQuotientLayer
    ∷ coincidenceSelectionLayer
    ∷ []

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  data SlitBranch : Set where
    leftBranch : SlitBranch
    rightBranch : SlitBranch
    whichPathDistinguishedBranch : SlitBranch

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  data PhaseCouplingMode : Set where
    coherentCrossCoupling : PhaseCouplingMode
    constructiveInterference : PhaseCouplingMode
    destructiveInterference : PhaseCouplingMode
    decoheredWhichPathCoupling : PhaseCouplingMode

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  data PathIntegralTopology : Set where
    allAdmissibleFibres : PathIntegralTopology
    stationaryActionAttractor : PathIntegralTopology
    stationaryPhaseAttractor : PathIntegralTopology
    mirrorFermatAttractor : PathIntegralTopology
    gratingMaskRetopologized : PathIntegralTopology

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  data ObservationQuotientKind : Set where
    coherentScreenQuotient : ObservationQuotientKind
    whichPathQuotient : ObservationQuotientKind
    oneParticleSmudgeQuotient : ObservationQuotientKind
    jointCoincidenceQuotient : ObservationQuotientKind
    correlatedSubFibreQuotient : ObservationQuotientKind

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  data QuantumPathNonPromotionBoundary : Set where
    noFutureChangesPastClaim : QuantumPathNonPromotionBoundary
    noClassicalHiddenPathClaim : QuantumPathNonPromotionBoundary
    noGlobalQEDCompletenessClaim : QuantumPathNonPromotionBoundary
    noO1RendererTheorem : QuantumPathNonPromotionBoundary
    noMeasurementCollapseTheorem : QuantumPathNonPromotionBoundary
    noRetrocausalEraserClaim : QuantumPathNonPromotionBoundary

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalQuantumPathBoundaries :
    List QuantumPathNonPromotionBoundary
  canonicalQuantumPathBoundaries =
    noFutureChangesPastClaim
    ∷ noClassicalHiddenPathClaim
    ∷ noGlobalQEDCompletenessClaim
    ∷ noO1RendererTheorem
    ∷ noMeasurementCollapseTheorem
    ∷ noRetrocausalEraserClaim
    ∷ []

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  ------------------------------------------------------------------------
  -- Common carrier: admissible path fibres with amplitude/action/phase data.

  record AdmissiblePathFibreCarrier : Set₁ where
    field
      SourceBoundary : Set
      DetectorBoundary : Set
      PathFibre : Set
      Amplitude : Set
      Action : Set
      PhaseContribution : Set
      AdmissibilityReceipt : Set

      admissibleFibre :
        SourceBoundary →
        DetectorBoundary →
        PathFibre →
        AdmissibilityReceipt →
        Set

      amplitudeOf :
        PathFibre →
        Amplitude

      actionOf :
        PathFibre →
        Action

      phaseContributionOf :
        PathFibre →
        PhaseContribution

      combineAmplitudes :
        List PathFibre →
        Amplitude

      phaseCoupling :
        PathFibre →
        PathFibre →
        PhaseCouplingMode

      carrierReading :
        String

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  open AdmissiblePathFibreCarrier public

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  ------------------------------------------------------------------------
  -- Double slit: coherent branch split and which-path quotient.

  record DoubleSlitPhaseSurface
      (carrier : AdmissiblePathFibreCarrier) : Set₁ where
    field
      ScreenObservation : Set
      BranchQuotient : Set

      leftFibre :
        PathFibre carrier

      rightFibre :
        PathFibre carrier

      coherentSplit :
        PathFibre carrier →
        List (PathFibre carrier)

      branchOf :
        PathFibre carrier →
        SlitBranch

      crossFibrePhaseCoupling :
        PathFibre carrier →
        PathFibre carrier →
        PhaseCouplingMode

      interferenceAtScreen :
        PathFibre carrier →
        PathFibre carrier →
        ScreenObservation

      whichPathObservation :
        PathFibre carrier →
        BranchQuotient

      branchDistinguished :
        BranchQuotient →
        Set

      quotientKind :
        BranchQuotient →
        ObservationQuotientKind

      doubleSlitReading :
        String

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  open DoubleSlitPhaseSurface public

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  ------------------------------------------------------------------------
  -- Feynman/Fermat mirror: path integral and stationary-phase attractor.

  record FeynmanFermatPathSurface
      (carrier : AdmissiblePathFibreCarrier) : Set₁ where
    field
      PathIntegralObservable : Set
      GratingMask : Set
      CancellationTopology : Set

      admissibleFibresBetween :
        SourceBoundary carrier →
        DetectorBoundary carrier →
        List (PathFibre carrier)

      pathIntegralOver :
        List (PathFibre carrier) →
        PathIntegralObservable

      stationaryAction :
        PathFibre carrier →
        Set

      stationaryPhase :
        PathFibre carrier →
        Set

      attractorTopology :
        PathFibre carrier →
        PathIntegralTopology

      mirrorFermatPath :
        SourceBoundary carrier →
        DetectorBoundary carrier →
        PathFibre carrier

      retopologizeByMask :
        GratingMask →
        List (PathFibre carrier) →
        List (PathFibre carrier)

      cancellationTopology :
        GratingMask →
        CancellationTopology

      feynmanFermatReading :
        String

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  open FeynmanFermatPathSurface public

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  ------------------------------------------------------------------------
  -- Quantum eraser: one-particle quotient vs joint coincidence quotient.

  record QuantumEraserQuotient
      (carrier : AdmissiblePathFibreCarrier) : Set₁ where
    field
      Signal : Set
      Idler : Set
      EntangledPair : Set
      OneParticleObservation : Set
      CoincidenceObservation : Set
      CorrelatedSubFibre : Set

      entangle :
        Signal →
        Idler →
        EntangledPair

      signalFibre :
        EntangledPair →
        PathFibre carrier

      idlerFibre :
        EntangledPair →
        PathFibre carrier

      oneParticleQuotient :
        EntangledPair →
        OneParticleObservation

      oneParticleQuotientKind :
        OneParticleObservation →
        ObservationQuotientKind

      smudgedByIdlerTrace :
        OneParticleObservation →
        Set

      coincidenceQuotient :
        EntangledPair →
        CoincidenceObservation

      coincidenceQuotientKind :
        CoincidenceObservation →
        ObservationQuotientKind

      selectCorrelatedSubFibre :
        CoincidenceObservation →
        CorrelatedSubFibre

      subFibreIsSelectedByJointData :
        CorrelatedSubFibre →
        Set

      eraserReading :
        String

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  open QuantumEraserQuotient public

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  ------------------------------------------------------------------------
  -- Aggregate observation quotient and non-promotion certificate.

  record QuantumPathFibreObservationQuotient : Set₁ where
    field
      carrier :
        AdmissiblePathFibreCarrier

      doubleSlitSurface :
        DoubleSlitPhaseSurface carrier

      feynmanFermatSurface :
        FeynmanFermatPathSurface carrier

      quantumEraserSurface :
        QuantumEraserQuotient carrier

      layers :
        List PathFibreLayer

      layersAreCanonical :
        layers ≡ canonicalQuantumPathLayers

      boundaries :
        List QuantumPathNonPromotionBoundary

      boundariesAreCanonical :
        boundaries ≡ canonicalQuantumPathBoundaries

      observationReading :
        String

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  open QuantumPathFibreObservationQuotient public

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  record QuantumPathNonPromotionCertificate
      (surface : QuantumPathFibreObservationQuotient) : Set where
    field
      boundariesHeld :
        boundaries surface ≡ canonicalQuantumPathBoundaries

      futureChangesPastPromoted :
        Bool

      futureChangesPastPromotedIsFalse :
        futureChangesPastPromoted ≡ false

      classicalHiddenPathPromoted :
        Bool

      classicalHiddenPathPromotedIsFalse :
        classicalHiddenPathPromoted ≡ false

      globalQEDCompletenessPromoted :
        Bool

      globalQEDCompletenessPromotedIsFalse :
        globalQEDCompletenessPromoted ≡ false

      o1RendererTheoremPromoted :
        Bool

      o1RendererTheoremPromotedIsFalse :
        o1RendererTheoremPromoted ≡ false

      measurementCollapseTheoremPromoted :
        Bool

      measurementCollapseTheoremPromotedIsFalse :
        measurementCollapseTheoremPromoted ≡ false

      retrocausalEraserPromoted :
        Bool

      retrocausalEraserPromotedIsFalse :
        retrocausalEraserPromoted ≡ false

      certificateReading :
        String

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  open QuantumPathNonPromotionCertificate public

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  ------------------------------------------------------------------------
  -- Toy inhabitants.

  data QuantumPathToken : Set where
    sourceToken : QuantumPathToken
    detectorToken : QuantumPathToken
    genericFibreToken : QuantumPathToken
    leftFibreToken : QuantumPathToken
    rightFibreToken : QuantumPathToken
    signalToken : QuantumPathToken
    idlerToken : QuantumPathToken
    pairToken : QuantumPathToken
    maskToken : QuantumPathToken
    observationToken : QuantumPathToken
    subFibreToken : QuantumPathToken

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalAdmissiblePathFibreCarrier :
    AdmissiblePathFibreCarrier
  canonicalAdmissiblePathFibreCarrier =
    record
      { SourceBoundary =
          QuantumPathToken
      ; DetectorBoundary =
          QuantumPathToken
      ; PathFibre =
          QuantumPathToken
      ; Amplitude =
          QuantumPathToken
      ; Action =
          QuantumPathToken
      ; PhaseContribution =
          QuantumPathToken
      ; AdmissibilityReceipt =
          ⊤
      ; admissibleFibre =
          λ _ _ _ _ => ⊤
      ; amplitudeOf =
          λ _ => observationToken
      ; actionOf =
          λ _ => observationToken
      ; phaseContributionOf =
          λ _ => observationToken
      ; combineAmplitudes =
          λ _ => observationToken
      ; phaseCoupling =
          λ _ _ => coherentCrossCoupling
      ; carrierReading =
          "Toy path carrier: every admissible fibre carries amplitude, action, and phase contribution slots."
      }

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalDoubleSlitPhaseSurface :
    DoubleSlitPhaseSurface canonicalAdmissiblePathFibreCarrier
  canonicalDoubleSlitPhaseSurface =
    record
      { ScreenObservation =
          QuantumPathToken
      ; BranchQuotient =
          QuantumPathToken
      ; leftFibre =
          leftFibreToken
      ; rightFibre =
          rightFibreToken
      ; coherentSplit =
          λ _ => leftFibreToken ∷ rightFibreToken ∷ []
      ; branchOf =
          λ fibre =>
            leftBranch
      ; crossFibrePhaseCoupling =
          λ _ _ => coherentCrossCoupling
      ; interferenceAtScreen =
          λ _ _ => observationToken
      ; whichPathObservation =
          λ _ => observationToken
      ; branchDistinguished =
          λ _ => ⊤
      ; quotientKind =
          λ _ => whichPathQuotient
      ; doubleSlitReading =
          "Double slit transport splits coherently into branch fibres; a which-path quotient distinguishes branch data and changes the observation quotient."
      }

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalFeynmanFermatPathSurface :
    FeynmanFermatPathSurface canonicalAdmissiblePathFibreCarrier
  canonicalFeynmanFermatPathSurface =
    record
      { PathIntegralObservable =
          QuantumPathToken
      ; GratingMask =
          QuantumPathToken
      ; CancellationTopology =
          QuantumPathToken
      ; admissibleFibresBetween =
          λ _ _ => genericFibreToken ∷ leftFibreToken ∷ rightFibreToken ∷ []
      ; pathIntegralOver =
          λ _ => observationToken
      ; stationaryAction =
          λ _ => ⊤
      ; stationaryPhase =
          λ _ => ⊤
      ; attractorTopology =
          λ _ => stationaryPhaseAttractor
      ; mirrorFermatPath =
          λ _ _ => genericFibreToken
      ; retopologizeByMask =
          λ _ fibres => fibres
      ; cancellationTopology =
          λ _ => observationToken
      ; feynmanFermatReading =
          "Feynman/Fermat transport sums admissible fibres while stationary action/phase acts as an attractor; gratings and masks alter cancellation topology."
      }

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalQuantumEraserQuotient :
    QuantumEraserQuotient canonicalAdmissiblePathFibreCarrier
  canonicalQuantumEraserQuotient =
    record
      { Signal =
          QuantumPathToken
      ; Idler =
          QuantumPathToken
      ; EntangledPair =
          QuantumPathToken
      ; OneParticleObservation =
          QuantumPathToken
      ; CoincidenceObservation =
          QuantumPathToken
      ; CorrelatedSubFibre =
          QuantumPathToken
      ; entangle =
          λ _ _ => pairToken
      ; signalFibre =
          λ _ => signalToken
      ; idlerFibre =
          λ _ => idlerToken
      ; oneParticleQuotient =
          λ _ => observationToken
      ; oneParticleQuotientKind =
          λ _ => oneParticleSmudgeQuotient
      ; smudgedByIdlerTrace =
          λ _ => ⊤
      ; coincidenceQuotient =
          λ _ => observationToken
      ; coincidenceQuotientKind =
          λ _ => jointCoincidenceQuotient
      ; selectCorrelatedSubFibre =
          λ _ => subFibreToken
      ; subFibreIsSelectedByJointData =
          λ _ => ⊤
      ; eraserReading =
          "Quantum eraser transport keeps the one-particle quotient smudged while a joint coincidence quotient may select a correlated sub-fibre without retrocausal promotion."
      }

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalQuantumPathFibreObservationQuotient :
    QuantumPathFibreObservationQuotient
  canonicalQuantumPathFibreObservationQuotient =
    record
      { carrier =
          canonicalAdmissiblePathFibreCarrier
      ; doubleSlitSurface =
          canonicalDoubleSlitPhaseSurface
      ; feynmanFermatSurface =
          canonicalFeynmanFermatPathSurface
      ; quantumEraserSurface =
          canonicalQuantumEraserQuotient
      ; layers =
          canonicalQuantumPathLayers
      ; layersAreCanonical =
          refl
      ; boundaries =
          canonicalQuantumPathBoundaries
      ; boundariesAreCanonical =
          refl
      ; observationReading =
          "Quantum optics is recorded here as phase-sensitive transport over admissible path fibres, observed through explicit quotients."
      }

agda_module DASHI.Physics.Closure.QuantumPathFibreObservationQuotient where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalQuantumPathNonPromotionCertificate :
    QuantumPathNonPromotionCertificate
      canonicalQuantumPathFibreObservationQuotient
  canonicalQuantumPathNonPromotionCertificate =
    record
      { boundariesHeld =
          refl
      ; futureChangesPastPromoted =
          false
      ; futureChangesPastPromotedIsFalse =
          refl
      ; classicalHiddenPathPromoted =
          false
      ; classicalHiddenPathPromotedIsFalse =
          refl
      ; globalQEDCompletenessPromoted =
          false
      ; globalQEDCompletenessPromotedIsFalse =
          refl
      ; o1RendererTheoremPromoted =
          false
      ; o1RendererTheoremPromotedIsFalse =
          refl
      ; measurementCollapseTheoremPromoted =
          false
      ; measurementCollapseTheoremPromotedIsFalse =
          refl
      ; retrocausalEraserPromoted =
          false
      ; retrocausalEraserPromotedIsFalse =
          refl
      ; certificateReading =
          "The quotient is observation-only: it blocks retrocausal, hidden-path, global-QED, O(1)-renderer, and measurement-collapse promotion."
      }

