module DASHI.Reasoning.AristotleMCGSRecoveredWitness where

open import Agda.Builtin.Bool using (Bool; true; false)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.List using (List; []; _∷_)
open import Agda.Builtin.Nat using (Nat)
open import Agda.Builtin.String using (String)

import DASHI.Reasoning.AristotleMCGSIntrospectiveSpecimen as Spec

open Spec using
  ( State; S0; S1; S1p; S2; S3; S4
  ; Action; A0; A1; A2; T1; T1p; T2; T3
  )

------------------------------------------------------------------------
-- Pixel-derived semantic signature.
--
-- These values are transcribed from the machine artifact generated by
-- scripts/aristotle_introspective_roundtrip.py:
--
--   artifacts/introspection/aristotle/opencv_decode_faithful.json
--
-- The decoder does not read the Agda constructors.  It recovers circles,
-- wide rectangles, inner proof outlines, triangle fibre tags, and edge roles
-- from the raster.  The source/target distinction is recovered from the
-- distinct source/target stroke grammar plus intermediate-node occlusion.
------------------------------------------------------------------------

recoveredStateCount : Nat
recoveredStateCount = 6

recoveredActionCount : Nat
recoveredActionCount = 7

recoveredStateProved : State → Bool
recoveredStateProved S0  = true
recoveredStateProved S1  = true
recoveredStateProved S1p = true
recoveredStateProved S2  = true
recoveredStateProved S3  = true
recoveredStateProved S4  = false

recoveredActionProved : Action → Bool
recoveredActionProved A0  = true
recoveredActionProved A1  = true
recoveredActionProved A2  = false
recoveredActionProved T1  = true
recoveredActionProved T1p = true
recoveredActionProved T2  = true
recoveredActionProved T3  = true

recoveredSource : Action → State
recoveredSource A0  = S0
recoveredSource A1  = S0
recoveredSource A2  = S0
recoveredSource T1  = S1
recoveredSource T1p = S1p
recoveredSource T2  = S2
recoveredSource T3  = S3

recoveredTargets : Action → List State
recoveredTargets A0  = S1 ∷ S2 ∷ []
recoveredTargets A1  = S3 ∷ []
recoveredTargets A2  = S4 ∷ []
recoveredTargets T1  = []
recoveredTargets T1p = []
recoveredTargets T2  = []
recoveredTargets T3  = []

recoveredSharedFibreTag : State → Bool
recoveredSharedFibreTag S1  = true
recoveredSharedFibreTag S1p = true
recoveredSharedFibreTag _   = false

------------------------------------------------------------------------
-- Pointwise round-trip theorems.
------------------------------------------------------------------------

stateCountExact : recoveredStateCount ≡ 6
stateCountExact = refl

actionCountExact : recoveredActionCount ≡ 7
actionCountExact = refl

stateStatusExact :
  (s : State) → recoveredStateProved s ≡ Spec.expectedStateProved s
stateStatusExact S0  = refl
stateStatusExact S1  = refl
stateStatusExact S1p = refl
stateStatusExact S2  = refl
stateStatusExact S3  = refl
stateStatusExact S4  = refl

actionStatusExact :
  (a : Action) → recoveredActionProved a ≡ Spec.expectedActionProved a
actionStatusExact A0  = refl
actionStatusExact A1  = refl
actionStatusExact A2  = refl
actionStatusExact T1  = refl
actionStatusExact T1p = refl
actionStatusExact T2  = refl
actionStatusExact T3  = refl

sourceExact : (a : Action) → recoveredSource a ≡ Spec.source a
sourceExact A0  = refl
sourceExact A1  = refl
sourceExact A2  = refl
sourceExact T1  = refl
sourceExact T1p = refl
sourceExact T2  = refl
sourceExact T3  = refl

targetsExact : (a : Action) → recoveredTargets a ≡ Spec.targets a
targetsExact A0  = refl
targetsExact A1  = refl
targetsExact A2  = refl
targetsExact T1  = refl
targetsExact T1p = refl
targetsExact T2  = refl
targetsExact T3  = refl

fibreTagExact :
  (s : State) → recoveredSharedFibreTag s ≡ Spec.expectedSharedFibreTag s
fibreTagExact S0  = refl
fibreTagExact S1  = refl
fibreTagExact S1p = refl
fibreTagExact S2  = refl
fibreTagExact S3  = refl
fibreTagExact S4  = refl

------------------------------------------------------------------------
-- One certificate bundles the introspective round-trip obligations.
------------------------------------------------------------------------

record CVRoundTripExact : Set where
  constructor cvRoundTripExact
  field
    stateCountRecovered : recoveredStateCount ≡ 6
    actionCountRecovered : recoveredActionCount ≡ 7
    stateProofStatusRecovered :
      (s : State) → recoveredStateProved s ≡ Spec.expectedStateProved s
    actionProofStatusRecovered :
      (a : Action) → recoveredActionProved a ≡ Spec.expectedActionProved a
    actionSourcesRecovered :
      (a : Action) → recoveredSource a ≡ Spec.source a
    actionTargetsRecovered :
      (a : Action) → recoveredTargets a ≡ Spec.targets a
    observerFibreRecovered :
      (s : State) → recoveredSharedFibreTag s ≡ Spec.expectedSharedFibreTag s

open CVRoundTripExact public

canonicalCVRoundTripExact : CVRoundTripExact
canonicalCVRoundTripExact = cvRoundTripExact
  stateCountExact
  actionCountExact
  stateStatusExact
  actionStatusExact
  sourceExact
  targetsExact
  fibreTagExact

recoveredReading : String
recoveredReading =
  "OpenCV(Render(Aristotle specimen)) recovers the finite state/action counts, proof-status signature, directed hypergraph source/targets, and nontrivial observer fibre exactly."
