module DASHI.Core.PluralEpistemicRevisionBackpropagationEverything where

import DASHI.Core.ExperimentalOutcomeOrientationBackpropagationBidiExact
import DASHI.Core.OrientationCompassExperimentalInterpretationBidiExact
import DASHI.Core.ArgumentResponseNonGeometricOppositeBidiExact
import DASHI.Core.DependencySensitiveClosureReopeningBidiExact
import DASHI.Core.DependencyGraphResultBackpropagationBidiExact
import DASHI.Core.SequentialOutcomeBackpropagationBidiExact

import DASHI.Core.DiagnosisFibreSalienceSchedulerBidiExact
import DASHI.Core.DiagnosisExperimentPortfolioBidiExact
import DASHI.Core.DependencyWeightedDiagnosisSchedulerBidiExact
import DASHI.Core.SequentialDiagnosisDebugLoopBidiExact
import DASHI.Core.ArgumentDiagnosisDebuggingBidiExact
import DASHI.Governance.GovernanceDiagnosisRepairSchedulerBidiExact
import DASHI.Core.RuntimeDiagnosisRepairSchedulerBidiExact
import DASHI.Cognition.PNF.SensibLawDiagnosisRepairSchedulerBidiExact
import DASHI.Biology.DrosophilaDiagnosisRepairSchedulerBidiExact

import DASHI.Core.TemporalDiagnosisProvenanceHistoryBidiExact
import DASHI.Core.TemporalDiagnosisFibreProjectionBidiExact
import DASHI.Core.TemporalDiagnosisHotColdProjectionBidiExact
import DASHI.Core.TemporalDiagnosisSalienceRecalibrationBidiExact
import DASHI.Core.SequentialTemporalDiagnosisRevisionLoopBidiExact
import DASHI.Core.ArgumentTemporalDiagnosisHistoryBidiExact
import DASHI.Core.RuntimeTemporalDiagnosisHistoryBidiExact
import DASHI.Governance.GovernanceTemporalDiagnosisHistoryBidiExact
import DASHI.Cognition.PNF.SensibLawTemporalDiagnosisHistoryBidiExact
import DASHI.Biology.DrosophilaTemporalDiagnosisHistoryBidiExact

import DASHI.Core.TemporalDiagnosisDependencyLineageBidiExact
import DASHI.Core.IncrementalDiagnosisTruthMaintenanceBidiExact

import DASHI.Core.SelectiveInvalidationParetoFrontierBidiExact
import DASHI.Core.RecursiveSelectiveInvalidationParetoTruthMaintenanceBidiExact

-- Uploaded Aristotle Lean methodology bridge + exact recompute worklist.
import DASHI.Core.AristotleFrontierWorklistTruthMaintenanceBridgeExact
import DASHI.Core.SelectiveInvalidationWorklistBidiExact

-- Conservative ontology-gap frontiers and non-monotone diagnosis frontiers are
-- kept distinct: evidence extension may retain old entailments while the current
-- diagnosis projection can still expand through reactivation.
import DASHI.Core.ConservativeEvidenceFrontierDiagnosisNonMonotonicityBidiExact

-- Dependency-derived least invalidation + recursive compiler.
import DASHI.Core.DependencyDerivedMinimalInvalidationBidiExact
import DASHI.Core.DependencyDerivedRecursiveParetoTruthMaintenanceBidiExact

import DASHI.Biology.AliceBrownDiagnosisRepairSchedulerBidiExact
import DASHI.Biology.AliceBrownTemporalDiagnosisDependencyLineageBidiExact
import DASHI.Biology.AliceBrownSelectiveInvalidationParetoBidiExact
import DASHI.Biology.AliceBrownRecursiveParetoTruthMaintenanceBidiExact
import DASHI.Biology.AliceBrownDependencyDerivedInvalidationBidiExact
import DASHI.Culture.JohnAnthonyBrownDiagnosisRepairSchedulerBidiExact
import DASHI.Culture.JohnAnthonyBrownTemporalDiagnosisDependencyLineageBidiExact
import DASHI.Culture.JohnAnthonyBrownSelectiveInvalidationParetoBidiExact
import DASHI.Culture.JohnAnthonyBrownRecursiveParetoTruthMaintenanceBidiExact
import DASHI.Culture.JohnAnthonyBrownDependencyDerivedInvalidationBidiExact
