module DASHI.Governance.JusticeEvidenceQualifiedValidationExact where

------------------------------------------------------------------------
-- EVIDENCE-QUALIFIED GOVERNANCE VALIDATION
--
-- GovernanceValidation and the Belnap/Dunn-style support square are distinct
-- four-way objects.  GovernanceValidation's fourth constructor is role
-- inapplicability; the support square instead distinguishes contradictory
-- support from missing support.  They therefore must not be identified merely
-- because both happen to have four named states.
--
-- Source calibration:
-- Nuel D. Belnap, "A Useful Four-Valued Logic", in J. Michael Dunn and
-- George Epstein (eds.), Modern Uses of Multiple-Valued Logic, 1977, pp. 5-37.
-- DOI: 10.1007/978-94-010-1161-7_2.
--
-- J. Michael Dunn, "Intuitive Semantics for First-Degree Entailments and
-- 'Coupled Trees'", Philosophical Studies 29(3), 149-168 (1976).
-- DOI: 10.1007/BF00373152.
--
-- The collapse below is a DASHI presentation map, not a claim that the cited
-- logics define GovernanceValidation.
------------------------------------------------------------------------

open import DASHI.Core.Prelude

import DASHI.Core.RequiredAxisSupportSquareExact as Support
import DASHI.Governance.TransitionResidual as Transition

------------------------------------------------------------------------
-- Evidence presentation into the existing governance residual surface.
-- Contradictory and missing evidence are both unresolved at this coarse layer.
-- Role inapplicability is deliberately not generated by evidence polarity.
------------------------------------------------------------------------

evidencePresentation :
  Support.SupportSquare → Transition.GovernanceValidation
evidencePresentation square with Support.supportState square
... | Support.positiveOnly = Transition.satisfied
... | Support.negativeOnly = Transition.positivelyViolated
... | Support.conflictingState = Transition.undeterminedAxisIncomplete
... | Support.missingState = Transition.undeterminedAxisIncomplete

contradictionAndMissingCollapseToSameGovernancePresentation :
  evidencePresentation (Support.supportSquare true true)
  ≡ evidencePresentation (Support.supportSquare false false)
contradictionAndMissingCollapseToSameGovernancePresentation = refl

supportStatesRemainDistinctBeforePresentation :
  Support.supportState (Support.supportSquare true true)
  ≡ Support.supportState (Support.supportSquare false false) →
  ⊥
supportStatesRemainDistinctBeforePresentation = Support.conflictingIsNotMissing

record EvidenceQualifiedGovernanceValidation : Set where
  constructor evidenceQualifiedGovernanceValidation
  field
    evidence : Support.SupportSquare
    validation : Transition.GovernanceValidation
    presentationMatches : validation ≡ evidencePresentation evidence

open EvidenceQualifiedGovernanceValidation public

conflictingQualifiedValidation : EvidenceQualifiedGovernanceValidation
conflictingQualifiedValidation =
  evidenceQualifiedGovernanceValidation
    (Support.supportSquare true true)
    Transition.undeterminedAxisIncomplete
    refl

missingQualifiedValidation : EvidenceQualifiedGovernanceValidation
missingQualifiedValidation =
  evidenceQualifiedGovernanceValidation
    (Support.supportSquare false false)
    Transition.undeterminedAxisIncomplete
    refl

qualifiedValidationsShareCoarsePresentation :
  validation conflictingQualifiedValidation
  ≡ validation missingQualifiedValidation
qualifiedValidationsShareCoarsePresentation = refl

qualifiedValidationsRetainDifferentEvidenceState :
  Support.supportState (evidence conflictingQualifiedValidation)
  ≡ Support.supportState (evidence missingQualifiedValidation) →
  ⊥
qualifiedValidationsRetainDifferentEvidenceState =
  Support.conflictingIsNotMissing

record GovernanceValidationDeterminesEvidenceState : Set₁ where
  constructor governanceValidationDeterminesEvidenceState
  field
    reconstructEvidenceState :
      Transition.GovernanceValidation → Support.SupportState
    exactOnQualified :
      (qualified : EvidenceQualifiedGovernanceValidation) →
      reconstructEvidenceState (validation qualified)
      ≡ Support.supportState (evidence qualified)

open GovernanceValidationDeterminesEvidenceState public

governanceValidationCannotReconstructEvidenceState :
  GovernanceValidationDeterminesEvidenceState → ⊥
governanceValidationCannotReconstructEvidenceState decoder =
  Support.conflictingIsNotMissing
    (trans
      (sym (exactOnQualified decoder conflictingQualifiedValidation))
      (trans
        (cong (reconstructEvidenceState decoder)
          qualifiedValidationsShareCoarsePresentation)
        (exactOnQualified decoder missingQualifiedValidation)))

record JusticeEvidenceQualifiedValidationBoundary : Set where
  constructor justiceEvidenceQualifiedValidationBoundary
  field
    governanceValidationEqualsSupportSquare : Bool
    contradictionEqualsMissingEvidence : Bool
    unresolvedPresentationMayHideDistinctEvidenceStates : Bool
    inapplicableToRoleIsGeneratedByEvidencePolarity : Bool

canonicalJusticeEvidenceQualifiedValidationBoundary :
  JusticeEvidenceQualifiedValidationBoundary
canonicalJusticeEvidenceQualifiedValidationBoundary =
  justiceEvidenceQualifiedValidationBoundary false false true false
