/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Wikidata.Core

/-!
# Class order and narrative domain

Wikidata's class-order documentation defines a *second-order class* by the order
of its instances: the instances of a second-order class are themselves classes.
That is a coordinate of predication.  It says nothing about whether the class is
editorially *about* fiction, exists only inside a fictional world, or is an
ordinary modelling class whose member classes happen to classify fictional
individuals — and a label such as `fictional second-order class` names the pair
without distinguishing which reading is meant.

This module keeps the coordinates apart and proves that they are independent.

* **A label determines neither coordinate.** Three readings share one public
  label and one class order and differ in narrative domain, so no function of
  the label (`no_labelOnly_narrative_decoder`) and no function of the order
  (`no_orderOnly_narrative_decoder`) returns the domain.
* **The coordinates are genuinely independent**: every combination of class
  order, narrative domain and applicability is occupied
  (`state_of_coordinates_exists`), and each projection is surjective.
* **Order is a graph property; the narrative domain is not.** In one knowledge
  base two classes are second order by the `P31` engine of
  `RequestProject.Wikidata.Core` while only one of them is recorded as being
  about fiction (`secondOrder_does_not_determine_fiction`), so the graph fact
  that the order coordinate records leaves the narrative coordinate open.
* **Whether the question can be decided at the current level is a third
  coordinate**: the inspection decision is a function of applicability
  (`inspectionDecision`), and is not determined by the narrative domain
  (`decision_not_determined_by_narrative`).

Source: the upstream Agda module
`DASHI.Ontology.WikidataHigherOrderFictionContextExact`, and Wikidata's
class-order and fiction-modelling documentation.
-/

/-! ### Provenance (generated by `tools/provenance.py`)

Source mix of this module's 35 declarations: 0 traced to the DASHI Agda
bridge (`chboishabba/dashi_agda` PR #555 / #581 / #582), 16 rendering the Wikidata
data model, 19 original to this port.  The bridge-traced declarations are
marked with `-- @source` below.  Full ledger: `docs/status/PROVENANCE.md`.
-/

namespace Wikidata
namespace ClassOrder

/-! ## The coordinates -/

/-- The order of predication of a class. -/
inductive Order
  /-- Its instances are individuals. -/
  | firstOrder
  /-- Its instances are first-order classes. -/
  | secondOrder
  /-- Its instances are second-order classes. -/
  | thirdOrder
  /-- Its instances vary in order. -/
  | variableOrder
  deriving DecidableEq, Repr, Inhabited

/-- What the class has to do with fiction. -/
inductive NarrativeDomain
  /-- An ordinary real-world modelling class. -/
  | ordinaryModelling
  /-- A class that is editorially *about* fiction. -/
  | editoriallyAboutFiction
  /-- A class read as existing inside a fictional world. -/
  | inWorldFictional
  /-- A class whose member classes classify fictional individuals. -/
  | memberClassesClassifyFictionalIndividuals
  /-- Not recorded. -/
  | unspecified
  deriving DecidableEq, Repr, Inhabited

/-- Whether the question being asked can be settled at the level of inspection
currently committed to. -/
inductive Applicability
  /-- Yes. -/
  | applicableHere
  /-- The coordinates do not meet at this level. -/
  | noTypedMeetAtCurrentLevel
  /-- The question is outside the comparison currently in scope. -/
  | outsideCurrentComparisonScope
  /-- The projection to this level has collapsed a coordinate the question
  needs. -/
  | projectionCollapsedRequiredCoordinate
  deriving DecidableEq, Repr, Inhabited

/-- A class as an editor meets it: a public label over three coordinates. -/
structure State where
  /-- What the item is called. -/
  publicLabel : String
  /-- Its order of predication. -/
  order : Order
  /-- Its relation to fiction. -/
  narrativeDomain : NarrativeDomain
  /-- Whether the current level can settle the question asked. -/
  applicability : Applicability
  /-- Why this reading is recorded. -/
  provenanceNote : String
  deriving DecidableEq, Repr, Inhabited

/-! ## Three readings of one label -/

/-- An editorial class of classes used to organise fiction. -/
def editorialReading : State where
  publicLabel := "fictional second-order class"
  order := .secondOrder
  narrativeDomain := .editoriallyAboutFiction
  applicability := .applicableHere
  provenanceNote := "editorial classification about fictional first-order classes"

/-- The same label read as a second-order class inside a fictional world.  This
is a countermodel carrier, not a claim about any live item. -/
def inWorldReading : State where
  publicLabel := "fictional second-order class"
  order := .secondOrder
  narrativeDomain := .inWorldFictional
  applicability := .outsideCurrentComparisonScope
  provenanceNote := "countermodel: second-order classification inside a fictional world"

/-- The same label read as an ordinary class of classes whose member classes
classify fictional individuals. -/
def memberClassReading : State where
  publicLabel := "fictional second-order class"
  order := .secondOrder
  narrativeDomain := .memberClassesClassifyFictionalIndividuals
  applicability := .applicableHere
  provenanceNote := "ordinary modelling class of classes of fictional individuals"

/-- The three readings share the public label. -/
theorem readings_share_label :
    editorialReading.publicLabel = inWorldReading.publicLabel ∧
    editorialReading.publicLabel = memberClassReading.publicLabel :=
  ⟨rfl, rfl⟩

/-- The three readings share the class order. -/
theorem readings_share_order :
    editorialReading.order = inWorldReading.order ∧
    editorialReading.order = memberClassReading.order :=
  ⟨rfl, rfl⟩

/-- The three readings have pairwise different narrative domains. -/
theorem readings_differ_in_narrative :
    editorialReading.narrativeDomain ≠ inWorldReading.narrativeDomain ∧
    editorialReading.narrativeDomain ≠ memberClassReading.narrativeDomain ∧
    inWorldReading.narrativeDomain ≠ memberClassReading.narrativeDomain := by
  refine ⟨by decide, by decide, by decide⟩

/-- The readings under consideration. -/
def readings : List State := [editorialReading, inWorldReading, memberClassReading]

/-- **The class order does not determine the narrative domain.** -/
theorem no_orderOnly_narrative_decoder :
    ¬ ∃ decode : Order → NarrativeDomain,
        ∀ s ∈ readings, decode s.order = s.narrativeDomain := by
  rintro ⟨decode, h⟩
  have h₁ := h editorialReading (by simp [readings])
  have h₂ := h inWorldReading (by simp [readings])
  rw [show editorialReading.order = inWorldReading.order from rfl] at h₁
  exact absurd (h₁.symm.trans h₂) (by decide)

/-- **The public label does not determine the narrative domain.** -/
theorem no_labelOnly_narrative_decoder :
    ¬ ∃ decode : String → NarrativeDomain,
        ∀ s ∈ readings, decode s.publicLabel = s.narrativeDomain := by
  rintro ⟨decode, h⟩
  have h₁ := h editorialReading (by simp [readings])
  have h₂ := h inWorldReading (by simp [readings])
  rw [show editorialReading.publicLabel = inWorldReading.publicLabel from rfl] at h₁
  exact absurd (h₁.symm.trans h₂) (by decide)

/-- Nor does the pair of label and order. -/
theorem no_labelAndOrder_narrative_decoder :
    ¬ ∃ decode : String → Order → NarrativeDomain,
        ∀ s ∈ readings, decode s.publicLabel s.order = s.narrativeDomain := by
  rintro ⟨decode, h⟩
  have h₁ := h editorialReading (by simp [readings])
  have h₂ := h inWorldReading (by simp [readings])
  rw [show editorialReading.publicLabel = inWorldReading.publicLabel from rfl,
    show editorialReading.order = inWorldReading.order from rfl] at h₁
  exact absurd (h₁.symm.trans h₂) (by decide)

/-! ## The coordinates are independent -/

/-- Every combination of the three coordinates is occupied, so none of them
constrains another. -/
theorem state_of_coordinates_exists (o : Order) (d : NarrativeDomain) (a : Applicability) :
    ∃ s : State, s.order = o ∧ s.narrativeDomain = d ∧ s.applicability = a :=
  ⟨{ publicLabel := "", order := o, narrativeDomain := d, applicability := a,
     provenanceNote := "" }, rfl, rfl, rfl⟩

/-- The order projection is surjective. -/
theorem order_surjective (o : Order) : ∃ s : State, s.order = o :=
  let ⟨s, h, _⟩ := state_of_coordinates_exists o .unspecified .applicableHere
  ⟨s, h⟩

/-- The narrative projection is surjective. -/
theorem narrative_surjective (d : NarrativeDomain) : ∃ s : State, s.narrativeDomain = d :=
  let ⟨s, _, h, _⟩ := state_of_coordinates_exists .firstOrder d .applicableHere
  ⟨s, h⟩

/-! ## Deciding at this level -/

/-- Whether to decide the question here or re-chart first. -/
inductive Decision
  /-- The question can be settled at this level. -/
  | decideAtThisLevel
  /-- A coordinate has to be restored before the question can be settled. -/
  | rechartBeforeDecision
  deriving DecidableEq, Repr, Inhabited

/-- Only an applicable level decides. -/
def inspectionDecision (s : State) : Decision :=
  match s.applicability with
  | .applicableHere => .decideAtThisLevel
  | _ => .rechartBeforeDecision

theorem editorial_decides : inspectionDecision editorialReading = .decideAtThisLevel := rfl

theorem inWorld_recharts : inspectionDecision inWorldReading = .rechartBeforeDecision := rfl

/-- **The decision is not a function of the narrative domain**, and not a
function of the order either: the editorial and in-world readings are decided
differently while the member-class reading, whose domain differs again, is
decided like the editorial one. -/
theorem decision_not_determined_by_narrative :
    ¬ ∃ f : Order → Decision, ∀ s ∈ readings, f s.order = inspectionDecision s := by
  rintro ⟨f, h⟩
  have h₁ := h editorialReading (by simp [readings])
  have h₂ := h inWorldReading (by simp [readings])
  rw [show editorialReading.order = inWorldReading.order from rfl] at h₁
  rw [editorial_decides] at h₁
  rw [inWorld_recharts] at h₂
  exact absurd (h₁.symm.trans h₂) (by decide)

/-! ## Order in the graph

The order coordinate is a fact about the `P31` graph, and the engine of
`RequestProject.Wikidata.Core` computes it.  The narrative coordinate is not
recoverable from it. -/

/-- A class is second order in `kb` when one of its instances itself has an
instance. -/
def isSecondOrderIn (kb : KB) (c : Qid) : Bool :=
  kb.entities.any fun x =>
    isInstanceOf kb x c && kb.entities.any fun y => isInstanceOf kb y x

/-- `Q1000010`: an editorial metaclass of classes of fictional characters. -/
def qFictionalCharacterMetaclass : Qid := ⟨1000010⟩
/-- `Q1000011`: an ordinary metaclass of classes of chemical elements. -/
def qElementMetaclass : Qid := ⟨1000011⟩
/-- `Q1000012`: a class of fictional characters. -/
def qFictionalCharacterClass : Qid := ⟨1000012⟩
/-- `Q1000013`: a class of chemical elements. -/
def qElementClass : Qid := ⟨1000013⟩
/-- `Q1000014`: a fictional character. -/
def qFrodo : Qid := ⟨1000014⟩
/-- `Q1000015`: a chemical element. -/
def qHelium : Qid := ⟨1000015⟩
/-- `Q1000016`: the class of items that are about fiction. -/
def qAboutFiction : Qid := ⟨1000016⟩

/-- A knowledge base with two second-order classes, one of them recorded as
being about fiction. -/
def orderKB : KB where
  entities := [qFictionalCharacterMetaclass, qElementMetaclass, qFictionalCharacterClass,
    qElementClass, qFrodo, qHelium, qAboutFiction]
  statements :=
    [ { subject := qFictionalCharacterClass, property := P31,
        value := qFictionalCharacterMetaclass },
      { subject := qFrodo, property := P31, value := qFictionalCharacterClass },
      { subject := qElementClass, property := P31, value := qElementMetaclass },
      { subject := qHelium, property := P31, value := qElementClass },
      { subject := qFictionalCharacterMetaclass, property := P31, value := qAboutFiction } ]

/-- Both metaclasses are second order. -/
theorem both_metaclasses_second_order :
    isSecondOrderIn orderKB qFictionalCharacterMetaclass = true ∧
    isSecondOrderIn orderKB qElementMetaclass = true := by
  refine ⟨by decide, by decide⟩

/-- Only one of them is recorded as being about fiction. -/
theorem only_one_is_about_fiction :
    isInstanceOf orderKB qFictionalCharacterMetaclass qAboutFiction = true ∧
    isInstanceOf orderKB qElementMetaclass qAboutFiction = false := by
  refine ⟨by decide, by decide⟩

/-- **Being second order does not determine being about fiction.** The two
classes agree on everything the order coordinate records and differ on the
narrative one, so a checker that reads `P31` depth alone cannot recover it. -/
theorem secondOrder_does_not_determine_fiction :
    ¬ ∃ f : Bool → Bool, ∀ c ∈ [qFictionalCharacterMetaclass, qElementMetaclass],
        f (isSecondOrderIn orderKB c) = isInstanceOf orderKB c qAboutFiction := by
  rintro ⟨f, h⟩
  have h₁ := h qFictionalCharacterMetaclass (by simp)
  have h₂ := h qElementMetaclass (by simp)
  rw [show isSecondOrderIn orderKB qFictionalCharacterMetaclass
      = isSecondOrderIn orderKB qElementMetaclass by decide] at h₁
  rw [h₁] at h₂
  revert h₂
  decide

/-- The first-order classes below them are not second order, so the
computation is not constant. -/
theorem classes_are_not_second_order :
    isSecondOrderIn orderKB qFictionalCharacterClass = false ∧
    isSecondOrderIn orderKB qElementClass = false := by
  refine ⟨by decide, by decide⟩

end ClassOrder
end Wikidata
