/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Epistemic.OrderDescent
import RequestProject.Wikidata.Core

/-!
# The derived class relation does not remember the edit order

Two curators add two different *redundant* `P279` statements to the same
knowledge base.  Each edit leaves the derived subclass relation exactly as it
was, so the two possible edit orders end on the same public reading — and on
different knowledge bases, because a statement list records what was added and
when.

Consequently the ontology surface cannot say which edit came last
(`classSurface_cannot_decode_editOrder`), and no further summary of that surface
can either (`coarsening_cannot_decode_editOrder`): coarsening never recovers a
distinction the first projection already erased.  What *does* descend is the
content: the derived relation is the same whichever order was used
(`classSurface_editOrder_eq`), and it is the same as before the edits
(`classSurface_edits_eq_base`).

This is the Wikidata instance of `RequestProject.Epistemic.OrderDescent`.
-/

/-! ### Provenance (generated by `tools/provenance.py`)

Source mix of this module's 16 declarations: 1 traced to the DASHI Agda
bridge (`chboishabba/dashi_agda` PR #555 / #581 / #582), 0 rendering the Wikidata
data model, 15 original to this port.  The bridge-traced declarations are
marked with `-- @source` below.  Full ledger: `docs/status/PROVENANCE.md`.
-/

namespace Wikidata

open Epistemic

/-! ## A three-class fragment -/

/-- Painter. -/
def painter : Qid := ⟨1028181⟩
/-- Artist. -/
def artist : Qid := ⟨483501⟩
/-- Creator. -/
def creator : Qid := ⟨2500638⟩

/-- The classes the public surface is read over. -/
def orderItems : List Qid := [painter, artist, creator]

/-- `painter ⊑ artist ⊑ creator`, with nothing else recorded. -/
def orderBase : KB where
  entities := orderItems
  statements :=
    [ { subject := painter, property := P279, value := artist, rank := Rank.normal },
      { subject := artist, property := P279, value := creator, rank := Rank.normal } ]

/-- Insert a statement at the front of the statement list. -/
def insertStatement (st : Statement) (kb : KB) : KB :=
  { kb with statements := st :: kb.statements }

/-- The first edit: record the derivable superclass `painter ⊑ creator`. -/
def addShortcut : KB → KB :=
  insertStatement { subject := painter, property := P279, value := creator, rank := Rank.normal }

/-- The second edit: record a duplicate of the existing `painter ⊑ artist`. -/
def addDuplicate : KB → KB :=
  insertStatement { subject := painter, property := P279, value := artist, rank := Rank.normal }

/-! ## The public surface -/

/-- The derived subclass relation, read off over `orderItems`: the public
ontology surface. -/
def classSurface (kb : KB) : List Bool :=
  orderItems.flatMap (fun a => orderItems.map (fun b => isSubclassOf kb a b))

/-- The coarsest useful summary of that surface: does the fragment derive
anything at all? -/
def anyDerived (s : List Bool) : Bool := s.any id

/-! ## Both orders agree on the surface and differ as knowledge bases -/

/-- **Both edit orders leave the derived class relation as it was.** -/
theorem classSurface_edits_eq_base :
    classSurface (addShortcut (addDuplicate orderBase)) = classSurface orderBase ∧
      classSurface (addDuplicate (addShortcut orderBase)) = classSurface orderBase := by
  constructor <;> decide

/-- **The two orders are indistinguishable on the surface.** -/
theorem classSurface_editOrder_eq :
    orderedSurface classSurface addShortcut addDuplicate orderBase
        UpdateOrder.firstAfterSecond =
      orderedSurface classSurface addShortcut addDuplicate orderBase
        UpdateOrder.secondAfterFirst := by
  decide

/-- **The two orders are different knowledge bases**: a statement list records
which edit was made last. -/
theorem editOrder_endpoints_ne :
    addShortcut (addDuplicate orderBase) ≠ addDuplicate (addShortcut orderBase) := by
  intro h
  have := congrArg KB.statements h
  simp [addShortcut, addDuplicate, insertStatement, orderBase, painter, artist, creator] at this

/-! ## Non-descent -/

-- @source DASHI Agda bridge (PR #555/#581/#582): hidden update order does not descend through a surface it leaves fixed
/-- **The ontology surface cannot decode the edit order.**  No reading of the
derived class relation reconstructs which of the two redundant edits was applied
last. -/
theorem classSurface_cannot_decode_editOrder :
    ¬ FactorsThrough (orderedSurface classSurface addShortcut addDuplicate orderBase)
        (orderedEndpoint addShortcut addDuplicate orderBase) :=
  not_factorsThrough_orderedEndpoint_of_surface_eq classSurface_editOrder_eq
    editOrder_endpoints_ne

/-- **Nor can any coarsening of it.**  Summarising the surface further — here to
the single bit "does the fragment derive anything" — cannot restore the lost
order. -/
theorem coarsening_cannot_decode_editOrder :
    ¬ FactorsThrough
        (fun o => anyDerived (orderedSurface classSurface addShortcut addDuplicate orderBase o))
        (orderedEndpoint addShortcut addDuplicate orderBase) :=
  not_factorsThrough_postcomp classSurface_cannot_decode_editOrder

/-- The knowledge base itself is of course a separating record: the fine state
determines the order.  The point of the two theorems above is that the public
projection does not. -/
theorem editOrder_recoverable_from_kb :
    ∃ decode : KB → UpdateOrder,
      ∀ o, decode (orderedEndpoint addShortcut addDuplicate orderBase o) = o := by
  refine ⟨fun kb => if kb.statements.head? =
      some { subject := painter, property := P279, value := creator, rank := Rank.normal } then
        UpdateOrder.firstAfterSecond else UpdateOrder.secondAfterFirst, ?_⟩
  intro o
  cases o <;> decide

end Wikidata
