/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Wikidata.ClassExpressions

/-!
# Nominals, cardinality restrictions and datatype restrictions

`Wikidata/ClassExpressions.lean` covers OWL's class fragment — `⊓`, `⊔`, `¬`,
`∃p.C`, `∀p.C` — and `Wikidata/Owl.lean` the property characteristics.  What
neither reaches is the part of OWL that *counts* and the part that *enumerates*:
nominals `{a, b, c}`, the qualified cardinality restrictions `≥ n p.C`,
`≤ n p.C`, `= n p.C`, and restrictions on data values rather than entities.
That is the remaining gap this module closes.

Counting is where a description logic and a wiki disagree most sharply, and the
disagreement is the subject here.

* **What is counted is distinct fillers, not statements.**  Wikidata records the
  same value twice when two sources assert it, and a count over the recorded
  statements would then report two where the ontology means one
  (`raw_statement_count_is_not_a_cardinality`).  The semantics here counts
  `List.dedup`ed fillers, and `distinctCount_le_rawCount` bounds the naive count
  from below.
* **`≥ n` is monotone, `≤ n` is not** (`minCard_mono`, `maxCard_not_monotone`),
  and `= n` is neither (`exactCard_is_neither_monotone_nor_antitone`).  A
  maximum-cardinality answer is therefore withdrawn by the arrival of data, in
  exactly the way `Sparql.lean`'s `!bound` answers are.
* **A cardinality violation is relative to an identity assumption.**  OWL has no
  unique-name assumption, and neither does Wikidata: two Qids may be two records
  of one thing, awaiting a merge.  Read up to a coreference relation, the very
  same base satisfies `≤ 1 p.⊤` that it violates when the two Qids are taken to
  be distinct (`maxCard_violation_is_relative_to_identity`).  So a
  constraint report is a report about a naming, not about the world.
* **Deprecation repairs a violation without deleting anything**
  (`deprecation_repairs_max_cardinality`): the count reads the truthy
  projection, so lowering a statement's rank removes it from the count while
  leaving it in the base — which is what Wikidata's editors actually do.
* **Nominals do not read the base at all** (`oneOf_is_base_independent`), which
  makes them the one constructor here that is trivially monotone, and
  `hasValue` is `∃p.{y}` (`hasValue_iff_mem_fillers`).
* **A datatype restriction is not a fact about the entity graph**
  (`no_entity_graph_decoder_for_a_data_restriction`): two data assignments over
  the same knowledge base disagree on it, so nothing computed from the item
  surface decides it.
-/

/-! ### Provenance (generated by `tools/provenance.py`)

Source mix of this module's 32 declarations: 0 traced to the DASHI Agda
bridge (`chboishabba/dashi_agda` PR #555 / #581 / #582), 0 rendering the Wikidata
data model, 32 original to this port.  The bridge-traced declarations are
marked with `-- @source` below.  Full ledger: `docs/status/PROVENANCE.md`.
-/

namespace Wikidata

namespace Owl

/-! ## Counting fillers -/

/-- The truthy fillers of `p` at `x` that satisfy the class expression `e`. -/
def qualifiedFillers (kb : KB) (x : Qid) (p : Pid) (e : ClassExpr) : List Qid :=
  (fillersOf kb x p).filter (fun y => sat kb e y)

/-- The number of *statements* that contribute a qualified filler.  This is what
a naive count over the recorded triples reports, and it is not a cardinality. -/
def rawCount (kb : KB) (x : Qid) (p : Pid) (e : ClassExpr) : Nat :=
  (qualifiedFillers kb x p e).length

/-- The number of *distinct* qualified fillers: the cardinality a restriction
means. -/
def distinctCount (kb : KB) (x : Qid) (p : Pid) (e : ClassExpr) : Nat :=
  (qualifiedFillers kb x p e).dedup.length

theorem distinctCount_le_rawCount (kb : KB) (x : Qid) (p : Pid) (e : ClassExpr) :
    distinctCount kb x p e ≤ rawCount kb x p e :=
  (List.dedup_sublist (qualifiedFillers kb x p e)).length_le

theorem mem_qualifiedFillers_iff (kb : KB) (x : Qid) (p : Pid) (e : ClassExpr) (y : Qid) :
    y ∈ qualifiedFillers kb x p e ↔ y ∈ fillersOf kb x p ∧ Sat kb e y := by
  simp [qualifiedFillers, List.mem_filter, sat_iff]

/-- A subset of fillers cannot have more distinct elements. -/
theorem dedup_length_le_of_subset {l₁ l₂ : List Qid} (h : l₁ ⊆ l₂) :
    l₁.dedup.length ≤ l₂.dedup.length := by
  rw [← List.card_toFinset, ← List.card_toFinset]
  refine Finset.card_le_card ?_
  intro y hy
  rw [List.mem_toFinset] at hy ⊢
  exact h hy

/-! ## The extended expressions -/

/-- The OWL constructors beyond the class and property fragments: a nominal, a
value restriction, and the three qualified cardinality restrictions. -/
inductive CardExpr
  /-- A class expression of the fragment already modelled. -/
  | expr (e : ClassExpr)
  /-- The nominal `{q₁, …, qₙ}`. -/
  | oneOf (qs : List Qid)
  /-- `∃p.{y}`, OWL's `hasValue`. -/
  | hasValue (p : Pid) (y : Qid)
  /-- `≥ n p.C`. -/
  | minCard (n : Nat) (p : Pid) (e : ClassExpr)
  /-- `≤ n p.C`. -/
  | maxCard (n : Nat) (p : Pid) (e : ClassExpr)
  /-- `= n p.C`. -/
  | exactCard (n : Nat) (p : Pid) (e : ClassExpr)
  deriving DecidableEq, Repr, Inhabited

/-- The declarative semantics. -/
def CSat (kb : KB) : CardExpr → Qid → Prop
  | CardExpr.expr e, x => Sat kb e x
  | CardExpr.oneOf qs, x => x ∈ qs
  | CardExpr.hasValue p y, x => y ∈ fillersOf kb x p
  | CardExpr.minCard n p e, x => n ≤ distinctCount kb x p e
  | CardExpr.maxCard n p e, x => distinctCount kb x p e ≤ n
  | CardExpr.exactCard n p e, x => distinctCount kb x p e = n

/-- The executable semantics. -/
def csat (kb : KB) : CardExpr → Qid → Bool
  | CardExpr.expr e, x => sat kb e x
  | CardExpr.oneOf qs, x => qs.contains x
  | CardExpr.hasValue p y, x => (fillersOf kb x p).contains y
  | CardExpr.minCard n p e, x => decide (n ≤ distinctCount kb x p e)
  | CardExpr.maxCard n p e, x => decide (distinctCount kb x p e ≤ n)
  | CardExpr.exactCard n p e, x => decide (distinctCount kb x p e = n)

/-- **Exactness of the extended checker.** -/
theorem csat_iff (kb : KB) (c : CardExpr) (x : Qid) : csat kb c x = true ↔ CSat kb c x := by
  cases c with
  | expr e => exact sat_iff kb e x
  | oneOf qs => simp [csat, CSat]
  | hasValue p y => simp [csat, CSat]
  | minCard n p e => simp [csat, CSat]
  | maxCard n p e => simp [csat, CSat]
  | exactCard n p e => simp [csat, CSat]

instance (kb : KB) (c : CardExpr) (x : Qid) : Decidable (CSat kb c x) :=
  decidable_of_iff _ (csat_iff kb c x)

/-- `hasValue` is the existential restriction at a nominal. -/
theorem hasValue_iff_mem_fillers (kb : KB) (p : Pid) (y x : Qid) :
    CSat kb (CardExpr.hasValue p y) x ↔ y ∈ fillersOf kb x p := Iff.rfl

/-- **A nominal does not read the base.**  `{q₁, …, qₙ}` is the same class in
every knowledge base, so it is monotone for the trivial reason. -/
theorem oneOf_is_base_independent (kb₁ kb₂ : KB) (qs : List Qid) (x : Qid) :
    CSat kb₁ (CardExpr.oneOf qs) x ↔ CSat kb₂ (CardExpr.oneOf qs) x := Iff.rfl

/-! ## Which restrictions survive new data -/

/-- The qualified fillers of a positive class expression only grow. -/
theorem qualifiedFillers_mono {kb₁ kb₂ : KB} (hsub : kb₁.statements ⊆ kb₂.statements)
    (h₂ : AllNormal kb₂) {x : Qid} {p : Pid} {e : ClassExpr} (hpos : PositiveExpr e) :
    qualifiedFillers kb₁ x p e ⊆ qualifiedFillers kb₂ x p e := by
  intro y hy
  rw [mem_qualifiedFillers_iff] at hy ⊢
  exact ⟨mem_fillersOf_mono hsub h₂ hy.1, sat_mono hsub h₂ e hpos y hy.2⟩

/-- **`≥ n p.C` is monotone.**  New data can only add distinct fillers, so a
minimum-cardinality answer is never withdrawn. -/
theorem minCard_mono {kb₁ kb₂ : KB} (hsub : kb₁.statements ⊆ kb₂.statements)
    (h₂ : AllNormal kb₂) {n : Nat} {p : Pid} {e : ClassExpr} (hpos : PositiveExpr e)
    {x : Qid} (h : CSat kb₁ (CardExpr.minCard n p e) x) :
    CSat kb₂ (CardExpr.minCard n p e) x :=
  le_trans h (dedup_length_le_of_subset (qualifiedFillers_mono hsub h₂ hpos))

/-! ## Two bases for the counting results -/

/-- One recorded value for `P31` at `Q1`. -/
def oneFillerKB : KB := ⟨[⟨1⟩, ⟨2⟩, ⟨3⟩], [⟨⟨1⟩, P31, ⟨2⟩, Rank.normal⟩]⟩

/-- Two distinct recorded values. -/
def twoFillerKB : KB :=
  ⟨[⟨1⟩, ⟨2⟩, ⟨3⟩], [⟨⟨1⟩, P31, ⟨2⟩, Rank.normal⟩, ⟨⟨1⟩, P31, ⟨3⟩, Rank.normal⟩]⟩

/-- The same value recorded twice, as two sources asserting it. -/
def duplicateKB : KB :=
  ⟨[⟨1⟩, ⟨2⟩], [⟨⟨1⟩, P31, ⟨2⟩, Rank.normal⟩, ⟨⟨1⟩, P31, ⟨2⟩, Rank.normal⟩]⟩

/-- `twoFillerKB` with the second value deprecated rather than removed. -/
def deprecatedKB : KB :=
  ⟨[⟨1⟩, ⟨2⟩, ⟨3⟩],
    [⟨⟨1⟩, P31, ⟨2⟩, Rank.normal⟩, ⟨⟨1⟩, P31, ⟨3⟩, Rank.deprecated⟩]⟩

theorem oneFiller_subset_twoFiller : oneFillerKB.statements ⊆ twoFillerKB.statements := by
  intro st h
  simp [oneFillerKB] at h
  simp [twoFillerKB, h]

theorem twoFillerKB_allNormal : AllNormal twoFillerKB := by
  intro st h
  simp [twoFillerKB] at h
  rcases h with h | h <;> simp [h]

/-- **`≤ n p.C` is not monotone.**  `Q1` has at most one type until a second one
is recorded, and then the answer is withdrawn. -/
theorem maxCard_not_monotone :
    oneFillerKB.statements ⊆ twoFillerKB.statements ∧
      CSat oneFillerKB (CardExpr.maxCard 1 P31 ClassExpr.top) ⟨1⟩ ∧
      ¬ CSat twoFillerKB (CardExpr.maxCard 1 P31 ClassExpr.top) ⟨1⟩ :=
  ⟨oneFiller_subset_twoFiller, by decide, by decide⟩

/-- **`= n p.C` is neither monotone nor antitone**: the exact count is lost both
by adding a filler and, read the other way, by removing one. -/
theorem exactCard_is_neither_monotone_nor_antitone :
    CSat oneFillerKB (CardExpr.exactCard 1 P31 ClassExpr.top) ⟨1⟩ ∧
      ¬ CSat twoFillerKB (CardExpr.exactCard 1 P31 ClassExpr.top) ⟨1⟩ ∧
      CSat twoFillerKB (CardExpr.exactCard 2 P31 ClassExpr.top) ⟨1⟩ ∧
      ¬ CSat oneFillerKB (CardExpr.exactCard 2 P31 ClassExpr.top) ⟨1⟩ := by
  refine ⟨by decide, by decide, by decide, by decide⟩

/-- **A count over statements is not a cardinality.**  When two sources assert
the same value, the recorded statements number two and the distinct fillers
one; a checker that counted statements would report a violation of `≤ 1` that
the ontology does not mean. -/
theorem raw_statement_count_is_not_a_cardinality :
    rawCount duplicateKB ⟨1⟩ P31 ClassExpr.top = 2 ∧
      distinctCount duplicateKB ⟨1⟩ P31 ClassExpr.top = 1 ∧
      CSat duplicateKB (CardExpr.maxCard 1 P31 ClassExpr.top) ⟨1⟩ := by
  refine ⟨by decide, by decide, by decide⟩

/-- **Deprecation repairs a maximum-cardinality violation without deleting
anything.**  The count reads the truthy projection, so lowering the rank of one
statement takes it out of the count while it stays in the base — the repair a
Wikidata editor actually performs. -/
theorem deprecation_repairs_max_cardinality :
    ¬ CSat twoFillerKB (CardExpr.maxCard 1 P31 ClassExpr.top) ⟨1⟩ ∧
      CSat deprecatedKB (CardExpr.maxCard 1 P31 ClassExpr.top) ⟨1⟩ ∧
      (⟨⟨1⟩, P31, ⟨3⟩, Rank.deprecated⟩ : Statement) ∈ deprecatedKB.statements := by
  refine ⟨by decide, by decide, by simp [deprecatedKB]⟩

/-! ## Counting without a unique-name assumption -/

/-- The distinct fillers *up to a coreference relation*: two Qids that name the
same thing are counted once.  `List.dedup` is the special case in which
coreference is equality of Qids. -/
def distinctCountUpTo (same : Qid → Qid → Bool) (kb : KB) (x : Qid) (p : Pid)
    (e : ClassExpr) : Nat :=
  ((qualifiedFillers kb x p e).pwFilter (fun a b => ¬ same a b = true)).length

/-- The coreference relation that identifies `Q2` and `Q3` — two records of one
thing, awaiting a merge. -/
def mergeQ2Q3 (a b : Qid) : Bool :=
  (a == b) || (a == ⟨2⟩ && b == ⟨3⟩) || (a == ⟨3⟩ && b == ⟨2⟩)

/-- **A cardinality violation is relative to an identity assumption.**  OWL makes
no unique-name assumption and Wikidata makes none either: the base that violates
`≤ 1 P31.⊤` when `Q2` and `Q3` are taken to be two things satisfies it when they
are taken to be one.  A constraint report is therefore a report about a naming,
and the repair may be a merge rather than a deletion. -/
theorem maxCard_violation_is_relative_to_identity :
    ¬ distinctCount twoFillerKB ⟨1⟩ P31 ClassExpr.top ≤ 1 ∧
      distinctCountUpTo mergeQ2Q3 twoFillerKB ⟨1⟩ P31 ClassExpr.top ≤ 1 := by
  refine ⟨by decide, by decide⟩

/-! ## Datatype restrictions -/

/-- The numeric values a knowledge base carries for a *data* property.  Wikidata
records these as quantities (`Values.lean`); what matters here is that they are
not entities, so nothing in the item graph decides a question about them. -/
structure DataAssignment where
  /-- The numbers recorded for a property at an item. -/
  values : Qid → Pid → List ℚ

/-- A datatype restriction: the recorded numbers all lie in `[lo, hi]`. -/
def InRange (d : DataAssignment) (x : Qid) (p : Pid) (lo hi : ℚ) : Prop :=
  ∀ v ∈ d.values x p, lo ≤ v ∧ v ≤ hi

/-- One assignment records a value inside the range. -/
def smallData : DataAssignment := ⟨fun _ _ => [1]⟩

/-- The other records one outside it. -/
def largeData : DataAssignment := ⟨fun _ _ => [100]⟩

/-- **A datatype restriction is not a fact about the entity graph.**  The two
assignments above are attached to the very same knowledge base and disagree on
whether the recorded value lies in `[0, 10]`, so no function of the base and the
item decides a datatype restriction.  Data values are a separate surface, and
`Values.lean` is where their own comparisons live. -/
theorem no_entity_graph_decoder_for_a_data_restriction :
    ¬ ∃ decode : KB → Qid → Pid → ℚ → ℚ → Bool,
        ∀ (d : DataAssignment) (kb : KB) (x : Qid) (p : Pid) (lo hi : ℚ),
          d ∈ [smallData, largeData] →
          (decode kb x p lo hi = true ↔ InRange d x p lo hi) := by
  rintro ⟨decode, h⟩
  have h₁ := (h smallData oneFillerKB ⟨1⟩ P31 0 10 (by simp)).2
  have h₂ := (h largeData oneFillerKB ⟨1⟩ P31 0 10 (by simp)).1
  have hsmall : InRange smallData ⟨1⟩ P31 0 10 := by
    intro v hv
    simp [smallData] at hv
    subst hv
    norm_num
  have := h₂ (h₁ hsmall)
  have hlarge := this 100 (by simp [largeData])
  norm_num at hlarge

end Owl

end Wikidata
