/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Wikidata.Diagnostics
import RequestProject.Epistemic.OrderDescent

/-!
# Retrieval bias and ontology defect are different objects

Two things can go wrong when a knowledge base is queried, and they are
routinely conflated:

* **retrieval bias** — the query surfaces only some of the items it should,
  because of a limit, an ordering, or an index;
* **ontology defect** — the recorded data is malformed: a dangling reference, a
  subclass cycle.

This module keeps them apart.  Truncated retrieval is *sound and incomplete*:
every item it returns really is an instance (`retrieveTop_sound`), and it can
miss one (`retrieveTop_not_complete`), so a biased answer is not a false answer.
And neither phenomenon decodes the other:

* `defect_not_factorsThrough_retrieval` — two knowledge bases returning the same
  candidate list, one valid and one not, so no reading of the query answer
  diagnoses the ontology;
* `retrieval_not_factorsThrough_defect` — two knowledge bases with the same
  validity verdict and different candidate lists, so the diagnostic verdict does
  not predict what a query will return.

By `Epistemic.not_factorsThrough_postcomp`, neither failure is repaired by
reporting the answer or the verdict in some more digested form.
-/

/-! ### Provenance (generated by `tools/provenance.py`)

Source mix of this module's 15 declarations: 2 traced to the DASHI Agda
bridge (`chboishabba/dashi_agda` PR #555 / #581 / #582), 0 rendering the Wikidata
data model, 13 original to this port.  The bridge-traced declarations are
marked with `-- @source` below.  Full ledger: `docs/status/PROVENANCE.md`.
-/

namespace Wikidata

open Epistemic

/-! ## Retrieval with a limit -/

/-- Every recorded item that the engine sees as an instance of `c`. -/
def retrieveAll (kb : KB) (c : Qid) : List Qid :=
  kb.entities.filter (fun x => isInstanceOf kb x c)

/-- What a limited query returns: the first `n` of them. -/
def retrieveTop (n : Nat) (kb : KB) (c : Qid) : List Qid :=
  (retrieveAll kb c).take n

/-- **Truncated retrieval is sound**: everything it returns is an instance. -/
theorem retrieveTop_sound (n : Nat) (kb : KB) (c x : Qid) (h : x ∈ retrieveTop n kb c) :
    InstanceOf kb x c := by
  have hx : x ∈ retrieveAll kb c := List.mem_of_mem_take h
  simp only [retrieveAll, List.mem_filter] at hx
  exact (isInstanceOf_iff kb x c).1 (by simpa using hx.2)

/-- A two-instance fragment. -/
def twoInstancesKB : KB :=
  ⟨[⟨5592⟩, ⟨762⟩, ⟨483501⟩],
    [{ subject := ⟨5592⟩, property := P31, value := ⟨483501⟩, rank := Rank.normal },
     { subject := ⟨762⟩, property := P31, value := ⟨483501⟩, rank := Rank.normal }]⟩

/-- **Truncated retrieval is incomplete**: an instance the engine knows about is
missing from the answer. -/
theorem retrieveTop_not_complete :
    ∃ x, InstanceOf twoInstancesKB x ⟨483501⟩ ∧ x ∉ retrieveTop 1 twoInstancesKB ⟨483501⟩ := by
  refine ⟨⟨762⟩, (isInstanceOf_iff _ _ _).1 (by decide), by decide⟩

/-- **A missing item is not a refuted item.**  The truncated answer omits an
instance that the checker confirms, so incompleteness of retrieval is not
evidence against the claim. -/
theorem retrieval_gap_is_not_refutation :
    isInstanceOf twoInstancesKB ⟨762⟩ ⟨483501⟩ = true ∧
      ⟨762⟩ ∉ retrieveTop 1 twoInstancesKB ⟨483501⟩ := by
  refine ⟨by decide, by decide⟩

/-! ## Neither phenomenon decodes the other -/

/-- A defective fragment: the subject of a statement is not a recorded entity,
while the query for instances of `Q483501` returns the same single item as the
sound fragment below. -/
def danglingKB : KB :=
  ⟨[⟨5592⟩, ⟨483501⟩],
    [{ subject := ⟨5592⟩, property := P31, value := ⟨483501⟩, rank := Rank.normal },
     { subject := ⟨999999⟩, property := P279, value := ⟨483501⟩, rank := Rank.normal }]⟩

/-- A sound fragment with the same query answer. -/
def cleanKB : KB :=
  ⟨[⟨5592⟩, ⟨483501⟩],
    [{ subject := ⟨5592⟩, property := P31, value := ⟨483501⟩, rank := Rank.normal }]⟩

/-- The two fragments answer the query identically. -/
theorem retrieval_eq : retrieveAll danglingKB ⟨483501⟩ = retrieveAll cleanKB ⟨483501⟩ := by decide

/-- They differ on validity. -/
theorem validity_ne : valid danglingKB ≠ valid cleanKB := by decide

-- @source DASHI Agda bridge (PR #555/#581/#582): retrieval bias is not a formal defect
/-- **A query answer does not diagnose the ontology.**  No reading of the
retrieved candidates decides whether the knowledge base is well formed. -/
theorem defect_not_factorsThrough_retrieval :
    ¬ FactorsThrough (fun kb => retrieveAll kb ⟨483501⟩) (fun kb => valid kb) :=
  not_factorsThrough retrieval_eq validity_ne

/-- **Nor does any digest of the query answer.** -/
theorem no_digest_of_retrieval_diagnoses {Public : Type} (report : List Qid → Public) :
    ¬ FactorsThrough (fun kb => report (retrieveAll kb ⟨483501⟩)) (fun kb => valid kb) :=
  not_factorsThrough_postcomp defect_not_factorsThrough_retrieval

/-- Both fragments below are valid, and they return different candidates. -/
theorem validity_eq : valid cleanKB = valid twoInstancesKB := by decide

theorem retrieval_ne : retrieveAll cleanKB ⟨483501⟩ ≠ retrieveAll twoInstancesKB ⟨483501⟩ := by
  decide

-- @source DASHI Agda bridge (PR #555/#581/#582): retrieval bias is not a formal defect
/-- **A clean diagnostic does not predict the query answer.**  Validity says the
data is well formed; it says nothing about what is in it. -/
theorem retrieval_not_factorsThrough_defect :
    ¬ FactorsThrough (fun kb => valid kb) (fun kb => retrieveAll kb ⟨483501⟩) :=
  not_factorsThrough validity_eq retrieval_ne

end Wikidata
