module DASHI.Analysis.NonArchimedeanOddCharacterDFTSourceReuseExact where

------------------------------------------------------------------------
-- CORRECT ODD-CHARACTER DFT FROM EXISTING SOURCE MACHINERY
--
-- The source already owns a normalized DFT on ZMod N with exact unitarity.
-- The odd-character kernel on the antisymmetric sheet coordinate is
--
--   omega^((2j+1)v) = omega^v * (omega^2)^(jv).
--
-- Therefore the corrected transform is not new Fourier mathematics.  It is
-- the existing half-size DFT generated by omega^2, composed with a diagonal
-- modulation by omega^v.  This owner records that reuse and exposes only the
-- source-specific receipts needed to instantiate it.
------------------------------------------------------------------------

open import Agda.Builtin.Bool using (Bool; true; false)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.List using (List; []; _∷_)

record OddCharacterDFTReuse : Set₁ where
  field
    HalfIndex : Set
    Scalar : Set

    ordinaryHalfDFT : HalfIndex → HalfIndex → Scalar
    modulation : HalfIndex → Scalar
    multiply : Scalar → Scalar → Scalar
    oddCharacterKernel : HalfIndex → HalfIndex → Scalar

    oddKernelFactorization :
      (frequencyPosition spatialPosition : HalfIndex) →
      oddCharacterKernel frequencyPosition spatialPosition
      ≡ multiply
          (modulation spatialPosition)
          (ordinaryHalfDFT frequencyPosition spatialPosition)

open OddCharacterDFTReuse public

record SourceReuseStatus : Set where
  constructor sourceReuseStatus
  field
    normalizedFiniteCyclicDFTOwned : Bool
    dftUnitarityOwned : Bool
    primitiveRootPowerReductionOwnedUpstream : Bool
    oddFrequencyParameterizationByTwoJPlusOneElementary : Bool
    oddKernelFactorizationElementary : Bool
    newGenericFourierLibraryRequired : Bool
    currentProductDFTShouldBeReusedForOddCharacters : Bool

canonicalSourceReuseStatus : SourceReuseStatus
canonicalSourceReuseStatus =
  sourceReuseStatus true true true true true false false


data OddDFTLeaf : Set where
  instantiateOmega : OddDFTLeaf
  instantiateOmegaSquaredHalfRoot : OddDFTLeaf
  instantiateExistingHalfDFT : OddDFTLeaf
  instantiateDiagonalModulation : OddDFTLeaf
  proveKernelFactorization : OddDFTLeaf
  compileCorrectOddCharacterTransform : OddDFTLeaf
  rebuildDFTTheory : OddDFTLeaf
  reuseProductTensorDFT : OddDFTLeaf


data OddDFTDisposition : Set where
  live : OddDFTDisposition
  reusable : OddDFTDisposition
  downstream : OddDFTDisposition
  pruned : OddDFTDisposition
  forbiddenShortcut : OddDFTDisposition

leafDisposition : OddDFTLeaf → OddDFTDisposition
leafDisposition instantiateOmega = live
leafDisposition instantiateOmegaSquaredHalfRoot = reusable
leafDisposition instantiateExistingHalfDFT = reusable
leafDisposition instantiateDiagonalModulation = live
leafDisposition proveKernelFactorization = live
leafDisposition compileCorrectOddCharacterTransform = downstream
leafDisposition rebuildDFTTheory = pruned
leafDisposition reuseProductTensorDFT = forbiddenShortcut

highestAlphaOddDFTPath : List OddDFTLeaf
highestAlphaOddDFTPath =
  instantiateOmega ∷
  instantiateDiagonalModulation ∷
  proveKernelFactorization ∷
  compileCorrectOddCharacterTransform ∷
  []

record OddDFTFanout : Set where
  constructor oddDFTFanout
  field
    feedsCharacterBasisAction : Bool
    feedsSpatialSpectrumWeld : Bool
    feedsSpatialTraceWeld : Bool
    feedsSpatialPowerWeld : Bool
    feedsOrbitPhaseCancellationAutomatically : Bool

canonicalOddDFTFanout : OddDFTFanout
canonicalOddDFTFanout =
  oddDFTFanout true true true true false

newFourierLibraryIsPruned :
  SourceReuseStatus.newGenericFourierLibraryRequired canonicalSourceReuseStatus
  ≡ false
newFourierLibraryIsPruned = refl

productTensorDFTIsForbiddenSubstitute :
  SourceReuseStatus.currentProductDFTShouldBeReusedForOddCharacters
    canonicalSourceReuseStatus
  ≡ false
productTensorDFTIsForbiddenSubstitute = refl
