/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Agda.Syntax
import AgdaVendor.DASHI.Core.AdapterCanonicalityCore
import AgdaVendor.DASHI.Core.AuthorityNonPromotionCore
import AgdaVendor.DASHI.Core.BridgeRequirementCore
import AgdaVendor.DASHI.Core.CandidateOnlyCore
import AgdaVendor.DASHI.Core.FormalLensVocabularyCore
import AgdaVendor.DASHI.Core.GenericReceipt

/-!
# `DASHI.Core.FormalLensQualificationCore`, transliterated

Generated by `tools/agda2lean.py` from the ingested upstream source
`upstream/dashi_agda/agent/evidence-polarity-cross-pollination/DASHI/Core/FormalLensQualificationCore.agda`.
Do not edit by hand: re-run the translator instead.
-/

open Agda

agda_module DASHI.Core.FormalLensQualificationCore where

  open import Agda.Builtin.Bool

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String

  open import DASHI.Core.AdapterCanonicalityCore

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  ------------------------------------------------------------------------
  -- Reusable formal-lens qualification core.
  --
  -- A formal lens names an inspection grammar only.  Qualification rows can
  -- say which thresholds and residual boundaries are visible, but they do not
  -- promote analytic, empirical, clinical, physical, theorem, metaphysical,
  -- external, governance, or promotion authority.

  listCount : ∀ {A : Set} , List A → Nat
  listCount [] =
    zero
  listCount (_ ∷ xs) =
    suc (listCount xs)

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  ------------------------------------------------------------------------
  -- Formal-lens vocabulary.

  data FormalLens : Set where
    SymbolicRational :
      FormalLens

    Operator :
      FormalLens

    Functional :
      FormalLens

    Hamiltonian :
      FormalLens

    GradientFlow :
      FormalLens

    ResistiveTransport :
      FormalLens

    Spectral :
      FormalLens

    Group :
      FormalLens

    Category :
      FormalLens

    Number :
      FormalLens

    Lattice :
      FormalLens

    Topological :
      FormalLens

    Probabilistic :
      FormalLens

    Graph :
      FormalLens

    Information :
      FormalLens

    NamedFormalLens :
      String →
      FormalLens

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalFormalLenses : List FormalLens
  canonicalFormalLenses =
    SymbolicRational
    ∷ Operator
    ∷ Functional
    ∷ Hamiltonian
    ∷ GradientFlow
    ∷ ResistiveTransport
    ∷ Spectral
    ∷ Group
    ∷ Category
    ∷ Number
    ∷ Lattice
    ∷ Topological
    ∷ Probabilistic
    ∷ Graph
    ∷ Information
    ∷ []

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalFormalLensCount : Nat
  canonicalFormalLensCount =
    listCount canonicalFormalLenses

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  ------------------------------------------------------------------------
  -- DASHI.Core.FormalLensVocabularyCore compatibility.
  --
  -- The legacy `FormalLens` vocabulary remains public for existing consumers.
  -- These helpers provide a stable bridge to the forthcoming vocabulary core
  -- without renaming any constructor in this module.

  formalLensKindOf :
    FormalLens →
    DASHI.Core.FormalLensVocabularyCore.FormalLensKind
  formalLensKindOf SymbolicRational =
    DASHI.Core.FormalLensVocabularyCore.SymbolicRational
  formalLensKindOf Operator =
    DASHI.Core.FormalLensVocabularyCore.Operator
  formalLensKindOf Functional =
    DASHI.Core.FormalLensVocabularyCore.Functional
  formalLensKindOf Hamiltonian =
    DASHI.Core.FormalLensVocabularyCore.Hamiltonian
  formalLensKindOf GradientFlow =
    DASHI.Core.FormalLensVocabularyCore.GradientFlow
  formalLensKindOf ResistiveTransport =
    DASHI.Core.FormalLensVocabularyCore.QuotientResidue
  formalLensKindOf Spectral =
    DASHI.Core.FormalLensVocabularyCore.SpectralSequence
  formalLensKindOf Group =
    DASHI.Core.FormalLensVocabularyCore.Group
  formalLensKindOf Category =
    DASHI.Core.FormalLensVocabularyCore.Category
  formalLensKindOf Number =
    DASHI.Core.FormalLensVocabularyCore.Number
  formalLensKindOf Lattice =
    DASHI.Core.FormalLensVocabularyCore.Lattice
  formalLensKindOf Topological =
    DASHI.Core.FormalLensVocabularyCore.Topology
  formalLensKindOf Probabilistic =
    DASHI.Core.FormalLensVocabularyCore.Probability
  formalLensKindOf Graph =
    DASHI.Core.FormalLensVocabularyCore.Graph
  formalLensKindOf Information =
    DASHI.Core.FormalLensVocabularyCore.Information
  formalLensKindOf (NamedFormalLens s) =
    DASHI.Core.FormalLensVocabularyCore.NamedFormalLensKind s

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  formalLensFamilyOf :
    FormalLens →
    DASHI.Core.FormalLensVocabularyCore.FormalLensFamily
  formalLensFamilyOf lens =
    DASHI.Core.FormalLensVocabularyCore.familyOf (formalLensKindOf lens)

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  formalLensVocabularyKindsOf :
    List FormalLens →
    List DASHI.Core.FormalLensVocabularyCore.FormalLensKind
  formalLensVocabularyKindsOf [] = []
  formalLensVocabularyKindsOf (lens ∷ lenses) =
    formalLensKindOf lens ∷ formalLensVocabularyKindsOf lenses

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  formalLensVocabularyFamiliesOf :
    List FormalLens →
    List DASHI.Core.FormalLensVocabularyCore.FormalLensFamily
  formalLensVocabularyFamiliesOf [] = []
  formalLensVocabularyFamiliesOf (lens ∷ lenses) =
    formalLensFamilyOf lens ∷ formalLensVocabularyFamiliesOf lenses

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalFormalLensVocabularyKinds :
    List DASHI.Core.FormalLensVocabularyCore.FormalLensKind
  canonicalFormalLensVocabularyKinds =
    formalLensVocabularyKindsOf canonicalFormalLenses

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalFormalLensVocabularyKindsAreCanonical :
    canonicalFormalLensVocabularyKinds
    ≡
    formalLensVocabularyKindsOf canonicalFormalLenses
  canonicalFormalLensVocabularyKindsAreCanonical =
    refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalFormalLensVocabularyKindCount :
    Nat
  canonicalFormalLensVocabularyKindCount =
    listCount canonicalFormalLensVocabularyKinds

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalFormalLensVocabularyFamilies :
    List DASHI.Core.FormalLensVocabularyCore.FormalLensFamily
  canonicalFormalLensVocabularyFamilies =
    formalLensVocabularyFamiliesOf canonicalFormalLenses

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalFormalLensVocabularyFamiliesAreCanonical :
    canonicalFormalLensVocabularyFamilies
    ≡
    formalLensVocabularyFamiliesOf canonicalFormalLenses
  canonicalFormalLensVocabularyFamiliesAreCanonical =
    refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalFormalLensVocabularyFamilyCount :
    Nat
  canonicalFormalLensVocabularyFamilyCount =
    listCount canonicalFormalLensVocabularyFamilies

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  record FormalLensVocabularyCompatibilityReceipt : Set₁ where
    constructor formalLensVocabularyCompatibilityReceipt
    field
      vocabularyKinds :
        List DASHI.Core.FormalLensVocabularyCore.FormalLensKind

      vocabularyKindsAreCanonical :
        vocabularyKinds ≡ canonicalFormalLensVocabularyKinds

      vocabularyKindCount :
        Nat

      vocabularyKindCountIsCanonical :
        vocabularyKindCount ≡ canonicalFormalLensVocabularyKindCount

      vocabularyFamilies :
        List DASHI.Core.FormalLensVocabularyCore.FormalLensFamily

      vocabularyFamiliesAreCanonical :
        vocabularyFamilies ≡ canonicalFormalLensVocabularyFamilies

      vocabularyFamilyCount :
        Nat

      vocabularyFamilyCountIsCanonical :
        vocabularyFamilyCount ≡ canonicalFormalLensVocabularyFamilyCount

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  open FormalLensVocabularyCompatibilityReceipt public

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalFormalLensVocabularyCompatibilityReceipt :
    FormalLensVocabularyCompatibilityReceipt
  canonicalFormalLensVocabularyCompatibilityReceipt =
    formalLensVocabularyCompatibilityReceipt
      canonicalFormalLensVocabularyKinds
      refl
      canonicalFormalLensVocabularyKindCount
      refl
      canonicalFormalLensVocabularyFamilies
      refl
      canonicalFormalLensVocabularyFamilyCount
      refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  ------------------------------------------------------------------------
  -- Threshold, role, and residual boundary vocabulary.

  data QualificationRole : Set where
    sourceLensRole :
      QualificationRole

    targetLensRole :
      QualificationRole

    residualBoundaryRole :
      QualificationRole

    thresholdWitnessRole :
      QualificationRole

    adapterConsumerRole :
      QualificationRole

    namedQualificationRole :
      String →
      QualificationRole

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  data ThresholdLabel : Set where
    requiredThresholdLabel :
      ThresholdLabel

    metThresholdLabel :
      ThresholdLabel

    missingThresholdLabel :
      ThresholdLabel

    namedThresholdLabel :
      String →
      ThresholdLabel

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  data ThresholdStatus : Set where
    thresholdRequired :
      ThresholdStatus

    thresholdMet :
      ThresholdStatus

    thresholdMissing :
      ThresholdStatus

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  data ResidualBoundaryLabel : Set where
    explicitResidualBoundary :
      ResidualBoundaryLabel

    explicitOpenResidualBoundary :
      ResidualBoundaryLabel

    explicitMissingThresholdResidualBoundary :
      ResidualBoundaryLabel

    explicitBridgeResidualBoundary :
      ResidualBoundaryLabel

    explicitAdapterResidualBoundary :
      ResidualBoundaryLabel

    namedResidualBoundary :
      String →
      ResidualBoundaryLabel

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  thresholdStatusRequired :
    ThresholdStatus →
    Bool
  thresholdStatusRequired thresholdRequired =
    true
  thresholdStatusRequired thresholdMet =
    true
  thresholdStatusRequired thresholdMissing =
    true

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  thresholdStatusMet :
    ThresholdStatus →
    Bool
  thresholdStatusMet thresholdRequired =
    false
  thresholdStatusMet thresholdMet =
    true
  thresholdStatusMet thresholdMissing =
    false

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  thresholdStatusMissing :
    ThresholdStatus →
    Bool
  thresholdStatusMissing thresholdRequired =
    false
  thresholdStatusMissing thresholdMet =
    false
  thresholdStatusMissing thresholdMissing =
    true

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  record ThresholdRow : Set where
    constructor thresholdRow
    field
      thresholdRowLabel :
        String

      thresholdRowRole :
        QualificationRole

      thresholdRowStatus :
        ThresholdStatus

      thresholdRowBoundary :
        ResidualBoundaryLabel

      thresholdRequiredFlag :
        Bool

      thresholdMetFlag :
        Bool

      thresholdMissingFlag :
        Bool

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  open ThresholdRow public

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  record ThresholdRowReceipt
    (row : ThresholdRow) :
    Set where
    constructor thresholdRowReceipt
    field
      thresholdRequiredMatchesStatus :
        thresholdRequiredFlag row
        ≡
        thresholdStatusRequired (thresholdRowStatus row)

      thresholdMetMatchesStatus :
        thresholdMetFlag row
        ≡
        thresholdStatusMet (thresholdRowStatus row)

      thresholdMissingMatchesStatus :
        thresholdMissingFlag row
        ≡
        thresholdStatusMissing (thresholdRowStatus row)

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  open ThresholdRowReceipt public

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  mkThresholdRow :
    String →
    QualificationRole →
    ThresholdStatus →
    ResidualBoundaryLabel →
    ThresholdRow
  mkThresholdRow label role status boundary =
    thresholdRow
      label
      role
      status
      boundary
      (thresholdStatusRequired status)
      (thresholdStatusMet status)
      (thresholdStatusMissing status)

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalRequiredThresholdRow : ThresholdRow
  canonicalRequiredThresholdRow =
    mkThresholdRow
      "formal lens threshold required"
      thresholdWitnessRole
      thresholdRequired
      explicitOpenResidualBoundary

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalMetThresholdRow : ThresholdRow
  canonicalMetThresholdRow =
    mkThresholdRow
      "formal lens threshold met"
      thresholdWitnessRole
      thresholdMet
      explicitResidualBoundary

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalMissingThresholdRow : ThresholdRow
  canonicalMissingThresholdRow =
    mkThresholdRow
      "formal lens threshold missing"
      thresholdWitnessRole
      thresholdMissing
      explicitMissingThresholdResidualBoundary

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalRequiredThresholdRowReceipt :
    ThresholdRowReceipt canonicalRequiredThresholdRow
  canonicalRequiredThresholdRowReceipt =
    thresholdRowReceipt refl refl refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalMetThresholdRowReceipt :
    ThresholdRowReceipt canonicalMetThresholdRow
  canonicalMetThresholdRowReceipt =
    thresholdRowReceipt refl refl refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalMissingThresholdRowReceipt :
    ThresholdRowReceipt canonicalMissingThresholdRow
  canonicalMissingThresholdRowReceipt =
    thresholdRowReceipt refl refl refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalThresholdRows : List ThresholdRow
  canonicalThresholdRows =
    canonicalRequiredThresholdRow
    ∷ canonicalMetThresholdRow
    ∷ canonicalMissingThresholdRow
    ∷ []

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalThresholdRowCount : Nat
  canonicalThresholdRowCount =
    listCount canonicalThresholdRows

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  ------------------------------------------------------------------------
  -- Canonical adapters consumed by qualification surfaces.

  canonicalCandidateOnlyCoreAdapter :
    DASHI.Core.AdapterCanonicalityCore.AdapterCanonicalityReceipt
      DASHI.Core.CandidateOnlyCore.CandidateOnlyRow
      DASHI.Core.CandidateOnlyCore.canonicalRowCandidateOnlyRow
  canonicalCandidateOnlyCoreAdapter =
    DASHI.Core.AdapterCanonicalityCore.mkCanonicalAdapterReceipt
      "formal lens candidate-only core adapter"
      "DASHI.Core.FormalLensQualificationCore"
      "DASHI.Core.CandidateOnlyCore.canonicalRowCandidateOnlyRow"
      DASHI.Core.AdapterCanonicalityCore.receiptAdapterKind
      DASHI.Core.CandidateOnlyCore.canonicalRowCandidateOnlyRow

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalAuthorityNonPromotionCoreAdapter :
    DASHI.Core.AdapterCanonicalityCore.AdapterCanonicalityReceipt
      DASHI.Core.AuthorityNonPromotionCore.AuthorityNonPromotionBundle
      DASHI.Core.AuthorityNonPromotionCore.canonicalAuthorityNonPromotionBundle
  canonicalAuthorityNonPromotionCoreAdapter =
    DASHI.Core.AdapterCanonicalityCore.mkCanonicalAdapterReceipt
      "formal lens authority non-promotion core adapter"
      "DASHI.Core.FormalLensQualificationCore"
      "DASHI.Core.AuthorityNonPromotionCore.canonicalAuthorityNonPromotionBundle"
      DASHI.Core.AdapterCanonicalityCore.authorityAdapterKind
      DASHI.Core.AuthorityNonPromotionCore.canonicalAuthorityNonPromotionBundle

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalBridgeRequirementCoreAdapter :
    DASHI.Core.AdapterCanonicalityCore.AdapterCanonicalityReceipt
      DASHI.Core.BridgeRequirementCore.BridgeRequirementCoreReceipt
      DASHI.Core.BridgeRequirementCore.canonicalBridgeRequirementCoreReceipt
  canonicalBridgeRequirementCoreAdapter =
    DASHI.Core.AdapterCanonicalityCore.mkCanonicalAdapterReceipt
      "formal lens bridge requirement core adapter"
      "DASHI.Core.FormalLensQualificationCore"
      "DASHI.Core.BridgeRequirementCore.canonicalBridgeRequirementCoreReceipt"
      DASHI.Core.AdapterCanonicalityCore.bridgeAdapterKind
      DASHI.Core.BridgeRequirementCore.canonicalBridgeRequirementCoreReceipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalAdapterCanonicalityCoreAdapter :
    DASHI.Core.AdapterCanonicalityCore.AdapterCanonicalityReceipt
      DASHI.Core.AdapterCanonicalityCore.AdapterSurface
      DASHI.Core.AdapterCanonicalityCore.canonicalAdapter
  canonicalAdapterCanonicalityCoreAdapter =
    DASHI.Core.AdapterCanonicalityCore.canonicalAdapterCanonicalityReceipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  ------------------------------------------------------------------------
  -- DASHI.Core.CandidateOnlyCore and bridge rows used by the canonical qualification surfaces.

  genericFormalLensCandidateRow : DASHI.Core.CandidateOnlyCore.CandidateOnlyRow
  genericFormalLensCandidateRow =
    DASHI.Core.CandidateOnlyCore.mkCandidateOnlyRow
      "formal lens qualification candidate"
      "DASHI.Core.FormalLensQualificationCore"
      "genericFormalLensCandidateRow"
      DASHI.Core.CandidateOnlyCore.rowCandidateKind
      DASHI.Core.CandidateOnlyCore.rowCandidateOnlyStatus
      "formal-lens qualification records an inspection grammar only"
      "domain acceptance, support, authority, and promotion remain external"

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  genericFormalLensCandidateReceipt :
    DASHI.Core.CandidateOnlyCore.CandidateOnlyReceipt genericFormalLensCandidateRow
  genericFormalLensCandidateReceipt =
    DASHI.Core.CandidateOnlyCore.mkCandidateOnlyReceipt
      genericFormalLensCandidateRow
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  gradientResistiveCandidateRow : DASHI.Core.CandidateOnlyCore.CandidateOnlyRow
  gradientResistiveCandidateRow =
    DASHI.Core.CandidateOnlyCore.mkCandidateOnlyRow
      "gradient-flow resistive-transport candidate"
      "DASHI.Core.FormalLensQualificationCore"
      "gradientResistiveCandidateRow"
      DASHI.Core.CandidateOnlyCore.operatorCandidateKind
      DASHI.Core.CandidateOnlyCore.operatorCandidateOnlyStatus
      "gradient-flow and resistive-transport lenses share a candidate residual row"
      "analytic PDE, physical transport, empirical fit, and theorem authority remain absent"

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  gradientResistiveCandidateReceipt :
    DASHI.Core.CandidateOnlyCore.CandidateOnlyReceipt gradientResistiveCandidateRow
  gradientResistiveCandidateReceipt =
    DASHI.Core.CandidateOnlyCore.mkCandidateOnlyReceipt
      gradientResistiveCandidateRow
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  genericFormalLensBridgeRow : DASHI.Core.BridgeRequirementCore.BridgeRequirementRow
  genericFormalLensBridgeRow =
    DASHI.Core.BridgeRequirementCore.canonicalBridgeRequirementRow
      "formal lens source"
      "formal lens target"
      DASHI.Core.BridgeRequirementCore.bridgeSuppliedCandidateOnly
      true
      true
      true

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  genericFormalLensBridgeReceipt :
    DASHI.Core.BridgeRequirementCore.BridgeRequirementRowReceipt genericFormalLensBridgeRow
  genericFormalLensBridgeReceipt =
    DASHI.Core.BridgeRequirementCore.bridgeRequirementRowReceipt refl refl refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  gradientResistiveBridgeRow : DASHI.Core.BridgeRequirementCore.BridgeRequirementRow
  gradientResistiveBridgeRow =
    DASHI.Core.BridgeRequirementCore.canonicalBridgeRequirementRow
      "gradient flow"
      "resistive transport"
      DASHI.Core.BridgeRequirementCore.transportMapRequired
      true
      false
      false

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  gradientResistiveBridgeReceipt :
    DASHI.Core.BridgeRequirementCore.BridgeRequirementRowReceipt gradientResistiveBridgeRow
  gradientResistiveBridgeReceipt =
    DASHI.Core.BridgeRequirementCore.bridgeRequirementRowReceipt refl refl refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  ------------------------------------------------------------------------
  -- Qualification surface and receipt.

  record FormalLensQualificationSurface : Set where
    constructor formalLensQualificationSurface
    field
      qualificationLabel :
        String

      qualificationOwner :
        String

      qualificationSurface :
        String

      sourceLens :
        FormalLens

      targetLens :
        FormalLens

      qualificationRole :
        QualificationRole

      threshold :
        ThresholdRow

      thresholdReceipt :
        ThresholdRowReceipt threshold

      residualBoundary :
        ResidualBoundaryLabel

      candidateRow :
        DASHI.Core.CandidateOnlyCore.CandidateOnlyRow

      candidateReceipt :
        DASHI.Core.CandidateOnlyCore.CandidateOnlyReceipt candidateRow

      authorityBundle :
        DASHI.Core.AuthorityNonPromotionCore.AuthorityNonPromotionBundle

      bridgeRow :
        DASHI.Core.BridgeRequirementCore.BridgeRequirementRow

      bridgeReceipt :
        DASHI.Core.BridgeRequirementCore.BridgeRequirementRowReceipt bridgeRow

      candidateCoreAdapter :
        DASHI.Core.AdapterCanonicalityCore.AdapterCanonicalityReceipt
          DASHI.Core.CandidateOnlyCore.CandidateOnlyRow
          DASHI.Core.CandidateOnlyCore.canonicalRowCandidateOnlyRow

      authorityCoreAdapter :
        DASHI.Core.AdapterCanonicalityCore.AdapterCanonicalityReceipt
          DASHI.Core.AuthorityNonPromotionCore.AuthorityNonPromotionBundle
          DASHI.Core.AuthorityNonPromotionCore.canonicalAuthorityNonPromotionBundle

      bridgeCoreAdapter :
        DASHI.Core.AdapterCanonicalityCore.AdapterCanonicalityReceipt
          DASHI.Core.BridgeRequirementCore.BridgeRequirementCoreReceipt
          DASHI.Core.BridgeRequirementCore.canonicalBridgeRequirementCoreReceipt

      adapterCoreAdapter :
        DASHI.Core.AdapterCanonicalityCore.AdapterCanonicalityReceipt
          DASHI.Core.AdapterCanonicalityCore.AdapterSurface
          DASHI.Core.AdapterCanonicalityCore.canonicalAdapter

      qualificationStatement :
        String

      qualificationRemainingGap :
        String

      qualificationCandidateOnly :
        Bool

      qualificationPromoted :
        Bool

      analyticAuthority :
        Bool

      empiricalAuthority :
        Bool

      clinicalAuthority :
        Bool

      physicalAuthority :
        Bool

      theoremAuthority :
        Bool

      metaphysicalAuthority :
        Bool

      externalAuthority :
        Bool

      governanceAuthority :
        Bool

      promotionAuthority :
        Bool

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  open FormalLensQualificationSurface public

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  record FormalLensQualificationReceipt
    (surface : FormalLensQualificationSurface) :
    Set where
    constructor formalLensQualificationReceipt
    field
      receiptCandidateOnlyIsTrue :
        qualificationCandidateOnly surface ≡ true

      receiptPromotedIsFalse :
        qualificationPromoted surface ≡ false

      receiptAnalyticAuthorityFalse :
        analyticAuthority surface ≡ false

      receiptEmpiricalAuthorityFalse :
        empiricalAuthority surface ≡ false

      receiptClinicalAuthorityFalse :
        clinicalAuthority surface ≡ false

      receiptPhysicalAuthorityFalse :
        physicalAuthority surface ≡ false

      receiptTheoremAuthorityFalse :
        theoremAuthority surface ≡ false

      receiptMetaphysicalAuthorityFalse :
        metaphysicalAuthority surface ≡ false

      receiptExternalAuthorityFalse :
        externalAuthority surface ≡ false

      receiptGovernanceAuthorityFalse :
        governanceAuthority surface ≡ false

      receiptPromotionAuthorityFalse :
        promotionAuthority surface ≡ false

      receiptAuthorityBundleNonPromoting :
        DASHI.Core.AuthorityNonPromotionCore.promotesAnyAuthority (authorityBundle surface) ≡ false

      receiptBridgeAuthorityPromotionFalse :
        DASHI.Core.BridgeRequirementCore.rowAuthorityPromotion (bridgeRow surface) ≡ false

      receiptBridgeTransportMapAuthorityFalse :
        DASHI.Core.BridgeRequirementCore.rowTransportMapAuthority (bridgeRow surface) ≡ false

      receiptBridgeBackgroundAuthorityFalse :
        DASHI.Core.BridgeRequirementCore.rowBackgroundBridgeAuthority (bridgeRow surface) ≡ false

      receiptCandidateAdapterCanonical :
        DASHI.Core.AdapterCanonicalityCore.adapter (candidateCoreAdapter surface)
        ≡
        DASHI.Core.CandidateOnlyCore.canonicalRowCandidateOnlyRow

      receiptAuthorityAdapterCanonical :
        DASHI.Core.AdapterCanonicalityCore.adapter (authorityCoreAdapter surface)
        ≡
        DASHI.Core.AuthorityNonPromotionCore.canonicalAuthorityNonPromotionBundle

      receiptBridgeAdapterCanonical :
        DASHI.Core.AdapterCanonicalityCore.adapter (bridgeCoreAdapter surface)
        ≡
        DASHI.Core.BridgeRequirementCore.canonicalBridgeRequirementCoreReceipt

      receiptAdapterAdapterCanonical :
        DASHI.Core.AdapterCanonicalityCore.adapter (adapterCoreAdapter surface)
        ≡
        DASHI.Core.AdapterCanonicalityCore.canonicalAdapter

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  open FormalLensQualificationReceipt public

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  mkFormalLensQualificationSurface :
    String →
    String →
    String →
    FormalLens →
    FormalLens →
    QualificationRole →
    (threshold : ThresholdRow) →
    ThresholdRowReceipt threshold →
    ResidualBoundaryLabel →
    (candidateRow : DASHI.Core.CandidateOnlyCore.CandidateOnlyRow) →
    DASHI.Core.CandidateOnlyCore.CandidateOnlyReceipt candidateRow →
    (bridgeRow : DASHI.Core.BridgeRequirementCore.BridgeRequirementRow) →
    DASHI.Core.BridgeRequirementCore.BridgeRequirementRowReceipt bridgeRow →
    String →
    String →
    FormalLensQualificationSurface
  mkFormalLensQualificationSurface
    label
    owner
    surface
    source
    target
    role
    thresholdRowValue
    thresholdRowReceiptValue
    boundary
    candidateRowValue
    candidateReceiptValue
    bridgeRowValue
    bridgeReceiptValue
    statement
    remainingGap =
    formalLensQualificationSurface
      label
      owner
      surface
      source
      target
      role
      thresholdRowValue
      thresholdRowReceiptValue
      boundary
      candidateRowValue
      candidateReceiptValue
      DASHI.Core.AuthorityNonPromotionCore.canonicalAuthorityNonPromotionBundle
      bridgeRowValue
      bridgeReceiptValue
      canonicalCandidateOnlyCoreAdapter
      canonicalAuthorityNonPromotionCoreAdapter
      canonicalBridgeRequirementCoreAdapter
      canonicalAdapterCanonicalityCoreAdapter
      statement
      remainingGap
      true
      false
      false
      false
      false
      false
      false
      false
      false
      false
      false

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  mkFormalLensQualificationReceipt :
    (surface : FormalLensQualificationSurface) →
    qualificationCandidateOnly surface ≡ true →
    qualificationPromoted surface ≡ false →
    analyticAuthority surface ≡ false →
    empiricalAuthority surface ≡ false →
    clinicalAuthority surface ≡ false →
    physicalAuthority surface ≡ false →
    theoremAuthority surface ≡ false →
    metaphysicalAuthority surface ≡ false →
    externalAuthority surface ≡ false →
    governanceAuthority surface ≡ false →
    promotionAuthority surface ≡ false →
    DASHI.Core.AuthorityNonPromotionCore.promotesAnyAuthority (authorityBundle surface) ≡ false →
    DASHI.Core.BridgeRequirementCore.rowAuthorityPromotion (bridgeRow surface) ≡ false →
    DASHI.Core.BridgeRequirementCore.rowTransportMapAuthority (bridgeRow surface) ≡ false →
    DASHI.Core.BridgeRequirementCore.rowBackgroundBridgeAuthority (bridgeRow surface) ≡ false →
    DASHI.Core.AdapterCanonicalityCore.adapter (candidateCoreAdapter surface)
      ≡
      DASHI.Core.CandidateOnlyCore.canonicalRowCandidateOnlyRow →
    DASHI.Core.AdapterCanonicalityCore.adapter (authorityCoreAdapter surface)
      ≡
      DASHI.Core.AuthorityNonPromotionCore.canonicalAuthorityNonPromotionBundle →
    DASHI.Core.AdapterCanonicalityCore.adapter (bridgeCoreAdapter surface)
      ≡
      DASHI.Core.BridgeRequirementCore.canonicalBridgeRequirementCoreReceipt →
    DASHI.Core.AdapterCanonicalityCore.adapter (adapterCoreAdapter surface)
      ≡
      DASHI.Core.AdapterCanonicalityCore.canonicalAdapter →
    FormalLensQualificationReceipt surface
  mkFormalLensQualificationReceipt
    surface
    candidateOnlyProof
    promotedProof
    analyticProof
    empiricalProof
    clinicalProof
    physicalProof
    theoremProof
    metaphysicalProof
    externalProof
    governanceProof
    promotionProof
    authorityBundleProof
    bridgeAuthorityProof
    bridgeTransportProof
    bridgeBackgroundProof
    candidateAdapterProof
    authorityAdapterProof
    bridgeAdapterProof
    adapterAdapterProof =
    formalLensQualificationReceipt
      candidateOnlyProof
      promotedProof
      analyticProof
      empiricalProof
      clinicalProof
      physicalProof
      theoremProof
      metaphysicalProof
      externalProof
      governanceProof
      promotionProof
      authorityBundleProof
      bridgeAuthorityProof
      bridgeTransportProof
      bridgeBackgroundProof
      candidateAdapterProof
      authorityAdapterProof
      bridgeAdapterProof
      adapterAdapterProof

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  ------------------------------------------------------------------------
  -- Projection lemmas.

  qualificationIsCandidateOnly :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    qualificationCandidateOnly surface ≡ true
  qualificationIsCandidateOnly receipt =
    receiptCandidateOnlyIsTrue receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  qualificationPromotedFalse :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    qualificationPromoted surface ≡ false
  qualificationPromotedFalse receipt =
    receiptPromotedIsFalse receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  qualificationAnalyticAuthorityFalse :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    analyticAuthority surface ≡ false
  qualificationAnalyticAuthorityFalse receipt =
    receiptAnalyticAuthorityFalse receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  qualificationEmpiricalAuthorityFalse :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    empiricalAuthority surface ≡ false
  qualificationEmpiricalAuthorityFalse receipt =
    receiptEmpiricalAuthorityFalse receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  qualificationClinicalAuthorityFalse :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    clinicalAuthority surface ≡ false
  qualificationClinicalAuthorityFalse receipt =
    receiptClinicalAuthorityFalse receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  qualificationPhysicalAuthorityFalse :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    physicalAuthority surface ≡ false
  qualificationPhysicalAuthorityFalse receipt =
    receiptPhysicalAuthorityFalse receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  qualificationTheoremAuthorityFalse :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    theoremAuthority surface ≡ false
  qualificationTheoremAuthorityFalse receipt =
    receiptTheoremAuthorityFalse receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  qualificationMetaphysicalAuthorityFalse :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    metaphysicalAuthority surface ≡ false
  qualificationMetaphysicalAuthorityFalse receipt =
    receiptMetaphysicalAuthorityFalse receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  qualificationExternalAuthorityFalse :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    externalAuthority surface ≡ false
  qualificationExternalAuthorityFalse receipt =
    receiptExternalAuthorityFalse receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  qualificationGovernanceAuthorityFalse :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    governanceAuthority surface ≡ false
  qualificationGovernanceAuthorityFalse receipt =
    receiptGovernanceAuthorityFalse receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  qualificationPromotionAuthorityFalse :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    promotionAuthority surface ≡ false
  qualificationPromotionAuthorityFalse receipt =
    receiptPromotionAuthorityFalse receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  qualificationCandidateAdapterCanonical :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    DASHI.Core.AdapterCanonicalityCore.adapter (candidateCoreAdapter surface)
    ≡
    DASHI.Core.CandidateOnlyCore.canonicalRowCandidateOnlyRow
  qualificationCandidateAdapterCanonical receipt =
    receiptCandidateAdapterCanonical receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  qualificationAuthorityAdapterCanonical :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    DASHI.Core.AdapterCanonicalityCore.adapter (authorityCoreAdapter surface)
    ≡
    DASHI.Core.AuthorityNonPromotionCore.canonicalAuthorityNonPromotionBundle
  qualificationAuthorityAdapterCanonical receipt =
    receiptAuthorityAdapterCanonical receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  qualificationBridgeAdapterCanonical :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    DASHI.Core.AdapterCanonicalityCore.adapter (bridgeCoreAdapter surface)
    ≡
    DASHI.Core.BridgeRequirementCore.canonicalBridgeRequirementCoreReceipt
  qualificationBridgeAdapterCanonical receipt =
    receiptBridgeAdapterCanonical receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  qualificationAdapterAdapterCanonical :
    {surface : FormalLensQualificationSurface} →
    FormalLensQualificationReceipt surface →
    DASHI.Core.AdapterCanonicalityCore.adapter (adapterCoreAdapter surface)
    ≡
    DASHI.Core.AdapterCanonicalityCore.canonicalAdapter
  qualificationAdapterAdapterCanonical receipt =
    receiptAdapterAdapterCanonical receipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  ------------------------------------------------------------------------
  -- Canonical qualification surfaces and receipts.

  canonicalGenericFormalLensQualificationSurface :
    FormalLensQualificationSurface
  canonicalGenericFormalLensQualificationSurface =
    mkFormalLensQualificationSurface
      "generic formal-lens qualification"
      "DASHI.Core.FormalLensQualificationCore"
      "canonicalGenericFormalLensQualificationSurface"
      (NamedFormalLens "generic formal lens")
      (NamedFormalLens "generic residual target")
      sourceLensRole
      canonicalRequiredThresholdRow
      canonicalRequiredThresholdRowReceipt
      explicitOpenResidualBoundary
      genericFormalLensCandidateRow
      genericFormalLensCandidateReceipt
      genericFormalLensBridgeRow
      genericFormalLensBridgeReceipt
      "generic formal-lens qualification records the lens, threshold, residual boundary, and canonical core adapters"
      "no domain authority, theorem authority, external acceptance, or governance promotion is supplied here"

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalGenericFormalLensQualificationReceipt :
    FormalLensQualificationReceipt
      canonicalGenericFormalLensQualificationSurface
  canonicalGenericFormalLensQualificationReceipt =
    mkFormalLensQualificationReceipt
      canonicalGenericFormalLensQualificationSurface
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalGradientResistiveQualificationSurface :
    FormalLensQualificationSurface
  canonicalGradientResistiveQualificationSurface =
    mkFormalLensQualificationSurface
      "gradient-flow resistive-transport qualification"
      "DASHI.Core.FormalLensQualificationCore"
      "canonicalGradientResistiveQualificationSurface"
      GradientFlow
      ResistiveTransport
      residualBoundaryRole
      canonicalMissingThresholdRow
      canonicalMissingThresholdRowReceipt
      explicitMissingThresholdResidualBoundary
      gradientResistiveCandidateRow
      gradientResistiveCandidateReceipt
      gradientResistiveBridgeRow
      gradientResistiveBridgeReceipt
      "gradient-flow and resistive-transport are related only as a candidate residual-boundary row"
      "missing transport threshold, analytic PDE proof, physical law, empirical validation, and theorem authority remain open"

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalGradientResistiveQualificationReceipt :
    FormalLensQualificationReceipt
      canonicalGradientResistiveQualificationSurface
  canonicalGradientResistiveQualificationReceipt =
    mkFormalLensQualificationReceipt
      canonicalGradientResistiveQualificationSurface
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl
      refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  genericQualificationSourceLens :
    sourceLens canonicalGenericFormalLensQualificationSurface
    ≡
    NamedFormalLens "generic formal lens"
  genericQualificationSourceLens =
    refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  genericQualificationThresholdRequired :
    thresholdRowStatus (threshold canonicalGenericFormalLensQualificationSurface)
    ≡
    thresholdRequired
  genericQualificationThresholdRequired =
    refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  genericQualificationPromotedFalse :
    qualificationPromoted canonicalGenericFormalLensQualificationSurface
    ≡
    false
  genericQualificationPromotedFalse =
    qualificationPromotedFalse canonicalGenericFormalLensQualificationReceipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  gradientResistiveSourceLens :
    sourceLens canonicalGradientResistiveQualificationSurface
    ≡
    GradientFlow
  gradientResistiveSourceLens =
    refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  gradientResistiveTargetLens :
    targetLens canonicalGradientResistiveQualificationSurface
    ≡
    ResistiveTransport
  gradientResistiveTargetLens =
    refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  gradientResistiveThresholdMissing :
    thresholdRowStatus (threshold canonicalGradientResistiveQualificationSurface)
    ≡
    thresholdMissing
  gradientResistiveThresholdMissing =
    refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  gradientResistivePromotedFalse :
    qualificationPromoted canonicalGradientResistiveQualificationSurface
    ≡
    false
  gradientResistivePromotedFalse =
    qualificationPromotedFalse canonicalGradientResistiveQualificationReceipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  gradientResistivePhysicalAuthorityFalse :
    physicalAuthority canonicalGradientResistiveQualificationSurface
    ≡
    false
  gradientResistivePhysicalAuthorityFalse =
    qualificationPhysicalAuthorityFalse
      canonicalGradientResistiveQualificationReceipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  gradientResistiveTheoremAuthorityFalse :
    theoremAuthority canonicalGradientResistiveQualificationSurface
    ≡
    false
  gradientResistiveTheoremAuthorityFalse =
    qualificationTheoremAuthorityFalse
      canonicalGradientResistiveQualificationReceipt

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalFormalLensQualificationSurfaces :
    List FormalLensQualificationSurface
  canonicalFormalLensQualificationSurfaces =
    canonicalGenericFormalLensQualificationSurface
    ∷ canonicalGradientResistiveQualificationSurface
    ∷ []

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalFormalLensQualificationSurfaceCount : Nat
  canonicalFormalLensQualificationSurfaceCount =
    listCount canonicalFormalLensQualificationSurfaces

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  data AllQualificationSurfacesFailClosed :
    List FormalLensQualificationSurface →
    Set where
    allQualificationSurfacesFailClosedNil :
      AllQualificationSurfacesFailClosed []

    allQualificationSurfacesFailClosedCons :
      ∀ {surface surfaces} ,
      qualificationPromoted surface ≡ false →
      analyticAuthority surface ≡ false →
      empiricalAuthority surface ≡ false →
      clinicalAuthority surface ≡ false →
      physicalAuthority surface ≡ false →
      theoremAuthority surface ≡ false →
      metaphysicalAuthority surface ≡ false →
      externalAuthority surface ≡ false →
      governanceAuthority surface ≡ false →
      promotionAuthority surface ≡ false →
      AllQualificationSurfacesFailClosed surfaces →
      AllQualificationSurfacesFailClosed (surface ∷ surfaces)

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalFormalLensQualificationSurfacesFailClosed :
    AllQualificationSurfacesFailClosed
      canonicalFormalLensQualificationSurfaces
  canonicalFormalLensQualificationSurfacesFailClosed =
    allQualificationSurfacesFailClosedCons
      (qualificationPromotedFalse
        canonicalGenericFormalLensQualificationReceipt)
      (qualificationAnalyticAuthorityFalse
        canonicalGenericFormalLensQualificationReceipt)
      (qualificationEmpiricalAuthorityFalse
        canonicalGenericFormalLensQualificationReceipt)
      (qualificationClinicalAuthorityFalse
        canonicalGenericFormalLensQualificationReceipt)
      (qualificationPhysicalAuthorityFalse
        canonicalGenericFormalLensQualificationReceipt)
      (qualificationTheoremAuthorityFalse
        canonicalGenericFormalLensQualificationReceipt)
      (qualificationMetaphysicalAuthorityFalse
        canonicalGenericFormalLensQualificationReceipt)
      (qualificationExternalAuthorityFalse
        canonicalGenericFormalLensQualificationReceipt)
      (qualificationGovernanceAuthorityFalse
        canonicalGenericFormalLensQualificationReceipt)
      (qualificationPromotionAuthorityFalse
        canonicalGenericFormalLensQualificationReceipt)
      (allQualificationSurfacesFailClosedCons
        (qualificationPromotedFalse
          canonicalGradientResistiveQualificationReceipt)
        (qualificationAnalyticAuthorityFalse
          canonicalGradientResistiveQualificationReceipt)
        (qualificationEmpiricalAuthorityFalse
          canonicalGradientResistiveQualificationReceipt)
        (qualificationClinicalAuthorityFalse
          canonicalGradientResistiveQualificationReceipt)
        (qualificationPhysicalAuthorityFalse
          canonicalGradientResistiveQualificationReceipt)
        (qualificationTheoremAuthorityFalse
          canonicalGradientResistiveQualificationReceipt)
        (qualificationMetaphysicalAuthorityFalse
          canonicalGradientResistiveQualificationReceipt)
        (qualificationExternalAuthorityFalse
          canonicalGradientResistiveQualificationReceipt)
        (qualificationGovernanceAuthorityFalse
          canonicalGradientResistiveQualificationReceipt)
        (qualificationPromotionAuthorityFalse
          canonicalGradientResistiveQualificationReceipt)
        allQualificationSurfacesFailClosedNil)

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  ------------------------------------------------------------------------
  -- Generic receipt adapter.

  formalLensQualificationGenericReceipt :
    FormalLensQualificationSurface →
    DASHI.Core.GenericReceipt.GenericReceipt
  formalLensQualificationGenericReceipt surface =
    DASHI.Core.GenericReceipt.mkNonPromotingReceipt
      (qualificationLabel surface)
      (qualificationOwner surface)
      (qualificationSurface surface)
      (qualificationStatement surface)
      (qualificationRemainingGap surface)
      "agda -i . DASHI/Core/FormalLensQualificationCore.agda"

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalGenericFormalLensQualificationGenericReceipt :
    DASHI.Core.GenericReceipt.GenericReceipt
  canonicalGenericFormalLensQualificationGenericReceipt =
    formalLensQualificationGenericReceipt
      canonicalGenericFormalLensQualificationSurface

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalGradientResistiveQualificationGenericReceipt :
    DASHI.Core.GenericReceipt.GenericReceipt
  canonicalGradientResistiveQualificationGenericReceipt =
    formalLensQualificationGenericReceipt
      canonicalGradientResistiveQualificationSurface

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalGenericFormalLensQualificationGenericReceiptNonPromoting :
    DASHI.Core.GenericReceipt.promotesClaim
      canonicalGenericFormalLensQualificationGenericReceipt
    ≡
    false
  canonicalGenericFormalLensQualificationGenericReceiptNonPromoting =
    refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalGradientResistiveQualificationGenericReceiptNonPromoting :
    DASHI.Core.GenericReceipt.promotesClaim
      canonicalGradientResistiveQualificationGenericReceipt
    ≡
    false
  canonicalGradientResistiveQualificationGenericReceiptNonPromoting =
    refl

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalFormalLensQualificationGenericReceipts :
    List DASHI.Core.GenericReceipt.GenericReceipt
  canonicalFormalLensQualificationGenericReceipts =
    canonicalGenericFormalLensQualificationGenericReceipt
    ∷ canonicalGradientResistiveQualificationGenericReceipt
    ∷ []

agda_module DASHI.Core.FormalLensQualificationCore where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.Nat
  open import Agda.Builtin.String
  open import DASHI.Core.AdapterCanonicalityCore
  open import DASHI.Core.AuthorityNonPromotionCore
  open import DASHI.Core.BridgeRequirementCore
  open import DASHI.Core.CandidateOnlyCore
  open import DASHI.Core.GenericReceipt
  open import DASHI.Core.FormalLensVocabularyCore

  canonicalFormalLensQualificationGenericReceiptsNonPromoting :
    DASHI.Core.GenericReceipt.AllReceiptsNonPromoting
      canonicalFormalLensQualificationGenericReceipts
  canonicalFormalLensQualificationGenericReceiptsNonPromoting =
    DASHI.Core.GenericReceipt.proveAllReceiptsNonPromoting
      canonicalFormalLensQualificationGenericReceipts

