import Mathlib.Tactic
import NSBControl.Rational345RealInitialState

/-!
# W2 sparse real snapshot compiler

The real radius-four carrier has 9^3 modal slots, but the R850 initial state
has exactly six nonzero velocity modes.  This file makes that support
executable and reduces the literal projected nonlinearity to the 6x6 ordered
seed table before any helical arithmetic is performed.
-/

open scoped BigOperators

namespace NSBControl
namespace Rational345RealSnapshotSparse

open Rational345RealRadius4
open Rational345RealInitialState

classical

/-- The two forcing-only 3-4-5 outputs. -/
def km340 : Mode := ⟨1, 8, 4⟩   -- (-3, 4, 0)
def k3m40 : Mode := ⟨7, 0, 4⟩   -- ( 3,-4, 0)

/-- Six nonzero velocity modes of the initial state. -/
def seedModes : Finset Mode :=
  {km3m40, km300, k0m40, k040, k300, k340}

/-- Eight nonzero in-cutoff sums of two seed modes. -/
def activeOutputs : Finset Mode :=
  {km3m40, km300, km340, k0m40, k040, k3m40, k300, k340}

/-- Executable support generated by resonant ordered seed pairs.  Zero is
excluded because the projected radius-four dynamics treats the zero mode
separately. -/
def generatedOutputs : Finset Mode :=
  Finset.univ.filter fun k =>
    ¬ isZeroMode k ∧
      ∃ p ∈ seedModes, ∃ q ∈ seedModes, Resonates p q k

/-- This is the finite 6x6 support exhaustion corresponding to Agda R848. -/
theorem generatedOutputs_eq_activeOutputs :
    generatedOutputs = activeOutputs := by
  native_decide

lemma u₀_zero_of_not_mem_seed {k : Mode} (hk : k ∉ seedModes) :
    u₀ k = 0 := by
  simp [seedModes, u₀, k300, km300, k040, k0m40, k340, km3m40] at hk ⊢
  aesop

lemma projectedOrderedBilinear_zero_left
    (right : State) (p q k : Mode) :
    projectedOrderedBilinear (fun _ => 0) right p q k = 0 := by
  simp [projectedOrderedBilinear, bilinearDot, leray]

lemma projectedOrderedBilinear_zero_right
    (left : State) (p q k : Mode) :
    projectedOrderedBilinear left (fun _ => 0) p q k = 0 := by
  simp [projectedOrderedBilinear, bilinearDot, leray]

lemma projectedOrderedBilinear_u₀_zero_left
    {p q k : Mode} (hp : p ∉ seedModes) :
    projectedOrderedBilinear u₀ u₀ p q k = 0 := by
  rw [show u₀ p = 0 from u₀_zero_of_not_mem_seed hp]
  simp [projectedOrderedBilinear, bilinearDot, leray]

lemma projectedOrderedBilinear_u₀_zero_right
    {p q k : Mode} (hq : q ∉ seedModes) :
    projectedOrderedBilinear u₀ u₀ p q k = 0 := by
  rw [show u₀ q = 0 from u₀_zero_of_not_mem_seed hq]
  simp [projectedOrderedBilinear, bilinearDot, leray]

/-- Literal nonlinear forcing evaluated only on the six-by-six seed table. -/
def sparseForcing (k : Mode) : Vec3 :=
  if isZeroMode k then 0
  else ∑ p in seedModes, ∑ q in seedModes,
    projectedOrderedBilinear u₀ u₀ p q k

lemma sum_univ_eq_sum_seed_left (k : Mode) :
    (∑ p : Mode, ∑ q : Mode,
      projectedOrderedBilinear u₀ u₀ p q k) =
    ∑ p in seedModes, ∑ q : Mode,
      projectedOrderedBilinear u₀ u₀ p q k := by
  symm
  apply Finset.sum_subset (by simp)
  intro p hpUniv hpSeed
  simp only [Finset.mem_univ] at hpUniv
  simp [projectedOrderedBilinear_u₀_zero_left hpSeed]

lemma sum_seed_eq_sum_seed_seed (k : Mode) :
    (∑ p in seedModes, ∑ q : Mode,
      projectedOrderedBilinear u₀ u₀ p q k) =
    ∑ p in seedModes, ∑ q in seedModes,
      projectedOrderedBilinear u₀ u₀ p q k := by
  apply Finset.sum_congr rfl
  intro p hp
  symm
  apply Finset.sum_subset (by simp)
  intro q hqUniv hqSeed
  simp only [Finset.mem_univ] at hqUniv
  exact projectedOrderedBilinear_u₀_zero_right hqSeed

/-- The actual radius-four projected nonlinearity at the initial state is
exactly the finite 6x6 sparse forcing. -/
theorem projectedNonlinearity_u₀_eq_sparse (k : Mode) :
    projectedNonlinearity u₀ k = sparseForcing k := by
  simp only [projectedNonlinearity, projectedBilinear, sparseForcing]
  split_ifs with hzero
  · rfl
  · rw [sum_univ_eq_sum_seed_left k, sum_seed_eq_sum_seed_seed k]

lemma sparseForcing_zero_of_not_mem_active
    {k : Mode} (hk : k ∉ activeOutputs) :
    sparseForcing k = 0 := by
  by_cases hz : isZeroMode k
  · simp [sparseForcing, hz]
  · have hnotgen : k ∉ generatedOutputs := by
      simpa [generatedOutputs_eq_activeOutputs] using hk
    have hno :
        ¬ ∃ p ∈ seedModes, ∃ q ∈ seedModes, Resonates p q k := by
      intro hpair
      exact hnotgen (by simp [generatedOutputs, hz, hpair])
    simp only [sparseForcing, hz, if_false]
    apply Finset.sum_eq_zero
    intro p hp
    apply Finset.sum_eq_zero
    intro q hq
    have hnres : ¬ Resonates p q k := by
      intro hres
      exact hno ⟨p, hp, q, hq, hres⟩
    simp [projectedOrderedBilinear, hnres]

/-- Hence the literal real R30 forcing has precisely the eight-output support
needed by the R850 snapshot calculation. -/
theorem projectedNonlinearity_u₀_zero_of_not_mem_active
    {k : Mode} (hk : k ∉ activeOutputs) :
    projectedNonlinearity u₀ k = 0 := by
  rw [projectedNonlinearity_u₀_eq_sparse]
  exact sparseForcing_zero_of_not_mem_active hk

end Rational345RealSnapshotSparse
end NSBControl
