module DASHI.Physics.YangMills.CompactLieLangevinSkewConnectionCancellationExact where

------------------------------------------------------------------------
-- ROUND72: COMPACT-LIE LANGEVIN CONNECTION IS BASIS-FREE SKEW ENERGY ZERO
--
-- GEOMETRIC SOURCES
--
-- Brian C. Hall,
-- "Lie Groups, Lie Algebras, and Representations: An Elementary Introduction",
-- second edition, Graduate Texts in Mathematics 222, Springer (2015).
-- DOI: 10.1007/978-3-319-13467-3.
--
-- John Milnor,
-- "Curvatures of Left Invariant Metrics on Lie Groups",
-- Advances in Mathematics 21 (1976), 293--329.
-- DOI: 10.1016/S0001-8708(76)80002-3.
--
-- Standard compact-Lie geometry:
-- * compact G admits an Ad-invariant inner product / bi-invariant metric;
-- * infinitesimally ad_Z is skew-adjoint,
--
--       <[Z,X],Y> + <X,[Z,Y]> = 0;
--
-- * for a bi-invariant metric, the invariant-frame connection is generated by
--   the bracket and the Laplace--Beltrami operator is the central Casimir.
--
-- DASHI CONTRIBUTION
--
-- The previous coordinate proof paired colour indices and needed a separate
-- scalar `skewPairCancels` postulate.  That is unnecessary.  The Langevin
-- connection-energy contribution is already the basis-free bilinear pairing
-- above; at Y=X it vanishes directly by Ad-invariance.  The cancellation is
-- sitewise, and a finite lattice sum remains exactly zero by induction.
--
-- Consequently the compact-Lie connection contributes NO positive symmetric
-- derivative-energy growth constant and NO volume factor.  Once the physical
-- commutator is identified with this geometric ad term, the only nonlocal
-- growth/propagation budget is the SAME action Hessian controlled by the
-- marked CMP109 activity estimate.
------------------------------------------------------------------------

open import Agda.Builtin.Equality using (_≡_)
open import Data.List.Base using (List)

open import DASHI.Physics.YangMills.CompactLieProofLevel
import DASHI.Physics.YangMills.CompactLieBiInvariantSkewLangevinExact as Skew

------------------------------------------------------------------------
-- Exact basis-free cancellation inherited from the Ad-invariant metric core.
------------------------------------------------------------------------

connectionPairedEnergyCancels = Skew.connectionPairedEnergyCancels
connectionQuadraticEnergyCancels = Skew.connectionQuadraticEnergyCancels
finiteLatticeConnectionEnergyCancels = Skew.finiteLatticeConnectionEnergyCancels

compactLieSkewQuadraticCancellationLevel : ProofLevel
compactLieSkewQuadraticCancellationLevel = machineChecked

------------------------------------------------------------------------
-- Literal lattice-Langevin same-object boundary.
------------------------------------------------------------------------

record CompactLieLangevinFrameData : Set₁ where
  field
    Site Field Function : Set

    metric : Skew.BiInvariantLieMetricData

    -- The actual compact-group field derivative and generator carriers.
    frameDerivative : Site → Skew.Lie metric → Function → Function
    laplacian : Function → Function

    -- Geometric vectors appearing in the differentiated drift at one site.
    connectionDirection : Site → Field → Skew.Lie metric
    derivativeVector : Site → Field → Skew.Lie metric

    -- Casimir centrality / invariant-frame commutation on the literal carrier.
    laplacianCommutesWithFrame : Set

    -- Literal differentiated-generator identity.  Its symmetric nonlocal part
    -- must be the physical action Hessian; its remaining connection part must
    -- identify with `connectionDirection` acting by ad on `derivativeVector`.
    LangevinCommutatorIdentity : Set
    connectionIsOnsiteAdTerm : Set

open CompactLieLangevinFrameData public

literalConnectionQuadraticEnergyCancels :
  (D : CompactLieLangevinFrameData) →
  (field : Field D) →
  ∀ sites →
  Skew.sumConnectionQuadratic
    (metric D)
    (λ site → connectionDirection D site field)
    (λ site → derivativeVector D site field)
    sites
  ≡ Skew.zero (metric D)
literalConnectionQuadraticEnergyCancels D field =
  Skew.finiteLatticeConnectionEnergyCancels
    (metric D)
    (λ site → connectionDirection D site field)
    (λ site → derivativeVector D site field)

compactLieCasimirFrameCommutationLevel : ProofLevel
compactLieCasimirFrameCommutationLevel = standardImported

compactLieAdSkewConnectionLevel : ProofLevel
compactLieAdSkewConnectionLevel = standardImported

-- The ONLY Yang--Mills-specific connection seam left here: prove that the
-- actual differentiated lattice Langevin generator has the standard compact-
-- Lie commutator decomposition and that its connection term is the onsite ad
-- term named above.  Once identified, its full quadratic contribution is zero
-- by `literalConnectionQuadraticEnergyCancels`; no further connection estimate
-- is mathematically required.
physicalLiteralLangevinCommutatorIdentificationLevel : ProofLevel
physicalLiteralLangevinCommutatorIdentificationLevel = conditional
