module DASHI.Reasoning.DialecticMotifEverything where

import DASHI.Reasoning.DialecticMotifKernel
import DASHI.Reasoning.DialecticInvariantGeometry
import DASHI.Reasoning.TernarySynthesisOrbitWeldEverything
