/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Agda.Syntax

/-!
# `DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge`, transliterated

Generated by `tools/agda2lean.py` from the ingested upstream source
`upstream/dashi_agda/master/DASHI/Biology/HyperfabricIntersectionalBodyMemoryBridge.agda`.
Do not edit by hand: re-run the translator instead.
-/

open Agda

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where

  open import Agda.Builtin.Bool

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  ------------------------------------------------------------------------
  -- Hyperfabric / intersectional / body-memory bridge.
  --
  -- This module treats dialectics, spiral vocabularies, hypervoxel and
  -- hyperfabric talk, trit / 369 / stage / prime / p-adic references, and
  -- intersectional axis auditing as candidate interpretive carrier material.
  -- It does not promote any of that vocabulary to proof of social truth,
  -- clinical authority, legal authority, or educational authority.
  -- It also blocks abstract-humanity gluing and stable-nine justice promotion.

  data Never : Set where

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  data InterpretiveRoute : Set where
    candidateInterpretiveRoute :
      InterpretiveRoute

    neutralTriadUniversalismRoute :
      InterpretiveRoute

    monocultureCompressionRoute :
      InterpretiveRoute

    socialTruthProofRoute :
      InterpretiveRoute

    clinicalAuthorityRoute :
      InterpretiveRoute

    legalAuthorityRoute :
      InterpretiveRoute

    educationalAuthorityRoute :
      InterpretiveRoute

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  interpretiveRouteName : InterpretiveRoute → String
  interpretiveRouteName candidateInterpretiveRoute =
    "candidate-interpretive-route"
  interpretiveRouteName neutralTriadUniversalismRoute =
    "neutral-triad-universalism-route"
  interpretiveRouteName monocultureCompressionRoute =
    "monoculture-compression-route"
  interpretiveRouteName socialTruthProofRoute =
    "social-truth-proof-route"
  interpretiveRouteName clinicalAuthorityRoute =
    "clinical-authority-route"
  interpretiveRouteName legalAuthorityRoute =
    "legal-authority-route"
  interpretiveRouteName educationalAuthorityRoute =
    "educational-authority-route"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  AdmissibleInterpretiveRoute : InterpretiveRoute → Set
  AdmissibleInterpretiveRoute candidateInterpretiveRoute = ⊤
  AdmissibleInterpretiveRoute neutralTriadUniversalismRoute = Never
  AdmissibleInterpretiveRoute monocultureCompressionRoute = Never
  AdmissibleInterpretiveRoute socialTruthProofRoute = Never
  AdmissibleInterpretiveRoute clinicalAuthorityRoute = Never
  AdmissibleInterpretiveRoute legalAuthorityRoute = Never
  AdmissibleInterpretiveRoute educationalAuthorityRoute = Never

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  candidateInterpretiveRouteAdmissible :
    AdmissibleInterpretiveRoute candidateInterpretiveRoute
  candidateInterpretiveRouteAdmissible = tt

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  neutralTriadUniversalismRouteRejected :
    AdmissibleInterpretiveRoute neutralTriadUniversalismRoute →
    Never
  neutralTriadUniversalismRouteRejected ()

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  monocultureCompressionRouteRejected :
    AdmissibleInterpretiveRoute monocultureCompressionRoute →
    Never
  monocultureCompressionRouteRejected ()

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  socialTruthProofRouteRejected :
    AdmissibleInterpretiveRoute socialTruthProofRoute →
    Never
  socialTruthProofRouteRejected ()

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  clinicalAuthorityRouteRejected :
    AdmissibleInterpretiveRoute clinicalAuthorityRoute →
    Never
  clinicalAuthorityRouteRejected ()

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  legalAuthorityRouteRejected :
    AdmissibleInterpretiveRoute legalAuthorityRoute →
    Never
  legalAuthorityRouteRejected ()

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  educationalAuthorityRouteRejected :
    AdmissibleInterpretiveRoute educationalAuthorityRoute →
    Never
  educationalAuthorityRouteRejected ()

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  data TriadicRelationSurface : Set where
    dialecticTriadSurface :
      TriadicRelationSurface

    spiralTriadSurface :
      TriadicRelationSurface

    hypervoxelTriadSurface :
      TriadicRelationSurface

    hyperfabricTriadSurface :
      TriadicRelationSurface

    tritTriadSurface :
      TriadicRelationSurface

    stageTriadSurface :
      TriadicRelationSurface

    primeTriadSurface :
      TriadicRelationSurface

    padicTriadSurface :
      TriadicRelationSurface

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  triadicRelationSurfaceName :
    TriadicRelationSurface →
    String
  triadicRelationSurfaceName dialecticTriadSurface =
    "dialectic-triad-surface"
  triadicRelationSurfaceName spiralTriadSurface =
    "spiral-triad-surface"
  triadicRelationSurfaceName hypervoxelTriadSurface =
    "hypervoxel-triad-surface"
  triadicRelationSurfaceName hyperfabricTriadSurface =
    "hyperfabric-triad-surface"
  triadicRelationSurfaceName tritTriadSurface =
    "trit-triad-surface"
  triadicRelationSurfaceName stageTriadSurface =
    "stage-triad-surface"
  triadicRelationSurfaceName primeTriadSurface =
    "prime-triad-surface"
  triadicRelationSurfaceName padicTriadSurface =
    "p-adic-triad-surface"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  record TriadicRelationRow : Set where
    constructor mkTriadicRelationRow
    field
      rowLabel :
        String

      rowSurface :
        TriadicRelationSurface

      rowCarrierName :
        String

      rowInterpretiveStatement :
        String

      rowCandidateInterpretiveCarrier :
        Bool

      rowCandidateInterpretiveCarrierIsTrue :
        rowCandidateInterpretiveCarrier ≡ true

      rowNoSocialTruthProof :
        Bool

      rowNoSocialTruthProofIsTrue :
        rowNoSocialTruthProof ≡ true

      rowNoAuthorityPromotion :
        Bool

      rowNoAuthorityPromotionIsTrue :
        rowNoAuthorityPromotion ≡ true

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  open TriadicRelationRow public

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  mkCandidateTriadicRelationRow :
    String →
    TriadicRelationSurface →
    String →
    String →
    TriadicRelationRow
  mkCandidateTriadicRelationRow label surface carrierName interpretiveStatement =
    mkTriadicRelationRow
      label
      surface
      carrierName
      interpretiveStatement
      true
      refl
      true
      refl
      true
      refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalDialecticTriadicRelationRow : TriadicRelationRow
  canonicalDialecticTriadicRelationRow =
    mkCandidateTriadicRelationRow
      "dialectic-triadic-relation-row"
      dialecticTriadSurface
      "body-memory"
      "dialectics are read as candidate interpretive tension, not social truth proof"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalSpiralTriadicRelationRow : TriadicRelationRow
  canonicalSpiralTriadicRelationRow =
    mkCandidateTriadicRelationRow
      "spiral-triadic-relation-row"
      spiralTriadSurface
      "body-memory"
      "spiral motion is a candidate interpretive carrier for staged revisiting, not authority"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalHypervoxelTriadicRelationRow : TriadicRelationRow
  canonicalHypervoxelTriadicRelationRow =
    mkCandidateTriadicRelationRow
      "hypervoxel-triadic-relation-row"
      hypervoxelTriadSurface
      "body-memory"
      "hypervoxel vocabulary marks a candidate geometric carrier, not a proof of truth"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalHyperfabricTriadicRelationRow : TriadicRelationRow
  canonicalHyperfabricTriadicRelationRow =
    mkCandidateTriadicRelationRow
      "hyperfabric-triadic-relation-row"
      hyperfabricTriadSurface
      "body-memory"
      "hyperfabric vocabulary names a layered candidate interpretive carrier"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalTritTriadicRelationRow : TriadicRelationRow
  canonicalTritTriadicRelationRow =
    mkCandidateTriadicRelationRow
      "trit-triadic-relation-row"
      tritTriadSurface
      "body-memory"
      "trit vocabulary keeps ternary structure distinct from universalism"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalStageTriadicRelationRow : TriadicRelationRow
  canonicalStageTriadicRelationRow =
    mkCandidateTriadicRelationRow
      "stage-triadic-relation-row"
      stageTriadSurface
      "body-memory"
      "stage vocabulary marks ordered interpretive placement without authority promotion"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalPrimeTriadicRelationRow : TriadicRelationRow
  canonicalPrimeTriadicRelationRow =
    mkCandidateTriadicRelationRow
      "prime-triadic-relation-row"
      primeTriadSurface
      "body-memory"
      "prime vocabulary tracks candidate recurrence and structure, not proof of social truth"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalPadicTriadicRelationRow : TriadicRelationRow
  canonicalPadicTriadicRelationRow =
    mkCandidateTriadicRelationRow
      "p-adic-triadic-relation-row"
      padicTriadSurface
      "body-memory"
      "p-adic vocabulary marks candidate scale sensitivity, not clinical authority"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalTriadicRelationRows : List TriadicRelationRow
  canonicalTriadicRelationRows =
    canonicalDialecticTriadicRelationRow
    ∷ canonicalSpiralTriadicRelationRow
    ∷ canonicalHypervoxelTriadicRelationRow
    ∷ canonicalHyperfabricTriadicRelationRow
    ∷ canonicalTritTriadicRelationRow
    ∷ canonicalStageTriadicRelationRow
    ∷ canonicalPrimeTriadicRelationRow
    ∷ canonicalPadicTriadicRelationRow
    ∷ []

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  record StageSpiralHyperfabricRow : Set where
    constructor mkStageSpiralHyperfabricRow
    field
      rowLabel :
        String

      rowStageTerm :
        String

      rowSpiralTerm :
        String

      rowHyperfabricTerm :
        String

      rowBodyMemoryCarrier :
        String

      rowCandidateInterpretiveCarrier :
        Bool

      rowCandidateInterpretiveCarrierIsTrue :
        rowCandidateInterpretiveCarrier ≡ true

      rowNoNeutralTriadUniversalism :
        Bool

      rowNoNeutralTriadUniversalismIsTrue :
        rowNoNeutralTriadUniversalism ≡ true

      rowNoMonocultureCompression :
        Bool

      rowNoMonocultureCompressionIsTrue :
        rowNoMonocultureCompression ≡ true

      rowNoSocialTruthProof :
        Bool

      rowNoSocialTruthProofIsTrue :
        rowNoSocialTruthProof ≡ true

      rowNoClinicalAuthority :
        Bool

      rowNoClinicalAuthorityIsTrue :
        rowNoClinicalAuthority ≡ true

      rowReading :
        String

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  open StageSpiralHyperfabricRow public

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  mkStageSpiralHyperfabricCandidateRow :
    String →
    String →
    String →
    String →
    String →
    StageSpiralHyperfabricRow
  mkStageSpiralHyperfabricCandidateRow
    label
    stageTerm
    spiralTerm
    hyperfabricTerm
    reading =
    mkStageSpiralHyperfabricRow
      label
      stageTerm
      spiralTerm
      hyperfabricTerm
      "body-memory"
      true
      refl
      true
      refl
      true
      refl
      true
      refl
      true
      refl
      reading

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalDialecticStageRow : StageSpiralHyperfabricRow
  canonicalDialecticStageRow =
    mkStageSpiralHyperfabricCandidateRow
      "dialectic-stage-row"
      "dialectic stage"
      "dialectic spiral"
      "dialectic hyperfabric"
      "dialectic and spiral form a candidate interpretive carrier for body-memory"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalSpiralStageRow : StageSpiralHyperfabricRow
  canonicalSpiralStageRow =
    mkStageSpiralHyperfabricCandidateRow
      "spiral-stage-row"
      "spiral stage"
      "spiral traversal"
      "spiral hyperfabric"
      "spiral revisiting remains candidate interpretation, not social proof"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalHypervoxelStageRow : StageSpiralHyperfabricRow
  canonicalHypervoxelStageRow =
    mkStageSpiralHyperfabricCandidateRow
      "hypervoxel-stage-row"
      "hypervoxel stage"
      "hypervoxel spiral"
      "hypervoxel hyperfabric"
      "hypervoxel staging keeps the carrier interpretive rather than evidentiary"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalHyperfabricStageRow : StageSpiralHyperfabricRow
  canonicalHyperfabricStageRow =
    mkStageSpiralHyperfabricCandidateRow
      "hyperfabric-stage-row"
      "hyperfabric stage"
      "hyperfabric spiral"
      "hyperfabric weave"
      "hyperfabric weaving is a carrier surface and not an authority surface"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalTrit369Row : StageSpiralHyperfabricRow
  canonicalTrit369Row =
    mkStageSpiralHyperfabricCandidateRow
      "trit-369-row"
      "trit stage"
      "369 spiral"
      "369 hyperfabric"
      "trit and 369 language can organize interpretation without universalizing it"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalPrimePadicRow : StageSpiralHyperfabricRow
  canonicalPrimePadicRow =
    mkStageSpiralHyperfabricCandidateRow
      "prime-padic-row"
      "prime stage"
      "prime spiral"
      "p-adic hyperfabric"
      "prime and p-adic language stay in the interpretive lane"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalStageSpiralHyperfabricRows : List StageSpiralHyperfabricRow
  canonicalStageSpiralHyperfabricRows =
    canonicalDialecticStageRow
    ∷ canonicalSpiralStageRow
    ∷ canonicalHypervoxelStageRow
    ∷ canonicalHyperfabricStageRow
    ∷ canonicalTrit369Row
    ∷ canonicalPrimePadicRow
    ∷ []

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  data IntersectionalAxis : Set where
    dialecticAxis :
      IntersectionalAxis

    spiralAxis :
      IntersectionalAxis

    hypervoxelAxis :
      IntersectionalAxis

    hyperfabricAxis :
      IntersectionalAxis

    tritAxis :
      IntersectionalAxis

    threeSixNineAxis :
      IntersectionalAxis

    stageAxis :
      IntersectionalAxis

    primeAxis :
      IntersectionalAxis

    padicAxis :
      IntersectionalAxis

    bodyMemoryAxis :
      IntersectionalAxis

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  axisName : IntersectionalAxis → String
  axisName dialecticAxis =
    "dialectic-axis"
  axisName spiralAxis =
    "spiral-axis"
  axisName hypervoxelAxis =
    "hypervoxel-axis"
  axisName hyperfabricAxis =
    "hyperfabric-axis"
  axisName tritAxis =
    "trit-axis"
  axisName threeSixNineAxis =
    "369-axis"
  axisName stageAxis =
    "stage-axis"
  axisName primeAxis =
    "prime-axis"
  axisName padicAxis =
    "p-adic-axis"
  axisName bodyMemoryAxis =
    "body-memory-axis"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  record IntersectionalAxisAuditRow : Set where
    constructor mkIntersectionalAxisAuditRow
    field
      rowLabel :
        String

      rowAxis :
        IntersectionalAxis

      rowAxisName :
        String

      rowCandidateInterpretiveCarrier :
        Bool

      rowCandidateInterpretiveCarrierIsTrue :
        rowCandidateInterpretiveCarrier ≡ true

      rowNoNeutralTriadUniversalism :
        Bool

      rowNoNeutralTriadUniversalismIsTrue :
        rowNoNeutralTriadUniversalism ≡ true

      rowNoMonocultureCompression :
        Bool

      rowNoMonocultureCompressionIsTrue :
        rowNoMonocultureCompression ≡ true

      rowNoSocialTruthProof :
        Bool

      rowNoSocialTruthProofIsTrue :
        rowNoSocialTruthProof ≡ true

      rowNoClinicalAuthority :
        Bool

      rowNoClinicalAuthorityIsTrue :
        rowNoClinicalAuthority ≡ true

      rowNoLegalAuthority :
        Bool

      rowNoLegalAuthorityIsTrue :
        rowNoLegalAuthority ≡ true

      rowNoEducationalAuthority :
        Bool

      rowNoEducationalAuthorityIsTrue :
        rowNoEducationalAuthority ≡ true

      rowAuditReading :
        String

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  open IntersectionalAxisAuditRow public

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  mkCandidateIntersectionalAxisAuditRow :
    String →
    IntersectionalAxis →
    String →
    String →
    IntersectionalAxisAuditRow
  mkCandidateIntersectionalAxisAuditRow label axis axisReading auditReading =
    mkIntersectionalAxisAuditRow
      label
      axis
      axisReading
      true
      refl
      true
      refl
      true
      refl
      true
      refl
      true
      refl
      true
      refl
      true
      refl
      auditReading

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalDialecticAxisAuditRow : IntersectionalAxisAuditRow
  canonicalDialecticAxisAuditRow =
    mkCandidateIntersectionalAxisAuditRow
      "dialectic-axis-audit-row"
      dialecticAxis
      "dialectic axis"
      "dialectic remains a candidate interpretive carrier"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalSpiralAxisAuditRow : IntersectionalAxisAuditRow
  canonicalSpiralAxisAuditRow =
    mkCandidateIntersectionalAxisAuditRow
      "spiral-axis-audit-row"
      spiralAxis
      "spiral axis"
      "spiral remains a candidate interpretive carrier"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalHypervoxelAxisAuditRow : IntersectionalAxisAuditRow
  canonicalHypervoxelAxisAuditRow =
    mkCandidateIntersectionalAxisAuditRow
      "hypervoxel-axis-audit-row"
      hypervoxelAxis
      "hypervoxel axis"
      "hypervoxel remains a candidate interpretive carrier"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalHyperfabricAxisAuditRow : IntersectionalAxisAuditRow
  canonicalHyperfabricAxisAuditRow =
    mkCandidateIntersectionalAxisAuditRow
      "hyperfabric-axis-audit-row"
      hyperfabricAxis
      "hyperfabric axis"
      "hyperfabric remains a candidate interpretive carrier"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalTritAxisAuditRow : IntersectionalAxisAuditRow
  canonicalTritAxisAuditRow =
    mkCandidateIntersectionalAxisAuditRow
      "trit-axis-audit-row"
      tritAxis
      "trit axis"
      "trit remains a candidate interpretive carrier"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonical369AxisAuditRow : IntersectionalAxisAuditRow
  canonical369AxisAuditRow =
    mkCandidateIntersectionalAxisAuditRow
      "369-axis-audit-row"
      threeSixNineAxis
      "369 axis"
      "369 remains a candidate interpretive carrier"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalStageAxisAuditRow : IntersectionalAxisAuditRow
  canonicalStageAxisAuditRow =
    mkCandidateIntersectionalAxisAuditRow
      "stage-axis-audit-row"
      stageAxis
      "stage axis"
      "stage remains a candidate interpretive carrier"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalPrimeAxisAuditRow : IntersectionalAxisAuditRow
  canonicalPrimeAxisAuditRow =
    mkCandidateIntersectionalAxisAuditRow
      "prime-axis-audit-row"
      primeAxis
      "prime axis"
      "prime remains a candidate interpretive carrier"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalPadicAxisAuditRow : IntersectionalAxisAuditRow
  canonicalPadicAxisAuditRow =
    mkCandidateIntersectionalAxisAuditRow
      "p-adic-axis-audit-row"
      padicAxis
      "p-adic axis"
      "p-adic remains a candidate interpretive carrier"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalBodyMemoryAxisAuditRow : IntersectionalAxisAuditRow
  canonicalBodyMemoryAxisAuditRow =
    mkCandidateIntersectionalAxisAuditRow
      "body-memory-axis-audit-row"
      bodyMemoryAxis
      "body-memory axis"
      "body-memory remains a candidate interpretive carrier"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalIntersectionalAxisAuditRows : List IntersectionalAxisAuditRow
  canonicalIntersectionalAxisAuditRows =
    canonicalDialecticAxisAuditRow
    ∷ canonicalSpiralAxisAuditRow
    ∷ canonicalHypervoxelAxisAuditRow
    ∷ canonicalHyperfabricAxisAuditRow
    ∷ canonicalTritAxisAuditRow
    ∷ canonical369AxisAuditRow
    ∷ canonicalStageAxisAuditRow
    ∷ canonicalPrimeAxisAuditRow
    ∷ canonicalPadicAxisAuditRow
    ∷ canonicalBodyMemoryAxisAuditRow
    ∷ []

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  data CulturalTriadRole : Set where
    originAuthorityRole :
      CulturalTriadRole

    embodiedSubjectRole :
      CulturalTriadRole

    relationalMediatorRole :
      CulturalTriadRole

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  culturalTriadRoleName : CulturalTriadRole → String
  culturalTriadRoleName originAuthorityRole =
    "origin-authority-role"
  culturalTriadRoleName embodiedSubjectRole =
    "embodied-subject-role"
  culturalTriadRoleName relationalMediatorRole =
    "relational-mediator-role"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  data PowerAtlasAxis : Set where
    racePowerAxis :
      PowerAtlasAxis

    classPowerAxis :
      PowerAtlasAxis

    genderPowerAxis :
      PowerAtlasAxis

    sexualityPowerAxis :
      PowerAtlasAxis

    disabilityPowerAxis :
      PowerAtlasAxis

    neurotypePowerAxis :
      PowerAtlasAxis

    religionPowerAxis :
      PowerAtlasAxis

    colonialityPowerAxis :
      PowerAtlasAxis

    lawPowerAxis :
      PowerAtlasAxis

    landPowerAxis :
      PowerAtlasAxis

    familyPowerAxis :
      PowerAtlasAxis

    institutionPowerAxis :
      PowerAtlasAxis

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  powerAtlasAxisName : PowerAtlasAxis → String
  powerAtlasAxisName racePowerAxis =
    "race-power-axis"
  powerAtlasAxisName classPowerAxis =
    "class-power-axis"
  powerAtlasAxisName genderPowerAxis =
    "gender-power-axis"
  powerAtlasAxisName sexualityPowerAxis =
    "sexuality-power-axis"
  powerAtlasAxisName disabilityPowerAxis =
    "disability-power-axis"
  powerAtlasAxisName neurotypePowerAxis =
    "neurotype-power-axis"
  powerAtlasAxisName religionPowerAxis =
    "religion-power-axis"
  powerAtlasAxisName colonialityPowerAxis =
    "coloniality-power-axis"
  powerAtlasAxisName lawPowerAxis =
    "law-power-axis"
  powerAtlasAxisName landPowerAxis =
    "land-power-axis"
  powerAtlasAxisName familyPowerAxis =
    "family-power-axis"
  powerAtlasAxisName institutionPowerAxis =
    "institution-power-axis"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalPowerAtlasAxes : List PowerAtlasAxis
  canonicalPowerAtlasAxes =
    racePowerAxis
    ∷ classPowerAxis
    ∷ genderPowerAxis
    ∷ sexualityPowerAxis
    ∷ disabilityPowerAxis
    ∷ neurotypePowerAxis
    ∷ religionPowerAxis
    ∷ colonialityPowerAxis
    ∷ lawPowerAxis
    ∷ landPowerAxis
    ∷ familyPowerAxis
    ∷ institutionPowerAxis
    ∷ []

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  data CrenshawTheoremKind : Set where
    trinityIntersectionalDeconstructionKind :
      CrenshawTheoremKind

    intersectionalTriTruthKind :
      CrenshawTheoremKind

    singleAxisProjectionLossKind :
      CrenshawTheoremKind

    primeFibreIntersectionalityKind :
      CrenshawTheoremKind

    padicSharedRootNotReductionKind :
      CrenshawTheoremKind

    stableNineNotJusticeKind :
      CrenshawTheoremKind

    hypervoxelLocalRepairKind :
      CrenshawTheoremKind

    hyperfabricNoErasureGluingKind :
      CrenshawTheoremKind

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  crenshawTheoremKindName : CrenshawTheoremKind → String
  crenshawTheoremKindName trinityIntersectionalDeconstructionKind =
    "trinity-intersectional-deconstruction"
  crenshawTheoremKindName intersectionalTriTruthKind =
    "intersectional-tri-truth"
  crenshawTheoremKindName singleAxisProjectionLossKind =
    "single-axis-projection-loss"
  crenshawTheoremKindName primeFibreIntersectionalityKind =
    "prime-fibre-intersectionality"
  crenshawTheoremKindName padicSharedRootNotReductionKind =
    "p-adic-shared-root-not-reduction"
  crenshawTheoremKindName stableNineNotJusticeKind =
    "stable-nine-not-justice"
  crenshawTheoremKindName hypervoxelLocalRepairKind =
    "hypervoxel-local-repair"
  crenshawTheoremKindName hyperfabricNoErasureGluingKind =
    "hyperfabric-no-erasure-gluing"

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  data ProjectionForm : Set where
    axisPreservingProductProjection :
      ProjectionForm

    singleAxisCollapseProjection :
      ProjectionForm

    abstractHumanityProjection :
      ProjectionForm

    abstractHumanityGluingProjection :
      ProjectionForm

    neutralTriadProjection :
      ProjectionForm

    stableNineJusticePromotionProjection :
      ProjectionForm

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  ProjectionAdmissible : ProjectionForm → Set
  ProjectionAdmissible axisPreservingProductProjection = ⊤
  ProjectionAdmissible singleAxisCollapseProjection = Never
  ProjectionAdmissible abstractHumanityProjection = Never
  ProjectionAdmissible abstractHumanityGluingProjection = Never
  ProjectionAdmissible neutralTriadProjection = Never
  ProjectionAdmissible stableNineJusticePromotionProjection = Never

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  singleAxisCollapseProjectionRejected :
    ProjectionAdmissible singleAxisCollapseProjection →
    Never
  singleAxisCollapseProjectionRejected ()

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  abstractHumanityProjectionRejected :
    ProjectionAdmissible abstractHumanityProjection →
    Never
  abstractHumanityProjectionRejected ()

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  abstractHumanityGluingProjectionRejected :
    ProjectionAdmissible abstractHumanityGluingProjection →
    Never
  abstractHumanityGluingProjectionRejected ()

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  neutralTriadProjectionRejected :
    ProjectionAdmissible neutralTriadProjection →
    Never
  neutralTriadProjectionRejected ()

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  stableNineJusticePromotionProjectionRejected :
    ProjectionAdmissible stableNineJusticePromotionProjection →
    Never
  stableNineJusticePromotionProjectionRejected ()

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  record AxisLoadedTriadRoleRow : Set where
    constructor mkAxisLoadedTriadRoleRow
    field
      rowLabel :
        String

      rowRole :
        CulturalTriadRole

      rowRoleName :
        String

      rowPowerAxes :
        List PowerAtlasAxis

      rowPowerAxesAreCanonical :
        rowPowerAxes ≡ canonicalPowerAtlasAxes

      rowTriadNotNeutral :
        Bool

      rowTriadNotNeutralIsTrue :
        rowTriadNotNeutral ≡ true

      rowCandidateOnly :
        Bool

      rowCandidateOnlyIsTrue :
        rowCandidateOnly ≡ true

      rowNoAuthorityPromotion :
        Bool

      rowNoAuthorityPromotionIsTrue :
        rowNoAuthorityPromotion ≡ true

      rowReading :
        String

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  open AxisLoadedTriadRoleRow public

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  mkAxisLoadedTriadRoleRowCanonical :
    String →
    CulturalTriadRole →
    String →
    String →
    AxisLoadedTriadRoleRow
  mkAxisLoadedTriadRoleRowCanonical label role roleReading reading =
    mkAxisLoadedTriadRoleRow
      label
      role
      roleReading
      canonicalPowerAtlasAxes
      refl
      true
      refl
      true
      refl
      true
      refl
      reading

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalOriginAuthorityTriadRoleRow : AxisLoadedTriadRoleRow
  canonicalOriginAuthorityTriadRoleRow =
    mkAxisLoadedTriadRoleRowCanonical
      "origin-authority-axis-loaded-triad-role-row"
      originAuthorityRole
      "origin authority role"
      "The origin term of a cultural triad is axis-loaded by authority, law, lineage, family, property, and institution."

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalEmbodiedSubjectTriadRoleRow : AxisLoadedTriadRoleRow
  canonicalEmbodiedSubjectTriadRoleRow =
    mkAxisLoadedTriadRoleRowCanonical
      "embodied-subject-axis-loaded-triad-role-row"
      embodiedSubjectRole
      "embodied subject role"
      "The embodied subject term is not neutral: body, gender, race, class, disability, neurotype, and coloniality stay explicit."

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalRelationalMediatorTriadRoleRow : AxisLoadedTriadRoleRow
  canonicalRelationalMediatorTriadRoleRow =
    mkAxisLoadedTriadRoleRowCanonical
      "relational-mediator-axis-loaded-triad-role-row"
      relationalMediatorRole
      "relational mediator role"
      "The mediator term is not empty relation: conscience, church, law, family, institution, and norm transmission remain auditable."

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalAxisLoadedTriadRoleRows : List AxisLoadedTriadRoleRow
  canonicalAxisLoadedTriadRoleRows =
    canonicalOriginAuthorityTriadRoleRow
    ∷ canonicalEmbodiedSubjectTriadRoleRow
    ∷ canonicalRelationalMediatorTriadRoleRow
    ∷ []

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  record CrenshawDeconstructionTheoremRow : Set where
    constructor mkCrenshawDeconstructionTheoremRow
    field
      rowLabel :
        String

      rowTheoremKind :
        CrenshawTheoremKind

      rowTheoremName :
        String

      rowProjectionForm :
        ProjectionForm

      rowProjectionAdmissible :
        ProjectionAdmissible rowProjectionForm

      rowAxisBundle :
        List PowerAtlasAxis

      rowAxisBundleIsCanonical :
        rowAxisBundle ≡ canonicalPowerAtlasAxes

      rowCandidateOnly :
        Bool

      rowCandidateOnlyIsTrue :
        rowCandidateOnly ≡ true

      rowIntersectionPreserved :
        Bool

      rowIntersectionPreservedIsTrue :
        rowIntersectionPreserved ≡ true

      rowNoSingleAxisReduction :
        Bool

      rowNoSingleAxisReductionIsTrue :
        rowNoSingleAxisReduction ≡ true

      rowNoStableSystemJusticePromotion :
        Bool

      rowNoStableSystemJusticePromotionIsTrue :
        rowNoStableSystemJusticePromotion ≡ true

      rowReading :
        String

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  open CrenshawDeconstructionTheoremRow public

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  mkCrenshawTheoremCandidateRow :
    String →
    CrenshawTheoremKind →
    String →
    String →
    CrenshawDeconstructionTheoremRow
  mkCrenshawTheoremCandidateRow label theoremKind theoremName reading =
    mkCrenshawDeconstructionTheoremRow
      label
      theoremKind
      theoremName
      axisPreservingProductProjection
      tt
      canonicalPowerAtlasAxes
      refl
      true
      refl
      true
      refl
      true
      refl
      true
      refl
      reading

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalTrinityIntersectionalDeconstructionRow :
    CrenshawDeconstructionTheoremRow
  canonicalTrinityIntersectionalDeconstructionRow =
    mkCrenshawTheoremCandidateRow
      "trinity-intersectional-deconstruction-row"
      trinityIntersectionalDeconstructionKind
      "TrinityIntersectionalDeconstruction"
      "A triadic relation may carry unity, subject, other, and relation only inside an explicit stratified power atlas."

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalIntersectionalTriTruthRow :
    CrenshawDeconstructionTheoremRow
  canonicalIntersectionalTriTruthRow =
    mkCrenshawTheoremCandidateRow
      "intersectional-tri-truth-row"
      intersectionalTriTruthKind
      "IntersectionalTriTruth"
      "Every trit and tri-truth surface declares its axis context; axis-free trit promotion is rejected."

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalSingleAxisProjectionLossRow :
    CrenshawDeconstructionTheoremRow
  canonicalSingleAxisProjectionLossRow =
    mkCrenshawTheoremCandidateRow
      "single-axis-projection-loss-row"
      singleAxisProjectionLossKind
      "SingleAxisProjectionLoss"
      "Projecting an intersection to one axis loses the intersectional harm and cannot serve as a valid glue."

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalPrimeFibreIntersectionalityRow :
    CrenshawDeconstructionTheoremRow
  canonicalPrimeFibreIntersectionalityRow =
    mkCrenshawTheoremCandidateRow
      "prime-fibre-intersectionality-row"
      primeFibreIntersectionalityKind
      "PrimeFibreIntersectionality"
      "Prime-product addresses preserve axis factors; a product fibre is not reducible to either single prime fibre."

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalPadicSharedRootNotReductionRow :
    CrenshawDeconstructionTheoremRow
  canonicalPadicSharedRootNotReductionRow =
    mkCrenshawTheoremCandidateRow
      "p-adic-shared-root-not-reduction-row"
      padicSharedRootNotReductionKind
      "PAdicSharedRootNotReduction"
      "P-adic shared-root closeness is candidate structural affinity, not identity, diagnosis, or legal proof."

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalStableNineNotJusticeRow :
    CrenshawDeconstructionTheoremRow
  canonicalStableNineNotJusticeRow =
    mkCrenshawTheoremCandidateRow
      "stable-nine-not-justice-row"
      stableNineNotJusticeKind
      "StableNineNotJustice"
      "A stable stage-nine attractor can be hegemony; justice requires intersectional, power, material, care, and anti-domination gates."

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalHypervoxelLocalRepairRow :
    CrenshawDeconstructionTheoremRow
  canonicalHypervoxelLocalRepairRow =
    mkCrenshawTheoremCandidateRow
      "hypervoxel-local-repair-row"
      hypervoxelLocalRepairKind
      "HypervoxelLocalRepair"
      "A plus-one handle is repair-candidate only when it is local to subject, body, time, place, relation, institution, and axis bundle."

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalHyperfabricNoErasureGluingRow :
    CrenshawDeconstructionTheoremRow
  canonicalHyperfabricNoErasureGluingRow =
    mkCrenshawTheoremCandidateRow
      "hyperfabric-no-erasure-gluing-row"
      hyperfabricNoErasureGluingKind
      "HyperfabricNoErasureGluing"
      "Global gluing is invalid when it preserves categories while erasing their intersections."

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalCrenshawDeconstructionTheoremRows :
    List CrenshawDeconstructionTheoremRow
  canonicalCrenshawDeconstructionTheoremRows =
    canonicalTrinityIntersectionalDeconstructionRow
    ∷ canonicalIntersectionalTriTruthRow
    ∷ canonicalSingleAxisProjectionLossRow
    ∷ canonicalPrimeFibreIntersectionalityRow
    ∷ canonicalPadicSharedRootNotReductionRow
    ∷ canonicalStableNineNotJusticeRow
    ∷ canonicalHypervoxelLocalRepairRow
    ∷ canonicalHyperfabricNoErasureGluingRow
    ∷ []

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  record HyperfabricIntersectionalBodyMemoryBridge : Set where
    constructor mkHyperfabricIntersectionalBodyMemoryBridge
    field
      bridgeLabel :
        String

      interpretiveRoute :
        InterpretiveRoute

      interpretiveRouteIsCandidate :
        interpretiveRoute ≡ candidateInterpretiveRoute

      routeAdmissible :
        AdmissibleInterpretiveRoute interpretiveRoute

      triadicRelationSurfaceRows :
        List TriadicRelationRow

      triadicRelationSurfaceRowsAreCanonical :
        triadicRelationSurfaceRows ≡ canonicalTriadicRelationRows

      stageSpiralHyperfabricRows :
        List StageSpiralHyperfabricRow

      stageSpiralHyperfabricRowsAreCanonical :
        stageSpiralHyperfabricRows ≡ canonicalStageSpiralHyperfabricRows

      intersectionalAxisAuditRows :
        List IntersectionalAxisAuditRow

      intersectionalAxisAuditRowsAreCanonical :
        intersectionalAxisAuditRows ≡ canonicalIntersectionalAxisAuditRows

      axisLoadedTriadRoleRows :
        List AxisLoadedTriadRoleRow

      axisLoadedTriadRoleRowsAreCanonical :
        axisLoadedTriadRoleRows ≡ canonicalAxisLoadedTriadRoleRows

      crenshawDeconstructionTheoremRows :
        List CrenshawDeconstructionTheoremRow

      crenshawDeconstructionTheoremRowsAreCanonical :
        crenshawDeconstructionTheoremRows
        ≡
        canonicalCrenshawDeconstructionTheoremRows

      bodyMemoryCarrier :
        String

      bodyMemoryCarrierIsCandidate :
        Bool

      bodyMemoryCarrierIsCandidateIsTrue :
        bodyMemoryCarrierIsCandidate ≡ true

      noNeutralTriadUniversalism :
        Bool

      noNeutralTriadUniversalismIsFalse :
        noNeutralTriadUniversalism ≡ false

      noMonocultureCompression :
        Bool

      noMonocultureCompressionIsFalse :
        noMonocultureCompression ≡ false

      noSocialTruthProof :
        Bool

      noSocialTruthProofIsFalse :
        noSocialTruthProof ≡ false

      noClinicalAuthority :
        Bool

      noClinicalAuthorityIsFalse :
        noClinicalAuthority ≡ false

      noLegalAuthority :
        Bool

      noLegalAuthorityIsFalse :
        noLegalAuthority ≡ false

      noEducationalAuthority :
        Bool

      noEducationalAuthorityIsFalse :
        noEducationalAuthority ≡ false

      noAbstractHumanityGluing :
        Bool

      noAbstractHumanityGluingIsFalse :
        noAbstractHumanityGluing ≡ false

      noStableNineJusticePromotion :
        Bool

      noStableNineJusticePromotionIsFalse :
        noStableNineJusticePromotion ≡ false

      bridgeReading :
        String

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  open HyperfabricIntersectionalBodyMemoryBridge public

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  record HyperfabricIntersectionalBodyMemoryCertificate
      (bridge : HyperfabricIntersectionalBodyMemoryBridge) : Set where
    field
      certificateRoute :
        InterpretiveRoute

      certificateRouteMatches :
        certificateRoute ≡
        HyperfabricIntersectionalBodyMemoryBridge.interpretiveRoute bridge

      certificateIsCandidateRoute :
        certificateRoute ≡ candidateInterpretiveRoute

      certificateRouteAdmissible :
        AdmissibleInterpretiveRoute certificateRoute

      certificateTriadicRows :
        List TriadicRelationRow

      certificateTriadicRowsMatch :
        certificateTriadicRows ≡
        HyperfabricIntersectionalBodyMemoryBridge.triadicRelationSurfaceRows
          bridge

      certificateStageRows :
        List StageSpiralHyperfabricRow

      certificateStageRowsMatch :
        certificateStageRows ≡
        HyperfabricIntersectionalBodyMemoryBridge.stageSpiralHyperfabricRows
          bridge

      certificateAxisRows :
        List IntersectionalAxisAuditRow

      certificateAxisRowsMatch :
        certificateAxisRows ≡
        HyperfabricIntersectionalBodyMemoryBridge.intersectionalAxisAuditRows
          bridge

      certificateAxisLoadedTriadRoleRows :
        List AxisLoadedTriadRoleRow

      certificateAxisLoadedTriadRoleRowsMatch :
        certificateAxisLoadedTriadRoleRows ≡
        HyperfabricIntersectionalBodyMemoryBridge.axisLoadedTriadRoleRows
          bridge

      certificateCrenshawRows :
        List CrenshawDeconstructionTheoremRow

      certificateCrenshawRowsMatch :
        certificateCrenshawRows ≡
        HyperfabricIntersectionalBodyMemoryBridge.crenshawDeconstructionTheoremRows
          bridge

      certificateBodyMemoryCarrier :
        String

      certificateBodyMemoryCarrierIsCandidate :
        Bool

      certificateBodyMemoryCarrierIsCandidateIsTrue :
        certificateBodyMemoryCarrierIsCandidate ≡ true

      certificateNoSocialTruthProof :
        Bool

      certificateNoSocialTruthProofIsFalse :
        certificateNoSocialTruthProof ≡ false

      certificateNoClinicalAuthority :
        Bool

      certificateNoClinicalAuthorityIsFalse :
        certificateNoClinicalAuthority ≡ false

      certificateNoLegalAuthority :
        Bool

      certificateNoLegalAuthorityIsFalse :
        certificateNoLegalAuthority ≡ false

      certificateNoEducationalAuthority :
        Bool

      certificateNoEducationalAuthorityIsFalse :
        certificateNoEducationalAuthority ≡ false

      certificateNoAbstractHumanityGluing :
        Bool

      certificateNoAbstractHumanityGluingIsFalse :
        certificateNoAbstractHumanityGluing ≡ false

      certificateNoStableNineJusticePromotion :
        Bool

      certificateNoStableNineJusticePromotionIsFalse :
        certificateNoStableNineJusticePromotion ≡ false

      certificateReading :
        String

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  open HyperfabricIntersectionalBodyMemoryCertificate public

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalHyperfabricIntersectionalBodyMemoryBridge :
    HyperfabricIntersectionalBodyMemoryBridge
  canonicalHyperfabricIntersectionalBodyMemoryBridge =
    mkHyperfabricIntersectionalBodyMemoryBridge
      "hyperfabric-intersectional-body-memory-bridge"
      candidateInterpretiveRoute
      refl
      candidateInterpretiveRouteAdmissible
      canonicalTriadicRelationRows
      refl
      canonicalStageSpiralHyperfabricRows
      refl
      canonicalIntersectionalAxisAuditRows
      refl
      canonicalAxisLoadedTriadRoleRows
      refl
      canonicalCrenshawDeconstructionTheoremRows
      refl
      "body-memory"
      true
      refl
      false
      refl
      false
      refl
      false
      refl
      false
      refl
      false
      refl
      false
      refl
      false
      refl
      false
      refl
      "Hyperfabric, dialectic, spiral, trit, 369, stage, prime, and p-adic vocabulary are retained as candidate interpretive carriers for body-memory only; the bridge does not prove social truth, does not promote clinical, legal, or educational authority, and does not collapse distinct layers into monoculture compression."

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalHyperfabricIntersectionalBodyMemoryCertificate :
    HyperfabricIntersectionalBodyMemoryCertificate
      canonicalHyperfabricIntersectionalBodyMemoryBridge
  canonicalHyperfabricIntersectionalBodyMemoryCertificate =
    record
      { certificateRoute = candidateInterpretiveRoute
      ; certificateRouteMatches = refl
      ; certificateIsCandidateRoute = refl
      ; certificateRouteAdmissible = candidateInterpretiveRouteAdmissible
      ; certificateTriadicRows = canonicalTriadicRelationRows
      ; certificateTriadicRowsMatch = refl
      ; certificateStageRows = canonicalStageSpiralHyperfabricRows
      ; certificateStageRowsMatch = refl
      ; certificateAxisRows = canonicalIntersectionalAxisAuditRows
      ; certificateAxisRowsMatch = refl
      ; certificateAxisLoadedTriadRoleRows =
          canonicalAxisLoadedTriadRoleRows
      ; certificateAxisLoadedTriadRoleRowsMatch = refl
      ; certificateCrenshawRows =
          canonicalCrenshawDeconstructionTheoremRows
      ; certificateCrenshawRowsMatch = refl
      ; certificateBodyMemoryCarrier = "body-memory"
      ; certificateBodyMemoryCarrierIsCandidate = true
      ; certificateBodyMemoryCarrierIsCandidateIsTrue = refl
      ; certificateNoSocialTruthProof = false
      ; certificateNoSocialTruthProofIsFalse = refl
      ; certificateNoClinicalAuthority = false
      ; certificateNoClinicalAuthorityIsFalse = refl
      ; certificateNoLegalAuthority = false
      ; certificateNoLegalAuthorityIsFalse = refl
      ; certificateNoEducationalAuthority = false
      ; certificateNoEducationalAuthorityIsFalse = refl
      ; certificateNoAbstractHumanityGluing = false
      ; certificateNoAbstractHumanityGluingIsFalse = refl
      ; certificateNoStableNineJusticePromotion = false
      ; certificateNoStableNineJusticePromotionIsFalse = refl
      ; certificateReading =
          "Candidate interpretive body-memory carrier only: no neutral triad universalism, no monoculture compression, no proof of social truth, and no clinical, legal, educational, abstract-humanity, or stable-nine justice promotion."
      }

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalInterpretiveRouteIsCandidate :
    interpretiveRoute canonicalHyperfabricIntersectionalBodyMemoryBridge ≡
    candidateInterpretiveRoute
  canonicalInterpretiveRouteIsCandidate =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalInterpretiveRouteAdmissible :
    AdmissibleInterpretiveRoute
      (interpretiveRoute canonicalHyperfabricIntersectionalBodyMemoryBridge)
  canonicalInterpretiveRouteAdmissible =
    candidateInterpretiveRouteAdmissible

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalNoNeutralTriadUniversalismIsFalse :
    noNeutralTriadUniversalism
      canonicalHyperfabricIntersectionalBodyMemoryBridge
    ≡
    false
  canonicalNoNeutralTriadUniversalismIsFalse =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalNoMonocultureCompressionIsFalse :
    noMonocultureCompression
      canonicalHyperfabricIntersectionalBodyMemoryBridge
    ≡
    false
  canonicalNoMonocultureCompressionIsFalse =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalNoSocialTruthProofIsFalse :
    noSocialTruthProof
      canonicalHyperfabricIntersectionalBodyMemoryBridge
    ≡
    false
  canonicalNoSocialTruthProofIsFalse =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalNoClinicalAuthorityIsFalse :
    noClinicalAuthority
      canonicalHyperfabricIntersectionalBodyMemoryBridge
    ≡
    false
  canonicalNoClinicalAuthorityIsFalse =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalNoLegalAuthorityIsFalse :
    noLegalAuthority
      canonicalHyperfabricIntersectionalBodyMemoryBridge
    ≡
    false
  canonicalNoLegalAuthorityIsFalse =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalNoEducationalAuthorityIsFalse :
    noEducationalAuthority
      canonicalHyperfabricIntersectionalBodyMemoryBridge
    ≡
    false
  canonicalNoEducationalAuthorityIsFalse =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalNoAbstractHumanityGluingIsFalse :
    noAbstractHumanityGluing
      canonicalHyperfabricIntersectionalBodyMemoryBridge
    ≡
    false
  canonicalNoAbstractHumanityGluingIsFalse =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalNoStableNineJusticePromotionIsFalse :
    noStableNineJusticePromotion
      canonicalHyperfabricIntersectionalBodyMemoryBridge
    ≡
    false
  canonicalNoStableNineJusticePromotionIsFalse =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalCertificateRouteMatches :
    HyperfabricIntersectionalBodyMemoryCertificate.certificateRoute
      canonicalHyperfabricIntersectionalBodyMemoryCertificate
    ≡
    candidateInterpretiveRoute
  canonicalCertificateRouteMatches =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalCertificateRouteAdmissible :
    HyperfabricIntersectionalBodyMemoryCertificate.certificateRouteAdmissible
      canonicalHyperfabricIntersectionalBodyMemoryCertificate
    ≡
    tt
  canonicalCertificateRouteAdmissible =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalCertificateBodyMemoryCarrierIsCandidate :
    HyperfabricIntersectionalBodyMemoryCertificate.certificateBodyMemoryCarrierIsCandidate
      canonicalHyperfabricIntersectionalBodyMemoryCertificate
    ≡
    true
  canonicalCertificateBodyMemoryCarrierIsCandidate =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalCertificateNoSocialTruthProofIsFalse :
    HyperfabricIntersectionalBodyMemoryCertificate.certificateNoSocialTruthProof
      canonicalHyperfabricIntersectionalBodyMemoryCertificate
    ≡
    false
  canonicalCertificateNoSocialTruthProofIsFalse =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalCertificateNoClinicalAuthorityIsFalse :
    HyperfabricIntersectionalBodyMemoryCertificate.certificateNoClinicalAuthority
      canonicalHyperfabricIntersectionalBodyMemoryCertificate
    ≡
    false
  canonicalCertificateNoClinicalAuthorityIsFalse =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalCertificateNoLegalAuthorityIsFalse :
    HyperfabricIntersectionalBodyMemoryCertificate.certificateNoLegalAuthority
      canonicalHyperfabricIntersectionalBodyMemoryCertificate
    ≡
    false
  canonicalCertificateNoLegalAuthorityIsFalse =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalCertificateNoEducationalAuthorityIsFalse :
    HyperfabricIntersectionalBodyMemoryCertificate.certificateNoEducationalAuthority
      canonicalHyperfabricIntersectionalBodyMemoryCertificate
    ≡
    false
  canonicalCertificateNoEducationalAuthorityIsFalse =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalCertificateNoAbstractHumanityGluingIsFalse :
    HyperfabricIntersectionalBodyMemoryCertificate.certificateNoAbstractHumanityGluing
      canonicalHyperfabricIntersectionalBodyMemoryCertificate
    ≡
    false
  canonicalCertificateNoAbstractHumanityGluingIsFalse =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalCertificateNoStableNineJusticePromotionIsFalse :
    HyperfabricIntersectionalBodyMemoryCertificate.certificateNoStableNineJusticePromotion
      canonicalHyperfabricIntersectionalBodyMemoryCertificate
    ≡
    false
  canonicalCertificateNoStableNineJusticePromotionIsFalse =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalAxisLoadedTriadRoleRowsAreCanonical :
    axisLoadedTriadRoleRows
      canonicalHyperfabricIntersectionalBodyMemoryBridge
    ≡
    canonicalAxisLoadedTriadRoleRows
  canonicalAxisLoadedTriadRoleRowsAreCanonical =
    refl

agda_module DASHI.Biology.HyperfabricIntersectionalBodyMemoryBridge where
  open import Agda.Builtin.Bool
  open import Agda.Builtin.Equality
  open import Agda.Builtin.List
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  canonicalCrenshawDeconstructionTheoremRowsAreCanonical :
    crenshawDeconstructionTheoremRows
      canonicalHyperfabricIntersectionalBodyMemoryBridge
    ≡
    canonicalCrenshawDeconstructionTheoremRows
  canonicalCrenshawDeconstructionTheoremRowsAreCanonical =
    refl

