/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Agda.Syntax

/-!
# `DASHI.Physics.Closure.Validation.ObservableCollapse`, transliterated

Generated by `tools/agda2lean.py` from the ingested upstream source
`upstream/dashi_agda/agent/evidence-polarity-cross-pollination/DASHI/Physics/Closure/Validation/ObservableCollapse.agda`.
Do not edit by hand: re-run the translator instead.
-/

open Agda

agda_module DASHI.Physics.Closure.Validation.ObservableCollapse where

  open import Agda.Primitive

agda_module DASHI.Physics.Closure.Validation.ObservableCollapse where
  open import Agda.Primitive
  open import Agda.Builtin.String

agda_module DASHI.Physics.Closure.Validation.ObservableCollapse where
  open import Agda.Primitive
  open import Agda.Builtin.String
  open import Agda.Builtin.Equality

agda_module DASHI.Physics.Closure.Validation.ObservableCollapse where
  open import Agda.Primitive
  open import Agda.Builtin.String
  open import Agda.Builtin.Equality

  data ObservableCollapseVerdict : Set where
    collapseEstablished : ObservableCollapseVerdict

agda_module DASHI.Physics.Closure.Validation.ObservableCollapse where
  open import Agda.Primitive
  open import Agda.Builtin.String
  open import Agda.Builtin.Equality

  record ObservableCollapseHarness : Setω where
    field
      label : String
      Obs : Set
      obs0 : Obs
      obsT : Obs → Obs
      obsFixed : obsT obs0 ≡ obs0
      obsUnique : ∀ o , obsT o ≡ o → o ≡ obs0

agda_module DASHI.Physics.Closure.Validation.ObservableCollapse where
  open import Agda.Primitive
  open import Agda.Builtin.String
  open import Agda.Builtin.Equality

  record ObservableCollapseFacts (harness : ObservableCollapseHarness) : Setω where
    field
      fixedWitness :
        ObservableCollapseHarness.obsT harness
          (ObservableCollapseHarness.obs0 harness)
        ≡ ObservableCollapseHarness.obs0 harness
      uniquenessWitness :
        ∀ o ,
        ObservableCollapseHarness.obsT harness o ≡ o →
        o ≡ ObservableCollapseHarness.obs0 harness

agda_module DASHI.Physics.Closure.Validation.ObservableCollapse where
  open import Agda.Primitive
  open import Agda.Builtin.String
  open import Agda.Builtin.Equality

  computeFacts : (harness : ObservableCollapseHarness) → ObservableCollapseFacts harness
  computeFacts harness =
    record
      { fixedWitness = ObservableCollapseHarness.obsFixed harness
      ; uniquenessWitness = ObservableCollapseHarness.obsUnique harness
      }

agda_module DASHI.Physics.Closure.Validation.ObservableCollapse where
  open import Agda.Primitive
  open import Agda.Builtin.String
  open import Agda.Builtin.Equality

  classify : ∀ {harness} , ObservableCollapseFacts harness → ObservableCollapseVerdict
  classify _ = collapseEstablished

