/- Attribution: JMD (github.com/meta-introspector) -/
import Mathlib

/-!
# `A2L-E-PROOF-RELEVANCE`: why a `Σ` in `Set` may not be mirrored by an `∃` in `Prop`

The `agda2lean` mirror registry carries one fixture row that is expected to
*block* rather than pass.  The Agda structure `ConstraintClosure.Closure` has a
`commute` field whose type is a proof-relevant `Σ` living in `Set`; the
historical Lean mirror gives the corresponding field the type `∃ …`, living in
`Prop`.  The registry records this as `expected = "blocked"` with the code
`A2L-E-PROOF-RELEVANCE`, on the ground that a faithful comparison must refuse
the substitution.

This module is that refusal, proved rather than asserted.  It is stated for an
arbitrary family, so it is a statement about the translation rule and not about
one fixture.

* `forget` is the substitution the mirror performs: it always exists, so the
  weakening is *type-correct*, which is why the failure has to be diagnosed
  rather than caught by the elaborator.
* `injective_forget_iff_subsingleton` is the exact criterion: the weakening is
  faithful — that is, `forget` is injective — **iff** the `Σ`-type was a
  subsingleton all along.  As soon as two distinct witnesses exist, the mirror
  identifies declarations the source keeps apart.
* `no_witness_extraction` shows there is no way back at all inside the theory:
  no function on `∃ n : ℕ, True` can return the witness it was built from,
  because proof irrelevance has already identified all of them.
* `two_sigma_elements_one_exists_proof` exhibits the collapse concretely.
* Finally, the reconstruction that *is* available, `Classical.choice`, is
  exhibited together with a machine-checked record of the axiom it costs —
  which is what the fixture policy `allowed-lean-axioms = []` forbids.
-/

/-! ### Provenance (generated by `tools/provenance.py`)

Source mix of this module's 11 declarations: 0 traced to the DASHI Agda
bridge (`chboishabba/dashi_agda` PR #555 / #581 / #582), 0 rendering the Wikidata
data model, 11 original to this port.  The bridge-traced declarations are
marked with `-- @source` below.  Full ledger: `docs/status/PROVENANCE.md`.
-/

namespace Mirror.ProofRelevance

universe u v

variable {α : Type u} {P : α → Prop}

/-- The substitution the Lean mirror performs: a proof-relevant `Σ` in `Type`
is replaced by an `∃` in `Prop`. -/
def forget (p : Σ a : α, PLift (P a)) : ∃ a : α, P a := ⟨p.1, p.2.down⟩

/-- **The blocking criterion.**  Weakening `Σ` to `∃` is faithful exactly when
there was nothing to forget. -/
theorem injective_forget_iff_subsingleton :
    Function.Injective (forget (α := α) (P := P)) ↔ Subsingleton (Σ a : α, PLift (P a)) := by
  constructor
  · intro h
    exact ⟨fun p q => h (Subsingleton.elim _ _)⟩
  · intro h _ _ _
    exact Subsingleton.elim _ _

/-- Two distinct `Σ`-elements with one and the same `∃`-proof: the mirror maps
them to the same declaration. -/
theorem two_sigma_elements_one_exists_proof :
    ∃ p q : Σ _ : ℕ, PLift True, p ≠ q ∧ forget p = forget q := by
  refine ⟨⟨0, ⟨trivial⟩⟩, ⟨1, ⟨trivial⟩⟩, ?_, rfl⟩
  intro h
  exact absurd (congrArg Sigma.fst h) (by norm_num)

/-- Consequently the weakening is not faithful for that family. -/
theorem forget_not_injective :
    ¬ Function.Injective (forget (α := ℕ) (P := fun _ => True)) := by
  obtain ⟨p, q, hne, heq⟩ := two_sigma_elements_one_exists_proof
  exact fun h => hne (h heq)

/-- **No witness extraction.**  Nothing definable on the `Prop`-valued
existential recovers the witness it was built from: proof irrelevance has
already identified every proof of it. -/
theorem no_witness_extraction :
    ¬ ∃ g : (∃ _ : ℕ, True) → ℕ, ∀ n : ℕ, g ⟨n, trivial⟩ = n := by
  rintro ⟨g, hg⟩
  have h0 : g ⟨0, trivial⟩ = 0 := hg 0
  have h1 : g ⟨1, trivial⟩ = 1 := hg 1
  have : (⟨0, trivial⟩ : ∃ _ : ℕ, True) = ⟨1, trivial⟩ := rfl
  rw [this, h1] at h0
  exact absurd h0 (by norm_num)

/-! ## The closure shape of the fixture

A structure whose one field is proof-relevant, and the mirror that weakens it.
-/

/-- A closure operation that *chooses* a witness: the Agda shape. -/
structure ClosureSigma (α : Type u) (R : α → α → α → Prop) : Type u where
  commute : ∀ a b : α, Σ c : α, PLift (R a b c)

/-- A closure operation that only *asserts* a witness: the Lean-mirror shape. -/
structure ClosureExists (α : Type u) (R : α → α → α → Prop) : Prop where
  commute : ∀ a b : α, ∃ c : α, R a b c

/-- The mirror's forgetful map on the closure structures. -/
def ClosureSigma.weaken {α : Type u} {R : α → α → α → Prop}
    (c : ClosureSigma α R) : ClosureExists α R :=
  ⟨fun a b => ⟨(c.commute a b).1, (c.commute a b).2.down⟩⟩

/-- The relation "anything commutes to anything", which two different closure
operations satisfy. -/
private def triv : ℕ → ℕ → ℕ → Prop := fun _ _ _ => True

/-- **The fixture row, proved.**  Two genuinely different closure operations are
mirrored by the same `Prop`, so the mirror does not classify the source. -/
theorem weaken_not_injective :
    ∃ c₁ c₂ : ClosureSigma ℕ triv,
      (∀ a b, (c₁.commute a b).1 ≠ (c₂.commute a b).1) ∧ c₁.weaken = c₂.weaken := by
  refine ⟨⟨fun _ _ => ⟨0, ⟨trivial⟩⟩⟩, ⟨fun _ _ => ⟨1, ⟨trivial⟩⟩⟩, ?_, ?_⟩
  · intro a b
    norm_num
  · rfl

/-! ## What the reconstruction costs

Going the other way is possible in Lean, but only through choice — the axiom the
fixture policy `allowed-lean-axioms = []` refuses.
-/

/-- The classical reconstruction of a choice function from an existential. -/
noncomputable def reconstruct {α : Type u} {R : α → α → α → Prop}
    (c : ClosureExists α R) : ClosureSigma α R :=
  ⟨fun a b => ⟨(c.commute a b).choose, ⟨(c.commute a b).choose_spec⟩⟩⟩

/-- info: 'Mirror.ProofRelevance.ClosureSigma.weaken' does not depend on any axioms -/
#guard_msgs in
#print axioms ClosureSigma.weaken

/-- info: 'Mirror.ProofRelevance.reconstruct' depends on axioms: [Classical.choice] -/
#guard_msgs in
#print axioms reconstruct

end Mirror.ProofRelevance
