import Synthesis.RiemannQuarticProducerRoleCertificate

#print axioms Synthesis.RiemannQuarticProducerRoleCertificate.pole_coordinate_same_object
#print axioms Synthesis.RiemannQuarticProducerRoleCertificate.origin_coordinate_same_object
#print axioms Synthesis.RiemannQuarticProducerRoleCertificate.j_coordinate_same_object
#print axioms Synthesis.RiemannQuarticProducerRoleCertificate.target_coordinate_same_object
#print axioms Synthesis.RiemannQuarticProducerRoleCertificate.primitive_kernel_via_source_roles
#print axioms Synthesis.RiemannQuarticProducerRoleCertificate.depth_five_source_roles_exact
#print axioms Synthesis.RiemannQuarticProducerRoleCertificate.canonical_certificate_inhabited
