import Synthesis.LinearConsumerMatrixFamilyAction

/-!
# Krylov-specialized linear consumer action

A domain-neutral specialization of the matrix-family action to the recurrence
shape used by Block-Wiedemann/mksol-style evaluation.

Given a linear endomorphism `M` on the Krylov-block carrier and a seed block
`V`, define the layer family by

    K_i = M^i V.

Then coefficient evaluation is the linear map

    F |-> sum_i (M^i V) * F_i.

This file does not identify `M` with the synthetic `apply_B`, bind `V` to a
seeded runtime block, choose a CADO solution range, or claim production
RSA-260 semantics.  Those are same-object realization obligations.
-/

namespace Synthesis

open scoped BigOperators

universe uL uM uN

/-- The finite coefficient-family action generated by an abstract Krylov
endomorphism and seed block. -/
def krylovCoefficientFamilyAction
    {d : Nat} {l : Type uL} {m : Type uM} {n : Type uN}
    [Fintype m]
    (M : Module.End (ZMod 2) (Matrix l m (ZMod 2)))
    (V : Matrix l m (ZMod 2)) :
    (Fin d → Matrix m n (ZMod 2)) →ₗ[ZMod 2] Matrix l n (ZMod 2) :=
  matrixCoefficientFamilyAction (fun i : Fin d => (M ^ (i : Nat)) V)

@[simp]
theorem krylovCoefficientFamilyAction_apply
    {d : Nat} {l : Type uL} {m : Type uM} {n : Type uN}
    [Fintype m]
    (M : Module.End (ZMod 2) (Matrix l m (ZMod 2)))
    (V : Matrix l m (ZMod 2))
    (F : Fin d → Matrix m n (ZMod 2)) :
    krylovCoefficientFamilyAction M V F =
      ∑ i, ((M ^ (i : Nat)) V) * F i :=
  rfl

end Synthesis
