module DASHI.Culture.MissingDeceasedScientificWorkEverything where

-- Focused aggregate for attribution-safe scientific-work reconstruction,
-- source-exact citation, DOI/QID/Dewey snowball bindings, technical-intersection
-- proof search, independent common-selector/visibility analysis, selector-
-- discrimination search, higher-order capability synthesis, capability-indexed
-- selector salience, denominator-aware matched-control enrichment, competing-
-- hypothesis discrimination, critical-knowledge BIDI acquisition, viewpoint-
-- provenance testing, open-science/knowledge-release and externalisation-boundary
-- BIDI testing, science-to-capability-carrier reconstruction, application-
-- transformation modelling, event-time alignment, organisational/custody
-- confounders, capability resilience and reconstruction cost, science-driven
-- acquisition compilation, disruption-benefit evidence testing, actor
-- benefit/visibility/effect intersection, matched disruption-impact controls,
-- and the parallel roster role/event audit.
--
-- Acquisition is intentionally parallel across the retained cohort. Each person
-- keeps an independent unpaid frontier. External QID/Dewey coordinates are
-- traversal aids only; evidentiary authority remains with the cited primary or
-- bounded secondary source.

import DASHI.Core.ScientificWorkAttributionExact
import DASHI.Core.ScientificSourceCitationExact
import DASHI.Core.ScientificMechanismEvidenceBidiExact
import DASHI.Core.ScientificCapabilityCarrierBidiExact
import DASHI.Core.ApplicationTransformationCapabilityBidiExact
import DASHI.Core.DistributedApplicationSurfaceBidiExact
import DASHI.Core.EventTimeCapabilityAlignmentBidiExact
import DASHI.Core.CapabilityFragilityConfoundersBidiExact
import DASHI.Core.CapabilityResilienceBidiExact
import DASHI.Core.CapabilityReconstructionCostBidiExact
import DASHI.Core.TechnicalDependencyHypergraphExact
import DASHI.Core.CommonSelectorVisibilityHyperfabricExact
import DASHI.Core.SelectorDiscriminationSearchExact
import DASHI.Core.CapabilitySynthesisHypergraphExact
import DASHI.Core.CapabilityIndexedSelectorSalienceExact
import DASHI.Core.ReferencePopulationRosterEnrichmentExact
import DASHI.Core.DisruptionBenefitHypothesisExact
import DASHI.Core.ActorBenefitVisibilityDisruptionIntersectionExact
import DASHI.Core.CounterfactualDisruptionImpactExact
import DASHI.Core.CriticalKnowledgeConcentrationBidiExact
import DASHI.Core.ViewpointProvenanceBidiExact
import DASHI.Core.OpenScienceKnowledgeReleaseBidiExact
import DASHI.Core.TechnicalExternalisationDepthBidiExact
import DASHI.Core.ExternalisationBoundaryEnrichmentBidiExact
import DASHI.Physics.BoundaryScienceEverything
import DASHI.Culture.MissingDeceasedScientistWorkAttributionExact
import DASHI.Culture.MissingDeceasedScientificWorkCrossPollinationExact
import DASHI.Culture.MissingDeceasedScientificWorkSourceRegistryExact
import DASHI.Culture.MissingDeceasedScientificWorkSourceRegistryExtendedExact
import DASHI.Culture.MissingDeceasedScientificWorkSnowballAttributionBindingsExact
import DASHI.Culture.MissingDeceasedIbrahimAcquisitionTraversalExact
import DASHI.Culture.MissingDeceasedIbrahimInvestigativeParetoExact
import DASHI.Culture.MissingDeceasedIbrahimDeweyConvergenceExact
import DASHI.Culture.MissingDeceasedTechnicalDependencyHypergraphExact
import DASHI.Culture.MissingDeceasedTechnicalIntersectionAcquisitionExact
import DASHI.Culture.MissingDeceasedCommonSelectorVisibilityExact
import DASHI.Culture.MissingDeceasedSelectorAcquisitionExact
import DASHI.Culture.MissingDeceasedSelectorDiscriminationFrontierExact
import DASHI.Culture.MissingDeceasedCapabilitySynthesisExact
import DASHI.Culture.MissingDeceasedCapabilityIndexedSelectorSalienceExact
import DASHI.Culture.MissingDeceasedCapabilitySelectorAcquisitionExact
import DASHI.Culture.MissingDeceasedScientificCapabilityCarrierMatrixExact
import DASHI.Culture.MissingDeceasedScientificCapabilityPublicControlsExact
import DASHI.Culture.MissingDeceasedScienceDrivenAcquisitionExact
import DASHI.Culture.MissingDeceasedApplicationTransformationMatrixExact
import DASHI.Culture.AmyEskridgeApplicationTransformationExact
import DASHI.Culture.AmyEskridgeInstituteTeamSuccessionSurfaceExact
import DASHI.Culture.AmyEskridgePOAMSRegisteredSTIAcquisitionRouteExact
import DASHI.Culture.MissingDeceasedFullApplicationTransformationAtlasExact
import DASHI.Culture.MissingDeceasedFullApplicationAcquisitionExact
import DASHI.Culture.ChavezApplicationTransformationPossessionExact
import DASHI.Culture.LeBlancApplicationTransformationPossessionExact
import DASHI.Culture.RezaApplicationTransformationPossessionExact
import DASHI.Culture.RezaRoleSourceArchaeologyExact
import DASHI.Culture.MaiwaldActionSpectroscopyProjectSuccessionExact
import DASHI.Culture.MaiwaldManifestationAttributionArchaeologyExact
import DASHI.Culture.MaiwaldGovernmentRepositoryResourceLineageExact
import DASHI.Culture.McCaslandEventTimeApplicationTransformationExact
import DASHI.Culture.McCaslandOrganizationalTransitionSurfaceExact
import DASHI.Culture.McCaslandDBEAttributionArchaeologyExact
import DASHI.Culture.LoureiroEventAlternativeEvidenceExact
import DASHI.Culture.LoureiroStudentSuccessionArchaeologyExact
import DASHI.Culture.MissingDeceasedRosterRoleAndCommitteeWeldAuditExact
import DASHI.Culture.MissingDeceasedOverlookedDimensionMatrixExact
import DASHI.Culture.MissingDeceasedReconstructionCostMatrixExact
import DASHI.Culture.MissingDeceasedApplicationSuccessionFrontierExact
import DASHI.Culture.MissingDeceasedRosterEnrichmentDesignExact
import DASHI.Culture.MissingDeceasedHypothesisDiscriminatorMatrixExact
import DASHI.Culture.MissingDeceasedDisruptionBenefitEvidenceExact
import DASHI.Culture.MissingDeceasedDisruptionBenefitAcquisitionExact
import DASHI.Culture.MissingDeceasedActorIntersectionFrontierExact
import DASHI.Culture.MissingDeceasedCounterfactualDisruptionImpactExact
import DASHI.Culture.MissingDeceasedCriticalKnowledgeBidiExact
import DASHI.Culture.MissingDeceasedViewpointEvidenceExact
import DASHI.Culture.MissingDeceasedOpenScienceBidiExact
import DASHI.Culture.MissingDeceasedOpenScienceEverything
import DASHI.Core.FiniteObservationClosureBidiExact
import DASHI.Core.InverseProblemIdentifiabilityBidiExact
import DASHI.Culture.ScientificRosterInverseProblemCrossPollinationExact
import DASHI.Culture.ScientificRosterWorkCoverageExact
import DASHI.Culture.MissingDeceasedScientificWorkPublicationExpansionExact
import DASHI.Culture.AmyEskridgeGravityMechanismCrossPollinationExact
import DASHI.Culture.McCaslandTechnicalProgrammeBidiExact
import DASHI.Control.McCaslandFaultTolerantFlexibleStructureControlBidiExact
import DASHI.Control.McCaslandGramianPlacementAlgorithmDepthExact
import DASHI.Control.McCaslandFailureSetPlacementCompilerExact
import DASHI.Control.McCaslandFiniteFailureFamilyScoreExact
import DASHI.Control.McCaslandBeamPlacementFiniteEngineExact
import DASHI.Physics.Plasma.LoureiroViriatoPlasmoidBidiExact
import DASHI.Physics.Plasma.LoureiroTearingMediatedMHDTurbulenceBidiExact
import DASHI.Physics.Plasma.LoureiroKREHMHermiteEquationDepthExact
import DASHI.Physics.Plasma.LoureiroTearingCrossoverCompilerExact
import DASHI.Physics.Plasma.LoureiroHermiteClosureReceiptExact
import DASHI.Physics.Plasma.LoureiroCrossoverExponentDerivationExact
import DASHI.Physics.Plasma.LoureiroBetaZeroCrossoverComputationExact
import DASHI.Physics.Nuclear.LeBlancFissionSurfacePowerICBidiExact
import DASHI.Physics.Nuclear.LeBlancFSPICQualificationDepthExact
import DASHI.Physics.Nuclear.LeBlancSensorQualificationMatrixExact
import DASHI.Physics.Spectroscopy.MaiwaldActionSpectroscopyBidiExact
import DASHI.Physics.Spectroscopy.MaiwaldQuadrupoleIonTrapMassSpectrometryBidiExact
import DASHI.Physics.Spectroscopy.MaiwaldQITActionSpectroscopyEquationDepthExact
import DASHI.Physics.Spectroscopy.MaiwaldMathieuStabilityAndActionResponseCompilerExact
import DASHI.Physics.Materials.RezaBurnResistantAlloyBidiExact
import DASHI.Physics.Materials.RezaGammaPrimeBurnStrengthTradeoffDepthExact
import DASHI.Physics.Materials.RezaTestedAlloyTradeoffMatrixExact
import DASHI.Physics.Materials.RezaParetoWitnessExact
import DASHI.Physics.Materials.RezaExample12NonDominanceClosedExact
import DASHI.Physics.Astrophysics.GrillmairStellarStreamBidiExact
import DASHI.Physics.Astrophysics.GrillmairMatchedFilterOrbitDepthExact
import DASHI.Physics.Astrophysics.GrillmairDistanceScanMatchedFilterCompilerExact
import DASHI.Physics.Astrophysics.GrillmairExecutableDistanceScanExact
import DASHI.Physics.Astrophysics.GrillmairFiniteDistanceGridOrderExact
import DASHI.Physics.Planetary.HicksSmallBodyPhotometryBidiExact
import DASHI.Physics.Planetary.HicksCometAsteroidSpecificWorksBidiExact
import DASHI.Physics.Accelerator.AnthonyChavezScorpiusBidiExact
import DASHI.Physics.Accelerator.AnthonyChavezPermanentMagnetSpectrometerCalibrationBidiExact
import DASHI.Biology.JasonThomasSignallingBidiExact
import DASHI.Biology.JasonThomasSTINGFerritinophagyMechanismDepthExact
import DASHI.Biology.JasonThomasTargetDeconvolutionCompilerExact
import DASHI.Culture.HouseOversightScientistRosterScopeExact

-- UAP/adversarial and Chinese strategic-science extensions.
import DASHI.Culture.MissingDeceasedTernaryAdversarialObserverExact
import DASHI.Culture.MissingDeceasedStrategicRoleCapabilityFibreExact
import DASHI.Culture.ChineseStrategicScientistRosterSnowballExact
import DASHI.Culture.ChineseStrategicScientistEventWorkRepairExact
import DASHI.Culture.MissingDeceasedRosterExtensionNingLiNickPopeExact
import DASHI.Culture.MissingDeceasedRosterScopeReconciliationExact
import DASHI.Culture.MissingDeceasedTwentyScientistRoundRobinProgressExact
import DASHI.Culture.MissingDeceasedTwentyScientistRound2ProgressExact
import DASHI.Culture.MissingDeceasedInvestigativeAttributedSourceAtlasExact
import DASHI.Culture.MissingDeceasedInvestigativeDiscoveryLinksAExact
import DASHI.Culture.MissingDeceasedInvestigativeDiscoveryLinksBExact
import DASHI.Culture.MissingDeceasedInvestigativeDiscoveryLinksCExact
import DASHI.Culture.MissingDeceasedSouthwestGeographyDiscriminatorExact
import DASHI.Culture.MissingDeceasedReportedAnomalyAttributionLedgerExact
import DASHI.Culture.MissingDeceasedFullAttachmentClaimAtlasExact
import DASHI.Culture.MissingDeceasedAttachmentSourcePromotionLedgerExact
import DASHI.Culture.MissingDeceasedUAPAdversarialClaimDiscriminatorExact
import DASHI.Culture.MissingDeceasedGameTheoryParetoProofSearchCrossPollinationExact
import DASHI.Culture.MissingDeceasedFullSetTechnicalIntersectionParetoExact
import DASHI.Culture.MissingDeceasedIbrahimInvestigativeParetoUAPChineseExact
import DASHI.Physics.Aerospace.YanHongHypersonicFlowControlBidiExact
import DASHI.Physics.ExoticGravity.LiTorrPRB1992AttributedSourceExact
import DASHI.Physics.ExoticGravity.NingLiYBCOGravityConstraintBidiExact
import DASHI.Physics.ExoticGravity.NingLiYBCORotatingFieldConstraintExact
import DASHI.Physics.ExoticGravity.NingLiNASACooperativeAgreementNCC8124Exact
import DASHI.Physics.ExoticGravity.NingLiArmyOtherTransactionSourceDiligenceExact
import DASHI.Physics.Materials.FangDainingActiveMechanicalMetamaterialBidiExact
import DASHI.Physics.Materials.RezaFangAlloyMetamaterialDiscriminationExact
import DASHI.Physics.Materials.FusionPropulsionMaterialSurvivabilityCrossPollinationExact
import DASHI.GameTheory.FengYangheMilitaryAIGameStatisticsBidiExact
