import RequestProject.Wikidata.Sparql

/-!
# Grouping and counting query answers, and what a count is worth

`Wikidata/Sparql.lean` models the core fragment of SPARQL and proves that its
positive part is monotone: an answer over a knowledge base is an answer over any
larger one.  Real consumers of the Wikidata query service almost never stop at
the answer list — they `GROUP BY` an identifier and `COUNT`, and then filter the
groups with `HAVING`.  This module adds that layer and asks the same epistemic
question of it.

What is modelled: projection onto a list of selected variables (`project`),
`DISTINCT` (`distinctAnswers`), grouping a query's answers by the value of one
variable (`groupOf`, `groupKeys`), `COUNT` (`countOf`) and `HAVING`
(`havingKeys`).

What is proved:

* **Exactness** of every construction — `mem_groupOf_iff`, `mem_groupKeys_iff`,
  `mem_havingKeys_iff`, `mem_distinctAnswers_iff` — so the group of a key really
  is the set of answers binding the grouping variable to that key.
* **Grouping is a partition** of the answers that bind the variable:
  `groupOf_disjoint` (distinct keys share no solution), `groupOf_sublist` (each
  group is a sublist of the answer list) and `countOf_pos_iff` (a key has a
  non-empty group exactly when it is a group key).
* **Group keys are monotone on the positive fragment** (`groupKeys_mono`): the
  keys behave like the answers do, and never disappear as data arrives.
* **Counts are not** (`countOf_not_monotone`) and therefore **`HAVING` is not**
  (`having_not_monotone`), *even on the positive fragment*.  This is the sharp
  statement of the epistemic point: SPARQL's monotonicity theorem does not
  survive aggregation, so `HAVING (COUNT(?y) = 1)` is a claim about the present
  state of a database and never about the world.
* **A count counts solutions, not facts** (`count_counts_solutions_not_facts`):
  the same fact reached along two branches of a `UNION` is counted twice, while
  the `DISTINCT` projection collapses it.  So the number depends on the query
  plan as well as on the data.
* **A count is a count of the truthy layer** (`count_ignores_deprecated`,
  `count_ignores_rank_shadowed`): recorded statements that the projection hides
  are missing from the total, so a `COUNT` is not a census of the base.
-/

/-! ### Provenance (generated by `tools/provenance.py`)

Source mix of this module's 34 declarations: 0 traced to the DASHI Agda
bridge (`chboishabba/dashi_agda` PR #555 / #581 / #582), 0 rendering the Wikidata
data model, 34 original to this port.  The bridge-traced declarations are
marked with `-- @source` below.  Full ledger: `docs/status/PROVENANCE.md`.
-/

namespace Wikidata

namespace Sparql

/-! ## Projection and `DISTINCT` -/

/-- The restriction of a solution mapping to the selected variables — SPARQL's
`SELECT` list.  Unbound variables are simply dropped. -/
def project (vs : List Var) (b : Binding) : Binding :=
  vs.filterMap (fun v => (lookupVar b v).map (fun q => (v, q)))

@[simp] theorem project_nil (b : Binding) : project [] b = [] := rfl

/-- The answers to a query, projected onto the selected variables and
deduplicated: `SELECT DISTINCT`. -/
def distinctAnswers (kb : KB) (q : Query) (vs : List Var) : List Binding :=
  ((eval kb q).map (project vs)).dedup

theorem mem_distinctAnswers_iff (kb : KB) (q : Query) (vs : List Var) (b : Binding) :
    b ∈ distinctAnswers kb q vs ↔ ∃ b' ∈ eval kb q, project vs b' = b := by
  simp [distinctAnswers, List.mem_dedup, List.mem_map, eq_comm]

theorem distinctAnswers_nodup (kb : KB) (q : Query) (vs : List Var) :
    (distinctAnswers kb q vs).Nodup :=
  List.nodup_dedup _

/-- **`SELECT DISTINCT` is monotone on the positive fragment.**  Projection and
deduplication commute with the growth of the base, so a distinct answer survives
new data exactly as an answer does. -/
theorem distinctAnswers_mono {kb₁ kb₂ : KB} (hsub : kb₁.statements ⊆ kb₂.statements)
    (h₂ : AllNormal kb₂) {q : Query} (hpos : Positive q) {vs : List Var} {b : Binding}
    (h : b ∈ distinctAnswers kb₁ q vs) : b ∈ distinctAnswers kb₂ q vs := by
  rw [mem_distinctAnswers_iff] at h ⊢
  obtain ⟨b', hb', hproj⟩ := h
  exact ⟨b', eval_mono hsub h₂ hpos hb', hproj⟩

/-! ## `GROUP BY`, `COUNT` and `HAVING` -/

/-- The group of the key `k`: the answers that bind the grouping variable `v` to
`k`. -/
def groupOf (kb : KB) (q : Query) (v : Var) (k : Qid) : List Binding :=
  (eval kb q).filter (fun b => decide (lookupVar b v = some k))

theorem mem_groupOf_iff (kb : KB) (q : Query) (v : Var) (k : Qid) (b : Binding) :
    b ∈ groupOf kb q v k ↔ b ∈ eval kb q ∧ lookupVar b v = some k := by
  simp [groupOf, List.mem_filter]

/-- Each group is a sublist of the answer list: grouping selects, it does not
invent. -/
theorem groupOf_sublist (kb : KB) (q : Query) (v : Var) (k : Qid) :
    List.Sublist (groupOf kb q v k) (eval kb q) :=
  List.filter_sublist

/-- **Distinct keys have disjoint groups**: grouping is a partition of the
answers that bind the grouping variable. -/
theorem groupOf_disjoint {kb : KB} {q : Query} {v : Var} {k₁ k₂ : Qid} (hne : k₁ ≠ k₂)
    {b : Binding} (h : b ∈ groupOf kb q v k₁) : b ∉ groupOf kb q v k₂ := by
  rw [mem_groupOf_iff] at h
  intro h₂
  rw [mem_groupOf_iff] at h₂
  exact hne (Option.some.inj (h.2 ▸ h₂.2))

/-- The keys of `GROUP BY ?v`: the values the grouping variable takes in the
answers. -/
def groupKeys (kb : KB) (q : Query) (v : Var) : List Qid :=
  ((eval kb q).filterMap (fun b => lookupVar b v)).dedup

theorem mem_groupKeys_iff (kb : KB) (q : Query) (v : Var) (k : Qid) :
    k ∈ groupKeys kb q v ↔ ∃ b ∈ eval kb q, lookupVar b v = some k := by
  simp [groupKeys, List.mem_dedup, List.mem_filterMap]

/-- `COUNT(*)` within a group. -/
def countOf (kb : KB) (q : Query) (v : Var) (k : Qid) : Nat :=
  (groupOf kb q v k).length

/-- A key has a non-empty group exactly when it is a group key. -/
theorem countOf_pos_iff (kb : KB) (q : Query) (v : Var) (k : Qid) :
    0 < countOf kb q v k ↔ k ∈ groupKeys kb q v := by
  rw [countOf, List.length_pos_iff_exists_mem, mem_groupKeys_iff]
  constructor
  · rintro ⟨b, hb⟩
    rw [mem_groupOf_iff] at hb
    exact ⟨b, hb.1, hb.2⟩
  · rintro ⟨b, hb, hlk⟩
    exact ⟨b, (mem_groupOf_iff _ _ _ _ _).2 ⟨hb, hlk⟩⟩

/-- No answer of a group can be lost without lowering the count: a group's count
bounds it from above in the answer list. -/
theorem countOf_le_length (kb : KB) (q : Query) (v : Var) (k : Qid) :
    countOf kb q v k ≤ (eval kb q).length :=
  (groupOf_sublist kb q v k).length_le

/-- `HAVING p(COUNT(*))`: the group keys whose count passes the test. -/
def havingKeys (kb : KB) (q : Query) (v : Var) (p : Nat → Bool) : List Qid :=
  (groupKeys kb q v).filter (fun k => p (countOf kb q v k))

theorem mem_havingKeys_iff (kb : KB) (q : Query) (v : Var) (p : Nat → Bool) (k : Qid) :
    k ∈ havingKeys kb q v p ↔ k ∈ groupKeys kb q v ∧ p (countOf kb q v k) = true := by
  simp [havingKeys, List.mem_filter]

/-- **Group keys are monotone on the positive fragment.**  A key present over a
knowledge base is present over any larger one — the keys inherit the
monotonicity of the answers. -/
theorem groupKeys_mono {kb₁ kb₂ : KB} (hsub : kb₁.statements ⊆ kb₂.statements)
    (h₂ : AllNormal kb₂) {q : Query} (hpos : Positive q) {v : Var} {k : Qid}
    (h : k ∈ groupKeys kb₁ q v) : k ∈ groupKeys kb₂ q v := by
  rw [mem_groupKeys_iff] at h ⊢
  obtain ⟨b, hb, hlk⟩ := h
  exact ⟨b, eval_mono hsub h₂ hpos hb, hlk⟩

/-! ## Counting is not monotone, and neither is `HAVING`

The two bases below differ by one further `P31` statement about the same subject.
Both are wholly normal, so both statements are truthy and the query is the
positive pattern `?x P31 ?y`. -/

/-- One instance statement about `Q1`. -/
def aggSmallKB : KB := ⟨[⟨1⟩, ⟨2⟩, ⟨3⟩], [⟨⟨1⟩, P31, ⟨2⟩, Rank.normal⟩]⟩

/-- The same, plus a second instance statement about the same subject. -/
def aggBigKB : KB :=
  ⟨[⟨1⟩, ⟨2⟩, ⟨3⟩], [⟨⟨1⟩, P31, ⟨2⟩, Rank.normal⟩, ⟨⟨1⟩, P31, ⟨3⟩, Rank.normal⟩]⟩

theorem aggSmall_subset_aggBig : aggSmallKB.statements ⊆ aggBigKB.statements := by decide

theorem aggBigKB_allNormal : AllNormal aggBigKB := by
  intro st hst
  simp only [aggBigKB, List.mem_cons, List.not_mem_nil, or_false] at hst
  rcases hst with h | h <;> subst h <;> rfl

/-- The grouped query: `SELECT ?x (COUNT(?y)) WHERE { ?x P31 ?y } GROUP BY ?x`. -/
def aggQuery : Query := patXY

theorem aggQuery_positive : Positive aggQuery := trivial

/-- The group key survives, as `groupKeys_mono` says it must. -/
theorem aggregation_key_survives :
    (⟨1⟩ : Qid) ∈ groupKeys aggSmallKB aggQuery "x" ∧
      (⟨1⟩ : Qid) ∈ groupKeys aggBigKB aggQuery "x" := by
  refine ⟨by decide, ?_⟩
  exact groupKeys_mono aggSmall_subset_aggBig aggBigKB_allNormal aggQuery_positive (by decide)

/-- **A count is not monotone**: the value attached to a surviving key changes
when data arrives.  Monotonicity of the positive fragment is a statement about
*membership* in the answer list and says nothing about any function of it. -/
theorem countOf_not_monotone :
    countOf aggSmallKB aggQuery "x" ⟨1⟩ = 1 ∧ countOf aggBigKB aggQuery "x" ⟨1⟩ = 2 := by
  refine ⟨by decide, by decide⟩

/-- **`HAVING` is not monotone, even on the positive fragment.**  `HAVING
(COUNT(*) = 1)` answers `Q1` over the smaller base and answers nothing over the
larger one: an answer was *withdrawn* by the arrival of a statement.  So a
`HAVING` answer is a report about the current contents of a database, and reading
it as a fact about the world is the closed-world error in aggregate form. -/
theorem having_not_monotone :
    (⟨1⟩ : Qid) ∈ havingKeys aggSmallKB aggQuery "x" (fun n => n == 1) ∧
      havingKeys aggBigKB aggQuery "x" (fun n => n == 1) = [] := by
  refine ⟨by decide, by decide⟩

/-- The two bases really are ordered, so the failure above is growth and not
revision. -/
theorem having_failure_is_growth :
    aggSmallKB.statements ⊆ aggBigKB.statements ∧
      aggSmallKB.statements ≠ aggBigKB.statements := by
  refine ⟨aggSmall_subset_aggBig, by decide⟩

/-! ## A count counts solutions, not facts -/

/-- The same pattern, offered twice as the two branches of a `UNION`. -/
def doubledQuery : Query := Query.union patXY patXY

/-- **A count counts solutions, not facts.**  Over the one-statement base the
doubled query has count `2` for the key `Q1`, while the `DISTINCT` projection of
the same query onto `?x` has exactly one answer.  The number therefore depends on
the shape of the query as well as on the data, which is why a bare `COUNT` is not
a measurement of the knowledge base. -/
theorem count_counts_solutions_not_facts :
    countOf aggSmallKB doubledQuery "x" ⟨1⟩ = 2 ∧
      distinctAnswers aggSmallKB doubledQuery ["x"] = [[("x", (⟨1⟩ : Qid))]] := by
  refine ⟨by decide, by decide⟩

/-- Deduplicating the projection is exactly what removes the artefact. -/
theorem distinct_collapses_the_duplicate :
    ((eval aggSmallKB doubledQuery).map (project ["x"])).length = 2 ∧
      (distinctAnswers aggSmallKB doubledQuery ["x"]).length = 1 := by
  refine ⟨by decide, by decide⟩

/-! ## A count is a count of the truthy layer -/

/-- **Deprecated statements are not counted.**  The statement is recorded and the
group of `Q1` is empty, so a `COUNT` of `0` does not mean the base is silent. -/
theorem count_ignores_deprecated :
    (⟨⟨1⟩, P31, ⟨2⟩, Rank.deprecated⟩ : Statement) ∈ deprecatedKB.statements ∧
      countOf deprecatedKB patXY "x" ⟨1⟩ = 0 := by
  refine ⟨by decide, by decide⟩

/-- **Rank-shadowed statements are not counted either.**  Two `P31` statements are
recorded about `Q1`, one of them preferred; the count is `1`, not `2`.  A `COUNT`
measures the truthy projection, and the difference between it and the base is
invisible in the number. -/
theorem count_ignores_rank_shadowed :
    rankedKB.statements.length = 2 ∧ countOf rankedKB patXY "x" ⟨1⟩ = 1 := by
  refine ⟨by decide, by decide⟩

/-- **A count is not stable under growth even when nothing is withdrawn**: the
count over the larger base is strictly larger, so no count is ever a final
answer. -/
theorem count_is_not_a_final_answer :
    countOf aggSmallKB aggQuery "x" ⟨1⟩ < countOf aggBigKB aggQuery "x" ⟨1⟩ := by
  decide

end Sparql

end Wikidata
