module DASHI.Biology.Microbiology.Everything where

-- Canonical microbiology/ancientbiotics aggregate.  The newer nine-day weld
-- consumes the earlier quorum/eyesalve owners and the chemistry/protein lanes;
-- this is an integration root, not a duplicate implementation.

import DASHI.Biology.Microbiology.QuorumSensingContextExact
import DASHI.Biology.Microbiology.BaldEyesalveMechanismBoundaryExact
import DASHI.Biology.Microbiology.BaldEyesalveQuorumCrossPollinationExact
import DASHI.Biology.Protein.AlliumThiolProteinInteractionExact
import DASHI.Biology.Protein.StaphylococcusAllicinThiolomeExact
import DASHI.Chemistry.AlliumMolecularIdentityExact
import DASHI.Chemistry.AlliumOrganosulfurMechanismExact
import DASHI.Chemistry.AlliumReactionNetworkCrossPollinationExact
import DASHI.Chemistry.AlliumMolecularTrajectoryExact
import DASHI.Chemistry.MechanismDiscriminationExact
import DASHI.Biology.Cell.StaphylococcusAllicinRedoxRecoveryBidiExact
import DASHI.Biology.Cell.StaphylococcusAllicinFunctionCellStateBidiExact
import DASHI.Biology.Microbiology.BaldEyesalveNineDayMechanismWeldExact
import DASHI.Biology.Microbiology.BaldEyesalveMechanismExperimentSelectionExact
import DASHI.Biology.Microbiology.BaldEyesalveMechanismDiscriminationBidiExact
import DASHI.Biology.Microbiology.BaldEyesalveResidualActionPolicyBidiExact
