import RequestProject.Wikidata.SparqlAggregation

/-!
# `MINUS` and `FILTER NOT EXISTS`: two negations that are not the same one

`Wikidata/Sparql.lean` models SPARQL's oldest negation, `OPTIONAL` plus
`!bound`, and proves it non-monotone.  Modern SPARQL has two more: `MINUS`,
which subtracts a solution set, and `FILTER NOT EXISTS`, which tests a pattern
in the scope of the current solution.  They are widely treated as
interchangeable, and they are not — the difference is a standing source of wrong
Wikidata queries, and this module makes it a theorem.

The two are defined exactly as the standard has them:

* `notExists kb q₁ q₂` keeps a solution of `q₁` when `q₂`, evaluated *with that
  solution already substituted in*, has no answers;
* `minus kb q₁ q₂` deletes a solution of `q₁` when some answer of `q₂` is
  `compatible` with it **and shares a variable with it** — the domain-overlap
  side condition is the whole of the difference.

What is proved:

* **Exactness and soundness** — `mem_notExists_iff`, `mem_minus_iff`, and both
  operators return a sublist of the left-hand answers (`notExists_sublist`,
  `minus_sublist`), so neither invents a solution.
* **They differ** (`minus_ne_notExists`): on one knowledge base and one pair of
  patterns whose variables are disjoint, `MINUS` removes *nothing*
  (`minus_with_disjoint_variables_removes_nothing`) and `NOT EXISTS` removes
  *everything* (`notExists_with_disjoint_variables_removes_everything`).
* **They agree when the variables are shared**
  (`minus_agrees_when_variables_are_shared`) — the case query authors have in
  mind when they treat the two as synonyms.
* **Both are non-monotone** (`notExists_not_monotone`, `minus_not_monotone`):
  each withdraws an answer when a statement arrives, so like `!bound` they report
  an absence from the base that was queried and never a refutation.
* **Neither closes over the class order**
  (`not_exists_does_not_close_over_subclasses`): a `NOT EXISTS { ?x P31 Q3 }`
  answer is returned for an item the engine knows to be an instance of `Q3`, so
  SPARQL negation is negation over recorded triples, not over the theory.
-/

/-! ### Provenance (generated by `tools/provenance.py`)

Source mix of this module's 26 declarations: 0 traced to the DASHI Agda
bridge (`chboishabba/dashi_agda` PR #555 / #581 / #582), 0 rendering the Wikidata
data model, 26 original to this port.  The bridge-traced declarations are
marked with `-- @source` below.  Full ledger: `docs/status/PROVENANCE.md`.
-/

namespace Wikidata

namespace Sparql

/-! ## Compatibility of solution mappings -/

/-- The variables a solution mapping binds. -/
def domain (b : Binding) : List Var := b.map Prod.fst

/-- Two solution mappings are compatible when they agree wherever both are
defined. -/
def compatible (b₁ b₂ : Binding) : Bool :=
  b₁.all (fun p => match lookupVar b₂ p.1 with
                    | none => true
                    | some q => decide (q = p.2))

/-- Do two solution mappings bind a variable in common?  This is the side
condition that distinguishes `MINUS` from `NOT EXISTS`. -/
def sharesVariable (b₁ b₂ : Binding) : Bool :=
  b₁.any (fun p => (lookupVar b₂ p.1).isSome)

@[simp] theorem compatible_nil_left (b : Binding) : compatible [] b = true := rfl

@[simp] theorem sharesVariable_nil_left (b : Binding) : sharesVariable [] b = false := rfl

@[simp] theorem compatible_nil_right (b : Binding) : compatible b [] = true := by
  simp [compatible, lookupVar]

@[simp] theorem sharesVariable_nil_right (b : Binding) : sharesVariable b [] = false := by
  simp [sharesVariable, lookupVar]

/-- Compatibility, unfolded: the two mappings agree wherever the second one is
defined on a variable the first binds. -/
theorem compatible_iff (b₁ b₂ : Binding) :
    compatible b₁ b₂ = true ↔
      ∀ p ∈ b₁, ∀ q, lookupVar b₂ p.1 = some q → q = p.2 := by
  simp only [compatible, List.all_eq_true]
  constructor
  · intro h p hp q hq
    have := h p hp
    rw [hq] at this
    simpa using this
  · intro h p hp
    cases hq : lookupVar b₂ p.1 with
    | none => simp
    | some q => simpa using h p hp q hq

/-! ## The two negations -/

/-- `q₁ FILTER NOT EXISTS { q₂ }`: keep a solution when `q₂`, evaluated in the
scope of that solution, has no answers. -/
def notExists (kb : KB) (q₁ q₂ : Query) : List Binding :=
  (eval kb q₁).filter (fun b => (evalFrom kb q₂ b).isEmpty)

/-- `q₁ MINUS { q₂ }`: delete a solution when some answer of `q₂` is compatible
with it *and shares a variable with it*. -/
def minus (kb : KB) (q₁ q₂ : Query) : List Binding :=
  (eval kb q₁).filter
    (fun b => !((eval kb q₂).any (fun c => sharesVariable b c && compatible b c)))

theorem mem_notExists_iff (kb : KB) (q₁ q₂ : Query) (b : Binding) :
    b ∈ notExists kb q₁ q₂ ↔ b ∈ eval kb q₁ ∧ evalFrom kb q₂ b = [] := by
  simp [notExists, List.mem_filter, List.isEmpty_iff]

theorem mem_minus_iff (kb : KB) (q₁ q₂ : Query) (b : Binding) :
    b ∈ minus kb q₁ q₂ ↔
      b ∈ eval kb q₁ ∧
        ∀ c ∈ eval kb q₂, ¬ (sharesVariable b c = true ∧ compatible b c = true) := by
  simp [minus, List.mem_filter, and_comm]

/-- `NOT EXISTS` only ever deletes: its answers are answers of the left side. -/
theorem notExists_sublist (kb : KB) (q₁ q₂ : Query) :
    List.Sublist (notExists kb q₁ q₂) (eval kb q₁) :=
  List.filter_sublist

/-- `MINUS` only ever deletes. -/
theorem minus_sublist (kb : KB) (q₁ q₂ : Query) :
    List.Sublist (minus kb q₁ q₂) (eval kb q₁) :=
  List.filter_sublist

theorem notExists_sound {kb : KB} {q₁ q₂ : Query} {b : Binding}
    (h : b ∈ notExists kb q₁ q₂) : b ∈ eval kb q₁ :=
  ((mem_notExists_iff kb q₁ q₂ b).1 h).1

theorem minus_sound {kb : KB} {q₁ q₂ : Query} {b : Binding}
    (h : b ∈ minus kb q₁ q₂) : b ∈ eval kb q₁ :=
  ((mem_minus_iff kb q₁ q₂ b).1 h).1

/-! ## The two negations are different

`bigKB` records `Q1 P31 Q2` and `Q1 P279 Q3`.  The left pattern is `?x P31 ?y`;
the right pattern is offered twice, once with variables disjoint from the left
and once sharing `?x`. -/

/-- `?z P279 ?w` — a right-hand pattern with no variable in common with `?x P31 ?y`. -/
def disjointRight : Query := Query.pattern ⟨Term.var "z", P279, Term.var "w"⟩

/-- `?x P279 ?w` — the same pattern sharing the variable `?x`. -/
def sharedRight : Query := Query.pattern ⟨Term.var "x", P279, Term.var "w"⟩

/-- **`MINUS` with disjoint variables removes nothing.**  Every answer of the left
side survives, because no answer of the right side shares a variable with it. -/
theorem minus_with_disjoint_variables_removes_nothing :
    minus bigKB patXY disjointRight = eval bigKB patXY := by decide

/-- **`FILTER NOT EXISTS` with disjoint variables removes everything.**  The right
pattern has an answer, and having one is all the filter tests. -/
theorem notExists_with_disjoint_variables_removes_everything :
    notExists bigKB patXY disjointRight = [] := by decide

/-- **The two negations are not the same operator.**  On one base and one pair of
patterns, `MINUS` keeps the answer and `NOT EXISTS` does not — so a query rewritten
from one to the other is a different query. -/
theorem minus_ne_notExists :
    minus bigKB patXY disjointRight ≠ notExists bigKB patXY disjointRight := by decide

/-- **They agree when the right side shares a variable**, which is the case query
authors have in mind: here both delete the only answer. -/
theorem minus_agrees_when_variables_are_shared :
    minus bigKB patXY sharedRight = notExists bigKB patXY sharedRight ∧
      minus bigKB patXY sharedRight = [] := by
  refine ⟨by decide, by decide⟩

/-! ## Both are non-monotone -/

/-- **`NOT EXISTS` is not monotone.**  Over `smallKB`, which records no `P279`
statement, the filter passes; over the larger `bigKB` it fails.  The answer was
withdrawn by the arrival of data. -/
theorem notExists_not_monotone :
    [("x", (⟨1⟩ : Qid)), ("y", (⟨2⟩ : Qid))] ∈ notExists smallKB patXY sharedRight ∧
      notExists bigKB patXY sharedRight = [] := by
  refine ⟨by decide, by decide⟩

/-- **`MINUS` is not monotone** either, on the same pair of bases. -/
theorem minus_not_monotone :
    [("x", (⟨1⟩ : Qid)), ("y", (⟨2⟩ : Qid))] ∈ minus smallKB patXY sharedRight ∧
      minus bigKB patXY sharedRight = [] := by
  refine ⟨by decide, by decide⟩

/-- The two bases are ordered, so both failures above are growth and not
revision. -/
theorem negation_failures_are_growth : smallKB.statements ⊆ bigKB.statements :=
  small_subset_big

/-! ## Negation is over recorded triples, not over the theory -/

/-- **`NOT EXISTS` does not close over the class order.**  In `closureKB` the
engine derives that `Q1` is an instance of `Q3` through a subclass edge, and
`FILTER NOT EXISTS { ?x P31 Q3 }` nevertheless returns `?x = Q1`: SPARQL negation
denies a *triple*, not a consequence.  Denying the consequence needs the property
path `P31/P279*`, which `Wikidata/SparqlPaths.lean` supplies. -/
theorem not_exists_does_not_close_over_subclasses :
    InstanceOf closureKB ⟨1⟩ ⟨3⟩ ∧
      [("x", (⟨1⟩ : Qid)), ("y", (⟨2⟩ : Qid))] ∈
        notExists closureKB (Query.pattern ⟨Term.var "x", P31, Term.var "y"⟩)
          (Query.pattern ⟨Term.var "x", P31, Term.item ⟨3⟩⟩) := by
  refine ⟨(isInstanceOf_iff _ ⟨1⟩ ⟨3⟩).1 (by decide), by decide⟩

end Sparql

end Wikidata
