module DASHI.Physics.Closure.NSPairIncidenceKernelProgram where

open import DASHI.Analysis.WeightedKernelSchurTest public
open import DASHI.Analysis.FiniteWeightedKernelSums public
open import DASHI.Analysis.FiniteWeightedKernelTransport public
open import DASHI.Physics.Closure.NSIntegerFourierLattice public
open import DASHI.Physics.Closure.NSWall1CanonicalModePacket public
open import DASHI.Physics.Closure.NSWall1ExactEvaluationCarrier public
open import DASHI.Physics.Closure.NSWall1CanonicalPacketEvaluation public
open import DASHI.Physics.Closure.NSWall1CanonicalAmplitudeProfile public
open import DASHI.Physics.Closure.NSWall1CanonicalPolarizations public
open import DASHI.Physics.Closure.NSWall1RationalScalarInstance public
open import DASHI.Physics.Closure.NSWall1RationalPolarizationProofs public
open import DASHI.Physics.Closure.NSWall1CanonicalFiniteSchur public
open import DASHI.Physics.Closure.NSWall1CanonicalPairIncidenceSchur public
open import DASHI.Physics.Closure.NSWall1CanonicalFourierRestriction public
open import DASHI.Physics.Closure.NSWall1CanonicalUniformRestrictionSchur public
open import DASHI.Physics.Closure.NSWall1CanonicalResolventGap public
open import DASHI.Physics.Closure.NSDivergenceFreePolarizationBasis public
open import DASHI.Physics.Closure.NSPairIncidenceKernel public
open import DASHI.Physics.Closure.NSFourierBiotSavartTriadKernel public
open import DASHI.Physics.Closure.NSDifferentiatedTriadAnalyticLeaf public
open import DASHI.Physics.Closure.NSCompactGammaDifferentiatedTriadInstantiation public
open import DASHI.Physics.Closure.NSWall1FourierShellInstance public
open import DASHI.Physics.Closure.NSWall1PolarizationInstantiation public
open import DASHI.Physics.Closure.NSWall1UniformWeightedSchur public
open import DASHI.Physics.Closure.NSFullShellWeightedSchur public
open import DASHI.Physics.Closure.NSPairIncidenceSchurBridge public
open import DASHI.Physics.Closure.NSWeightedShellTransferBridge public
open import DASHI.Physics.Closure.NSFactorizedSchurFrameGap public
open import DASHI.Physics.Closure.NSCompactGammaOffPacketWall1PairIncidenceBridge public
open import DASHI.Physics.Closure.NSCompactGammaOffPacketTriadMajorization public
open import DASHI.Physics.Closure.NSCompactGammaFullShellSchur public
open import DASHI.Physics.Closure.NSCutoffUniformIntegerShellSchur public
open import DASHI.Physics.Closure.NSZ3CutoffUniformIntegerShellSchur public
open import DASHI.Physics.Closure.NSZ3QuantitativeSchurWitnesses public
open import DASHI.Physics.Closure.NSZ3LiteralIntegerCubeSchurClosure public
open import DASHI.Physics.Closure.NSFullShellWeightedSchurClosure public
open import DASHI.Physics.Closure.NSCompactGammaTriadFullShellCoherence public
open import DASHI.Physics.Closure.NSCompactGammaOffPacketTailDecayBridge public
open import DASHI.Physics.Closure.NSCompactGammaOffPacketDifferentialModulusBridge public
open import DASHI.Physics.Closure.NSGalerkinCompactnessLimit public
open import DASHI.Physics.Closure.NSCompactGammaGalerkinLimitBridge public
open import DASHI.Physics.Closure.NSCompactGammaAdmissiblePreservation public
open import DASHI.Physics.Closure.NSCompactGammaTimeIntegrabilityBridge public
open import DASHI.Physics.Closure.NSCompactGammaBKMTimeIntegrability public
open import DASHI.Physics.Closure.NSCompactGammaHighestAlphaExpenditureCompletion public
open import DASHI.Physics.Closure.NSCompactGammaDifferentialExpenditureProducer public
open import DASHI.Physics.Closure.NSCompactGammaConcretePotentialInstantiation public
open import DASHI.Physics.Closure.NSCompactGammaConcretePotentialCompletion public
open import DASHI.Physics.Closure.NSCompactGammaAnalyticLeafCompletion public
open import DASHI.Physics.Closure.NSCompactGammaExactPotentialAndPacketBalance public
open import DASHI.Physics.Closure.NSCompactGammaAnalyticClosureProgram public

-- Focused namespace imports: compile the exact absorbed route and universal tail
-- reductions without flooding the existing public surface with projections.
import DASHI.Physics.Closure.NSCompactGammaFiveHalvesRouteDecision
import DASHI.Physics.Closure.NSCompactGammaFiveHalvesSummationReduction
import DASHI.Physics.Closure.NSCompactGammaNearTriadRouteDecision
import DASHI.Physics.Closure.NSCompactGammaNearTriadAbsorptionReduction
import DASHI.Physics.Closure.NSCompactGammaRadiusEightFourierReduction
import DASHI.Physics.Closure.NSCompactGammaCanonicalParameterBridge
import DASHI.Physics.Closure.NSCompactGammaFixedFloorScalingObstruction
import DASHI.Physics.Closure.NSCompactGammaGeneratedCertificateBridge
import DASHI.Physics.Closure.NSPeriodicFourierCancellationAlgebra
import DASHI.Physics.Closure.NSPeriodicFourierNearTriadPreYoung
import DASHI.Physics.Closure.NSPeriodicFourierYoungFactorization
import DASHI.Physics.Closure.NSPeriodicFourierNearTriadAuthorityBridge
import DASHI.Physics.Closure.NSPeriodicFourierRadiusEightPrimitiveReduction
import DASHI.Physics.Closure.NSPeriodicFourierRadiusEightAuthorityBridge
import DASHI.Physics.Closure.NSCompactGammaInvariantCoverageReduction
import DASHI.Physics.Closure.NSCompactGammaDiniFirstExitReduction
import DASHI.Physics.Closure.NSPeriodicFourierAnalyticAuthorityBoundary
import DASHI.Physics.Closure.NSPeriodicFourierAuthorityAdapters
import DASHI.Physics.Closure.NSPeriodicContinuationAuthorityAdapter
import DASHI.Physics.Closure.NSCompactGammaCoverageFromContinuationAuthority
import DASHI.Physics.Closure.NSPeriodicFourierUniversalTailReduction
import DASHI.Physics.Closure.NSCompactGammaCertificateUniversalTailCompletion
import DASHI.Physics.Closure.NSPeriodicFourierUniversalTailRegression
import DASHI.Physics.Closure.NSPeriodicConcreteProofProgramRegression
import DASHI.Physics.Closure.NSCompactGammaExactMathematicalCutset

-- Official-norm, integrated-expenditure, adaptive-coverage and continuum spine.
import DASHI.Physics.Closure.NSPeriodicOfficialNormIdentification
import DASHI.Physics.Closure.NSPeriodicOfficialNormBernsteinAdapter
import DASHI.Physics.Closure.NSPeriodicCoefficientUnitaryNormAdapter
import DASHI.Physics.Closure.NSPeriodicCoefficientUnitaryPythagoreanAdapter
import DASHI.Physics.Closure.NSPeriodicNearTriadCutoffUniformCompletion
import DASHI.Physics.Closure.NSPeriodicFarLowOfficialSchurCompletion
import DASHI.Physics.Closure.NSPeriodicOfficialFarLowSchurAdapter
import DASHI.Physics.Closure.NSPeriodicFarHighTailCompletion
import DASHI.Physics.Closure.NSPeriodicOfficialHarmonicAuthorityCompletion
import DASHI.Physics.Closure.NSPeriodicWallIHarmonicCompletion
import DASHI.Physics.Closure.NSPeriodicIntegratedExpenditureCompletion
import DASHI.Physics.Closure.NSPeriodicIntegratedExpenditureStandardAdapter
import DASHI.Physics.Closure.NSCompactGammaNormalizedBoundaryInwardnessCompletion
import DASHI.Physics.Closure.NSPeriodicAdaptiveSwitchCostCompletion
import DASHI.Physics.Closure.NSPeriodicDiffuseSpectrumBKMCompletion
import DASHI.Physics.Closure.NSPeriodicAllDataCoverageCompletion
import DASHI.Physics.Closure.NSPeriodicAllDataCutoffCoverageAdapter
import DASHI.Physics.Closure.NSPeriodicStandardContinuumAdapter
import DASHI.Physics.Closure.NSPeriodicCutoffUniformContinuumBKMCompletion
import DASHI.Physics.Closure.NSPeriodicCutoffUniformContinuumAssembly
import DASHI.Physics.Closure.NSPeriodicOfficialCompletionStatus
import DASHI.Physics.Closure.NSPeriodicOfficialCompletionRegression
import DASHI.Physics.Closure.NSPeriodicSevenAnalyticLeafCutset

-- Exact frontier reductions added after the seven-leaf cutset.
import DASHI.Physics.Closure.NSPeriodicRealVectorPolynomialIdentities
import DASHI.Physics.Closure.NSPeriodicRealFourierVectorLaws
import DASHI.Physics.Closure.NSPeriodicBiotSavartTransversality
import DASHI.Physics.Closure.NSPeriodicLerayBiotSavartNormReduction
import DASHI.Physics.Closure.NSPeriodicRealBiotSavartModeNorm
import DASHI.Physics.Closure.NSPeriodicFinitePythagoreanSum
import DASHI.Physics.Closure.NSPeriodicCanonicalStrictMarginCertificate
import DASHI.Physics.Closure.NSPeriodicCanonicalStrictMarginInterpretation
import DASHI.Physics.Closure.NSPeriodicCanonicalWallIMarginAdapter
import DASHI.Physics.Closure.NSPeriodicStrictDissipationMargin
import DASHI.Physics.Closure.NSPeriodicIntegratedExpenditureStrictMarginAdapter
import DASHI.Physics.Closure.NSPeriodicPacketFractionQuotientSign
import DASHI.Physics.Closure.NSPeriodicConcretePacketOffPartition
import DASHI.Physics.Closure.NSPeriodicPacketOffDerivativeDuality
import DASHI.Physics.Closure.NSPeriodicComplementaryBoundaryCoincidence
import DASHI.Physics.Closure.NSPeriodicNormalizedBoundaryCommonParameters
import DASHI.Physics.Closure.NSPeriodicNormalizedBoundaryCandidateTuple
import DASHI.Physics.Closure.NSPeriodicThreeIndependentBoundarySigns
import DASHI.Physics.Closure.NSPeriodicHysteresisSeparation
import DASHI.Physics.Closure.NSPeriodicHysteresisDwellTime
import DASHI.Physics.Closure.NSPeriodicAdaptiveSwitchSeparationAdapter
import DASHI.Physics.Closure.NSPeriodicDiffuseDissipationCharging
import DASHI.Physics.Closure.NSPeriodicDiffuseDissipationRouteAdapter
import DASHI.Physics.Closure.NSPeriodicZeroChartDiffuseSelection
import DASHI.Physics.Closure.NSPeriodicChartFailureCoverage
import DASHI.Physics.Closure.NSPeriodicExtendedCoverageBKM
import DASHI.Physics.Closure.NSPeriodicWeightedEnvelopeLimitTransport
import DASHI.Physics.Closure.NSPeriodicWeightedEnvelopeContinuumAdapter

-- Concrete carrier and narrowed analytic frontier.
import DASHI.Physics.Closure.NSPeriodicConcreteCutoffCubeCarrier
import DASHI.Physics.Closure.NSPeriodicConcreteIntegerModeNorm
import DASHI.Physics.Closure.NSPeriodicConcreteOfficialNormWeights
import DASHI.Physics.Closure.NSPeriodicCanonicalNearYoungAllocation
import DASHI.Physics.Closure.NSPeriodicConcreteCandidateBudgetArithmetic
import DASHI.Physics.Closure.NSPeriodicCompactGammaPDEBalance
import DASHI.Physics.Closure.NSPeriodicCanonicalThreeBoundaryTupleAdapter
import DASHI.Physics.Closure.NSPeriodicObservableDerivativeBoundReduction
import DASHI.Physics.Closure.NSPeriodicDiffuseLowHighSplit
import DASHI.Physics.Closure.NSPeriodicChartFailureAnalyticRoutes
import DASHI.Physics.Closure.NSPeriodicFixedShellFiniteRankConvergence
