module DASHI.Physics.Closure.NSTriadKNRawCurlFibreGramLedgerRound180Exact where

------------------------------------------------------------------------
-- ROUND180 / EXACT FINITE SAME-OUTPUT GRAM LEDGER
--
-- Round179 identifies the two-cell obstruction.  Here we telescope it across
-- an arbitrary finite output fibre BEFORE any absolute value:
--
--   ||sum cells||^2 = sum ||cell||^2 + GramDebt(cells).
--
-- `GramDebt` contains every signed cross interaction generated by adding one
-- cell to the already-assembled tail.  This is the exact quantity the physical
-- partner/Bony/trajectory argument must pay.  If it is nonpositive, the
-- complete fibre has a cardinality-free L2 bound immediately.
------------------------------------------------------------------------

open import Agda.Builtin.Bool using (Bool; true; false)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.List using (List; []; _∷_)
open import Data.Rational.Base using (ℚ; 0ℚ; _+_; _≤_)
import Data.Rational.Properties as ℚP
open import Data.Rational.Tactic.RingSolver using (solve)
open import Relation.Binary.PropositionalEquality using (subst)

import DASHI.Physics.Closure.NSTriadKNComplex3ExactCarrier as C3
import DASHI.Physics.Closure.NSTriadKNOrderedEuclideanL2Carrier as L2
import DASHI.Physics.Closure.NSTriadKNRawCurlFibreGramRound179Exact as R179

F = R179.F

sumCells : List (C3.Complex3 F) → C3.Complex3 F
sumCells [] = C3.complex3Zero F
sumCells (u ∷ us) = C3.complex3Add u (sumCells us)

cellMassSum : List (C3.Complex3 F) → ℚ
cellMassSum [] = 0ℚ
cellMassSum (u ∷ us) = L2.complex3NormSquared u + cellMassSum us

-- Recursive polarization debt.  Importantly this is SIGNED; no modulus is
-- inserted here.
gramDebt : List (C3.Complex3 F) → ℚ
gramDebt [] = 0ℚ
gramDebt (u ∷ us) =
  R179.two * R179.realHermitianCross u (sumCells us) + gramDebt us

zeroCellMass : L2.complex3NormSquared (C3.complex3Zero F) ≡ 0ℚ
zeroCellMass = solve []

finiteFibreGramLedger :
  (cells : List (C3.Complex3 F)) →
  L2.complex3NormSquared (sumCells cells)
  ≡ cellMassSum cells + gramDebt cells
finiteFibreGramLedger [] = zeroCellMass
finiteFibreGramLedger (u ∷ us)
  rewrite R179.complex3Polarization u (sumCells us)
        | finiteFibreGramLedger us =
  solve
    ( L2.complex3NormSquared u
    ∷ cellMassSum us
    ∷ gramDebt us
    ∷ R179.realHermitianCross u (sumCells us)
    ∷ [])

-- Exact sufficient condition for a multiplicity-free fibre estimate.  The
-- condition is intentionally NOT postulated for Navier--Stokes: it is the live
-- physical theorem target exported by this round.
nonpositiveGramDebtClosesFibre :
  (cells : List (C3.Complex3 F)) →
  gramDebt cells ≤ 0ℚ →
  L2.complex3NormSquared (sumCells cells) ≤ cellMassSum cells
nonpositiveGramDebtClosesFibre cells debtNonpositive =
  let
    shifted :
      cellMassSum cells + gramDebt cells
      ≤ cellMassSum cells + 0ℚ
    shifted = ℚP.+-monoʳ-≤ (cellMassSum cells) debtNonpositive

    rhsZero : cellMassSum cells + 0ℚ ≡ cellMassSum cells
    rhsZero = solve (cellMassSum cells ∷ [])
  in
  subst
    (λ left → left ≤ cellMassSum cells)
    (finiteFibreGramLedger cells)
    (subst (cellMassSum cells + gramDebt cells ≤_) rhsZero shifted)

record SignedFibreGramPayment (cells : List (C3.Complex3 F)) : Set where
  constructor signed-fibre-gram-payment
  field
    gramDebtNonpositive : gramDebt cells ≤ 0ℚ

open SignedFibreGramPayment public

paidFibreMassBound :
  (cells : List (C3.Complex3 F)) →
  SignedFibreGramPayment cells →
  L2.complex3NormSquared (sumCells cells) ≤ cellMassSum cells
paidFibreMassBound cells payment =
  nonpositiveGramDebtClosesFibre cells (gramDebtNonpositive payment)

round180ExactFiniteGramLedgerClosed : Bool
round180ExactFiniteGramLedgerClosed = true

round180NoCardinalityFactorAfterGramPayment : Bool
round180NoCardinalityFactorAfterGramPayment = true

round180PhysicalGramPaymentClosed : Bool
round180PhysicalGramPaymentClosed = false

round180PackageAClosed : Bool
round180PackageAClosed = false

round180ClayPromotion : Bool
round180ClayPromotion = false
