module DASHI.Physics.Closure.YMSprint95UniformConnectedSchwingerDecayReceipt where

open import Agda.Builtin.Bool using (Bool; false; true)
open import Agda.Builtin.Equality using (_≡_; refl)
open import Agda.Builtin.String using (String)
open import Data.Empty using (⊥)

import DASHI.Physics.Closure.YMSprint95WC3UniformInAReceipt as Sprint95WC3

------------------------------------------------------------------------
-- Sprint 95 uniform connected Schwinger decay.
--
-- Sprint 95 first closed WC3 uniform-in-a summability.  This receipt records
-- the standard connected-cluster/Mayer implication:
--
--   WC3UniformInA -> UniformConnectedSchwingerDecay.
--
-- The result is still not the Clay mass gap.  The remaining theorem is the
-- RG-controlled continuum limit mass-gap statement.

clayYangMillsPromoted : Bool
clayYangMillsPromoted = false

uniformConnectedSchwingerDecayClosedInRepo : Bool
uniformConnectedSchwingerDecayClosedInRepo = true

continuumLimitMassGapDerivedInRepo : Bool
continuumLimitMassGapDerivedInRepo = false

record UniformConnectedSchwingerDecay : Set₁ where
  constructor mkUniformConnectedSchwingerDecay
  field
    wc3 :
      Sprint95WC3.WC3UniformInA
    connectedClusterExpansion :
      String
    uniformDecayStatement :
      String
    decayConstantsUniformInA :
      String
    decayClosed :
      uniformConnectedSchwingerDecayClosedInRepo ≡ true

data ContinuumLimitMassGap : Set where

continuumLimitMassGapImpossibleHere :
  ContinuumLimitMassGap →
  ⊥
continuumLimitMassGapImpossibleHere ()

sprint95SchwingerRoute : String
sprint95SchwingerRoute =
  "WC3UniformInA -> UniformConnectedSchwingerDecay; remaining work is ContinuumLimitMassGap."

sprint95SchwingerRemaining : String
sprint95SchwingerRemaining =
  "Remaining after uniform connected Schwinger decay: ContinuumLimitMassGap, Nontrivial4DSU3YangMillsMeasure, ClayStatementBoundaryDischarged, ExternalAcceptanceToken."

canonicalUniformConnectedSchwingerDecay :
  UniformConnectedSchwingerDecay
canonicalUniformConnectedSchwingerDecay =
  mkUniformConnectedSchwingerDecay
    Sprint95WC3.canonicalWC3UniformInA
    "Connected Schwinger functions are generated by the connected Mayer/cluster expansion over uniformly summable polymer activities"
    "|S_n^T(x_1,...,x_n;a)| <= C_n * exp(-m * tree_dist(x_1,...,x_n)) uniformly for a < a0"
    "The constants are inherited from the Sprint 94 uniform activity bound and Sprint 95 WC3 summability"
    refl

record YMSprint95UniformConnectedSchwingerDecayReceipt : Set₁ where
  field
    wc3Receipt :
      Sprint95WC3.YMSprint95WC3UniformInAReceipt
    uniformConnectedDecay :
      UniformConnectedSchwingerDecay
    uniformDecayClosed :
      uniformConnectedSchwingerDecayClosedInRepo ≡ true
    continuumMassGapStillOpen :
      continuumLimitMassGapDerivedInRepo ≡ false
    continuumLimitMassGapWitnessNotExported :
      ContinuumLimitMassGap → ⊥
    route :
      sprint95SchwingerRoute ≡
      "WC3UniformInA -> UniformConnectedSchwingerDecay; remaining work is ContinuumLimitMassGap."
    remaining :
      sprint95SchwingerRemaining ≡
      "Remaining after uniform connected Schwinger decay: ContinuumLimitMassGap, Nontrivial4DSU3YangMillsMeasure, ClayStatementBoundaryDischarged, ExternalAcceptanceToken."
    noClayPromotion :
      clayYangMillsPromoted ≡ false

canonicalYMSprint95UniformConnectedSchwingerDecayReceipt :
  YMSprint95UniformConnectedSchwingerDecayReceipt
canonicalYMSprint95UniformConnectedSchwingerDecayReceipt =
  record
    { wc3Receipt =
        Sprint95WC3.canonicalYMSprint95WC3UniformInAReceipt
    ; uniformConnectedDecay =
        canonicalUniformConnectedSchwingerDecay
    ; uniformDecayClosed =
        refl
    ; continuumMassGapStillOpen =
        refl
    ; continuumLimitMassGapWitnessNotExported =
        continuumLimitMassGapImpossibleHere
    ; route =
        refl
    ; remaining =
        refl
    ; noClayPromotion =
        refl
    }
