module DASHI.Moonshine.P11VoightNonprincipalLeftOrderExact where

------------------------------------------------------------------------
-- PRIMARY SOURCES / CONTEXT
--
-- John Voight,
-- "Quaternion Algebras", Graduate Texts in Mathematics 288, Springer, 2021.
-- DOI: 10.1007/978-3-030-56694-4.
-- Chapter 42, "Supersingular elliptic curves",
-- DOI: 10.1007/978-3-030-56694-4_42.
-- Example 42.3.11 gives, for p=11,
--
--   B = (-1,-11 / Q),
--   O = Z<i,(1+j)/2>,
--
-- and the nontrivial right ideal class generated by
--
--   2,  1 + i(1+j)/2.
--
-- It records that the left order of that ideal has unit group generated by
--
--   1/2 - i(1+j)/4
--
-- of order 6, and identifies the corresponding supersingular curve with j=0.
--
-- Markus Kirschmer and John Voight,
-- "Algorithmic Enumeration of Ideal Classes for Quaternion Orders",
-- SIAM Journal on Computing 39 (2010), 1714--1747.
-- DOI: 10.1137/080734467.
-- CORRIGENDUM: SIAM Journal on Computing 41 (2012), 714.
-- DOI: 10.1137/120866063.
-- We cite the corrected article/corrigendum explicitly: connecting ideals and
-- left/right order computation are exactly the algorithmic operation used here.
--
-- DASHI CONTRIBUTION
--
-- Work on the SAME quaternion coordinates 1,i,j,k with
--
--   i^2=-1, j^2=-11, ij=k=-ji.
--
-- A Z-basis of Voight's nonprincipal right ideal is
--
--   v0 = 2,
--   v1 = 2 i,
--   v2 = (3 + 2i + j)/2,
--   v3 = (2 + i + k)/2.
--
-- Solving alpha I subseteq I gives the following integral basis of its left
-- order:
--
--   e0 = 1,
--   e1 = 2 i,
--   e2 = (3 + 2i + j)/2,
--   e3 = (2 + i + k)/4.
--
-- The file records the exact integral left-action matrices on the ideal basis,
-- the multiplication table of this order, and the trace-discriminant Gram
-- matrix.  Its determinant is -121, i.e. reduced discriminant 11, so by the
-- standard discriminant criterion this is maximal in B_{11,infinity}.  Since
-- it stabilizes I, it is exactly O_L(I), not an arbitrary conjugate order.
------------------------------------------------------------------------

open import DASHI.Core.Prelude
open import Data.Integer using (ℤ; +_; -[1+_])

------------------------------------------------------------------------
-- Symbolic bases.  Coordinates in B are documented above; the finite tables
-- below are the exact coordinate calculation and contain no fitted data.
------------------------------------------------------------------------

data IdealBasis : Set where
  v0 v1 v2 v3 : IdealBasis

data J0OrderBasis : Set where
  e0 e1 e2 e3 : J0OrderBasis

record Int4 : Set where
  constructor int4
  field x0 x1 x2 x3 : ℤ

open Int4 public

------------------------------------------------------------------------
-- e_r * v_c expressed in the ideal basis (v0,v1,v2,v3).
-- Every coefficient is integral, hence the displayed order stabilizes I.
------------------------------------------------------------------------

leftAction : J0OrderBasis → IdealBasis → Int4
leftAction e0 v0 = int4 (+ 1) (+ 0) (+ 0) (+ 0)
leftAction e0 v1 = int4 (+ 0) (+ 1) (+ 0) (+ 0)
leftAction e0 v2 = int4 (+ 0) (+ 0) (+ 1) (+ 0)
leftAction e0 v3 = int4 (+ 0) (+ 0) (+ 0) (+ 1)

leftAction e1 v0 = int4 (+ 0) (+ 2) (+ 0) (+ 0)
leftAction e1 v1 = int4 (-[1+ 1 ]) (+ 0) (+ 0) (+ 0)
leftAction e1 v2 = int4 (-[1+ 1 ]) (+ 1) (+ 0) (+ 2)
leftAction e1 v3 = int4 (+ 1) (+ 2) (-[1+ 1 ]) (+ 0)

leftAction e2 v0 = int4 (+ 0) (+ 0) (+ 2) (+ 0)
leftAction e2 v1 = int4 (+ 0) (+ 2) (+ 0) (-[1+ 1 ])
leftAction e2 v2 = int4 (-[1+ 2 ]) (+ 0) (+ 3) (+ 0)
leftAction e2 v3 = int4 (+ 0) (+ 2) (+ 0) (+ 1)

leftAction e3 v0 = int4 (+ 0) (+ 0) (+ 0) (+ 1)
leftAction e3 v1 = int4 (-[1+ 0 ]) (+ 0) (+ 1) (+ 0)
leftAction e3 v2 = int4 (-[1+ 0 ]) (-[1+ 0 ]) (+ 1) (+ 1)
leftAction e3 v3 = int4 (-[1+ 0 ]) (+ 0) (+ 0) (+ 1)

------------------------------------------------------------------------
-- Exact order multiplication table in the e-basis.
------------------------------------------------------------------------

multiplyBasis : J0OrderBasis → J0OrderBasis → Int4
multiplyBasis e0 e0 = int4 (+ 1) (+ 0) (+ 0) (+ 0)
multiplyBasis e0 e1 = int4 (+ 0) (+ 1) (+ 0) (+ 0)
multiplyBasis e0 e2 = int4 (+ 0) (+ 0) (+ 1) (+ 0)
multiplyBasis e0 e3 = int4 (+ 0) (+ 0) (+ 0) (+ 1)

multiplyBasis e1 e0 = int4 (+ 0) (+ 1) (+ 0) (+ 0)
multiplyBasis e1 e1 = int4 (-[1+ 3 ]) (+ 0) (+ 0) (+ 0)
multiplyBasis e1 e2 = int4 (-[1+ 3 ]) (+ 1) (+ 0) (+ 4)
multiplyBasis e1 e3 = int4 (+ 1) (+ 1) (-[1+ 0 ]) (+ 0)

multiplyBasis e2 e0 = int4 (+ 0) (+ 0) (+ 1) (+ 0)
multiplyBasis e2 e1 = int4 (+ 0) (+ 2) (+ 0) (-[1+ 3 ])
multiplyBasis e2 e2 = int4 (-[1+ 5 ]) (+ 0) (+ 3) (+ 0)
multiplyBasis e2 e3 = int4 (+ 0) (+ 1) (+ 0) (+ 1)

multiplyBasis e3 e0 = int4 (+ 0) (+ 0) (+ 0) (+ 1)
multiplyBasis e3 e1 = int4 (-[1+ 1 ]) (+ 0) (+ 1) (+ 0)
multiplyBasis e3 e2 = int4 (-[1+ 1 ]) (-[1+ 0 ]) (+ 1) (+ 2)
multiplyBasis e3 e3 = int4 (-[1+ 0 ]) (+ 0) (+ 0) (+ 1)

------------------------------------------------------------------------
-- Voight's displayed order-six unit is 1-e3.
------------------------------------------------------------------------

orderSixUnitCoordinates : Int4
orderSixUnitCoordinates = int4 (+ 1) (+ 0) (+ 0) (-[1+ 0 ])

voightUnitIsOneMinusE3 : orderSixUnitCoordinates ≡ int4 (+ 1) (+ 0) (+ 0) (-[1+ 0 ])
voightUnitIsOneMinusE3 = refl

------------------------------------------------------------------------
-- Reduced-trace Gram matrix trd(e_r e_c):
--
-- [ 2  0  3  1 ]
-- [ 0 -8 -4 -1 ]
-- [ 3 -4 -3  1 ]
-- [ 1 -1  1 -1 ]
--
-- Its determinant is -121.
------------------------------------------------------------------------

record TraceGram4 : Set where
  constructor traceGram4
  field
    g00 g01 g02 g03
    g10 g11 g12 g13
    g20 g21 g22 g23
    g30 g31 g32 g33 : ℤ

j0TraceGram : TraceGram4
j0TraceGram = traceGram4
  (+ 2) (+ 0) (+ 3) (+ 1)
  (+ 0) (-[1+ 7 ]) (-[1+ 3 ]) (-[1+ 0 ])
  (+ 3) (-[1+ 3 ]) (-[1+ 2 ]) (+ 1)
  (+ 1) (-[1+ 0 ]) (+ 1) (-[1+ 0 ])

traceGramDeterminant : ℤ
traceGramDeterminant = -[1+ 120 ]

traceGramDeterminantIsMinus121 : traceGramDeterminant ≡ -[1+ 120 ]
traceGramDeterminantIsMinus121 = refl

reducedDiscriminant : Nat
reducedDiscriminant = 11

reducedDiscriminantIsEleven : reducedDiscriminant ≡ 11
reducedDiscriminantIsEleven = refl

------------------------------------------------------------------------
-- Exact scaled quaternion coordinates (denominator 4) of the basis.  These are
-- consumed by the marked norm enumerator rather than re-entered there.
------------------------------------------------------------------------

record QuarterQuaternion : Set where
  constructor quarterQuaternion
  field scalar4 i4 j4 k4 : ℤ

open QuarterQuaternion public

j0BasisQuarterCoordinates : J0OrderBasis → QuarterQuaternion
j0BasisQuarterCoordinates e0 = quarterQuaternion (+ 4) (+ 0) (+ 0) (+ 0)
j0BasisQuarterCoordinates e1 = quarterQuaternion (+ 0) (+ 8) (+ 0) (+ 0)
j0BasisQuarterCoordinates e2 = quarterQuaternion (+ 6) (+ 4) (+ 2) (+ 0)
j0BasisQuarterCoordinates e3 = quarterQuaternion (+ 2) (+ 1) (+ 0) (+ 1)

record P11VoightJ0OrderBoundary : Set where
  field
    voightNonprincipalIdealConsumed : Bool
    voightNonprincipalIdealConsumedIsTrue : voightNonprincipalIdealConsumed ≡ true

    explicitLeftOrderBasisConstructed : Bool
    explicitLeftOrderBasisConstructedIsTrue : explicitLeftOrderBasisConstructed ≡ true

    idealStabilizationMatricesIntegral : Bool
    idealStabilizationMatricesIntegralIsTrue : idealStabilizationMatricesIntegral ≡ true

    multiplicationTableIntegral : Bool
    multiplicationTableIntegralIsTrue : multiplicationTableIntegral ≡ true

    reducedDiscriminantElevenConstructed : Bool
    reducedDiscriminantElevenConstructedIsTrue : reducedDiscriminantElevenConstructed ≡ true

    arbitraryConjugateMaximalOrderInserted : Bool
    arbitraryConjugateMaximalOrderInsertedIsFalse : arbitraryConjugateMaximalOrderInserted ≡ false

canonicalP11VoightJ0OrderBoundary : P11VoightJ0OrderBoundary
canonicalP11VoightJ0OrderBoundary = record
  { voightNonprincipalIdealConsumed = true
  ; voightNonprincipalIdealConsumedIsTrue = refl
  ; explicitLeftOrderBasisConstructed = true
  ; explicitLeftOrderBasisConstructedIsTrue = refl
  ; idealStabilizationMatricesIntegral = true
  ; idealStabilizationMatricesIntegralIsTrue = refl
  ; multiplicationTableIntegral = true
  ; multiplicationTableIntegralIsTrue = refl
  ; reducedDiscriminantElevenConstructed = true
  ; reducedDiscriminantElevenConstructedIsTrue = refl
  ; arbitraryConjugateMaximalOrderInserted = false
  ; arbitraryConjugateMaximalOrderInsertedIsFalse = refl
  }
