module DASHI.Moonshine.P37MarkedLegendreT3T5Exact where

------------------------------------------------------------------------
-- PRIMARY SOURCES / CONTEXT
--
-- Adel Betina and Emmanuel Lecouturier,
-- "Congruence formulae for Legendre modular polynomials",
-- Journal of Number Theory 188 (2018), 71--87.
-- DOI: 10.1016/j.jnt.2018.01.006.
--
-- Josep Gonzalez,
-- "On the p-th division polynomial", Journal of Number Theory 233 (2022),
-- 285--300. DOI: 10.1016/j.jnt.2021.06.011.
--
-- Nicholas M. Katz and Barry Mazur,
-- "Arithmetic Moduli of Elliptic Curves", Princeton, 1985.
-- DOI: 10.1515/9781400881710.
--
-- John Voight,
-- "Quaternion Algebras", Graduate Texts in Mathematics 288, Springer, 2021.
-- DOI: 10.1007/978-3-030-56694-4.
--
-- DASHI CONTRIBUTION
--
-- Construct the actual p=37 prime-to-2 marked Hecke correspondences on the
-- SAME 18 Deuring/full-level-2 roots built in
-- P37NonOggFullLevel2DeuringControlExact.
--
-- The finite table is independently regenerated by
--
--   scripts/verify_p37_legendre_marked_hecke.py
--
-- directly in F_37^2 = F_37[u]/(u^2-2):
--   * derive all 18 roots from the nine irreducible H_37 quadratics;
--   * evaluate the published Legendre modular polynomials F_3 and F_5;
--   * retain root multiplicities via Y-derivatives;
--   * verify every T3 row has multiplicity 4 and every T5 row multiplicity 6;
--   * compute j(lambda) and obtain three six-sheet coarse fibres;
--   * recover exactly
--
--       B37(3) = [[2,1,1],[1,0,3],[1,3,0]],
--       B37(5) = [[2,2,2],[2,1,3],[2,3,1]].
--
-- The Agda table below is compressed by Frobenius: only the nine root0 rows are
-- primitive; every root1 row is obtained by conjugating the corresponding
-- root0 row.  Frobenius equivariance is therefore structural rather than a
-- separately supplied target receipt.
------------------------------------------------------------------------

open import DASHI.Core.Prelude
open import Data.Fin using (Fin; zero; suc)

import DASHI.Moonshine.PositiveFiniteNeighbourSystemExact as Positive
import DASHI.Moonshine.BrandtStackUnweightingControlsExact as Controls
import DASHI.Moonshine.P37NonOggFullLevel2DeuringControlExact as P37
import DASHI.Moonshine.P37SageSupersingularFrobeniusExact as CoarseF

------------------------------------------------------------------------
-- Coarse j(lambda) fibre map obtained by exact finite-field evaluation.
-- The c1/c2 labels are the Frobenius-conjugate Sage Brandt classes; swapping
-- both produces the same symmetric coarse matrices.
------------------------------------------------------------------------

coarseClass : P37.P37SupersingularLambda → Controls.P37BrandtClass
coarseClass (P37.lambda37 P37.q0 P37.root0) = Controls.p37c1
coarseClass (P37.lambda37 P37.q0 P37.root1) = Controls.p37c2
coarseClass (P37.lambda37 P37.q1 P37.root0) = Controls.p37c0
coarseClass (P37.lambda37 P37.q1 P37.root1) = Controls.p37c0
coarseClass (P37.lambda37 P37.q2 P37.root0) = Controls.p37c2
coarseClass (P37.lambda37 P37.q2 P37.root1) = Controls.p37c1
coarseClass (P37.lambda37 P37.q3 P37.root0) = Controls.p37c2
coarseClass (P37.lambda37 P37.q3 P37.root1) = Controls.p37c1
coarseClass (P37.lambda37 P37.q4 P37.root0) = Controls.p37c1
coarseClass (P37.lambda37 P37.q4 P37.root1) = Controls.p37c2
coarseClass (P37.lambda37 P37.q5 P37.root0) = Controls.p37c1
coarseClass (P37.lambda37 P37.q5 P37.root1) = Controls.p37c2
coarseClass (P37.lambda37 P37.q6 P37.root0) = Controls.p37c0
coarseClass (P37.lambda37 P37.q6 P37.root1) = Controls.p37c0
coarseClass (P37.lambda37 P37.q7 P37.root0) = Controls.p37c2
coarseClass (P37.lambda37 P37.q7 P37.root1) = Controls.p37c1
coarseClass (P37.lambda37 P37.q8 P37.root0) = Controls.p37c0
coarseClass (P37.lambda37 P37.q8 P37.root1) = Controls.p37c0

coarseProjectionIntertwinesFrobenius :
  (x : P37.P37SupersingularLambda) →
  coarseClass (P37.p37MarkedFrobenius x)
  ≡ CoarseF.brandtFrobenius (coarseClass x)
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q0 P37.root0) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q0 P37.root1) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q1 P37.root0) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q1 P37.root1) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q2 P37.root0) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q2 P37.root1) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q3 P37.root0) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q3 P37.root1) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q4 P37.root0) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q4 P37.root1) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q5 P37.root0) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q5 P37.root1) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q6 P37.root0) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q6 P37.root1) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q7 P37.root0) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q7 P37.root1) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q8 P37.root0) = refl
coarseProjectionIntertwinesFrobenius (P37.lambda37 P37.q8 P37.root1) = refl

------------------------------------------------------------------------
-- Nine base T3 rows from F_3(lambda_source,Y), including multiplicity.
------------------------------------------------------------------------

baseT3 :
  P37.P37QuadraticFactor → Fin 4 → P37.P37SupersingularLambda
baseT3 P37.q0 zero = P37.lambda37 P37.q0 P37.root1
baseT3 P37.q0 (suc zero) = P37.lambda37 P37.q5 P37.root1
baseT3 P37.q0 (suc (suc zero)) = P37.lambda37 P37.q6 P37.root1
baseT3 P37.q0 (suc (suc (suc zero))) = P37.lambda37 P37.q7 P37.root0
baseT3 P37.q1 zero = P37.lambda37 P37.q1 P37.root1
baseT3 P37.q1 (suc zero) = P37.lambda37 P37.q1 P37.root1
baseT3 P37.q1 (suc (suc zero)) = P37.lambda37 P37.q2 P37.root0
baseT3 P37.q1 (suc (suc (suc zero))) = P37.lambda37 P37.q7 P37.root1
baseT3 P37.q2 zero = P37.lambda37 P37.q1 P37.root0
baseT3 P37.q2 (suc zero) = P37.lambda37 P37.q2 P37.root1
baseT3 P37.q2 (suc (suc zero)) = P37.lambda37 P37.q4 P37.root0
baseT3 P37.q2 (suc (suc (suc zero))) = P37.lambda37 P37.q7 P37.root1
baseT3 P37.q3 zero = P37.lambda37 P37.q3 P37.root1
baseT3 P37.q3 (suc zero) = P37.lambda37 P37.q4 P37.root0
baseT3 P37.q3 (suc (suc zero)) = P37.lambda37 P37.q5 P37.root0
baseT3 P37.q3 (suc (suc (suc zero))) = P37.lambda37 P37.q8 P37.root1
baseT3 P37.q4 zero = P37.lambda37 P37.q2 P37.root0
baseT3 P37.q4 (suc zero) = P37.lambda37 P37.q3 P37.root0
baseT3 P37.q4 (suc (suc zero)) = P37.lambda37 P37.q4 P37.root1
baseT3 P37.q4 (suc (suc (suc zero))) = P37.lambda37 P37.q8 P37.root1
baseT3 P37.q5 zero = P37.lambda37 P37.q0 P37.root1
baseT3 P37.q5 (suc zero) = P37.lambda37 P37.q3 P37.root0
baseT3 P37.q5 (suc (suc zero)) = P37.lambda37 P37.q5 P37.root1
baseT3 P37.q5 (suc (suc (suc zero))) = P37.lambda37 P37.q6 P37.root0
baseT3 P37.q6 zero = P37.lambda37 P37.q0 P37.root1
baseT3 P37.q6 (suc zero) = P37.lambda37 P37.q5 P37.root0
baseT3 P37.q6 (suc (suc zero)) = P37.lambda37 P37.q6 P37.root1
baseT3 P37.q6 (suc (suc (suc zero))) = P37.lambda37 P37.q6 P37.root1
baseT3 P37.q7 zero = P37.lambda37 P37.q0 P37.root0
baseT3 P37.q7 (suc zero) = P37.lambda37 P37.q1 P37.root1
baseT3 P37.q7 (suc (suc zero)) = P37.lambda37 P37.q2 P37.root1
baseT3 P37.q7 (suc (suc (suc zero))) = P37.lambda37 P37.q7 P37.root1
baseT3 P37.q8 zero = P37.lambda37 P37.q3 P37.root1
baseT3 P37.q8 (suc zero) = P37.lambda37 P37.q4 P37.root1
baseT3 P37.q8 (suc (suc zero)) = P37.lambda37 P37.q8 P37.root1
baseT3 P37.q8 (suc (suc (suc zero))) = P37.lambda37 P37.q8 P37.root1

markedT3Neighbour :
  P37.P37SupersingularLambda → Fin 4 → P37.P37SupersingularLambda
markedT3Neighbour (P37.lambda37 q P37.root0) edge = baseT3 q edge
markedT3Neighbour (P37.lambda37 q P37.root1) edge =
  P37.p37MarkedFrobenius (baseT3 q edge)

MarkedT3 : Positive.PositiveFiniteNeighbourSystem P37.P37SupersingularLambda
MarkedT3 = record
  { Positive.arity = 4
  ; Positive.neighbour = markedT3Neighbour
  }

markedT3FrobeniusEquivariant :
  (source : P37.P37SupersingularLambda) → (edge : Fin 4) →
  markedT3Neighbour (P37.p37MarkedFrobenius source) edge
  ≡ P37.p37MarkedFrobenius (markedT3Neighbour source edge)
markedT3FrobeniusEquivariant (P37.lambda37 q P37.root0) edge = refl
markedT3FrobeniusEquivariant (P37.lambda37 q P37.root1) edge =
  sym (P37.p37MarkedFrobeniusInvolution (baseT3 q edge))

------------------------------------------------------------------------
-- Nine base T5 rows from F_5(lambda_source,Y), including multiplicity.
------------------------------------------------------------------------

baseT5 :
  P37.P37QuadraticFactor → Fin 6 → P37.P37SupersingularLambda
baseT5 P37.q0 zero = P37.lambda37 P37.q1 P37.root0
baseT5 P37.q0 (suc zero) = P37.lambda37 P37.q4 P37.root1
baseT5 P37.q0 (suc (suc zero)) = P37.lambda37 P37.q4 P37.root1
baseT5 P37.q0 (suc (suc (suc zero))) = P37.lambda37 P37.q5 P37.root0
baseT5 P37.q0 (suc (suc (suc (suc zero)))) = P37.lambda37 P37.q7 P37.root0
baseT5 P37.q0 (suc (suc (suc (suc (suc zero))))) = P37.lambda37 P37.q8 P37.root0
baseT5 P37.q1 zero = P37.lambda37 P37.q0 P37.root0
baseT5 P37.q1 (suc zero) = P37.lambda37 P37.q3 P37.root0
baseT5 P37.q1 (suc (suc zero)) = P37.lambda37 P37.q4 P37.root1
baseT5 P37.q1 (suc (suc (suc zero))) = P37.lambda37 P37.q5 P37.root0
baseT5 P37.q1 (suc (suc (suc (suc zero)))) = P37.lambda37 P37.q6 P37.root0
baseT5 P37.q1 (suc (suc (suc (suc (suc zero))))) = P37.lambda37 P37.q8 P37.root1
baseT5 P37.q2 zero = P37.lambda37 P37.q4 P37.root0
baseT5 P37.q2 (suc zero) = P37.lambda37 P37.q5 P37.root0
baseT5 P37.q2 (suc (suc zero)) = P37.lambda37 P37.q5 P37.root0
baseT5 P37.q2 (suc (suc (suc zero))) = P37.lambda37 P37.q6 P37.root0
baseT5 P37.q2 (suc (suc (suc (suc zero)))) = P37.lambda37 P37.q7 P37.root0
baseT5 P37.q2 (suc (suc (suc (suc (suc zero))))) = P37.lambda37 P37.q8 P37.root0
baseT5 P37.q3 zero = P37.lambda37 P37.q1 P37.root0
baseT5 P37.q3 (suc zero) = P37.lambda37 P37.q4 P37.root1
baseT5 P37.q3 (suc (suc zero)) = P37.lambda37 P37.q5 P37.root0
baseT5 P37.q3 (suc (suc (suc zero))) = P37.lambda37 P37.q6 P37.root1
baseT5 P37.q3 (suc (suc (suc (suc zero)))) = P37.lambda37 P37.q7 P37.root1
baseT5 P37.q3 (suc (suc (suc (suc (suc zero))))) = P37.lambda37 P37.q7 P37.root1
baseT5 P37.q4 zero = P37.lambda37 P37.q0 P37.root1
baseT5 P37.q4 (suc zero) = P37.lambda37 P37.q0 P37.root1
baseT5 P37.q4 (suc (suc zero)) = P37.lambda37 P37.q1 P37.root1
baseT5 P37.q4 (suc (suc (suc zero))) = P37.lambda37 P37.q2 P37.root0
baseT5 P37.q4 (suc (suc (suc (suc zero)))) = P37.lambda37 P37.q3 P37.root1
baseT5 P37.q4 (suc (suc (suc (suc (suc zero))))) = P37.lambda37 P37.q6 P37.root0
baseT5 P37.q5 zero = P37.lambda37 P37.q0 P37.root0
baseT5 P37.q5 (suc zero) = P37.lambda37 P37.q1 P37.root0
baseT5 P37.q5 (suc (suc zero)) = P37.lambda37 P37.q2 P37.root0
baseT5 P37.q5 (suc (suc (suc zero))) = P37.lambda37 P37.q2 P37.root0
baseT5 P37.q5 (suc (suc (suc (suc zero)))) = P37.lambda37 P37.q3 P37.root0
baseT5 P37.q5 (suc (suc (suc (suc (suc zero))))) = P37.lambda37 P37.q8 P37.root0
baseT5 P37.q6 zero = P37.lambda37 P37.q1 P37.root0
baseT5 P37.q6 (suc zero) = P37.lambda37 P37.q2 P37.root0
baseT5 P37.q6 (suc (suc zero)) = P37.lambda37 P37.q3 P37.root1
baseT5 P37.q6 (suc (suc (suc zero))) = P37.lambda37 P37.q4 P37.root0
baseT5 P37.q6 (suc (suc (suc (suc zero)))) = P37.lambda37 P37.q7 P37.root0
baseT5 P37.q6 (suc (suc (suc (suc (suc zero))))) = P37.lambda37 P37.q8 P37.root1
baseT5 P37.q7 zero = P37.lambda37 P37.q0 P37.root0
baseT5 P37.q7 (suc zero) = P37.lambda37 P37.q2 P37.root0
baseT5 P37.q7 (suc (suc zero)) = P37.lambda37 P37.q3 P37.root1
baseT5 P37.q7 (suc (suc (suc zero))) = P37.lambda37 P37.q3 P37.root1
baseT5 P37.q7 (suc (suc (suc (suc zero)))) = P37.lambda37 P37.q6 P37.root0
baseT5 P37.q7 (suc (suc (suc (suc (suc zero))))) = P37.lambda37 P37.q8 P37.root0
baseT5 P37.q8 zero = P37.lambda37 P37.q0 P37.root0
baseT5 P37.q8 (suc zero) = P37.lambda37 P37.q1 P37.root1
baseT5 P37.q8 (suc (suc zero)) = P37.lambda37 P37.q2 P37.root0
baseT5 P37.q8 (suc (suc (suc zero))) = P37.lambda37 P37.q5 P37.root0
baseT5 P37.q8 (suc (suc (suc (suc zero)))) = P37.lambda37 P37.q6 P37.root1
baseT5 P37.q8 (suc (suc (suc (suc (suc zero))))) = P37.lambda37 P37.q7 P37.root0

markedT5Neighbour :
  P37.P37SupersingularLambda → Fin 6 → P37.P37SupersingularLambda
markedT5Neighbour (P37.lambda37 q P37.root0) edge = baseT5 q edge
markedT5Neighbour (P37.lambda37 q P37.root1) edge =
  P37.p37MarkedFrobenius (baseT5 q edge)

MarkedT5 : Positive.PositiveFiniteNeighbourSystem P37.P37SupersingularLambda
MarkedT5 = record
  { Positive.arity = 6
  ; Positive.neighbour = markedT5Neighbour
  }

markedT5FrobeniusEquivariant :
  (source : P37.P37SupersingularLambda) → (edge : Fin 6) →
  markedT5Neighbour (P37.p37MarkedFrobenius source) edge
  ≡ P37.p37MarkedFrobenius (markedT5Neighbour source edge)
markedT5FrobeniusEquivariant (P37.lambda37 q P37.root0) edge = refl
markedT5FrobeniusEquivariant (P37.lambda37 q P37.root1) edge =
  sym (P37.p37MarkedFrobeniusInvolution (baseT5 q edge))

------------------------------------------------------------------------
-- Multiplicity is visible in the finite geometry, not erased to a set relation.
------------------------------------------------------------------------

t3DoubleRootWitness :
  markedT3Neighbour (P37.lambda37 P37.q1 P37.root0) zero
  ≡ markedT3Neighbour (P37.lambda37 P37.q1 P37.root0) (suc zero)
t3DoubleRootWitness = refl

t5DoubleRootWitness :
  markedT5Neighbour (P37.lambda37 P37.q0 P37.root0) (suc zero)
  ≡ markedT5Neighbour
      (P37.lambda37 P37.q0 P37.root0)
      (suc (suc zero))
t5DoubleRootWitness = refl

------------------------------------------------------------------------
-- Exact coarse projection by actual edge counting.
------------------------------------------------------------------------

isCoarse0 : P37.P37SupersingularLambda → Nat
isCoarse0 x with coarseClass x
... | Controls.p37c0 = 1
... | Controls.p37c1 = 0
... | Controls.p37c2 = 0

isCoarse1 : P37.P37SupersingularLambda → Nat
isCoarse1 x with coarseClass x
... | Controls.p37c0 = 0
... | Controls.p37c1 = 1
... | Controls.p37c2 = 0

isCoarse2 : P37.P37SupersingularLambda → Nat
isCoarse2 x with coarseClass x
... | Controls.p37c0 = 0
... | Controls.p37c1 = 0
... | Controls.p37c2 = 1

record CoarseRow : Set where
  constructor coarseRow
  field
    to0 to1 to2 : Nat

open CoarseRow public

markedT3CoarseRow : P37.P37SupersingularLambda → CoarseRow
markedT3CoarseRow x = coarseRow
  (Positive.positiveOperator MarkedT3 isCoarse0 x)
  (Positive.positiveOperator MarkedT3 isCoarse1 x)
  (Positive.positiveOperator MarkedT3 isCoarse2 x)

markedT5CoarseRow : P37.P37SupersingularLambda → CoarseRow
markedT5CoarseRow x = coarseRow
  (Positive.positiveOperator MarkedT5 isCoarse0 x)
  (Positive.positiveOperator MarkedT5 isCoarse1 x)
  (Positive.positiveOperator MarkedT5 isCoarse2 x)

expectedT3Row : Controls.P37BrandtClass → CoarseRow
expectedT3Row Controls.p37c0 = coarseRow 2 1 1
expectedT3Row Controls.p37c1 = coarseRow 1 0 3
expectedT3Row Controls.p37c2 = coarseRow 1 3 0

expectedT5Row : Controls.P37BrandtClass → CoarseRow
expectedT5Row Controls.p37c0 = coarseRow 2 2 2
expectedT5Row Controls.p37c1 = coarseRow 2 1 3
expectedT5Row Controls.p37c2 = coarseRow 2 3 1

markedT3ProjectsToCoarse :
  (x : P37.P37SupersingularLambda) →
  markedT3CoarseRow x ≡ expectedT3Row (coarseClass x)
markedT3ProjectsToCoarse (P37.lambda37 P37.q0 P37.root0) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q0 P37.root1) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q1 P37.root0) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q1 P37.root1) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q2 P37.root0) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q2 P37.root1) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q3 P37.root0) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q3 P37.root1) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q4 P37.root0) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q4 P37.root1) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q5 P37.root0) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q5 P37.root1) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q6 P37.root0) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q6 P37.root1) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q7 P37.root0) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q7 P37.root1) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q8 P37.root0) = refl
markedT3ProjectsToCoarse (P37.lambda37 P37.q8 P37.root1) = refl

markedT5ProjectsToCoarse :
  (x : P37.P37SupersingularLambda) →
  markedT5CoarseRow x ≡ expectedT5Row (coarseClass x)
markedT5ProjectsToCoarse (P37.lambda37 P37.q0 P37.root0) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q0 P37.root1) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q1 P37.root0) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q1 P37.root1) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q2 P37.root0) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q2 P37.root1) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q3 P37.root0) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q3 P37.root1) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q4 P37.root0) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q4 P37.root1) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q5 P37.root0) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q5 P37.root1) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q6 P37.root0) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q6 P37.root1) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q7 P37.root0) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q7 P37.root1) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q8 P37.root0) = refl
markedT5ProjectsToCoarse (P37.lambda37 P37.q8 P37.root1) = refl

record P37MarkedLegendreT3T5Boundary : Set where
  field
    actualEighteenStateDeuringCarrierConsumed : Bool
    actualEighteenStateDeuringCarrierConsumedIsTrue :
      actualEighteenStateDeuringCarrierConsumed ≡ true

    legendreT3MultiplicityGeometryConstructed : Bool
    legendreT3MultiplicityGeometryConstructedIsTrue :
      legendreT3MultiplicityGeometryConstructed ≡ true

    legendreT5MultiplicityGeometryConstructed : Bool
    legendreT5MultiplicityGeometryConstructedIsTrue :
      legendreT5MultiplicityGeometryConstructed ≡ true

    frobeniusEquivarianceStructural : Bool
    frobeniusEquivarianceStructuralIsTrue :
      frobeniusEquivarianceStructural ≡ true

    exactCoarseB37T3T5Recovered : Bool
    exactCoarseB37T3T5RecoveredIsTrue :
      exactCoarseB37T3T5Recovered ≡ true

    independentFiniteFieldVerifierIncluded : Bool
    independentFiniteFieldVerifierIncludedIsTrue :
      independentFiniteFieldVerifierIncluded ≡ true

canonicalP37MarkedLegendreT3T5Boundary : P37MarkedLegendreT3T5Boundary
canonicalP37MarkedLegendreT3T5Boundary = record
  { actualEighteenStateDeuringCarrierConsumed = true
  ; actualEighteenStateDeuringCarrierConsumedIsTrue = refl
  ; legendreT3MultiplicityGeometryConstructed = true
  ; legendreT3MultiplicityGeometryConstructedIsTrue = refl
  ; legendreT5MultiplicityGeometryConstructed = true
  ; legendreT5MultiplicityGeometryConstructedIsTrue = refl
  ; frobeniusEquivarianceStructural = true
  ; frobeniusEquivarianceStructuralIsTrue = refl
  ; exactCoarseB37T3T5Recovered = true
  ; exactCoarseB37T3T5RecoveredIsTrue = refl
  ; independentFiniteFieldVerifierIncluded = true
  ; independentFiniteFieldVerifierIncludedIsTrue = refl
  }
