module DASHI.Wikimedia.IbrahimSnowballMemoryRepetitionSourceDependencyConsensusBidiExact where

open import DASHI.Core.Prelude
open import Agda.Builtin.Bool using (Bool; true; false)
open import Agda.Builtin.Equality using (refl)
open import Agda.Builtin.String using (String)
open import Data.Empty using (⊥)

import DASHI.Core.IntersectionalNonFactorability as INF
import DASHI.Core.AttributedSourceCore as Attribution
import DASHI.Wikimedia.SnowballExternalIdentityAvailabilityExact as Identity
import DASHI.Wikimedia.IbrahimSnowballSymbolicVerificationDeweyQidDoiBidiExact as Dewey
import DASHI.Wikimedia.IbrahimSnowballLearningMemoryTraumaReplicationConsensusBidiExact as MemoryReplication
import DASHI.Wikimedia.IbrahimSnowballTestimonyMemoryCredibilityCorroborationExpertBidiExact as Testimony
import DASHI.Wikimedia.IbrahimSnowballSocialInfluenceConsentCoercionPrimarySourcesExact as SocialInfluence
import DASHI.Wikimedia.IbrahimSnowballConspiracyDistrustAlternativeMediaBidiExact as Media

------------------------------------------------------------------------
-- IBRAHIM / MEMORY-REPETITION / SOURCE-DEPENDENCY / CONSENSUS BIDI
--
-- A repeated public surface may be generated by repeated retrieval from one
-- memory/source, social copying, common datasets/code, shared instruments, or
-- genuinely independent observations.  Multiplicity therefore cannot pay
-- evidential independence by itself.  Conversely, dependence does not make a
-- source worthless: it changes the evidential weight and must remain explicit.
------------------------------------------------------------------------

mkQid : String → String → Identity.ExternalIdentityDemand
mkQid label qid = Identity.mkOptionalIdentityDemand
  "Ibrahim memory/repetition/source-dependency/consensus BIDI"
  "verified external identity only"
  label Identity.wikidataQid
  (Identity.verified qid
    "Wikidata identity inspected 2026-09-11; identity does not create provenance independence, replication success, consensus truth or source authority")

memoryQid : Identity.ExternalIdentityDemand
memoryQid = MemoryReplication.memoryQid

reproducibilityQid : Identity.ExternalIdentityDemand
reproducibilityQid = MemoryReplication.reproducibilityQid

scientificConsensusQid : Identity.ExternalIdentityDemand
scientificConsensusQid = MemoryReplication.scientificConsensusQid

consensusQid : Identity.ExternalIdentityDemand
consensusQid = mkQid "consensus" "Q202722"

sourceIndependenceQid : Identity.ExternalIdentityDemand
sourceIndependenceQid = Identity.mkOptionalIdentityDemand
  "Ibrahim memory/repetition/source-dependency/consensus BIDI"
  "external concept identity"
  "evidential/source independence and common-source dependence"
  Identity.wikidataQid
  (Identity.unresolved
    "no exact general QID promoted; statistical independence, source independence, social independence and replication independence remain consumer-distinct")

scientificReplicationQid : Identity.ExternalIdentityDemand
scientificReplicationQid = Identity.mkOptionalIdentityDemand
  "Ibrahim memory/repetition/source-dependency/consensus BIDI"
  "external concept identity"
  "scientific replication / replicability distinct from reproducibility"
  Identity.wikidataQid
  (Identity.unresolved
    "Wikidata reproducibility Q1425625 is explicit and distinct from replicability; no separate exact replication identity promoted in this pass")

------------------------------------------------------------------------
-- Dewey stays a navigation coordinate. No nearby value is inferred merely
-- from memory, reproducibility, consensus or evidence adjacency.
------------------------------------------------------------------------

memoryDewey : Dewey.DeweyCoordinate
memoryDewey = MemoryReplication.memoryDewey

reproducibilityDewey : Dewey.DeweyCoordinate
reproducibilityDewey = MemoryReplication.reproducibilityDewey

scientificConsensusDewey : Dewey.DeweyCoordinate
scientificConsensusDewey = MemoryReplication.scientificConsensusDewey

sourceDependencyDewey : Dewey.DeweyCoordinate
sourceDependencyDewey = Dewey.mkUnresolvedDewey
  "evidential/source dependence"
  "no exact inspected DDC value promoted; dependence occurs across law, psychology, science, media and statistics"

------------------------------------------------------------------------
-- DOI-bounded scholarship paying the dependency / replication / consensus seam.
------------------------------------------------------------------------

pilditchDependencySource : Attribution.AttributedSource
pilditchDependencySource = Attribution.mkDOISource
  "Toby D. Pilditch; Ulrike Hahn; David Lagnado"
  "The problem of dependency"
  "Synthese 205, 143"
  "2025"
  "10.1007/s11229-025-04969-w"
  "https://doi.org/10.1007/s11229-025-04969-w"
  Attribution.academicArticleSource
  "analysis of evidential non-independence across testimony, measurement and social networks; dependence changes evidential aggregation and must not be flattened into simple source count"
  Attribution.publicAttribution

connorDesaiConsensusSource : Attribution.AttributedSource
connorDesaiConsensusSource = Attribution.mkDOISource
  "Saoirse Connor Desai; Jacqueline Fai; Jaimie Lee; Brett K. Hayes"
  "Explaining away the illusion of consensus"
  "Memory & Cognition 54, 1667-1687"
  "2026"
  "10.3758/s13421-025-01831-9"
  "https://doi.org/10.3758/s13421-025-01831-9"
  Attribution.academicArticleSource
  "experimental evidence concerning dependent versus independent consensus and the tendency to over-credit repeated information from one origin; source role is cognitive evidence, not a universal social-network theorem"
  Attribution.publicAttribution

tynerReplicationSource : Attribution.AttributedSource
tynerReplicationSource = Attribution.mkDOISource
  "Andrew H. Tyner et al."
  "Investigating the replicability of the social and behavioural sciences"
  "Nature 652, 143-150"
  "2026"
  "10.1038/s41586-025-10078-y"
  "https://doi.org/10.1038/s41586-025-10078-y"
  Attribution.academicArticleSource
  "large coordinated replication project across social and behavioural science claims; replication outcomes depend on claim, method and criterion and do not reduce to publication count"
  Attribution.publicAttribution

havenIoannidisSource : Attribution.AttributedSource
havenIoannidisSource = Attribution.mkDOISource
  "Tamarinde L. Haven; John P. A. Ioannidis"
  "Reproducibility Failure in Biomedical Research: Problems and Solutions"
  "Annual Review of Medicine 77, 537-549"
  "2026"
  "10.1146/annurev-med-050124-050859"
  "https://doi.org/10.1146/annurev-med-050124-050859"
  Attribution.academicArticleSource
  "review of methodological, reporting and institutional contributors to irreproducibility; reproducibility failure is not represented as one universal mechanism"
  Attribution.publicAttribution

------------------------------------------------------------------------
-- Exact reuse of the immediately prior memory/replication and testimony owners.
------------------------------------------------------------------------

memoryReplicationBoundary : MemoryReplication.LearningMemoryTraumaReplicationConsensusBoundary
memoryReplicationBoundary = MemoryReplication.canonicalLearningMemoryTraumaReplicationConsensusBoundary

testimonyBoundary : Testimony.TestimonyMemoryCredibilityBoundary
testimonyBoundary = Testimony.canonicalTestimonyMemoryCredibilityBoundary

------------------------------------------------------------------------
-- Regression 1: count/repetition cannot recover dependency genealogy.
------------------------------------------------------------------------

data RepetitionCase : Set where
  sameCountIndependentOrigins sameCountOneCommonOrigin : RepetitionCase

data RepetitionSurface : Set where sameRepeatedClaimCount : RepetitionSurface
data DependencyGenealogy : Set where independentOrigins commonOriginDependence : DependencyGenealogy

repetitionSurface : RepetitionCase → RepetitionSurface
repetitionSurface _ = sameRepeatedClaimCount

dependencyGenealogy : RepetitionCase → DependencyGenealogy
dependencyGenealogy sameCountIndependentOrigins = independentOrigins
dependencyGenealogy sameCountOneCommonOrigin = commonOriginDependence

repetitionDependencyDefect : INF.NonFactorabilityWitness repetitionSurface dependencyGenealogy
repetitionDependencyDefect = INF.nonFactorabilityWitness
  sameCountIndependentOrigins sameCountOneCommonOrigin refl (λ ())

repetitionCountCannotFactorDependency :
  INF.FactorsThrough repetitionSurface dependencyGenealogy → ⊥
repetitionCountCannotFactorDependency =
  INF.witnessRulesOutEveryFlatFactorisation repetitionDependencyDefect

------------------------------------------------------------------------
-- Regression 2: agreement surface cannot recover independent consensus.
------------------------------------------------------------------------

data AgreementCase : Set where
  sameAgreementIndependentConsensus sameAgreementEchoConsensus : AgreementCase

data AgreementSurface : Set where sameObservedAgreement : AgreementSurface
data ConsensusIndependence : Set where independentlySupportedConsensus echoOrCommonSourceConsensus : ConsensusIndependence

agreementSurface : AgreementCase → AgreementSurface
agreementSurface _ = sameObservedAgreement

consensusIndependence : AgreementCase → ConsensusIndependence
consensusIndependence sameAgreementIndependentConsensus = independentlySupportedConsensus
consensusIndependence sameAgreementEchoConsensus = echoOrCommonSourceConsensus

agreementIndependenceDefect : INF.NonFactorabilityWitness agreementSurface consensusIndependence
agreementIndependenceDefect = INF.nonFactorabilityWitness
  sameAgreementIndependentConsensus sameAgreementEchoConsensus refl (λ ())

agreementCannotFactorIndependentConsensus :
  INF.FactorsThrough agreementSurface consensusIndependence → ⊥
agreementCannotFactorIndependentConsensus =
  INF.witnessRulesOutEveryFlatFactorisation agreementIndependenceDefect

------------------------------------------------------------------------
-- Regression 3: reproduced public output cannot recover latent generation path.
-- This is the direct Learning/Memory Hyperfabric cross-pollination: equal public
-- remembered PNFs can coexist with different underlying states; equal outputs
-- likewise do not establish independent generation.
------------------------------------------------------------------------

data OutputCase : Set where
  sameOutputIndependentGeneration sameOutputSharedGenerationPath : OutputCase

data OutputSurface : Set where samePublicOutput : OutputSurface
data GenerationPath : Set where independentGeneration sharedGenerationPath : GenerationPath

outputSurface : OutputCase → OutputSurface
outputSurface _ = samePublicOutput

generationPath : OutputCase → GenerationPath
generationPath sameOutputIndependentGeneration = independentGeneration
generationPath sameOutputSharedGenerationPath = sharedGenerationPath

outputGenerationDefect : INF.NonFactorabilityWitness outputSurface generationPath
outputGenerationDefect = INF.nonFactorabilityWitness
  sameOutputIndependentGeneration sameOutputSharedGenerationPath refl (λ ())

sameOutputCannotFactorGenerationIndependence :
  INF.FactorsThrough outputSurface generationPath → ⊥
sameOutputCannotFactorGenerationIndependence =
  INF.witnessRulesOutEveryFlatFactorisation outputGenerationDefect

------------------------------------------------------------------------
-- Regression 4: dependency status cannot recover evidential value as zero/nonzero.
-- Dependence requires modelling; it does not justify silently discarding all
-- dependent evidence, just as common context in memory does not erase the event.
------------------------------------------------------------------------

data DependentEvidenceCase : Set where
  sameDependentStatusAddsSomeInformation sameDependentStatusFullyRedundant : DependentEvidenceCase

data DependentSurface : Set where dependentEvidence : DependentSurface
data EvidentialContribution : Set where partialInformation fullyRedundant : EvidentialContribution

dependentSurface : DependentEvidenceCase → DependentSurface
dependentSurface _ = dependentEvidence

evidentialContribution : DependentEvidenceCase → EvidentialContribution
evidentialContribution sameDependentStatusAddsSomeInformation = partialInformation
evidentialContribution sameDependentStatusFullyRedundant = fullyRedundant

dependencyValueDefect : INF.NonFactorabilityWitness dependentSurface evidentialContribution
dependencyValueDefect = INF.nonFactorabilityWitness
  sameDependentStatusAddsSomeInformation sameDependentStatusFullyRedundant refl (λ ())

dependencyLabelCannotFactorEvidentialContribution :
  INF.FactorsThrough dependentSurface evidentialContribution → ⊥
dependencyLabelCannotFactorEvidentialContribution =
  INF.witnessRulesOutEveryFlatFactorisation dependencyValueDefect

------------------------------------------------------------------------
-- Reverse BIDI constraints back into Ibrahim parent nodes.
------------------------------------------------------------------------

record DependencyConsensusReverseConstraint : Set where
  constructor dependency-consensus-reverse-constraint
  field
    parentNode : String
    distinctionForcedUpward : String
    parentMayEraseDistinction : Bool
open DependencyConsensusReverseConstraint public

memoryLearningConstraint : DependencyConsensusReverseConstraint
memoryLearningConstraint = dependency-consensus-reverse-constraint
  "Memory / learning"
  "repeated retrieval, remembered semantic equality, latent state, context history and source of later information remain separate"
  false

scienceConstraint : DependencyConsensusReverseConstraint
scienceConstraint = dependency-consensus-reverse-constraint
  "Replication / reproducibility / scientific consensus"
  "same output, same method, independent team/data, common-source dependence, replication criterion and consensus remain separate"
  false

mediaConstraint : DependencyConsensusReverseConstraint
mediaConstraint = dependency-consensus-reverse-constraint
  "Media / social influence"
  "article/post count, originating report, copying, social transmission, audience exposure and independent corroboration remain separate"
  false

lawConstraint : DependencyConsensusReverseConstraint
lawConstraint = dependency-consensus-reverse-constraint
  "Evidence / testimony"
  "number of witnesses/reports, informational dependence, common interrogation/source, credibility and evidential contribution remain separate"
  false

------------------------------------------------------------------------
-- No-promotion gates.
------------------------------------------------------------------------

data RepetitionCreatesIndependence : Set where
data AgreementCreatesIndependentConsensus : Set where
data SameOutputCreatesIndependentReplication : Set where
data DependenceMeansNoEvidence : Set where
data ConsensusCreatesTruth : Set where
data ReproducibilityCreatesTruth : Set where
data QidCreatesIndependence : Set where

repetitionDoesNotCreateIndependence : RepetitionCreatesIndependence → ⊥
repetitionDoesNotCreateIndependence ()

agreementDoesNotCreateIndependentConsensus : AgreementCreatesIndependentConsensus → ⊥
agreementDoesNotCreateIndependentConsensus ()

sameOutputDoesNotCreateIndependentReplication : SameOutputCreatesIndependentReplication → ⊥
sameOutputDoesNotCreateIndependentReplication ()

dependenceDoesNotMeanNoEvidence : DependenceMeansNoEvidence → ⊥
dependenceDoesNotMeanNoEvidence ()

consensusDoesNotCreateTruth : ConsensusCreatesTruth → ⊥
consensusDoesNotCreateTruth ()

reproducibilityDoesNotCreateTruth : ReproducibilityCreatesTruth → ⊥
reproducibilityDoesNotCreateTruth ()

qidDoesNotCreateIndependence : QidCreatesIndependence → ⊥
qidDoesNotCreateIndependence ()

record MemoryRepetitionSourceDependencyConsensusBoundary : Set where
  constructor memory-repetition-source-dependency-consensus-boundary
  field
    qidsRetainedAsIdentityOnly : Bool
    unresolvedIndependenceQidRetained : Bool
    deweyRetainedAsNavigationOnly : Bool
    doiAndSourceRoleRetained : Bool
    repetitionSeparatedFromIndependence : Bool
    agreementSeparatedFromIndependentConsensus : Bool
    outputEqualitySeparatedFromIndependentGeneration : Bool
    dependenceSeparatedFromZeroEvidence : Bool
    memoryHyperfabricCrossPollinated : Bool
    testimonyAndMediaDependencyCrossPollinated : Bool
    reverseBidiConstraintsPropagateUpward : Bool
    presentAxisVocabularyClaimedComplete : Bool
open MemoryRepetitionSourceDependencyConsensusBoundary public

canonicalMemoryRepetitionSourceDependencyConsensusBoundary :
  MemoryRepetitionSourceDependencyConsensusBoundary
canonicalMemoryRepetitionSourceDependencyConsensusBoundary =
  memory-repetition-source-dependency-consensus-boundary
    true true true true true true true true true true true false
