module DASHI.Physics.Closure.NSTriadKNClayFrontierRound120Validation where

import DASHI.Physics.Closure.NSTriadKNClayFrontierRound117Validation
import DASHI.Physics.Closure.NSTriadKNExternalPureCommutatorPartnerRound120Exact
import DASHI.Physics.Closure.NSTriadKNClayFrontierRound120Exact
import DASHI.Papers.NavierStokes.TheoremInterfaceRound120Exact
