module DASHI.Physics.Closure.NSTriadKNClayFrontierRound115Validation where

import DASHI.Physics.Closure.NSTriadKNClayFrontierRound114Validation
import DASHI.Physics.Closure.NSTriadKNExternalWaleffeQuarticCellExpansionRound115Exact
import DASHI.Physics.Closure.NSTriadKNClayFrontierRound115Exact
import DASHI.Papers.NavierStokes.TheoremInterfaceRound115Exact
