module DASHI.Physics.Closure.NSTriadKNClayFrontierRound149Validation where

import DASHI.Physics.Closure.NSTriadKNHelicitySignNormalizedCurlRound142Exact
import DASHI.Physics.Closure.NSTriadKNHelicityWalshNormalizedCurlWeldRound143Exact
import DASHI.Physics.Closure.NSTriadKNCriticalNormalizedCurlDoubleCommutatorRound144Exact
import DASHI.Physics.Closure.NSTriadKNAntiParallelHelicitySlotKernelRound145Exact
import DASHI.Physics.Closure.NSTriadKNHHAntiParallelDefectSquareRound146Exact
import DASHI.Physics.Closure.NSTriadKNCriticalNormalizedCurlRadiusCancellationRound147Exact
import DASHI.Physics.Closure.NSTriadKNCriticalSimonUpgradeFollowsBarrierRound148Exact
import DASHI.Physics.Closure.NSTriadKNClayFrontierRound149Exact
