/- Attribution: JMD (github.com/meta-introspector) -/
/-!
# An Agda prelude for Lean 4

The upstream DASHI development (`chboishabba/dashi_agda`) is written in a small,
very regular fragment of Agda: `data`, `record`, top-level signature-plus-clause
definitions, propositional equality with `refl`, `List`, `Bool`, `String`, `Nat`,
and the empty type.  This module supplies the *vocabulary* of that fragment as
Lean definitions and notation; `RequestProject.Agda.Syntax` supplies the
*grammar*.

Everything here lives in the `Agda` namespace and the notation is `scoped`, so
using it is opt-in and nothing in the rest of the development changes meaning.
Nothing here is a new axiom or a new mathematical object: each Agda name is
*definitionally* the Lean one, and the theorems at the bottom of the file check
that, so the correspondence is verified rather than asserted.

The module deliberately imports nothing: the Agda fragment needs only the Lean
core types, and staying clear of Mathlib keeps names such as `Set` unambiguous
inside a transliterated module.
-/

/-! ### Provenance (generated by `tools/provenance.py`)

Source mix of this module's 46 declarations: 0 traced to the DASHI Agda
bridge (`chboishabba/dashi_agda` PR #555 / #581 / #582), 0 rendering the Wikidata
data model, 46 original to this port.  The bridge-traced declarations are
marked with `-- @source` below.  Full ledger: `docs/status/PROVENANCE.md`.
-/

namespace Agda

/-! ## Universes -/

/-- Agda's `Set` is Lean's `Type`. -/
abbrev Set := Type

/-- Agda's `Set₁`. -/
abbrev Set₁ := Type 1

/-- Agda's `Set₂`. -/
abbrev Set₂ := Type 2

/-- Agda's `Setω`.

Lean's universe hierarchy stops short of Agda's `Setω`, so there is no exact
rendering.  What `Setω` is used for in the upstream corpus is the sort of a
record that collects results living in several fixed universes, all of them
small, and a fixed universe above those is enough for that.  The rendering is
therefore `Type 3`, and it is *checked*: if a transliterated record has a field
that does not fit below it, Lean rejects the declaration rather than accepting a
weaker reading of it. -/
abbrev Setω := Type 3

/-- Agda's `Level`.

Agda's universe levels are terms, and Lean's are not.  An *implicit* level
binder `{ℓ : Level}` is therefore deleted and the declaration is checked as the
Lean universe-polymorphic one; an *explicit* one `(ℓ : Level)` has to stay,
because the applications in the Agda source pass it, and it is this one-point
type.  A sort written with such a level is then the lowest universe that fits:
`Set ℓ` is `Type`, `Set (lsuc ℓ)` is `Type 1`.  The reading is weaker than
Agda's, which is why it is written down here. -/
abbrev Level := Unit

/-- Agda's `lzero`. -/
abbrev lzero : Level := ()

/-- Agda's `lsuc`. -/
abbrev lsuc (_ : Level) : Level := ()

/-- The Agda fragment's `_⊔_`.

Agda spells both the maximum of two universe levels and the maximum of two
naturals `_⊔_`, so the notation here is resolved by type: `Level ⊔ Level` is the
one-point level and `Nat ⊔ Nat` is `Nat.max`. -/
class AgdaSup (α : Sort u) where
  /-- The operation `_⊔_` denotes at type `α`. -/
  sup : α → α → α

instance : AgdaSup Level := ⟨fun _ _ => ()⟩

instance : AgdaSup Nat := ⟨Nat.max⟩

@[inherit_doc AgdaSup] scoped infixl:65 " ⊔ " => AgdaSup.sup

/-! ## Propositional equality

Agda's `_≡_` is the same inductive family as Lean's `Eq`; we give it Agda's
name and Agda's spelling of the standard lemmas. -/

@[inherit_doc Eq]
scoped infix:40 " ≡ " => Eq

/-- Agda's `refl`.

It is a `@[match_pattern]`, so a transliterated clause may match on it: a
definition such as `sym refl = refl` is Lean's `| rfl => rfl`. -/
@[match_pattern] abbrev refl {α : Sort u} {a : α} : a = a := rfl

/-- Agda's `sym`. -/
abbrev sym {α : Sort u} {a b : α} (h : a = b) : b = a := h.symm

/-- Agda's `trans`. -/
abbrev trans {α : Sort u} {a b c : α} (h₁ : a = b) (h₂ : b = c) : a = c := h₁.trans h₂

/-- Agda's `cong`. -/
abbrev cong {α : Sort u} {β : Sort v} (f : α → β) {a b : α} (h : a = b) : f a = f b :=
  congrArg f h

/-- Agda's `subst`. -/
abbrev subst {α : Sort u} (P : α → Prop) {a b : α} (h : a = b) (p : P a) : P b :=
  h ▸ p

/-! ## The empty and unit types

Agda's `⊥` is a *type* with no constructors, living in `Set`, and negation is
`A → ⊥`.  Lean's `Empty` is that same type, so `⊥` is `Empty` here.  The
propositional `False` would also carry the upstream proofs, but it lives in
`Prop`, and an Agda abbreviation declared to land in `Set` — `¬_ : Set → Set`,
or `x ≢ y = x ≡ y → ⊥` — then does not typecheck.  Since Agda has no `Prop`,
`Empty` is both the faithful reading and the one the corpus needs; a negation of
a Lean proposition is recovered from it by `not_of_arrow_bot` below.

`⊤` is likewise the *trivial datum* — a record field of type `⊤`, a `Set`-valued
function returning `⊤` — so `⊤` is `Unit` and `tt` its inhabitant. -/

/-- Agda's `⊥`. -/
scoped notation "⊥" => Empty

/-- Agda's `⊤`. -/
scoped notation "⊤" => Unit

/-- Agda's `⊥-elim`. -/
abbrev «⊥-elim» {α : Sort u} (h : Empty) : α := h.elim

/-! ## Lists, pairs, options

These are Lean's own types; only some operators are spelled differently. -/

/-- Agda's `_∷_`. -/
scoped infixr:67 " ∷ " => List.cons

/-- Agda's `_,_`, the pair constructor of `Data.Product`.

Lean spells a pair `(a, b)`, but its comma is part of the bracket notation and
not an operator: `fun x => a, b` is a *pair of a function and a term*, where
Agda's `λ x → a , b` is a function returning a pair, and `f x = a , b` is not a
Lean definition at all.  Agda's pair comma is therefore an infix operator here,
binding looser than anything else, which is what Agda's fixity says. -/
scoped infixr:2 " ,ᴬ " => Prod.mk

/-- Agda's `Σ`, the dependent pair of `Data.Product`.

Agda writes the type as `Σ A B` with `B : A → Set`, which is Lean's `Sigma B`;
the front end writes the name in guillemets because Lean's own `Σ` is a binder
notation and not an identifier. -/
abbrev «Σ» (α : Type u) (β : α → Type v) : Type (max u v) := Sigma β

/-- What it takes to be a pair in the Agda fragment: a first component and a
second component whose type may depend on the first.

Agda's `_×_` is `Σ` with a constant family, and one pair of projections
`proj₁`/`proj₂` serves both; Lean keeps `Prod` and `Sigma` apart, so the two
names are given here once, over this class, with an instance for each. -/
class AgdaPair (P : Type u) where
  /-- The type of the first component. -/
  Fst : Type v
  /-- The type of the second component, which may depend on the pair. -/
  Snd : P → Type w
  /-- The first projection. -/
  fst : (p : P) → Fst
  /-- The second projection. -/
  snd : (p : P) → Snd p

instance {α : Type u} {β : Type v} : AgdaPair (α × β) where
  Fst := α
  Snd := fun _ => β
  fst := Prod.fst
  snd := Prod.snd

instance {α : Type u} {β : α → Type v} : AgdaPair (Sigma β) where
  Fst := α
  Snd := fun p => β p.1
  fst := Sigma.fst
  snd := Sigma.snd

/-- Agda's `proj₁`. -/
abbrev proj₁ {P : Type u} [inst : AgdaPair.{u, v, w} P] (p : P) : inst.Fst := inst.fst p

/-- Agda's `proj₂`. -/
abbrev proj₂ {P : Type u} [inst : AgdaPair.{u, v, w} P] (p : P) : inst.Snd p := inst.snd p

/-- Agda's `Maybe`. -/
abbrev Maybe := Option

/-- Agda's `just`. -/
abbrev just {α : Type u} (a : α) : Option α := some a

/-- Agda's `nothing`. -/
abbrev nothing {α : Type u} : Option α := none

/-- Agda's `Dec`. -/
abbrev Dec (P : Prop) := Decidable P

/-- Agda's `yes`, the affirmative constructor of `Dec`. -/
@[match_pattern] abbrev yes {P : Prop} (h : P) : Dec P := Decidable.isTrue h

/-- Agda's `no`, the negative constructor of `Dec`. -/
@[match_pattern] abbrev no {P : Prop} (h : ¬ P) : Dec P := Decidable.isFalse h

/-- Decidable equality of naturals, which the upstream corpus imports under the
name `nat≟`. -/
abbrev «nat≟» (m n : Nat) : Dec (m = n) := Nat.decEq m n

/-! ## Numbers

`Data.Nat` and `Data.Integer` spell the two number types `ℕ` and `ℤ`; the
arithmetic and comparison operators are Lean's own. -/

/-- Agda's `ℕ`. -/
abbrev «ℕ» := Nat

@[inherit_doc Nat] scoped notation "ℕ" => Nat

/-- Agda's `ℤ`. -/
abbrev «ℤ» := Int

@[inherit_doc Int] scoped notation "ℤ" => Int

/-- Agda's `ℚ`, from `Data.Rational.Base`.

Agda's standard-library rationals are pairs of a numerator and a positive
denominator kept in lowest terms, which is Lean's `Rat`; the arithmetic and the
ordering are Lean's own, so a transliterated `_+_`, `_*_`, `-_` or `_≤_` on
rationals means what the Agda says. -/
abbrev «ℚ» := Rat

@[inherit_doc Rat] scoped notation "ℚ" => Rat

/-- Agda's `0ℚ`. -/
abbrev «0ℚ» : Rat := 0

/-- Agda's `1ℚ`. -/
abbrev «1ℚ» : Rat := 1

/-- Agda's `½`. -/
abbrev «½» : Rat := 1 / 2

/-! ## Natural numbers and the unit type

Agda's `Agda.Builtin.Nat` gives the constructors the names `zero` and `suc`, and
`Agda.Builtin.Unit` calls the inhabitant of `⊤` by the name `tt`.  All three are
`@[match_pattern]`, so a transliterated clause may pattern-match on them. -/

/-- Agda's `zero`. -/
@[match_pattern] abbrev zero : Nat := Nat.zero

/-- Agda's `suc`. -/
@[match_pattern] abbrev suc (n : Nat) : Nat := Nat.succ n

/-- Agda's `tt`, the inhabitant of `⊤`. -/
@[match_pattern] abbrev tt : Unit := Unit.unit

/-! ## List membership

The upstream sources define `_∈_` on lists as an inductive family with
constructors `here` and `there`.  That family is Lean's `List.Mem`, whose
constructors are `head` and `tail`; the Agda names are provided here so that a
transliterated proof term still elaborates. -/

/-- Agda's list membership `_∈_`. -/
scoped infix:50 " ∈ᴬ " => List.Mem

/-- Agda's `here`. -/
abbrev here {α : Type u} {x : α} {xs : List α} : List.Mem x (x :: xs) :=
  List.Mem.head xs

/-- Agda's `there`. -/
abbrev there {α : Type u} {x y : α} {xs : List α} (h : List.Mem x xs) :
    List.Mem x (y :: xs) :=
  List.Mem.tail y h

/-! ## Faithfulness

The correspondence above is definitional, and these theorems check it.  They
are the reason the Agda front end is a *notation* layer and not a second
mathematical development: a statement written in the Agda fragment is the Lean
statement it looks like. -/

theorem eq_is_agda_equality {α : Sort u} (a b : α) : (a ≡ b) = (a = b) := rfl

theorem refl_is_rfl {α : Sort u} (a : α) : (refl : a = a) = rfl := rfl

theorem bot_is_empty : ⊥ = Empty := rfl

theorem top_is_unit : ⊤ = Unit := rfl

theorem cons_is_list_cons {α : Type u} (x : α) (xs : List α) : (x ∷ xs) = x :: xs := rfl

theorem mem_is_list_mem {α : Type u} (x : α) (xs : List α) : (x ∈ᴬ xs) = (x ∈ xs) := rfl

theorem here_is_head {α : Type u} (x : α) (xs : List α) :
    (here : List.Mem x (x :: xs)) = List.Mem.head xs := rfl

theorem there_is_tail {α : Type u} (x y : α) (xs : List α) (h : List.Mem x xs) :
    (there h : List.Mem x (y :: xs)) = List.Mem.tail y h := rfl

theorem pair_is_prod_mk {α : Type u} {β : Type v} (a : α) (b : β) : (a ,ᴬ b) = (a, b) := rfl

theorem nat_is_agda_nat : (ℕ) = Nat := rfl

theorem int_is_agda_int : (ℤ) = Int := rfl

theorem rat_is_agda_rat : (ℚ) = Rat := rfl

theorem zeroq_is_zero : «0ℚ» = (0 : Rat) := rfl

theorem oneq_is_one : «1ℚ» = (1 : Rat) := rfl

theorem zero_is_nat_zero : (zero : Nat) = Nat.zero := rfl

theorem suc_is_nat_succ (n : Nat) : suc n = Nat.succ n := rfl

theorem tt_is_trivial : (tt : Unit) = Unit.unit := rfl

/-- Negation in the Agda fragment is `A → ⊥`, which is a `Set` and not a
proposition; it *implies* the Lean negation, and this is the translation. -/
theorem not_of_arrow_bot {P : Prop} (f : P → ⊥) : ¬ P := fun p => (f p).elim

/-- Conversely, a Lean negation gives the Agda one, so the two readings of
`A → ⊥` agree on which types are empty.  `P → ⊥` is a `Type` rather than a
proposition, so this is a `def`. -/
def arrow_bot_of_not {P : Prop} (f : ¬ P) : P → ⊥ := fun p => absurd p f

end Agda
