module DASHI.Governance.Everything where

import DASHI.Governance.GovernedArtifactCore
import DASHI.Governance.PromotionSpine
import DASHI.Governance.ArtifactAuthorityPromotionBridge
import DASHI.Governance.PromotionSpineTests
import DASHI.Governance.PermacultureEvolution
import DASHI.Governance.PermacultureEvolutionTests
import DASHI.Governance.CaseyITIRNixBridge
import DASHI.Governance.CaseyITIRNixBridgeTests
import DASHI.Core.RequiredObserverAxisJoinAdequacyExact
import DASHI.Core.NonFactorabilityCompositionExact
import DASHI.Governance.AuthorityMandateCore
import DASHI.Governance.CouncilDelegationGraph
import DASHI.Governance.ExternalLegitimacyBoundary
import DASHI.Governance.LocalGlobalCouncilGluing
import DASHI.Governance.RelationalMandateFibre
import DASHI.Governance.SituatedConstituency
import DASHI.Governance.TransitionResidual
import DASHI.Governance.SituatedInverseJusticeFibreExact
import DASHI.Governance.InverseJusticeThroughputExact
import DASHI.Governance.NonCompensatoryJusticeOrderExact
import DASHI.Governance.SituatedAuthorityRoutingExact
import DASHI.Governance.MandateBackedAuthorityRoutingExact
import DASHI.Governance.AuthorityPhaseSeparationExact
import DASHI.Governance.AuthorityRoutingProjectionSafetyExact
import DASHI.Governance.OperationalLegibilityJusticeSafetyExact
import DASHI.Governance.JusticeRequiredAxisEvidenceExact
import DASHI.Governance.JusticeEvidenceQualifiedValidationExact
import DASHI.Governance.RequiredAxisAuthorityRoutingExact
import DASHI.Governance.JusticeQueryIndexedProjectionAdequacyExact
import DASHI.Governance.JusticeProvenanceOutcomeLensExact
import DASHI.Governance.RequiredAxisJusticeRegression
import DASHI.Governance.ArgumentLevelAuthorityRoutingExact
import DASHI.Governance.ArgumentHyperformalism369Regression
import DASHI.Governance.OptionConeCoercionExact
import DASHI.Governance.TypedBranchingOptionConeBridgeExact
import DASHI.Governance.SituatedIntegrityOptionConeBridgeExact
import DASHI.Governance.HistoryConditionedSocialEcologyOptionConeExact
import DASHI.Governance.ObserverValuationAuthoritySeparationExact
import DASHI.Governance.HistoryObserverAuthorityOptionConeCapstoneExact
import DASHI.Governance.CapabilityFunctioningNonDescentExact
import DASHI.Governance.RecognitionDistributionRepresentationAxesExact
import DASHI.Governance.LegitimacyEvidenceSeparationExact
import DASHI.Governance.AuthorityRepairLegitimacySeparationExact
import DASHI.Governance.InterventionMechanismDecompositionExact
import DASHI.Governance.FormalisationGovernanceCapstoneExact
import DASHI.Governance.ConsumerAdequacyResidualInterventionCapstoneExact
import DASHI.Governance.JusticeCrossPollinationBridgeExact
import DASHI.Governance.InverseJusticeAttractorExact
import DASHI.Governance.SecondOrderJusticeGrammarExact
import DASHI.Governance.ClosedAuthorityInverseJusticeExact
import DASHI.Governance.SituatedInverseJusticeRegression

-- Decision/action/potential projection and hidden-fibre dynamics.
import DASHI.Governance.LegalDecisionDoubleProjectionExact
import DASHI.Governance.LegalDecisionFibreDynamicsExact
import DASHI.Governance.DecisionPotentialAuthorityOrthogonalityExact

-- Contested ambient authority / legal-epistemic power convergence.
import DASHI.Governance.ContestedAmbientAuthorityHyperformalismExact
import DASHI.Governance.ContestedAmbientAuthorityRegression
import DASHI.Governance.ContestedJurisdictionPermissionExact
import DASHI.Governance.InstitutionalNoticeActuationCulpabilityExact
import DASHI.Governance.InstitutionalVerificationFibreRequiredAxisExact
import DASHI.Governance.LegalArgumentRequiredAxis369BridgeExact
import DASHI.Governance.EpistemicCaptureProfessionalClosureExact
import DASHI.Governance.InstitutionPreservingRechartAntiSublationExact
import DASHI.Governance.OppositionInterfaceAntiDomesticationExact
import DASHI.Governance.EpistemicErrorAllocationChillingBridgeExact
import DASHI.Governance.PeaceJusticeResidualNonFactorabilityExact
import DASHI.Governance.HyperformalTernaryCarrierEquivalenceExact
import DASHI.Foundations.Base369Ternary27HypervoxelFabricGeometryExact
import DASHI.Foundations.Base369Ternary27HypervoxelStratificationExact
import DASHI.Governance.HyperformalTernary27GeometryBridgeExact
import DASHI.Moonshine.Base369Ternary27SpectralSymmetryIrrepBridgeExact
import DASHI.Moonshine.Base369Ternary27CharacterAdjacencyEquivarianceExact
import DASHI.Moonshine.Base369Ternary27SignedSymmetryMonsterIntertwinerExact
import DASHI.Moonshine.Base369Ternary27PathCubeSpectralBandsExact
import DASHI.Governance.HyperformalNonFactorabilityTransportExact
import DASHI.Governance.FibrewiseInstitutionalPowerEverything
import DASHI.Governance.RevolutionarySourceAtlas
import DASHI.Governance.RevolutionaryPracticeBraid
import DASHI.Governance.TraumaMemorySublationBoundary
import DASHI.Governance.CabarlahTraumaProjectionBridgeExact
import DASHI.Governance.ComparativeCrisisClimateAtlas
import DASHI.Governance.RevolutionaryAdjunctRegression

-- Safe-and-just development / provisioning geometry. Empirical source claims,
-- allocation conventions, vector observations and causal interpretation remain
-- explicitly separated.
import DASHI.Governance.SafeJustSourceRegistryExact
import DASHI.Governance.SafeJustIndicatorSystemExact
import DASHI.Governance.PlanetaryBoundaryAllocationExact
import DASHI.Governance.ProvisioningGeometryExact
import DASHI.Governance.ONeill2018MethodsBoundaryExact
import DASHI.Governance.Fanning2022TemporalIndicatorExact
import DASHI.Governance.Fanning2022SocialIndicatorRevisionExact
import DASHI.Governance.Fanning2022NormalizationExact
import DASHI.Governance.Fanning2022ProjectionBoundaryExact
import DASHI.Governance.Fanning2022ForecastAuthorityExact
import DASHI.Governance.Fanning2022MissingnessAndBalancedSampleExact
import DASHI.Governance.Fanning2022DataRealizationExact
import DASHI.Governance.Fanning2022SupplementaryDataAuthorityExact
import DASHI.Governance.Fanning2022LiteralDataToFigureCommutationExact
import DASHI.Governance.Fanning2022LiteralSituatedQualifiedUseBridgeExact
import DASHI.Governance.Fanning2022LiteralSituatedQualifiedUseRegression
import DASHI.Governance.Fanning2022LiteralDataAuthorityRegression
import DASHI.Governance.Fanning2022MethodsRegression

-- Consumer-indexed adequacy / Kallis review-evidence layer.
import DASHI.Governance.SafeJustProvisioningCapabilityFunctioningBridgeExact
import DASHI.Governance.SafeJustForecastConsumerAdequacyExact
import DASHI.Governance.SafeJustEpistemicResidualLedgerExact
import DASHI.Governance.Kallis2025ClaimAuthorityRoutingExact
import DASHI.Governance.Kallis2025EvidenceAtlasExact
import DASHI.Governance.Kallis2025ClaimByClaimEvidenceRealizationExact
import DASHI.Governance.Kallis2025GDP15000UpstreamStudyBridgeExact
import DASHI.Governance.Kallis2025GDP15000UpstreamStudyRegression
import DASHI.Governance.Kallis2025ClaimEvidenceRegression
import DASHI.Governance.SafeJustFeministClimateJusticeBoundaryExact
import DASHI.Governance.SafeJustFeministClimateJusticeRegression
import DASHI.Governance.SafeJustQualifiedClaimPromotionExact
import DASHI.Governance.SafeJustQualifiedPromotionBoundaryExact
import DASHI.Governance.SafeJustSocialIndicatorJusticeBoundaryExact
import DASHI.Governance.SafeJustConsumerAdequacyResidualBridgeExact
import DASHI.Governance.SafeJustConsumerAdequacyResidualRegression
import DASHI.Governance.SafeJustSituatedClaimAuthorityBridgeExact
import DASHI.Governance.SafeJustSituatedClaimAuthorityRegression

-- Feminist economics / climate-justice cross-pollination.
import DASHI.Governance.FeministClimateJusticeSourceRegistryExact
import DASHI.Governance.WaringProductionBoundaryNonfactorabilityExact
import DASHI.Governance.FeministSocialProvisioningInterpretationExact
import DASHI.Governance.MacGregorMeasurableImpactObserverBoundaryExact
import DASHI.Governance.MacGregorPostPoliticalAuthorityBoundaryExact
import DASHI.Governance.SultanaClimateColonialityResidualExact
import DASHI.Governance.PacificWomenNegotiationContributionNonDescentExact
import DASHI.Governance.VanuatuGenderedRecoveryObserverBoundaryExact
import DASHI.Governance.YusoffGeologicCategoryAuthorityBoundaryExact
import DASHI.Governance.MaathaiSituatedProvisioningAuthorityExact
import DASHI.Governance.FeministClimateJusticeResidualBundleExact
import DASHI.Governance.FeministClimateQualifiedPromotionExact
import DASHI.Governance.FeministClimateJusticeSafeJustCapstoneExact
import DASHI.Governance.FeministClimateJusticeSafeJustRegression

-- Indigenous authority and recognition/constitution synthesis.
import DASHI.Governance.IndigenousAuthoritySourceRegistryExact
import DASHI.Governance.IndigenousAuthorityEnvelopeExact
import DASHI.Governance.FirstNationsOwnedEvidenceContractExact
import DASHI.Governance.SmithResearchAgendaAuthorityBoundaryExact
import DASHI.Governance.MoretonRobinsonRecognitionSovereigntyBoundaryExact
import DASHI.Governance.WhyteKinshipTemporalityBoundaryExact
import DASHI.Governance.FeministRecognitionAuthorityCrossPollinationExact
import DASHI.Governance.SituatedIndigenousFeministAuthorityRegression

-- Indigenous environmental authority / legal-recognition / knowledge-system
-- instantiations.  These consume the existing authority envelope instead of
-- flattening cultural permission, legal representation and knowledge content.
import DASHI.Governance.IndigenousEnvironmentalJusticeSourceRegistryExact
import DASHI.Governance.SteffensenCulturalFireAuthorityExact
import DASHI.Governance.CulturalFireAuthorityEnvelopeBridgeExact
import DASHI.Governance.NativeTitleAuthorityLayerExact
import DASHI.Governance.IPCCAR6IndigenousKnowledgeIntegrationAuditExact
import DASHI.Governance.CaceresAuthorityWithoutEnforcementExact
import DASHI.Governance.NavdanyaSeedSovereigntyNonseparabilityExact
import DASHI.Governance.IndigenousEnvironmentalAuthorityCapstoneExact
import DASHI.Governance.IndigenousEnvironmentalAuthorityRegression

-- Round-two claim-level environmental authority adjudication.
import DASHI.Governance.EnvironmentalAuthoritySourceRegistryRound2Exact
import DASHI.Governance.ThomasIntersectionalEnvironmentalismExact
import DASHI.Governance.CaceresDefenderPatternBridgeExact
import DASHI.Governance.EscazuProtectionEnforcementGapExact
import DASHI.Governance.ShivaBtCottonSuicideClaimContestedExact
import DASHI.Governance.BudjBimAquacultureAuthorityExact
import DASHI.Governance.MithakaArchaeologicalEvidenceExact
import DASHI.Governance.DarkEmuClaimStatusDecompositionExact
import DASHI.Governance.KunmingMontrealTarget3AuthorityBoundaryExact
import DASHI.Governance.IndigenousEnvironmentalAuthorityRound2CapstoneExact
import DASHI.Governance.IndigenousEnvironmentalAuthorityRound2Regression

-- Provenance-bearing policy routing, corrective reachability and source-bounded
-- application surfaces assembled as one focused tranche.
import DASHI.Governance.ProvenanceReflectionRoutingRound14

import DASHI.Governance.Sudan.RCEPPSourceBoundary
import DASHI.Governance.Sudan.RCEPPInstitutionalSurface
import DASHI.Governance.Sudan.RCEPPPromotionBoundary
import DASHI.Governance.Sudan.RCEPPRegression
------------------------------------------------------------------------
-- Developmental agency / epistemic-attractor / causal-resolution theorem lane.
import DASHI.Governance.DevelopmentalConsentAttractorEverything
import DASHI.Governance.EmancipatoryTransitionSafety
-- Provenance-bearing quotient / policy-routing / corrective-reachability lane.
import DASHI.Governance.ProvenancePolicyTransport
import DASHI.Governance.ProvenanceRestitutionBoundary
import DASHI.Governance.QuotientDefectResidualRouting
import DASHI.Governance.GovernanceQuotientCoreBridge
import DASHI.Governance.SelectiveMultiResidualRouting
import DASHI.Governance.TraumaWeightingTerminalisationLift
import DASHI.Governance.AsymmetricReflectionPropositionLocality
import DASHI.Governance.CorrectiveReachabilityEquivariance
import DASHI.Governance.RelationPolicyTransportComposition
import DASHI.Governance.DomainIndexedPeaceSubjectCarrier
import DASHI.Governance.TransitionGovernanceOperatorAdapter
import DASHI.Governance.MiddleEastProvenancePolicyRouting
-- Source-bounded/symbolic application surfaces. These do not promote the
-- generic structural operators into empirical motive, guilt, or ideology.
import DASHI.Governance.AmalekProvenanceRoleBinding
import DASHI.Governance.PopulistPlutocraticDualProjection
import DASHI.Governance.IranUS2026RestitutionObservation

------------------------------------------------------------------------
-- Religious-childhood / feminist subject-formation / witch-history BIDI.
-- Historical genealogy, empirical instantiation, identity attribution and
-- causal promotion remain separately typed.
import DASHI.Governance.ReligiousChildhoodSubjectFormationBidiExact
import DASHI.Governance.ReligiousChildhoodInstantiationEvidenceAtlasExact
import DASHI.Governance.WitchTrialEvidenceSubjectAttributionExact
import DASHI.Governance.SuffrageWitchReclamationGenealogyExact
import DASHI.Governance.HistoricalEventMeaningProvenanceBidiExact
import DASHI.Governance.SexedHistoricalSubjectDialecticBidiExact
import DASHI.Governance.SexedHistoricalCoConstitutionHyperfabricExact
import DASHI.Governance.SexedHistoricalTransitionHyperfabricExact
import DASHI.Governance.SexedHistoricalChoiceConeBridgeExact
import DASHI.Governance.SexedHistoricalActionFeedbackHyperfabricExact
import DASHI.Governance.SexedHistoricalCollectiveThresholdNetworkExact
import DASHI.Governance.SexedHistoricalStatisticalExperimentHyperfabricExact
import DASHI.Governance.SexedHistoricalConditionalReversalExact
import DASHI.Governance.SexedHistoricalDialecticalOrderHolonomyAnalogueExact
import DASHI.Governance.ReligiousChildhoodFeministWitchRegression
-- History-qualified manipulation / dissent / socio-technical assay lane.
import DASHI.Governance.SituatedDissentDeceptionAssayExact
import DASHI.Governance.SocioTechnicalPowerSelectionAssayExact

-- Physical-agent / resource-pressure / system-closure assay lane.
import DASHI.Governance.ResourcePressureTelemetryPermissionExact
import DASHI.Governance.ExecutionGovernanceClosureAssayExact
import DASHI.Governance.ConstitutionalAxisResidualCapabilityExact
import DASHI.Governance.MHSButterBenchPhysicalAgentCrossPollinationExact
