import Integration.RiemannSSP15RHProducerSameGraphWeld

#print axioms Integration.RiemannSSP15RHProducerSameGraphWeld.imported_certificate_inhabited
#print axioms Integration.RiemannSSP15RHProducerSameGraphWeld.imported_s_is_source_target
#print axioms Integration.RiemannSSP15RHProducerSameGraphWeld.imported_depth_five_coefficients
#print axioms Integration.RiemannSSP15RHProducerSameGraphWeld.imported_source_primitive_kernel
#print axioms Integration.RiemannSSP15RHProducerSameGraphWeld.signed_seed_reopens_marked_role
#print axioms Integration.RiemannSSP15RHProducerSameGraphWeld.origin_role_executes_inverse
#print axioms Integration.RiemannSSP15RHProducerSameGraphWeld.j_role_executes_empty
#print axioms Integration.RiemannSSP15RHProducerSameGraphWeld.s_target_role_executes_positive
#print axioms Integration.RiemannSSP15RHProducerSameGraphWeld.producer_origin_orientation_inverse
#print axioms Integration.RiemannSSP15RHProducerSameGraphWeld.producer_j_orientation_mediated
#print axioms Integration.RiemannSSP15RHProducerSameGraphWeld.producer_s_target_orientation_forward
#print axioms Integration.RiemannSSP15RHProducerSameGraphWeld.neutral_j_selected_primes_survive
#print axioms Integration.RiemannSSP15RHProducerSameGraphWeld.neutral_j_execution_collapses
