import Integration.RiemannOneTwoThreeCoefficientLanguage
import Integration.RiemannPrimitiveKernelBalancedTernaryStencil
import Integration.RiemannMonster196830TernaryShiftBridge
import Integration.RiemannTrialecticT9ScaleFactorizationBoundary

#print axioms Integration.RiemannOneTwoThreeCoefficientLanguage.ratio_cross_multiplication_exact
#print axioms Integration.RiemannPrimitiveKernelBalancedTernaryStencil.pole_coefficient_is_80
#print axioms Integration.RiemannPrimitiveKernelBalancedTernaryStencil.j_depth_five
#print axioms Integration.RiemannPrimitiveKernelBalancedTernaryStencil.three_adic_depth_profile_exact
#print axioms Integration.RiemannMonster196830TernaryShiftBridge.structured_bulk_at_depth_five
#print axioms Integration.RiemannMonster196830TernaryShiftBridge.depth_five_residual_factors_four_shift
#print axioms Integration.RiemannTrialecticT9ScaleFactorizationBoundary.actual_trialectic_carrier_factorization_owned
#print axioms Integration.RiemannTrialecticT9ScaleFactorizationBoundary.both_factorizations_same_count
