import Integration.ActionOrbitRecognition
import Integration.OggSSPSmallCharacteristicRecognition
import AgdaMirror.OggSSPSmallCharacteristicRecognition

#print axioms Integration.ActionOrbitRecognition.mapped_action_stays_in_mapped_orbit
#print axioms Integration.ActionOrbitRecognition.FullRecognition.targetOrbit_to_source_injective

#print axioms Integration.OggSSPSmallCharacteristicRecognition.p3_reopen_exact
#print axioms Integration.OggSSPSmallCharacteristicRecognition.p2_reopen_exact
#print axioms Integration.OggSSPSmallCharacteristicRecognition.p3_coarse_projection_has_no_left_inverse
#print axioms Integration.OggSSPSmallCharacteristicRecognition.p2_coarse_projection_has_no_left_inverse
#print axioms Integration.OggSSPSmallCharacteristicRecognition.no_surjection_coarse_j_to_p3_orbits
#print axioms Integration.OggSSPSmallCharacteristicRecognition.no_surjection_coarse_j_to_p2_target
#print axioms Integration.OggSSPSmallCharacteristicRecognition.p3_target_orbits_embed_into_arithmetic_source
#print axioms Integration.OggSSPSmallCharacteristicRecognition.p2_ten_target_states_embed_into_arithmetic_source

#print axioms AgdaMirror.OggSSPSmallCharacteristicRecognition.p2_codec_no_left_inverse_parity
#print axioms AgdaMirror.OggSSPSmallCharacteristicRecognition.p3_codec_no_left_inverse_parity
#print axioms AgdaMirror.OggSSPSmallCharacteristicRecognition.p2_coarse_j_no_go_parity
#print axioms AgdaMirror.OggSSPSmallCharacteristicRecognition.p3_coarse_j_no_go_parity
