import Integration.ActionOrbitRecognition
import Integration.OggSSPSmallCharacteristicRecognition
import AgdaMirror.OggSSPSmallCharacteristicRecognition

#print axioms Integration.ActionOrbitRecognition.mapped_action_stays_in_mapped_orbit
#print axioms Integration.ActionOrbitRecognition.FullRecognition.targetOrbit_to_source_injective

#print axioms Integration.OggSSPSmallCharacteristicRecognition.p3_reopen_exact
#print axioms Integration.OggSSPSmallCharacteristicRecognition.p2_reopen_exact
#print axioms Integration.OggSSPSmallCharacteristicRecognition.p3_coarse_projection_has_no_left_inverse
#print axioms Integration.OggSSPSmallCharacteristicRecognition.p2_coarse_projection_has_no_left_inverse
#print axioms Integration.OggSSPSmallCharacteristicRecognition.no_surjection_coarse_j_to_p3_orbits
#print axioms Integration.OggSSPSmallCharacteristicRecognition.no_surjection_coarse_j_to_p2_target
#print axioms Integration.OggSSPSmallCharacteristicRecognition.no_injective_f9_orbits_to_p3_target
#print axioms Integration.OggSSPSmallCharacteristicRecognition.no_full_f9_frobenius_recognition_to_p3
#print axioms Integration.OggSSPSmallCharacteristicRecognition.extensionCoordinate_surjective
#print axioms Integration.OggSSPSmallCharacteristicRecognition.extensionCoordinate_equivariant
#print axioms Integration.OggSSPSmallCharacteristicRecognition.f9_extension_coordinate_not_pi0_embedding
#print axioms Integration.OggSSPSmallCharacteristicRecognition.p3_target_orbits_embed_into_arithmetic_source
#print axioms Integration.OggSSPSmallCharacteristicRecognition.p2_ten_target_states_embed_into_arithmetic_source

#print axioms AgdaMirror.OggSSPSmallCharacteristicRecognition.p2_codec_no_left_inverse_parity
#print axioms AgdaMirror.OggSSPSmallCharacteristicRecognition.p3_codec_no_left_inverse_parity
#print axioms AgdaMirror.OggSSPSmallCharacteristicRecognition.p2_coarse_j_no_go_parity
#print axioms AgdaMirror.OggSSPSmallCharacteristicRecognition.p3_coarse_j_no_go_parity


#print axioms Integration.OggSSPIndependentBase369Recognition.kernel_ssp_roundtrip
#print axioms Integration.OggSSPIndependentBase369Recognition.p3IndependentFullRecognition
#print axioms Integration.OggSSPIndependentBase369Recognition.p2GaugeFullRecognition
#print axioms Integration.OggSSPIndependentBase369Recognition.p2RetainedFullRecognition
#print axioms Integration.OggSSPIndependentBase369Recognition.p3ProvenanceOrbitRecognition
#print axioms Integration.OggSSPIndependentBase369Recognition.p2GaugeProvenanceOrbitRecognition
#print axioms Integration.OggSSPIndependentBase369Recognition.p2RetainedProvenanceOrbitRecognition


#print axioms Integration.BalancedTernaryHypercubeAntipodalOrbitCount.ternary_state_split_exact
#print axioms Integration.BalancedTernaryHypercubeAntipodalOrbitCount.double_orbit_count_exact
#print axioms Integration.OggSSPExponentResidualArithmeticSource.recognition_count_closes_against_expected
#print axioms Integration.OggSSPExponentResidualArithmeticSource.p3_target_count_is_A1
#print axioms Integration.OggSSPExponentResidualArithmeticSource.p2_target_count_is_binary_times_A2
#print axioms Integration.OggSSPExponentResidualVsSupersingularOrbitSeparation.p3_supersingular_pi0_ne_exponent_residual
#print axioms Integration.OggSSPExponentResidualVsSupersingularOrbitSeparation.p5_supersingular_pi0_ne_monster_exponent
#print axioms Integration.OggSSPExponentResidualVsSupersingularOrbitSeparation.p7_supersingular_pi0_ne_monster_exponent
