import Integration.RiemannSSP15RoleCMContingency
import Integration.RiemannSSP15DepthFiveRoleCodec
import Integration.RiemannSSP15SignedProvenanceBridge
import Integration.RiemannSSP15PartitionSeparation
import Integration.RiemannSSP15ChosenGridTransversality
import Integration.RiemannSSP15FilteredProvenanceCapstone

#print axioms Integration.RiemannSSP15DepthFiveRoleCodec.decode_encode
#print axioms Integration.RiemannSSP15DepthFiveRoleCodec.encode_decode
#print axioms Integration.RiemannSSP15DepthFiveRoleCodec.role_code_cardinality
#print axioms Integration.RiemannSSP15DepthFiveRoleCodec.coarse_zero_does_not_recover_mode

#print axioms Integration.RiemannSSP15SignedProvenanceBridge.role_code_pointed_roundtrip
#print axioms Integration.RiemannSSP15SignedProvenanceBridge.j_role_valuation_is_zero
#print axioms Integration.RiemannSSP15SignedProvenanceBridge.distinct_neutral_codes_same_valuation
#print axioms Integration.RiemannSSP15SignedProvenanceBridge.five_neutral_j_states_share_zero_valuation

#print axioms Integration.RiemannSSP15PartitionSeparation.shape_tags_pairwise_distinct

#print axioms Integration.RiemannSSP15ChosenGridTransversality.origin_column_crosses_cm
#print axioms Integration.RiemannSSP15ChosenGridTransversality.j_column_crosses_cm
#print axioms Integration.RiemannSSP15ChosenGridTransversality.s_column_crosses_cm
#print axioms Integration.RiemannSSP15ChosenGridTransversality.native_occupancies_sum_to_fifteen
#print axioms Integration.RiemannSSP15ChosenGridTransversality.chosen_mode09_origin_not_native_mode

#print axioms Integration.RiemannSSP15FilteredProvenanceCapstone.PrimitiveRowProducerRoleCertificate.origin_coefficient
#print axioms Integration.RiemannSSP15FilteredProvenanceCapstone.PrimitiveRowProducerRoleCertificate.j_coefficient
#print axioms Integration.RiemannSSP15FilteredProvenanceCapstone.PrimitiveRowProducerRoleCertificate.s_coefficient
#print axioms Integration.RiemannSSP15FilteredProvenanceCapstone.producer_marked_role_code_roundtrip


#print axioms Integration.RiemannSSP15RoleCMContingency.origin_contingency
#print axioms Integration.RiemannSSP15RoleCMContingency.j_contingency
#print axioms Integration.RiemannSSP15RoleCMContingency.s_contingency
#print axioms Integration.RiemannSSP15RoleCMContingency.cm_column_sums
#print axioms Integration.RiemannSSP15RoleCMContingency.complete_contingency_matrix
