import Integration.RiemannPrimitiveKernelExplicitSmithReduction
import Integration.RiemannPrimitiveKernelUnimodularBasis
import Integration.RiemannPrimitiveKernelMod243Filtration
import Integration.RiemannPrimitiveKernelSmithFiltrationSeparation
import Integration.RiemannOneTwoThreeCoefficientLanguage
import Integration.RiemannPrimitiveKernelBalancedTernaryStencil
import Integration.RiemannMonster196830TernaryShiftBridge
import Integration.RiemannTrialecticT9ScaleFactorizationBoundary

#print axioms Integration.RiemannOneTwoThreeCoefficientLanguage.ratio_cross_multiplication_exact
#print axioms Integration.RiemannPrimitiveKernelBalancedTernaryStencil.pole_coefficient_is_80
#print axioms Integration.RiemannPrimitiveKernelBalancedTernaryStencil.j_depth_five
#print axioms Integration.RiemannPrimitiveKernelBalancedTernaryStencil.three_adic_depth_profile_exact
#print axioms Integration.RiemannMonster196830TernaryShiftBridge.structured_bulk_at_depth_five
#print axioms Integration.RiemannMonster196830TernaryShiftBridge.depth_five_residual_factors_four_shift
#print axioms Integration.RiemannTrialecticT9ScaleFactorizationBoundary.actual_trialectic_carrier_factorization_owned
#print axioms Integration.RiemannTrialecticT9ScaleFactorizationBoundary.both_factorizations_same_count


#print axioms Integration.RiemannPrimitiveKernelUnimodularBasis.determinant_U_is_one
#print axioms Integration.RiemannPrimitiveKernelUnimodularBasis.forward_after_inverse
#print axioms Integration.RiemannPrimitiveKernelUnimodularBasis.full_row_gcd_is_one
#print axioms Integration.RiemannPrimitiveKernelUnimodularBasis.depth_profile_changes
#print axioms Integration.RiemannPrimitiveKernelMod243Filtration.functional_transport
#print axioms Integration.RiemannPrimitiveKernelMod243Filtration.kernel_transport
#print axioms Integration.RiemannPrimitiveKernelMod243Filtration.coordinate_tail_flag_changes
#print axioms Integration.RiemannPrimitiveKernelSmithFiltrationSeparation.primitive_smith_invariant_one
#print axioms Integration.RiemannPrimitiveKernelSmithFiltrationSeparation.concrete_mod243_kernel_transport


#print axioms Integration.RiemannPrimitiveKernelExplicitSmithReduction.explicit_smith_normal_form
#print axioms Integration.RiemannPrimitiveKernelExplicitSmithReduction.row_map_surjective
#print axioms Integration.RiemannPrimitiveKernelSmithFiltrationSeparation.explicit_smith_form_owned
#print axioms Integration.RiemannPrimitiveKernelSmithFiltrationSeparation.bare_row_map_surjective
