import Integration.T5QuadraticOrbitAudit
import Mathlib

/-!
# E6 roots -> mod-3 five-dimensional quadratic shell

DASHI derivation, computationally audited first in local Python.

Use the E6 simple-root basis with Dynkin edges

  0--2--3--4--5
        |
        1

(where node 1 is attached to node 3).  The corresponding Cartan form has
determinant 3.  Modulo 3 its radical is one-dimensional; choosing the explicit
radical generator `(1,0,2,0,1,2)` and quotienting by it leaves a 5-dimensional
nondegenerate quadratic space.

An explicit change of basis carries that quotient form to the repository's
standard balanced five-trit form `qT5 = sum x_i^2`.  The bounded simple-root
coefficient box below contains exactly the 72 E6 roots, and exhaustive finite
checking proves that reduction/quotient/change-of-basis is a bijection onto the
72-point `QTwoShell`.

This is an E6/Q-shell recognition result.  It does *not* identify the 240-state
relative complement with E8, does not supply an E8 action intertwiner, and does
not create a physical or phenomenal mechanism.
-/

namespace Integration.E6Mod3QuadraticBridge

open Integration.TernaryHub
open Integration.TrialecticDyadicLocalComplement
open Integration.T5QuadraticOrbitAudit

/-! ## 1. Finite simple-root coefficient box

Python enumeration of the Weyl orbit showed the exact coordinate ranges

  [-1,1] × [-2,2] × [-2,2] × [-3,3] × [-2,2] × [-1,1].

Rather than importing that orbit as data, Lean defines the full finite box and
selects norm-2 vectors by the E6 Cartan quadratic form.
-/

structure E6BoundedCoeff where
  a0 : Fin 3
  a1 : Fin 5
  a2 : Fin 5
  a3 : Fin 7
  a4 : Fin 5
  a5 : Fin 3
  deriving DecidableEq, Repr, Fintype

def centered3 (x : Fin 3) : Int := (x.1 : Int) - 1
def centered5 (x : Fin 5) : Int := (x.1 : Int) - 2
def centered7 (x : Fin 7) : Int := (x.1 : Int) - 3

def c0 (x : E6BoundedCoeff) : Int := centered3 x.a0
def c1 (x : E6BoundedCoeff) : Int := centered5 x.a1
def c2 (x : E6BoundedCoeff) : Int := centered5 x.a2
def c3 (x : E6BoundedCoeff) : Int := centered7 x.a3
def c4 (x : E6BoundedCoeff) : Int := centered5 x.a4
def c5 (x : E6BoundedCoeff) : Int := centered3 x.a5

/-- E6 Cartan norm in the chosen simple-root basis. -/
def e6Norm (x : E6BoundedCoeff) : Int :=
  2 * (c0 x * c0 x + c1 x * c1 x + c2 x * c2 x +
       c3 x * c3 x + c4 x * c4 x + c5 x * c5 x) -
  2 * (c0 x * c2 x + c1 x * c3 x + c2 x * c3 x +
       c3 x * c4 x + c4 x * c5 x)

/-- Literal finite E6 root carrier: norm-2 vectors in the exact bounded box. -/
def E6Root := {x : E6BoundedCoeff // e6Norm x = 2}
instance : Fintype E6Root := inferInstance

theorem e6_root_card : Fintype.card E6Root = 72 := by
  native_decide

/-! ## 2. Exact mod-3 Cartan quotient

The mod-3 Cartan radical is generated by

  r = (1,0,2,0,1,2).

The finite theorems below check the radical invariance on all 729 vectors, the
quotient quadratic identity on all 729 vectors, and the standardizing isometry
on all 243 quotient vectors.  These are mathematical finite exhaustions, not
scientific/physical claims.
-/

structure F3Six where
  x0 : ZMod 3
  x1 : ZMod 3
  x2 : ZMod 3
  x3 : ZMod 3
  x4 : ZMod 3
  x5 : ZMod 3
  deriving DecidableEq, Repr, Fintype

structure F3Five where
  z0 : ZMod 3
  z1 : ZMod 3
  z2 : ZMod 3
  z3 : ZMod 3
  z4 : ZMod 3
  deriving DecidableEq, Repr, Fintype

/-- E6 Cartan quadratic form reduced modulo 3. -/
def e6Mod3Quadratic (x : F3Six) : ZMod 3 :=
  2 * (x.x0*x.x0 + x.x1*x.x1 + x.x2*x.x2 +
       x.x3*x.x3 + x.x4*x.x4 + x.x5*x.x5) -
  2 * (x.x0*x.x2 + x.x1*x.x3 + x.x2*x.x3 +
       x.x3*x.x4 + x.x4*x.x5)

/-- Translation by `a * (1,0,2,0,1,2)`, the mod-3 Cartan radical line. -/
def radicalTranslate (a : ZMod 3) (x : F3Six) : F3Six :=
  ⟨x.x0 + a,
   x.x1,
   x.x2 + 2*a,
   x.x3,
   x.x4 + a,
   x.x5 + 2*a⟩

theorem radical_translation_preserves_quadratic :
    ∀ x : F3Six, ∀ a : ZMod 3,
      e6Mod3Quadratic (radicalTranslate a x) = e6Mod3Quadratic x := by
  native_decide

/-- Canonical quotient representative: subtract `x0 * r` and drop coordinate 0. -/
def quotientCoordinates (x : F3Six) : F3Five :=
  ⟨x.x1,
   x.x2 - 2*x.x0,
   x.x3,
   x.x4 - x.x0,
   x.x5 - 2*x.x0⟩

/-- Quadratic form induced on the chosen five-dimensional quotient coordinates. -/
def quotientQuadratic (y : F3Five) : ZMod 3 :=
  2 * (y.z0*y.z0 + y.z1*y.z1 + y.z2*y.z2 + y.z3*y.z3 + y.z4*y.z4) -
  2 * (y.z0*y.z2 + y.z1*y.z2 + y.z2*y.z3 + y.z3*y.z4)

theorem quotient_coordinates_preserve_quadratic :
    ∀ x : F3Six,
      e6Mod3Quadratic x = quotientQuadratic (quotientCoordinates x) := by
  native_decide

/-- Explicit inverse change-of-basis matrix from quotient Cartan coordinates to
standard F3^5 coordinates:

  [2 2 2 1 2]
  [2 2 2 0 1]
  [2 2 0 2 0]
  [2 2 0 0 0]
  [2 1 0 0 0].
-/
def quotientToStandard (y : F3Five) : F3Five :=
  ⟨2*y.z0 + 2*y.z1 + 2*y.z2 + y.z3 + 2*y.z4,
   2*y.z0 + 2*y.z1 + 2*y.z2 + y.z4,
   2*y.z0 + 2*y.z1 + 2*y.z3,
   2*y.z0 + 2*y.z1,
   2*y.z0 + y.z1⟩

def standardQuadratic (z : F3Five) : ZMod 3 :=
  z.z0*z.z0 + z.z1*z.z1 + z.z2*z.z2 + z.z3*z.z3 + z.z4*z.z4

theorem quotient_to_standard_isometry :
    ∀ y : F3Five,
      quotientQuadratic y = standardQuadratic (quotientToStandard y) := by
  native_decide

/-! ## 3. Concrete map from integer E6 roots into the repository T5 shell -/

def intMod3 (z : Int) : ZMod 3 := z

def rootMod3 (root : E6Root) : F3Six :=
  let x := root.1
  ⟨intMod3 (c0 x), intMod3 (c1 x), intMod3 (c2 x),
   intMod3 (c3 x), intMod3 (c4 x), intMod3 (c5 x)⟩

/-- Root-specific quotient coordinates, now factored through the generic quotient. -/
def e6QuotientCoordinates (root : E6Root) : F3Five :=
  quotientCoordinates (rootMod3 root)

/-- Standard F3^5 coordinates rendered back into the repository's exact T5
balanced-ternary carrier. -/
def standardToT5 (z : F3Five) : T5Carrier :=
  ⟨balSSPEquiv.symm z.z0,
   balSSPEquiv.symm z.z1,
   balSSPEquiv.symm z.z2,
   balSSPEquiv.symm z.z3,
   balSSPEquiv.symm z.z4⟩

/-- Concrete E6-root map into the existing T5 carrier. -/
def rootToT5 (root : E6Root) : T5Carrier :=
  standardToT5 (quotientToStandard (e6QuotientCoordinates root))

/-- Every enumerated E6 root lands on the Q=2 shell. -/
theorem root_to_t5_has_qtwo : ∀ root : E6Root, qT5 (rootToT5 root) = 2 := by
  native_decide

/-- The map with the Q=2 proof attached. -/
def rootToQTwoShell (root : E6Root) : QTwoShell :=
  ⟨rootToT5 root, root_to_t5_has_qtwo root⟩

/-! ## 4. Exact finite recognition

The local Python preflight checked 72 distinct images and equality with the full
Q=2 shell.  These theorems ask Lean's kernel-facing finite evaluator to pay the
same injectivity/surjectivity obligations from the actual definitions above.
-/

theorem root_to_qtwo_injective : Function.Injective rootToQTwoShell := by
  native_decide

theorem root_to_qtwo_surjective : Function.Surjective rootToQTwoShell := by
  native_decide

def e6RootEquivQTwoShell : E6Root ≃ QTwoShell :=
  Equiv.ofBijective rootToQTwoShell ⟨root_to_qtwo_injective, root_to_qtwo_surjective⟩

/-- Cardinality consistency is now a corollary of the concrete recognition. -/
theorem e6_qtwo_same_card : Fintype.card E6Root = Fintype.card QTwoShell := by
  rw [e6_root_card, qtwo_shell_card]

inductive E6QTwoBijectionCreatesE8Recognition : Prop
inductive E6QTwoBijectionCreatesPhysicalMechanism : Prop

theorem e6QTwoBijectionCannotCreateE8Recognition :
    ¬ E6QTwoBijectionCreatesE8Recognition := by
  intro h
  cases h

theorem e6QTwoBijectionCannotCreatePhysicalMechanism :
    ¬ E6QTwoBijectionCreatesPhysicalMechanism := by
  intro h
  cases h

structure Boundary where
  e6BoundedRootCarrierTyped : Bool
  e6RootCount72Paid : Bool
  mod3RadicalQuotientTyped : Bool
  mod3RadicalInvariancePaid : Bool
  quotientQuadraticEqualityPaid : Bool
  explicitFiveDimensionalIsometryPaid : Bool
  rootImagesHaveQTwoPaid : Bool
  explicitQuadraticShellBijectionPaid : Bool
  bijectionAloneCreatesE8Recognition : Bool
  bijectionAloneCreatesPhysicalMechanism : Bool
  deriving Repr

def canonicalBoundary : Boundary where
  e6BoundedRootCarrierTyped := true
  e6RootCount72Paid := true
  mod3RadicalQuotientTyped := true
  mod3RadicalInvariancePaid := true
  quotientQuadraticEqualityPaid := true
  explicitFiveDimensionalIsometryPaid := true
  rootImagesHaveQTwoPaid := true
  explicitQuadraticShellBijectionPaid := true
  bijectionAloneCreatesE8Recognition := false
  bijectionAloneCreatesPhysicalMechanism := false

end Integration.E6Mod3QuadraticBridge
