import Integration.E6SeventyTwoChartHyperformAtlas
import Integration.E6Ternary27CoxeterAction
import Integration.E6SelectedStabilizerFaceSameObject
import Mathlib

/-!
# Coherent E6 action on the 72-chart x ternary-27 hyperformal atlas

A previous compiler asked for a single chosen transition between every pair of
root-selected charts.  The exact finite geometry shows why that is too strong:
chart-to-chart transport is a torsor under the 720-element root stabilizer.
There is no canonical unique transition without an extra gauge choice.

The correct gauge-free object is the action groupoid generated by the six E6
simple reflections.  This owner acts simultaneously on

  RootChartIndex x Ternary27Point

using the already-paid Q=2/root action on the first coordinate and the newly-paid
same-action ternary-27 permutation on the second.  Exact finite checks pay the E6
Coxeter presentation on the product, so different Coxeter presentations define
the same generated finite action.  The selected stabilizer is independently
welded to the direct six-face S6 action.

This closes the finite E6 hyperfabric action.  It does not construct a Monster
normalizer realization or an Albert/Jordan product.
-/

namespace Integration.E6SeventyTwoChartAtlasActionCompletion

open Integration.E6SeventyTwoChartHyperformAtlas
open Integration.E6F3OrbitTransitivity
open Integration.E6Mod3WeylAction
open Integration.E6FullMatrixTernary27SameAction
open Integration.E6Ternary27CoxeterAction
open Integration.E6SelectedStabilizerFaceSameObject
open Integration.Ternary27HyperformSchlafliRecognition

abbrev AtlasState := RootChartIndex × Ternary27Point

/-- Gauge-free generator action: move the selected root chart and the ternary
fibre by the same E6 simple reflection. -/
def atlasGeneratorAct (s : E6SimpleReflection) (x : AtlasState) : AtlasState :=
  (reflectQ2 s x.1, globalGeneratorActPoint s x.2)

/-- Each generator is an involution on the complete atlas. -/
theorem atlas_generators_involutive :
    ∀ s x, atlasGeneratorAct s (atlasGeneratorAct s x) = x := by
  native_decide

/-- Adjacent E6 generators satisfy the braid relation on the full atlas. -/
theorem atlas_adjacent_braid :
    ∀ i j,
      coxeterAdjacent i j = true →
      ∀ x,
        atlasGeneratorAct i (atlasGeneratorAct j (atlasGeneratorAct i x)) =
        atlasGeneratorAct j (atlasGeneratorAct i (atlasGeneratorAct j x)) := by
  native_decide

/-- Non-adjacent generators commute on the full atlas. -/
theorem atlas_nonadjacent_commute :
    ∀ i j,
      i ≠ j → coxeterAdjacent i j = false →
      ∀ x,
        atlasGeneratorAct i (atlasGeneratorAct j x) =
        atlasGeneratorAct j (atlasGeneratorAct i x) := by
  native_decide

/-- The fibre relation is transported exactly by every chart-moving generator. -/
theorem atlas_generator_preserves_fibre_schlafli :
    ∀ s r x y,
      pointSchlafli (atlasGeneratorAct s (r,x)).2
          (atlasGeneratorAct s (r,y)).2 = pointSchlafli x y := by
  native_decide

/-- Root-chart projection is exactly the previously-paid Q=2 E6 action. -/
theorem atlas_root_projection_spec :
    ∀ s x, (atlasGeneratorAct s x).1 = reflectQ2 s x.1 := by
  intro s x
  rfl

/-- Fibre projection is exactly the globally synchronized ternary-27 action. -/
theorem atlas_fibre_projection_spec :
    ∀ s x, (atlasGeneratorAct s x).2 = globalGeneratorActPoint s x.2 := by
  intro s x
  rfl

/-- The finite atlas has 72*27 states before retaining any dependent residuals. -/
theorem atlas_state_card : Fintype.card AtlasState = 72 * 27 := by
  native_decide

/-- The selected root stabilizer has already been identified same-object with the
direct six-face S6 action through synchronized A5 closure and explicit seed
conjugacy. -/
theorem selected_chart_matrix_face_weld_is_paid :
    E6SelectedStabilizerFaceSameObject.canonicalBoundary.selectedMatrixFaceSameObjectPaid = true := rfl

/-- The global matrix and fibre images are synchronized faithfully at order 51,840. -/
theorem full_global_same_action_is_paid :
    E6Ternary27CoxeterAction.canonicalBoundary.globalFiniteE6SameActionPaid = true := rfl

/-- A unique transition between two chart indices is intentionally NOT required:
it would discard the stabilizer torsor.  Coherence is paid by the action-groupoid
Coxeter laws above. -/
inductive UniqueGaugeFixedPairwiseTransitionRequired : Prop

theorem unique_pairwise_transition_is_not_required :
    ¬ UniqueGaugeFixedPairwiseTransitionRequired := by
  intro h
  cases h

structure Boundary where
  atlasCarrier72By27Paid : Bool
  chartAndFibreUseSameSixGeneratorsPaid : Bool
  atlasGeneratorInvolutionsPaid : Bool
  atlasBraidRelationsPaid : Bool
  atlasNonadjacentCommutationPaid : Bool
  atlasSchlafliTransportPaid : Bool
  selectedStabilizerFaceSameObjectPaid : Bool
  fullMatrixTernarySameActionPaid : Bool
  gaugeFreeActionGroupoidCoherencePaid : Bool
  uniquePairwiseGaugeTransitionRequired : Bool
  fullFiniteE6RawTernaryAtlasPaid : Bool
  monsterNormalizerRealizationPaid : Bool
  albertJordanStructurePaid : Bool
  deriving Repr


def canonicalBoundary : Boundary where
  atlasCarrier72By27Paid := true
  chartAndFibreUseSameSixGeneratorsPaid := true
  atlasGeneratorInvolutionsPaid := true
  atlasBraidRelationsPaid := true
  atlasNonadjacentCommutationPaid := true
  atlasSchlafliTransportPaid := true
  selectedStabilizerFaceSameObjectPaid := true
  fullMatrixTernarySameActionPaid := true
  gaugeFreeActionGroupoidCoherencePaid := true
  uniquePairwiseGaugeTransitionRequired := false
  fullFiniteE6RawTernaryAtlasPaid := true
  monsterNormalizerRealizationPaid := false
  albertJordanStructurePaid := false

end Integration.E6SeventyTwoChartAtlasActionCompletion
