import Integration.E8LiteralMixed27Schlafli
import Mathlib

/-!
# Bare ternary-cube translation obstruction for the literal E8 mixed 27 geometry

The repository already has two separate 27-state carriers:

* the bare ternary cube `F3^3`, used only as the exact carrier shape `27 = 1 + 26`;
* each literal mixed E8/A2 weight fibre, whose intrinsic relation is the
  Schlaefli graph `SRG(27,16,10,8)`.

This file tests the strongest recognition available from the bare additive
structure alone.  Any undirected translation-invariant graph on `F3^3` is a
Cayley graph whose connection set is a union of antipodal pairs.  There are 13
projective directions, hence only `2^13 = 8192` such graphs.

Exact finite enumeration shows that none has the Schlaefli common-neighbour
profile.  Therefore the bare ternary additive/translation structure cannot by
itself realize the literal E8 mixed-27 relation geometry.  A future
Albert/minuscule-27 recognition needs additional relation/product/action data;
cardinality `27 = 1 + 26` is not enough.
-/

namespace Integration.E8Mixed27TernaryTranslationObstruction

open Integration.E8LiteralMixed27Schlafli

abbrev F3 := ZMod 3
abbrev T3Cube := Fin 3 → F3

/-- Canonical representative of an antipodal nonzero direction in `F3^3`:
the first nonzero coordinate is `1`, never `2 = -1`. -/
def canonicalProjective3 (z : T3Cube) : Bool :=
  if z 0 = 0 then
    if z 1 = 0 then
      if z 2 = 0 then false else decide (z 2 = 1)
    else decide (z 1 = 1)
  else decide (z 0 = 1)

/-- The 13 antipodal projective directions of the ternary cube. -/
def Direction := {z : T3Cube // canonicalProjective3 z = true}

instance : Fintype Direction := inferInstance
instance : DecidableEq Direction := inferInstance

theorem direction_card : Fintype.card Direction = 13 := by
  native_decide

/-- Translation-invariant undirected adjacency generated by a selected set of
projective directions.  Selecting `d` automatically selects both `+d` and
`-d`. -/
def cayleyAdjacent (mask : Finset Direction) (x y : T3Cube) : Bool :=
  decide (x ≠ y ∧ ∃ d ∈ mask, y = x + d.1 ∨ y = x - d.1)

/-- Common-neighbour count for the Cayley relation. -/
def commonCount (mask : Finset Direction) (x y : T3Cube) : Nat :=
  (Finset.univ.filter fun z : T3Cube =>
    (cayleyAdjacent mask x z && cayleyAdjacent mask y z) = true).card

/-- Degree at one vertex.  Translation invariance makes the origin sufficient
for the degree test. -/
def degreeAt (mask : Finset Direction) (x : T3Cube) : Nat :=
  (Finset.univ.filter fun y : T3Cube => cayleyAdjacent mask x y = true).card

/-- Necessary origin-relative signature of `SRG(27,16,10,8)` for a
translation-invariant graph.  If a Cayley realization of the Schlaefli graph
existed, its mask would satisfy this predicate. -/
def SchlafliOriginProfile (mask : Finset Direction) : Prop :=
  degreeAt mask 0 = 16 ∧
  ∀ d : T3Cube, d ≠ 0 →
    if cayleyAdjacent mask 0 d = true then
      commonCount mask 0 d = 10
    else
      commonCount mask 0 d = 8

/-- Exhaustive finite no-go: none of the `2^13 = 8192` undirected
translation-invariant Cayley graphs on `F3^3` has the Schlaefli
`(27,16,10,8)` profile. -/
theorem no_translation_invariant_schlafli :
    ∀ mask : Finset Direction, ¬ SchlafliOriginProfile mask := by
  native_decide

/-- A source-facing recognition contract must therefore carry more than the
bare additive ternary action. -/
structure Ternary27ToLiteralMixedRecognition : Type 1 where
  equivPlus0 : T3Cube ≃ Plus0
  ternaryAdjacent : T3Cube → T3Cube → Bool
  preservesSchlafli : ∀ x y,
    ternaryAdjacent x y = schlafliAdjacent (equivPlus0 x) (equivPlus0 y)

inductive BareAdditiveTernaryCubeCreatesSchlafli27 : Prop
inductive Cardinality27CreatesMinusculeRecognition : Prop

theorem bare_additive_cube_does_not_create_schlafli :
    ¬ BareAdditiveTernaryCubeCreatesSchlafli27 := by
  intro h
  cases h

theorem cardinality27_does_not_create_minuscule_recognition :
    ¬ Cardinality27CreatesMinusculeRecognition := by
  intro h
  cases h

structure Boundary where
  ternaryCubeCard27Consumed : Bool
  projectiveDirectionCount13Paid : Bool
  allUndirectedTranslationInvariantMasksExhausted : Bool
  schlafliCayleyRealizationBlocked : Bool
  literalMixed27SchlafliGeometryConsumed : Bool
  extraAlbertOrE6GeometryStillRequired : Bool
  cardinality27PromotesMinusculeRecognition : Bool
  deriving Repr

def canonicalBoundary : Boundary where
  ternaryCubeCard27Consumed := true
  projectiveDirectionCount13Paid := true
  allUndirectedTranslationInvariantMasksExhausted := true
  schlafliCayleyRealizationBlocked := true
  literalMixed27SchlafliGeometryConsumed := true
  extraAlbertOrE6GeometryStillRequired := true
  cardinality27PromotesMinusculeRecognition := false

end Integration.E8Mixed27TernaryTranslationObstruction
