/- Attribution: JMD (github.com/meta-introspector) -/
import RequestProject.Agda.Syntax
import AgdaVendor.DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact
import AgdaVendor.DASHI.Physics.YangMills.CompactLieProofLevel

/-!
# `DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact`, transliterated

Generated by `tools/agda2lean.py` from the ingested upstream source
`upstream/dashi_agda/master/DASHI/Physics/YangMills/BalabanClayT5ClusteringToTransferGapExact.agda`.
Do not edit by hand: re-run the translator instead.
-/

open Agda

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where

  open import Agda.Builtin.Nat

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat

  open import DASHI.Physics.YangMills.CompactLieProofLevel

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel

  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  ------------------------------------------------------------------------
  -- Primary provenance.
  --
  -- Konrad Osterwalder and Robert Schrader,
  -- "Axioms for Euclidean Green's Functions",
  -- Communications in Mathematical Physics 31 (1973), 83--112.
  -- DOI: 10.1007/BF01645738.
  --
  -- Konrad Osterwalder and Robert Schrader,
  -- "Axioms for Euclidean Green's Functions II",
  -- Communications in Mathematical Physics 42 (1975), 281--305.
  -- DOI: 10.1007/BF01608978.
  --
  -- O. Penrose and J. L. Lebowitz,
  -- "On the Exponential Decay of Correlation Functions",
  -- Communications in Mathematical Physics 39 (1974), 165--184.
  -- DOI: 10.1007/BF01614239.
  --
  -- The OS papers own reconstruction of the positive transfer semigroup.  The
  -- finite contradiction below isolates the remaining spectral content: a mode
  -- strictly below the proposed gap gives a slower positive spectral contribution,
  -- while OS4 supplies a faster uniform upper envelope.  Density/overlap and the
  -- spectral lower representation are not silently inferred from the word
  -- "clustered".
  ------------------------------------------------------------------------

  data Empty : Set where

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  record ReconstructedClusteringSpectrum
      (Observable Energy Bound : Set) : Set₁ where
    field
      zeroEnergy gapCandidate : Energy
      PositiveEnergy : Energy → Set
      StrictlyBelow : Energy → Energy → Set

      connectedCorrelation : Observable → Nat → Bound
      clusteringEnvelope : Observable → Nat → Bound
      subgapSpectralEnvelope : Energy → Observable → Nat → Bound
      LessEqual : Bound → Bound → Set

      SubgapMode : Energy → Set
      modeObservable : ∀ energy , SubgapMode energy → Observable

      spectralRepresentationLowerBound : ∀ energy mode time ,
        LessEqual
          (subgapSpectralEnvelope energy (modeObservable energy mode) time)
          (connectedCorrelation (modeObservable energy mode) time)

      slowSubgapEnvelopeContradictsFastClustering : ∀ energy mode ,
        PositiveEnergy energy → StrictlyBelow energy gapCandidate →
        (∀ time ,
          LessEqual
            (subgapSpectralEnvelope energy (modeObservable energy mode) time)
            (connectedCorrelation (modeObservable energy mode) time)) →
        (∀ time ,
          LessEqual
            (connectedCorrelation (modeObservable energy mode) time)
            (clusteringEnvelope (modeObservable energy mode) time)) →
        Empty

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  open ReconstructedClusteringSpectrum public

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  ClusteringUpperBound :
    ∀ {Observable Energy Bound} ,
    ReconstructedClusteringSpectrum Observable Energy Bound → Set
  ClusteringUpperBound dataSet = ∀ observable time ,
    LessEqual dataSet
      (connectedCorrelation dataSet observable time)
      (clusteringEnvelope dataSet observable time)

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  NoPositiveSubgapMode :
    ∀ {Observable Energy Bound} ,
    ReconstructedClusteringSpectrum Observable Energy Bound → Set
  NoPositiveSubgapMode dataSet = ∀ energy ,
    PositiveEnergy dataSet energy →
    StrictlyBelow dataSet energy (gapCandidate dataSet) →
    SubgapMode dataSet energy → Empty

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  exponentialClusteringExcludesPositiveSubgapMode :
    ∀ {Observable Energy Bound}
      (dataSet : ReconstructedClusteringSpectrum Observable Energy Bound) ,
    ClusteringUpperBound dataSet →
    NoPositiveSubgapMode dataSet
  exponentialClusteringExcludesPositiveSubgapMode dataSet clusteringUpper
    energy positive below mode =
    slowSubgapEnvelopeContradictsFastClustering dataSet
      energy mode positive below
      (spectralRepresentationLowerBound dataSet energy mode)
      (clusteringUpper (modeObservable dataSet energy mode))

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  record PositiveTransferGap
      {Observable Energy Bound : Set}
      (dataSet : ReconstructedClusteringSpectrum Observable Energy Bound) : Set₁ where
    field
      clusteringUpperBound : ClusteringUpperBound dataSet
      gapCandidatePositive : PositiveEnergy dataSet (gapCandidate dataSet)
      noPositiveSubgapMode : NoPositiveSubgapMode dataSet

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  open PositiveTransferGap public

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  positiveTransferGapFromClusteringCutset :
    ∀ {Observable Energy Bound}
      (dataSet : ReconstructedClusteringSpectrum Observable Energy Bound) ,
    ClusteringUpperBound dataSet →
    PositiveEnergy dataSet (gapCandidate dataSet) →
    PositiveTransferGap dataSet
  positiveTransferGapFromClusteringCutset dataSet upper positiveGap = record
    { clusteringUpperBound = upper
    ; gapCandidatePositive = positiveGap
    ; noPositiveSubgapMode =
        exponentialClusteringExcludesPositiveSubgapMode dataSet upper
    }

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  record OS4SpectralInterpretation
      {Measure Schwinger Observable Energy Bound : Set}
      (closure : DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact.FiniteToContinuumOSClosure Measure Schwinger)
      (spectrum : ReconstructedClusteringSpectrum Observable Energy Bound) : Set₁ where
    field
      closureClusteringMeaning :
        DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact.Clustered closure
          (DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact.schwinger closure (DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact.continuumMeasure closure)) →
        ClusteringUpperBound spectrum

      candidateGapPositive : PositiveEnergy spectrum (gapCandidate spectrum)

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  open OS4SpectralInterpretation public

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  positiveTransferGapFromOS4 :
    ∀ {Measure Schwinger Observable Energy Bound}
      {closure : DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact.FiniteToContinuumOSClosure Measure Schwinger}
      {spectrum : ReconstructedClusteringSpectrum Observable Energy Bound} ,
    OS4SpectralInterpretation closure spectrum →
    DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact.Clustered closure
      (DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact.schwinger closure (DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact.continuumMeasure closure)) →
    PositiveTransferGap spectrum
  positiveTransferGapFromOS4 {spectrum = spectrum} interpretation clustered =
    positiveTransferGapFromClusteringCutset spectrum
      (closureClusteringMeaning interpretation clustered)
      (candidateGapPositive interpretation)

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  clusteringSpectralContradictionAssemblyLevel : ProofLevel
  clusteringSpectralContradictionAssemblyLevel = machineChecked

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  positiveTransferGapAssemblyLevel : ProofLevel
  positiveTransferGapAssemblyLevel = machineChecked

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  os4ToTransferGapAssemblyLevel : ProofLevel
  os4ToTransferGapAssemblyLevel = machineChecked

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  physicalSpectralRepresentationLowerBoundInputsLevel : ProofLevel
  physicalSpectralRepresentationLowerBoundInputsLevel = conditional

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  physicalObservableSubgapOverlapInputsLevel : ProofLevel
  physicalObservableSubgapOverlapInputsLevel = conditional

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  physicalSlowVersusFastRateComparisonInputsLevel : ProofLevel
  physicalSlowVersusFastRateComparisonInputsLevel = conditional

agda_module DASHI.Physics.YangMills.BalabanClayT5ClusteringToTransferGapExact where
  open import Agda.Builtin.Nat
  open import DASHI.Physics.YangMills.CompactLieProofLevel
  open import DASHI.Physics.YangMills.BalabanClayT5LimitAndNontrivialityExact

  physicalOS4ClusteringMeaningInputsLevel : ProofLevel
  physicalOS4ClusteringMeaningInputsLevel = conditional

