import AgdaMirror.Governance.IRISDenaHansardCorrectionAwareEvidence
import AgdaMirror.Governance.AUKUSOnboardConductSovereigntyBoundary
import AgdaMirror.Governance.AUKUSEmbeddedAuthorityCommandNoncollapse
import AgdaMirror.Governance.IRISDenaMinisterialBriefingFOIBoundary
import AgdaMirror.Governance.IRISDenaSameObjectAcquisitionMaxCut
import AgdaMirror.Governance.OriginalThreadParetoMaxCut20261008
